CONTAINER Oextrude
{
	NAME Oextrude;
	INCLUDE Obase;
	INCLUDE Onurbscaps;

	GROUP ID_OBJECTPROPERTIES
	{
		VECTOR EXTRUDEOBJECT_MOVE { UNIT METER; }
		LONG EXTRUDEOBJECT_SUB { MIN 1; MAX 4000; }
		LONG EXTRUDEOBJECT_ISOPARM { MIN 2; MAX 4000; }

		BOOL EXTRUDEOBJECT_FLIPNORMALS { }
		BOOL EXTRUDEOBJECT_HIERARCHIC  { }
	}
}
