CONTAINER Tedgeselection
{
	NAME Tedgeselection;
	INCLUDE Tbase;

	GROUP Obaselist
	{
		DEFAULT 1;
		GROUP
		{
			BUTTON EDGESELECTIONTAG_COMMAND1 { FIT_H; }
			BUTTON EDGESELECTIONTAG_COMMAND2 { FIT_H; }
			BUTTON EDGESELECTIONTAG_COMMAND3 { FIT_H; }
			BUTTON EDGESELECTIONTAG_COMMAND4 { FIT_H; }
			BUTTON EDGESELECTIONTAG_COMMAND5 { FIT_H; }
			BUTTON EDGESELECTIONTAG_COMMAND6 { FIT_H; }
		}
	}
}
