CONTAINER Tnormal
{
	NAME Tnormal;
	INCLUDE Tbase;

	GROUP ID_TAGPROPERTIES
	{
		BUTTON NORMALTAG_ALIGN_FACE2VERTEX {}
		BUTTON NORMALTAG_ALIGN_VERTEX2FACE {}
		BUTTON NORMALTAG_SWAP_NORMALS {}
	}
}
