CONTAINER Tpointselection
{
	NAME Tpointselection;
	INCLUDE Tbase;

	GROUP Obaselist
	{
		DEFAULT 1;
		GROUP
		{
			BUTTON POINTSELECTIONTAG_COMMAND1 { FIT_H; }
			BUTTON POINTSELECTIONTAG_COMMAND2 { FIT_H; }
			BUTTON POINTSELECTIONTAG_COMMAND3 { FIT_H; }
			BUTTON POINTSELECTIONTAG_COMMAND4 { FIT_H; }
			BUTTON POINTSELECTIONTAG_COMMAND5 { FIT_H; }
			BUTTON POINTSELECTIONTAG_COMMAND6 { FIT_H; }
		}
	}
}
