CONTAINER Tpolygonselection
{
	NAME Tpolygonselection;
	INCLUDE Tbase;

	GROUP Obaselist
	{
		DEFAULT 1;
		GROUP
		{
			BUTTON POLYGONSELECTIONTAG_COMMAND1 { FIT_H; }
			BUTTON POLYGONSELECTIONTAG_COMMAND2 { FIT_H; }
			BUTTON POLYGONSELECTIONTAG_COMMAND3 { FIT_H; }
			BUTTON POLYGONSELECTIONTAG_COMMAND4 { FIT_H; }
			BUTTON POLYGONSELECTIONTAG_COMMAND5 { FIT_H; }
			BUTTON POLYGONSELECTIONTAG_COMMAND6 { FIT_H; }
		}
	}
}
