CONTAINER Trestriction
{
	NAME Trestriction;
	INCLUDE Tbase;

	GROUP ID_TAGPROPERTIES
	{
		COLUMNS 2;
		STRING RESTRICTIONTAG_NAME_01 { SCALE_H; }
		REAL RESTRICTIONTAG_VAL_01 { UNIT PERCENT; MIN 0.0; MAX 100.0; }
		STRING RESTRICTIONTAG_NAME_02 { SCALE_H; }
		REAL RESTRICTIONTAG_VAL_02 { UNIT PERCENT; MIN 0.0; MAX 100.0; }
		STRING RESTRICTIONTAG_NAME_03 { SCALE_H; }
		REAL RESTRICTIONTAG_VAL_03 { UNIT PERCENT; MIN 0.0; MAX 100.0; }
		STRING RESTRICTIONTAG_NAME_04 { SCALE_H; }
		REAL RESTRICTIONTAG_VAL_04 { UNIT PERCENT; MIN 0.0; MAX 100.0; }
		STRING RESTRICTIONTAG_NAME_05 { SCALE_H; }
		REAL RESTRICTIONTAG_VAL_05 { UNIT PERCENT; MIN 0.0; MAX 100.0; }
		STRING RESTRICTIONTAG_NAME_06 { SCALE_H; }
		REAL RESTRICTIONTAG_VAL_06 { UNIT PERCENT; MIN 0.0; MAX 100.0; }
	}
}
