CONTAINER VPpreviewhardware
{
	NAME VPpreviewhardware;
	INCLUDE VPbase;

	GROUP ID_VIDEOPOSTPROPERTIES
	{
		BOOL VP_PREVIEWHARDWARE_ENHANCEDOPENGL { ANIM OFF; }
		BOOL VP_PREVIEWHARDWARE_TRANSPARENCY { ANIM OFF; }
		BOOL VP_PREVIEWHARDWARE_SHADOW	{ ANIM OFF; }
		BOOL VP_PREVIEWHARDWARE_POSTEFFECT { ANIM OFF; }
		BOOL VP_PREVIEWHARDWARE_NOISE { ANIM OFF; }
		LONG VP_PREVIEWHARDWARE_ANTIALIASING	{ ANIM OFF; CYCLE { } }
	}
}
