CONTAINER Xbase
{
	NAME Xbase;
	INCLUDE Obaselist;

	GROUP Obaselist
	{
		SEPARATOR { }
		REAL SHADER_MIPOFFSET { UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; }
		REAL SHADER_MIPSCALE { UNIT PERCENT; MIN -100.0; MAX 100.0; CUSTOMGUI REALSLIDER; }
	}

	GROUP ID_SHADERPROPERTIES
	{
		DEFAULT	1;	
	}
}
