CONTAINER Sclient
{
	NAME Sclient;

	GROUP 
	{
		SCALE_V;
		STATICTEXT SCLIENT_MACHINEID { BORDER; }
		STATICTEXT SCLIENT_IPADDRESS { BORDER; }
		STATICTEXT SCLIENT_COMPUTER { BORDER; }
		STATICTEXT SCLIENT_USER { BORDER; }
		STATICTEXT SCLIENT_SERIALPACKAGE { BORDER; }
		STATICTEXT SCLIENT_VERSION { BORDER; }
		STATICTEXT SCLIENT_LASTLOGIN { BORDER; }
		STATICTEXT SCLIENT_LASTSEEN { BORDER; }
		STATICTEXT SCLIENT_VALIDUNTIL { BORDER; }
		//STATICTEXT SCLIENT_CONNECTIONS { BORDER; }
		STATICTEXT SCLIENT_LOGINS { BORDER; }
		STATICTEXT SCLIENT_TIMEDIFF { BORDER; }	
		LINK SCLIENT_GROUP { ACCEPT { 200000207; } }
		BOOL SCLIENT_BLOCKED { }
		STRING SCLIENT_NOTES { CUSTOMGUI MULTISTRING; SCALE_V; WORDWRAP; }
	}
}
