CONTAINER Sgroup
{
	NAME Sgroup;

	GROUP 
	{
		COLUMNS 4;
		SCALE_V; 
		
		STRING SGROUP_NAME { }
		STATICTEXT { JOINEND; }
		STATICTEXT { JOINEND; }
		STATICTEXT { JOINEND; }

		BOOL SGROUP_BLOCKED { }
		STATICTEXT { NEWLINE; }
		
		LONG SGROUP_DEFAULT_LEASETIME_D	{ STEP 1; MIN 0; MAX 365; }
		LONG SGROUP_DEFAULT_LEASETIME_H	{ STEP 1; MIN 0; MAX 23; }
		LONG SGROUP_DEFAULT_LEASETIME_M	{ STEP 1; MIN 0; MAX 59; }
		STATICTEXT SGROUP_DEFAULT_LEASETIME_TEXT { SCALE_H; }

		LONG SGROUP_MAX_LEASETIME_D { STEP 1; MIN 0; MAX 365; }
		LONG SGROUP_MAX_LEASETIME_H { STEP 1; MIN 0; MAX 23; }
		LONG SGROUP_MAX_LEASETIME_M { STEP 1; MIN 0; MAX 59; }
		STATICTEXT SGROUP_MAX_LEASETIME_TEXT { SCALE_H; }
		
		COLOR SGROUP_COLOR { }
		STATICTEXT { JOINEND; }
		STATICTEXT { JOINEND; }
		STATICTEXT { NEWLINE; }
		
		IN_EXCLUDE SGROUP_NUMBERS { SCALE_V; NUM_FLAGS 0; INIT_STATE 0; ACCEPT { 200000176; }; }
		STATICTEXT { JOINEND; }
		STATICTEXT { JOINEND; }
		STATICTEXT { NEWLINE; }

		GROUP SGROUP_JOIN_GROUP
		{
			COLUMNS 2;

			BOOL SGROUP_JOIN_MACHINE { }
			STRING SGROUP_JOIN_MACHINE_EXP { SCALE_H; }
		
			BOOL SGROUP_JOIN_IP { }
			STRING SGROUP_JOIN_IP_EXP { SCALE_H; }
		
			BOOL SGROUP_JOIN_COMPUTER { }
			STRING SGROUP_JOIN_COMPUTER_EXP { SCALE_H; }
		
			BOOL SGROUP_JOIN_USER { }
			STRING SGROUP_JOIN_USER_EXP { SCALE_H; }
		}
	}
}
