CONTAINER Smodul
{
	NAME Smodul;

	GROUP 
	{
		STRING SMODUL_NAME { }
		STATICTEXT SMODUL_SERIAL { BORDER; }
		STATICTEXT SMODUL_VERSION { BORDER; }
		STATICTEXT SMODUL_LICENSES { BORDER; }
		STATICTEXT SMODUL_OS { BORDER; }
	}
}
