CONTAINER Sserial
{
	NAME Sserial;

	GROUP 
	{
		STRING SSERIAL_NAME { }
		STATICTEXT SSERIAL_BLOCK { BORDER; }
		STATICTEXT SSERIAL_VERSION { BORDER; }
		STATICTEXT SSERIAL_LICENSES { BORDER; }
		BOOL SSERIAL_BLOCKED { }
	}
}
