enum
{
	// IDs for the global string table
	STRING_CMD_APPLY_FILTER = 10000,
	STRING_CMD_SETTINGS,
	STRING_CMD_FBX_NAME,
	STRING_VERTEX_CACHE_WRITE_ERROR,

	STRING_PASSWORD,

	DLG_GETTAKE,
	GADGET_LISTVIEW,
	GADGET_FILEVERSION,
	STR_FILE_VERSION,

	DLG_GETPASSWORD,
	TITLE_STR_GET_PASSWORD,
	STR_PASSWORD,
	GADGET_PASSWORD,

	GADGET_FR_ENABLED,
	GADGET_FRAMERATE,
	GADGET_STARTTIME,
	GADGET_ENDTIME,
	STR_STARTTIME,
	STR_ENDTIME,
	GADGET_ST_ENABLED,
	GADGET_ET_ENABLED,

	STRING_FBX,
	STRING_FBX_IMPORT_SETTINGS,
	STRING_FBX_EXPORT_SETTINGS,

	STRING_FBX_MAT_LAYER_REFLECTION,
	STRING_FBX_MAT_LAYER_SPECULAR,
	STRING_FBX_EDITOR_CAMERA,

	DUMMY_

};
