enum
{
	// string table definitions
	IDS_ABOUT								= 1021453,

	CINEMANPREFS_DIALOG						= 1021454,
	IDS_CINEMANPREFS_DIALOG_TITLE			= 1021455,

	IDS_CINEMANPREFS_NAME					= 1021456,

	IDC_CINEMANPREFS_RENDERER				= 1021457,
	IDS_CINEMANPREFS_RENDERER				= 1021458,
		IDS_CINEMANPREFS_RENDERER_PRMAN_PRMAN = 0,
		IDS_CINEMANPREFS_RENDERER_PRMAN_NETRENDER = 1,
		IDS_CINEMANPREFS_RENDERER_AIR_AIR	= 2,
		IDS_CINEMANPREFS_RENDERER_AIR_VORTEX = 3,
		IDS_CINEMANPREFS_RENDERER_3DELIGHT_RENDERDL = 4,

	IDC_CINEMANPREFS_ROOTDIR				= 2021459,
	IDS_CINEMANPREFS_ROOTDIR				= 2021460,

	IDC_CINEMANPREFS_RENDERCOMMAND			= 1021459,
	IDS_CINEMANPREFS_RENDERCOMMAND			= 1021460,

	IDC_CINEMANPREFS_SHADERCOMMAND			= 1021461,
	IDS_CINEMANPREFS_SHADERCOMMAND			= 1021462,

	IDC_CINEMANPREFS_RIBTEMPMODE			= 1021463,
	IDS_CINEMANPREFS_RIBTEMPMODE			= 1021464,
		IDS_CINEMANPREFS_RIBTEMPMODE_LOCAL,
		IDS_CINEMANPREFS_RIBTEMPMODE_PROJECTDIR,
		IDS_CINEMANPREFS_RIBTEMPMODE_SPECIFY,

	IDC_CINEMANPREFS_RIBTEMPDIR				= 1021465,
	IDS_CINEMANPREFS_RIBTEMPDIR				= 1021466,

	// names
	IDS_RIBATTRIBUTESTAG					= 10001,
	IDS_RIBCONTAINERTAG,
	IDS_USECINEMAN,
	IDS_ABOUTCINEMAN,
	IDS_SELECTNONMANIFOLDEDGES,
	IDS_EXPORTSHADERS,

	IDS_PATHADD,
	IDS_PATHCHOOSE,

	IDS_CINEMANVP,
	IDS_EXTERNALRENDER,

	IDS_NOACTIVESETTING,
	IDS_CINEMANSHADER,

	IDS_SELECTLOCATION,
	IDS_RIBARCHIVE,
	IDS_PATHLIST,
	IDS_RIBSHADOWMAP,
	IDS_SELECTSHADERFILE,

	// Messages
	IDS_EXECUTABLE_NOT_FOUND,
	IDS_CANT_START_RENDER_SCRIPT,
	IDS_RENDERCOLLISION,

	IDS_POLYGONRIB_NAME,
	IDS_SPHERERIB_NAME,
	IDS_SKYRIB_NAME,
	IDS_FLOORRIB_NAME,
	IDS_HYPERNURBSRIB_NAME,
	IDS_HYPERNURBSRIB_OPTION_OFF,
	IDS_HYPERNURBSRIB_OPTION_CATMULLCLARK,
	IDS_HYPERNURBSRIB_OPTION_CATMULLCLARKALWAYS,
	IDS_CONTAINERTAGRIB_NAME,
	IDS_ATTRIBUTETAGRIB_NAME,

	IDS_PREFS_CINEMAN,

	DUMMY_
};
