#ifndef C4D_SYMBOLS_H__
#define C4D_SYMBOLS_H__
enum
{
	IDS_PYTHON = 1000,

	//instancables
	IDS_TPYTHON,
	IDS_GVPYTHON,
	IDS_OPYTHON,
	IDS_OEPYTHON,

	//common
	IDS_PYTHON_INPUT,
	IDS_GV_COMMON,

	//three dots
	IDS_DOT,

	// PythonNode
	IDS_PYTHONNODE_RENAME_PORT,
	IDS_PYTHONNODE_ERROR_PORT,

	IDS_SYNTAX_ERR,

	//global group dummy
	_DLG_DUMMY,

	// editor
	IDS_EDITOR,
	IDS_EDITOR_FILE,
	IDS_EDITOR_OPEN,
	IDS_EDITOR_COMMIT,
	IDS_EDITOR_SAVEASFILE,
	IDS_EDITOR_SAVE,
	IDS_EDITOR_DESC,
	IDS_EDITOR_SAVING_FAILED,
	IDS_DONT_SEND_CODE_BACK,

	// Directory
	IDS_SCRIPTS,
	IDS_SCRIPTDIR,
	IDS_SCRIPTDIR_DESC,
	IDS_SCRIPTDIR_FAIL,

	// reload
	IDS_RELOAD_PY,
	IDS_RELOAD_PY_DESC,

	// reset
	IDS_RESET_ALL,
	IDS_RESET_ALL_DESC,

	// Protector
	DLG_PROTECT,
	// Protector - dialog elements
	PROTECT_BTN_PROTECT,
	PROTECT_TXT_PATH,
	// Protector - string resources
	IDS_PROTECT,
	IDS_PROTECT_DESC,
	IDS_PROTECT_SUCCESS,
	IDS_PROTECT_FAILED,
	IDS_PROTECT_OVERWRITE,
	IDS_PROTECT_OPENFAIL,
	IDS_PROTECT_TITLE,

	// Run script
	IDS_RUNSCRIPT,
	IDS_RUNSCRIPT_DESC,
	IDS_RUNSCRIPT_NOTFOUND,

	IDS_PLUGIN_NOT_FOUND,
	IDS_PLUGIN_NOT_LOAD,

	//node
	IDS_NODE_INTEGER,
	IDS_NODE_STRING,
	IDS_NODE_FILENAME,
	IDS_NODE_VECTOR,
	IDS_NODE_TIME,
	IDS_NODE_MATRIX,
	IDS_NODE_TP,
	IDS_NODE_BOOL,
	IDS_NODE_FLOAT,
	IDS_NODE_LINK,
	IDS_NODE_GRADIENT,
	IDS_NODE_INEXCLUDELIST,
	IDS_NODE_SPLINEDATA,

	//scriptmanager dialog
	DLG_SCRIPTMANAGER,
	SCRIPTMANAGER_BTN_EXECUTE,
	SCRIPTMANAGER_BTN_RENDERICON,
	SCRIPTMANAGER_BTN_CREATESCRIPT,
	SCRIPTMANAGER_TXT_SCRIPT,
	SCRIPTMANAGER_TXT_SYNTAX,
	SCRIPTMANAGER_BTN_ICON,
	//scriptmanager - string resources
	IDS_SCRIPTMANAGER,
	IDS_SCRIPTMANAGER_DESC,
	IDS_SCRIPTMANAGER_FILE,
	IDS_SCRIPTMANAGER_IMPORT,
	IDS_SCRIPTMANAGER_EXPORT,
	IDS_SCRIPTMANAGER_RENDERICON,
	IDS_SCRIPTMANAGER_LOADICON,
	IDS_SCRIPTMANAGER_EXECUTE,
	IDS_SCRIPTMANAGER_CREATESCRIPT,
	IDS_SCRIPTMANAGER_CREATESUCCESS,
	IDS_SCRIPTMANAGER_REGISTERFAILED,
	IDS_SCRIPTMANAGER_SAVEFAILED,
	IDS_SCRIPTMANAGER_ASKCONTINUE,
	IDS_SCRIPTMANAGER_EXECUTESCRIPT,

	//plugin manager
	IDS_PLUGINMANAGER,
	IDS_PLUGINMANAGER_DESC,
	IDS_PLUGINMANAGER_SHOWPLUGINS,
	IDS_PLUGINMANAGER_NOINFO,
	IDS_PLUGINMANAGER_SHOWFINDER,
	IDS_PLUGINMANAGER_SHOWINFO,
	IDS_PLUGINMANAGER_TIME,
	IDS_PLUGINMANAGER_MS,
	IDS_PLUGINMANAGER_NAME,
	IDS_PLUGINMANAGER_TYPE,
	IDS_PLUGINMANAGER_RELOADPLUGIN,
	IDS_PLUGINMANAGER_RELOADALL,
	IDS_PLUGINMANAGER_FOLDALL,
	IDS_PLUGINMANAGER_UNFOLDALL,
	IDS_PLUGINMANAGER_CREATERELOADSCRIPT,

	IDS_CMATERIAL,
	IDS_CMATERIAL_DESC,
};
#endif // C4D_SYMBOLS_H__
