enum
{
	// string table definitions
	IDS_ABC = 10000,

	IDS_STATUS_LOADING_OBJECT,

	IDS_STATUS_PREPARING_PROJECT,
	IDS_STATUS_CLEANINGUP_PROJECT,
	IDS_STATUS_SAVING_FRAMES,

	IDS_ALEMBIC_GENERATOR,

	IDS_ALEMBIC_ALEMBIC,
	IDS_ALEMBIC_IMPORT_SETTINGS,
	IDS_ALEMBIC_EXPORT_SETTINGS,

	// End of symbol definition
	_DUMMY_ELEMENT_
};
