CONTAINER Marchigrass
{
	NAME Marchigrass;

	GROUP
	{
		MATPREVIEW GRASS_MAT_PREVIEW { OPEN; MIN_WIDTH 100; MIN_HEIGHT 100; }
	}

	INCLUDE Mbase;

	GROUP Obaselist
	{
		BOOL MATERIAL_PAGE_PROPERTIES { HIDDEN; PAGE; PARENTMSG ID_MATERIALPROPERTIES; }
	}
	
	GROUP ID_MATERIALPROPERTIES
	{
		DEFAULT 1;
		
		GRADIENT 			GRASS_COLOR							{ ICC_BASEDOCUMENT; }
		SHADERLINK		GRASS_COLOR_VAR_SHD			{  }
		REAL					GRASS_INHERITCOL				{ UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; }

		SEPARATOR															{ LINE; }

		REAL					GRASS_LENGTH						{ UNIT METER; MIN 0.0; }
		REAL					GRASS_WIDTH							{ UNIT METER; MIN 0.0; STEP 0.01; }
		REAL					GRASS_DENSITY						{ UNIT PERCENT; MIN 0.0; MINSLIDER 0.0; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }
		SHADERLINK		GRASS_DENSITY_SHD				{  }

		SEPARATOR															{ LINE; }

		REAL					GRASS_STYLE_1						{ UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; }
		REAL					GRASS_STYLE_2						{ UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; }
		REAL					GRASS_SPECULAR					{ UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; }

		//BOOL					GRASS_CULLING						{  }
		//REAL					GRASS_CULLING						{ UNIT DEGREE; }
		//REAL					GRASS_SHAPE							{ MIN 0.0; MAX 100.0; }
	}

	INCLUDE Massign;
}
