CONTAINER FCollada15Export
{
	NAME FCollada15Export;

	INCLUDE Fbase;

	GROUP COLLADA_EXPORT_GROUP
	{
		//UNITSCALE COLLADA_EXPORT_SCALE { }
 		BOOL COLLADA_EXPORT_2D_GEOMETRY { }
 		BOOL COLLADA_EXPORT_ANIMATION { }
 		BOOL COLLADA_EXPORT_TRIANGLES { }
  }
}
