enum
{
	// string table definitions for MotionTracker
	IDS_MOTIONTRACKEROBJECT	= 10000,

	IDS_SCENEHOOK,

	IDS_PH_CONSTRAINTTAG_POSITION,
	IDS_PH_CONSTRAINTTAG_VECTOR,
	IDS_PH_CONSTRAINTTAG_PLANAR,
	IDS_PH_CONSTRAINTTAG_CAMERA_ORIENT,

	IDS_PH_CONSTRAINTTAG_MASK,
	IDS_PH_MASK_TRACK,

	IDS_PH_CMD_CREATE_USER_FEAT_AT_POS,
	IDS_PH_CMD_INSERT_KEY_AT_POS,
	IDS_PH_CMD_INSERT_KEYS,
	IDS_PH_CMD_DELETE_KEYS,
	IDS_PH_CMD_TRIM_TRACK,
	IDS_PH_CMD_UNTRIM_TRACK,

	IDS_PH_TOOL_CREATOR_USER_TRACK_MODE,
	IDS_PH_TOOL_CREATOR_CONSTRAINT_MASK_MODE,
	IDS_PH_TOOL_CREATOR_CONSTRAINT_POSITION_MODE,
	IDS_PH_TOOL_CREATOR_CONSTRAINT_VECTOR_MODE,
	IDS_PH_TOOL_CREATOR_CONSTRAINT_PLANAR_MODE,

	IDS_PH_CMD_SELECT_AUTO_TRACKS,
	IDS_PH_CMD_SELECT_USER_TRACKS,
	IDS_PH_CMD_SELECT_RECONSTRUCTED_TRACKS,
	IDS_PH_CMD_INVERT_TRACK_SELECTION,
	IDS_PH_CMD_HIDE_SELECTED_TRACKS,
	IDS_PH_CMD_HIDE_UNSELECTED_TRACKS,
	IDS_PH_CMD_UNHIDE_ALL_TRACKS,
	IDS_PH_CMD_INVERT_TRACK_VISIBILITY,
	IDS_PH_CMD_DELETE_SELECTED_TRACKS,
	IDS_PH_CMD_RESTORE_DELETED_TRACKS,

	IDS_PH_CMD_SMARTTRACK_BD,
	IDS_PH_CMD_SMARTTRACK_FW,
	IDS_PH_CMD_SMARTTRACK_BW,

	IDS_PH_CMD_VIEW_MODE_2D,
	IDS_PH_CMD_VIEW_MODE_3D,

	IDS_PH_CMD_GRAPHVIEW,
	IDS_PH_CMD_SOLVE_FULL,

	IDS_PH_RENDER_ASPECT,

//	NONE_STR,

	IDS_PH_DLG_GRAPHVIEW_TITLE,

	IDS_PH_CMD_MASK_INSERT_VERTEX_ON_EDGE,
	IDS_PH_CMD_MASK_DELETE_SELECTED_VERTICES,

	IDS_PH_FOOTAGE_INFO_NO_FOOTAGE_LOADED,
	IDS_PH_FOOTAGE_INFO_PRE_LOADING_FOOTAGE_EXT,
	IDS_PH_FOOTAGE_INFO_PRE_LOADED_FOOTAGE,

	IDS_PH_FOOTAGE_INFO_00,
	IDS_PH_FOOTAGE_INFO_00_EXT,

	IDS_PH_FOOTAGE_INFO_01,
	IDS_PH_FOOTAGE_INFO_01_EXT,

	IDS_PH_FOOTAGE_INFO_02,
	IDS_PH_FOOTAGE_INFO_02_EXT,

	IDS_PH_FOOTAGE_INFO_03,

	IDS_PH_CAMERAOBJECT_APERTURE_35,

	IDS_PH_2DTRACKING_PROCESSING_FRAME_EXT,
	IDS_PH_2DTRACKING_PROCESSING_TRACK_2D_DONE,

	IDS_PH_RECONSTRUCTION_EXTENDING_RECONSTRUCTION,
	IDS_PH_RECONSTRUCTION_RUNNING_3D_SOLVER,
	IDS_PH_RECONSTRUCTION_SOLVING_DEFERRED_CAMERAS,
	IDS_PH_RECONSTRUCTION_PRE_OPTIMISATION,
	IDS_PH_RECONSTRUCTION_OPTIMISATION,

	IDS_PH_THREAD_CANCELLED_EXT,
	IDS_PH_THREAD_FAILED_EXT,
	IDS_PH_THREAD_FINISHED_EXT,

	IDS_PH_THREAD_EXTEND,
	IDS_PH_THREAD_2D_TRACK,
	IDS_PH_THREAD_3D_SOLVE,
	IDS_PH_THREAD_DEFERRED_SOLVE,
	IDS_PH_THREAD_NODAL_PAIR,
	IDS_PH_THREAD_TRIPLET,
	IDS_PH_THREAD_PLANAR,

	IDS_PH_PREFERENCES,

	IDS_PH_MULTIPLE_VALUES,
	IDS_PH_NO_VALUES,

	IDS_PH_FEATKEYS_TRACK,

	IDS_PH_FOCAL,
	IDS_PH_POS_X,
	IDS_PH_POS_Y,
	IDS_PH_POS_Z,

	IDS_PH_ROT_H,
	IDS_PH_ROT_P,
	IDS_PH_ROT_B,

	IDS_PH_SOLVED_CAMERA,
	IDS_PH_AUTO_FEATURES,
	IDS_PH_USER_FEATURES,

	IDS_PH_CHOOSE_FOOTAGE,

	IDS_PH_NAME_GROUP_AUTO,
	IDS_PH_NAME_GROUP_USER,
	IDS_PH_CACHE_FULL,


	// string table definitions for LensDistortTool
	IDS_LENSDISTORTIONTOOL	= 20000,

	LD_LENS_LOAD_PROFILE_STR,
	LD_LENS_SAVE_PROFILE_STR,

	IDS_PH_LENS_MODEL_TYPE_NONE = 29000,
	IDS_PH_LENS_MODEL_TYPE_3DE_ANAMORPHIC_DEG_4_SQZ,
	IDS_PH_LENS_MODEL_TYPE_3DE_ANAMORPHIC_DEG_6,
	IDS_PH_LENS_MODEL_TYPE_3DE_CLASSIC,
	IDS_PH_LENS_MODEL_TYPE_3DE_RADIAL_DEG_8,
	IDS_PH_LENS_MODEL_TYPE_3DE_RADIAL_STANDARD_DEG4,


	// string table definitions for CameraCalibrator
	IDS_CAMERAMAPPING	= 30000,

	VP_STATUS_TEXT_GENERIC,

	//-----------------------
	// List here MUST BE IDENTICAL (excluding _STR suffix) to that in 'enum VpStatus'
	VP_STATUS_UNDEFINED_STR,
	VP_STATUS_UNSOLVED_INSUFFICIENT_LINES_STR,
	VP_STATUS_UNSOLVED_INCONSISTENT_LINES_NEAR_AND_FAR_STR,
	VP_STATUS_SOLVED_FINITE_STR,
	VP_STATUS_SOLVED_INFINITE_STR,
	VP_STATUS_END_MARKER_STR,
	//-----------------------

	// Following deliberately AFTER 'END_MARKER', as it
	// is an _alternate_ representation for Finite/Infinite,
	// NOT an _additional_ state.
	VP_STATUS_SOLVED_STR,
	VP_STATUS_INDIRECTLY_SOLVED_STR,
	VP_STATUS_UNSOLVED_STR,
	VP_STATUS_POSITION_ASSUMED_DISTANCE_STR,

	VP_STATUS_STR_ELEM_ASSUMED,
	VP_STATUS_STR_ELEM_PRE,
		VP_STATUS_STR_ELEM_POST,

	CAL_FOCAL_LEN_UNKNOWN_STR,
	CAL_FOCAL_LEN_NA_STR,

		// List here MUST BE IDENTICAL to that in 'enum CameraCalibratorStatus'
	CAL_STATUS_UNDEFINED_STR,
	CAL_STATUS_UNSOLVED_INSUFFICIENT_VPS_STR,
	CAL_STATUS_UNSOLVED_GENERAL_FAILURE_STR,
	CAL_STATUS_SOLVED_ORIENTATION_ONLY_STR,
	CAL_STATUS_SOLVED_FOCAL_LENGTH_ONLY_STR,
	CAL_STATUS_SOLVED_ORIENTATION_AND_FOCAL_STR,
	CAL_STATUS_SOLVED_ORIENTATION_AND_FOCAL_AND_POSITION_ASSUMED_DISTANCE_STR,
	CAL_STATUS_SOLVED_ORIENTATION_AND_FOCAL_AND_POSITION_STR,
	CAL_STATUS_END_MARKER_STR,


	// Misc strings
	OUTLIER_STATUS_TRUE_STR,
	OUTLIER_STATUS_FALSE_STR,

	CONCAVE_STATUS_TRUE_STR,
	CONCAVE_STATUS_FALSE_STR,

	RENDER_A_STR,
	RENDER_B_STR,

	AXIS_SEP_STR,

	ENTITY_TYPE_LINE_STR,
	ENTITY_TYPE_GRID_STR,
	ENTITY_TYPE_PIN_STR,

	ENTITY_TYPE_LINE_WITH_PIN_STR,
	ENTITY_TYPE_GRID_WITH_PIN_STR,

	ENTITY_TYPE_NONE_SELECTED_STR,

	NONE_STR,

	IDS_PHLENSDISTORTIONSHADER,
	IDS_PHLENSDISTORTIONVIDEOPOST,

	// String definitions for Ph GraphView
	IDS_GRAPHVIEW = 40000,
	IDS_PHGV_SWITCH_PLAN,
	IDS_PHGV_SWITCH_GRAPH,
	IDS_PHGV_DATATYPE_2D_ERROR,
	IDS_PHGV_DATATYPE_2D_SPEED,
	IDS_PHGV_DATATYPE_2D_ACCEL,

	IDS_PHGV_HELP_SWITCH_PLAN,
	IDS_PHGV_HELP_SWITCH_GRAPH,
	IDS_PHGV_HELP_DATATYPE_2D_ERROR,
	IDS_PHGV_HELP_DATATYPE_2D_SPEED,
	IDS_PHGV_HELP_DATATYPE_2D_ACCEL,

	IDS_PHGRAPHVIEW_MGR,

	IDS_PHGV_FRAME_ALL,
	IDS_PHGV_FRAME_SELECTED,
	IDS_PHGV_GOTO_CURRENT_FRAME,

	IDS_PHGV_HELP_FRAME_ALL,
	IDS_PHGV_HELP_FRAME_SELECTED,
	IDS_PHGV_HELP_GOTO_CURRENT_FRAME,

	IDS_PHGV_GRID_TYPE_NO,
	IDS_PHGV_GRID_TYPE_SUB,
	IDS_PHGV_GRID_TYPE_FINE,
	IDS_PHGV_GRID_TYPE_MIDDLE,
	IDS_PHGV_GRID_TYPE_SEC,

	IDS_PHGV_HELP_GRID_TYPE_NO,
	IDS_PHGV_HELP_GRID_TYPE_SUB,
	IDS_PHGV_HELP_GRID_TYPE_FINE,
	IDS_PHGV_HELP_GRID_TYPE_MIDDLE,
	IDS_PHGV_HELP_GRID_TYPE_SEC,

	IDS_PHGV_SHOW_FILTER_TRIMS,
	IDS_PHGV_HELP_SHOW_FILTER_TRIMS,

	IDS_PHGV_FILTER_TRIM_ERROR_THRESH,
	IDS_PHGV_FILTER_TRIM_NEAR_EDGES,
	IDS_PHGV_FILTER_TRIM_MASK,
	IDS_PHGV_FILTER_TRIM_USER_TRIM,
	IDS_PHGV_FILTER_TRIM_ACCEL_THRESH,
	IDS_PHGV_FILTER_TRIM_ACCEL_SMART_THRESH,

	IDS_PHGV_KEY,

	IDS_PHGV_STATUS_CURRFRAME = 99000,
	IDS_PHGV_STATUS_PREVIEW,

	EVENT_LAYOUT_UPDATE   = -100004712,


	//-----------------------
	// List here MUST BE IDENTICAL (excluding AXIS_STATE_ prefix and _STR suffix) to that in 'enum AxisState'
	AXIS_STATE_UNKNOWN_STR = 100000,
	AXIS_STATE_X_STR,
	AXIS_STATE_Y_STR,
	AXIS_STATE_Z_STR,
	AXIS_STATE_UNKNOWN_AUTO_STR,
	AXIS_STATE_X_AUTO_STR,
	AXIS_STATE_Y_AUTO_STR,
	AXIS_STATE_Z_AUTO_STR,
	AXIS_STATE_END_MARKER_STR,
	//-----------------------

	// End of symbol definition
	_DUMMY_ELEMENT_
};
