#ifndef FSKPIMPORT_H__
#define FSKPIMPORT_H__

enum
{
	SKPIMPORT_GROUP = 999,
	SKPIMPORT_GRP_GENERAL = 1000,
	SKPIMPORT_DAYLIGHT_SYSTEM_PHYSICAL_SKY,
	SKPIMPORT_CAMERA,
	SKPIMPORT_SKIP_HIDDEN_OBJECTS,
	SKPIMPORT_SPLIT_OBJECTS_BY_LAYER,
	SKPIMPORT_GRP_ADDITIONAL,
	SKPIMPORT_SHOW_STATISTICS_IN_CONSOLE
};

#endif // FSKPIMPORT_H__
