CONTAINER Fskpimport
{
	NAME Fskpimport;
	INCLUDE Fbase;

	GROUP SKPIMPORT_GROUP
	{
		SEPARATOR SKPIMPORT_GRP_GENERAL {}

		BOOL SKPIMPORT_DAYLIGHT_SYSTEM_PHYSICAL_SKY { DEFAULT 0; }
		BOOL SKPIMPORT_CAMERA { DEFAULT 0; }
		BOOL SKPIMPORT_SKIP_HIDDEN_OBJECTS { DEFAULT 0; }
		BOOL SKPIMPORT_SPLIT_OBJECTS_BY_LAYER { DEFAULT 0; }

		SEPARATOR SKPIMPORT_GRP_ADDITIONAL { }

		BOOL SKPIMPORT_SHOW_STATISTICS_IN_CONSOLE { DEFAULT 0; }
	}
}
