#ifndef C4D_SYMBOLS_H__
#define C4D_SYMBOLS_H__

enum
{
	// string table definitions
	IDS_SCULPT_BRUSH_PULL =  10000,
	IDS_SCULPT_BRUSH_FLATTEN,
	IDS_SCULPT_BRUSH_PINCH,
	IDS_SCULPT_BRUSH_ERASE,
	IDS_SCULPT_BRUSH_GRAB,
	IDS_SCULPT_BRUSH_MASK,
	IDS_SCULPT_BRUSH_KNIFE,
	IDS_SCULPT_BRUSH_WAX,
	IDS_SCULPT_BRUSH_INFLATE,
	IDS_SCULPT_BRUSH_FILL,
	IDS_SCULPT_BRUSH_SCRAPE,
	IDS_SCULPT_BRUSH_REPEAT,
	IDS_SCULPT_BRUSH_AMPLIFY,
	IDS_SCULPT_BRUSH_SELECT,

	IDS_SCULPT_BRUSH_PULL_HELP,
	IDS_SCULPT_BRUSH_FLATTEN_HELP,
	IDS_SCULPT_BRUSH_PINCH_HELP,
	IDS_SCULPT_BRUSH_ERASE_HELP,
	IDS_SCULPT_BRUSH_GRAB_HELP,
	IDS_SCULPT_BRUSH_MASK_HELP,
	IDS_SCULPT_BRUSH_KNIFE_HELP,
	IDS_SCULPT_BRUSH_WAX_HELP,
	IDS_SCULPT_BRUSH_INFLATE_HELP,
	IDS_SCULPT_BRUSH_FILL_HELP,
	IDS_SCULPT_BRUSH_SCRAPE_HELP,
	IDS_SCULPT_BRUSH_REPEAT_HELP,
	IDS_SCULPT_BRUSH_AMPLIFY_HELP,
	IDS_SCULPT_BRUSH_SELECT_HELP,

// End of symbol definition
	_DUMMY_ELEMENT_
};

#endif // C4D_SYMBOLS_H__
