// C4D-DialogResource
DIALOG IDD_UVEDIT_NUMERIC
{
  NAME IDS_UVEDIT_TRANSFORM; CENTER_V; CENTER_H; 
  
  GROUP 
  {
    ALIGN_TOP; FIT_H; SCALE_H; 
    BORDERSIZE 0, 0, 0, 0; 
    ROWS 3;
    SPACE 4, 2;
    
    GROUP IDC_STATIC
    {
      NAME IDS_UVEDIT_POSITOIN; ALIGN_TOP; ALIGN_LEFT; 
      BORDERSIZE 0, 0, 0, 0; 
      ROWS 3;
      SPACE 4, 2;
      
      STATICTEXT IDC_STATIC { NAME IDS_STATIC8; CENTER_V; ALIGN_LEFT; }
      STATICTEXT  { NAME IDS_UVEDIT_X; CENTER_V; FIT_H; }
      STATICTEXT  { NAME IDS_UVEDIT_Y; CENTER_V; FIT_H; }

      STATICTEXT IDC_STATIC { NAME IDS_STATIC5; CENTER_V; ALIGN_LEFT; }
      EDITNUMBERARROWS IDC_UVEDIT_POS_X_EDIT { CENTER_V; FIT_H; SIZE 60, 10; }
      EDITNUMBERARROWS IDC_UVEDIT_POS_Y_EDIT { CENTER_V; FIT_H; SIZE 60, 10; }

      STATICTEXT IDC_STATIC { NAME IDS_STATIC9; CENTER_V; ALIGN_LEFT; }
      STATICTEXT  { NAME IDS_UVEDIT_X; CENTER_V; FIT_H; }
      STATICTEXT  { NAME IDS_UVEDIT_Y; CENTER_V; FIT_H; }

      STATICTEXT IDC_STATIC { NAME IDS_STATIC6; CENTER_V; ALIGN_LEFT; }
      EDITNUMBERARROWS IDC_UVEDIT_SCALE_X_EDIT { CENTER_V; FIT_H; SIZE 60, 10; }
      EDITNUMBERARROWS IDC_UVEDIT_SCALE_Y_EDIT { CENTER_V; FIT_H; SIZE 60, 10; }

      STATICTEXT IDC_STATIC { NAME IDS_STATIC10; CENTER_V; ALIGN_LEFT; }
      STATICTEXT IDC_STATIC { NAME IDS_STATIC7; CENTER_V; ALIGN_LEFT; }
      STATICTEXT IDC_STATIC { NAME IDS_STATIC11; CENTER_V; ALIGN_LEFT; }

      STATICTEXT IDC_STATIC { NAME IDS_UVEDIT_ROTATION; CENTER_V; ALIGN_LEFT; }
      EDITNUMBERARROWS IDC_UVEDIT_ANGLE_EDIT { CENTER_V; FIT_H; SIZE 60, 10; }
      BUTTON IDC_UVEDIT_APPLY_BTN { NAME IDS_UVEDIT_APPLY_BTN; ALIGN_TOP; FIT_H; SIZE 0, 10; }
    }
  }
}