// C4D-DialogResource
DIALOG IDD_PROJECTION_DIALOG
{
  NAME IDS_PROJECTION_CAPTION; CENTER_V; CENTER_H; 
  
  GROUP IDC_STATIC
  {
    NAME IDS_STATIC3; ALIGN_TOP; ALIGN_LEFT; 
    BORDERSIZE 0, 0, 0, 0; 
    COLUMNS 1;
    SPACE 4, 4;
    
    GROUP IDC_STATIC
    {
      NAME IDS_STATIC4; ALIGN_TOP; ALIGN_LEFT; 
      BORDERSIZE 0, 0, 0, 0; 
      ROWS 1;
      SPACE 4, 4;
      
      GROUP IDC_STATIC
      {
        NAME IDS_STATIC6; ALIGN_TOP; ALIGN_LEFT; 
        BORDERSIZE 0, 0, 0, 0; 
        COLUMNS 1;
        SPACE 2, 2;
        
        GROUP IDC_STATIC
        {
          NAME IDS_STATIC1; ALIGN_TOP; ALIGN_LEFT; 
          BORDERSIZE 0, 0, 0, 0; 
          ROWS 1;
          SPACE 2, 2;
          
          GROUP IDC_STATIC
          {
            NAME IDS_STATIC; ALIGN_TOP; FIT_H; SCALE_H; 
            BORDERSIZE 0, 0, 0, 0; 
            COLUMNS 4;
            EQUAL_COLS; 
            SPACE 2, 2;
            
            BUTTON IDC_PROJECTION_SPHERE_BTN { NAME IDS_PROJECTION_SPHERE; ALIGN_TOP; FIT_H; SCALE_H; SIZE 0, 11; }
            BUTTON IDC_PROJECTION_CYLINDER_BTN { NAME IDS_PROJECTION_CYLINDER; ALIGN_TOP; FIT_H; SCALE_H; SIZE 0, 11; }
            BUTTON IDC_PROJECTION_FRONTAL_BTN { NAME IDS_PROJECTION_FRONTAL; ALIGN_TOP; FIT_H; SCALE_H; SIZE 0, 11; }
            BUTTON IDC_PROJECTION_FLAT_BTN { NAME IDS_PROJECTION_FLAT; ALIGN_TOP; FIT_H; SCALE_H; SIZE 0, 11; }
            BUTTON IDC_PROJECTION_CUBIC_BTN { NAME IDS_PROJECTION_CUBIC; ALIGN_TOP; FIT_H; SCALE_H; SIZE 0, 11; }
            BUTTON IDC_PROJECTION_CUBIC_2_BTN { NAME IDS_PROJECTION_CUBIC_2; ALIGN_TOP; FIT_H; SCALE_H; SIZE 0, 11; }
            BUTTON IDC_PROJECTION_BOX_BTN { NAME IDS_PROJECTION_BOX; ALIGN_TOP; FIT_H; SCALE_H; SIZE 0, 11; }
            BUTTON IDC_PROJECTION_SHRINK_BTN { NAME IDS_PROJECTION_SHRINK; ALIGN_TOP; FIT_H; SCALE_H; SIZE 0, 11; }
          }
        }
        GROUP IDC_STATIC
        {
          NAME IDS_STATIC7; ALIGN_TOP; ALIGN_LEFT; 
          BORDERSTYLE BORDER_NONE; BORDERSIZE 0, 0, 0, 0; 
          ROWS 1;
          
          GROUP IDC_STATIC
          {
            NAME IDS_STATIC2; ALIGN_TOP; ALIGN_LEFT; 
            BORDERSIZE 0, 0, 0, 0; 
            COLUMNS 1;
            SPACE 4, 4;
            
            CHECKBOX IDC_PROJECTION_FITTOSELECTION_CHK { NAME IDS_PROJECTION_FIT_TO_SEL; ALIGN_TOP; ALIGN_LEFT;  }
            CHECKBOX IDC_PROJECTION_WEIGHT_NORMAL_CHK { NAME IDS_PROJECTION_WEIGHT_NORMAL; ALIGN_TOP; ALIGN_LEFT;  }
          }
          COMBOBOX IDC_PROJECTION_SYSTEM_COMBO
          {
            ALIGN_TOP; ALIGN_LEFT; SIZE 150, 11; 
            CHILDS
            {
              IDC_PROJECTION_SYSTEM_OBJECT, IDS_PROJECTION_SYSTEM_OBJECT; 
              IDC_PROJECTION_SYSTEM_WORLD, IDS_PROJECTION_SYSTEM_WORLD; 
              IDC_PROJECTION_SYSTEM_AV_NORMAL, IDS_PROJECTION_SYSTEM_AV_NORMAL; 
            }
          }
        }
      }
    }
  }
}