// C4D-DialogResource
DIALOG IDD_RELAXUV
{
	NAME IDS_RELAXUV_TITLE; CENTER_V; FIT_H; SCALE_H; 

	GROUP IDC_STATIC
	{
		NAME IDS_STATIC1; ALIGN_TOP; ALIGN_LEFT; 
		ROWS 3;
		SPACE 4,4;

		GROUP {
			COLUMNS 2;
			BORDERSIZE 2,2,2,2;	
			SCALE_V; FIT_H;				
			
			STATICTEXT { NAME T6; CENTER_V; FIT_H;  }
			CHECKBOX IDC_RELAX_UV_PIN_BORDER { CENTER_V; FIT_H; }
			
			STATICTEXT { NAME T5; CENTER_V; FIT_H;  }	
			CHECKBOX IDC_RELAX_UV_PIN_NEIGHBORS { CENTER_V; FIT_H; }		
		}	
		
		SEPARATOR { SCALE_H; }
		
		GROUP {
			COLUMNS 2;
			BORDERSIZE 2,2,2,2;	
			CENTER_V; CENTER_H;
			
			COMBOBOX IDC_RELAX_UV_MODE { 
                CHILDS
                {
                    0, T13;
                    1, T14;
                }			
			}
			STATICTEXT { }
			
			BUTTON IDC_RELAX_UV_START_BTN { NAME IDS_BUTTON1; CENTER_V; CENTER_H; SIZE 0, 11; }
			STATICTEXT { }
			
			STATICTEXT { NAME T12; CENTER_V; FIT_H; SCALE_H; }	
			CHECKBOX IDC_RELAX_UV_AUTO_REALIGN {  }
		}

		SEPARATOR { SCALE_V; }
		STATICTEXT {  }
		SEPARATOR { SCALE_V; }

		GROUP {			
			COLUMNS 3;
			//BORDERSTYLE BORDER_THIN_IN;
			BORDERSIZE 2,2,2,2;	
			//SCALE_H;
			
			STATICTEXT { NAME T9; CENTER_V; FIT_H; SCALE_H; }
			CHECKBOX IDC_RELAX_UV_PIN_SEL { CENTER_V; FIT_H; }
			STATICTEXT { }
			
			EDITTEXT IDC_RELAX_UV_PIN_SEL_LINK { SCALE_H; SIZE 200, 9; }			
			CHECKBOX IDC_RELAX_UV_PIN_SEL_USE_LINK { CENTER_V; FIT_H; }								
			STATICTEXT { NAME T11;  CENTER_V; FIT_H;  }									
		}	
		
		SEPARATOR { SCALE_H; }
		
		GROUP {
			COLUMNS 3;
			//BORDERSTYLE BORDER_THIN_IN;
			BORDERSIZE 2,2,2,2;	
			//SCALE_H;
			
			STATICTEXT { NAME T10; CENTER_V; FIT_H; SCALE_H; }
			CHECKBOX IDC_RELAX_UV_CUT_EDGES { CENTER_V; FIT_H; }			
			STATICTEXT { }
			
			EDITTEXT IDC_RELAX_UV_CUT_EDGES_LINK { SCALE_H;  SIZE 200, 9; }
			CHECKBOX IDC_RELAX_UV_CUT_EDGES_USE_LINK { CENTER_V; FIT_H; }			
			STATICTEXT { NAME T11;  CENTER_V; FIT_H; }					
		}				
	}  
}