// C4D-DialogResource
DIALOG IDD_OPTIMAL_MAPPING
{
  NAME IDS_OPT_MAP_TITLE; ALIGN_TOP; ALIGN_LEFT; 
  
  GROUP IDC_STATIC
  {
    NAME IDS_STATIC12; ALIGN_TOP; ALIGN_LEFT; 
    BORDERSIZE 0, 0, 0, 0; 
    ROWS 1;
    SPACE 4, 4;
    
    GROUP IDC_STATIC
    {
      NAME IDS_STATIC11; FIT_V; SCALE_V; ALIGN_LEFT; 
      BORDERSIZE 0, 0, 0, 0; 
      COLUMNS 1;
      SPACE 4, 4;
      
      RADIOGADGET IDC_OPT_MAP_OPTIMALCUBIC_RADIO { NAME IDS_OPT_MAP_OPTIMALCUBIC; ALIGN_TOP; ALIGN_LEFT;  }
      RADIOGADGET IDC_OPT_MAP_OPTIMAL_RADIO { NAME IDS_OPT_MAP_OPTIMAL; ALIGN_TOP; ALIGN_LEFT;  }
      RADIOGADGET IDC_OPT_MAP_REALIGN_RADIO { NAME IDS_RADIO4; ALIGN_TOP; ALIGN_LEFT;  }
      STATICTEXT IDC_STATIC { NAME IDS_STATIC13; FIT_V; SCALE_V; ALIGN_LEFT; }
      BUTTON IDC_OPT_MAP_OK_BTN { NAME IDS_OPT_MAP_OK_BTN; ALIGN_TOP; ALIGN_LEFT; SIZE 0, 11; }
    }
    SEPARATOR { SCALE_V; }
    TAB IDC_OPT_MAP_TAB_GROUP
    {
      NAME IDS_STATIC5; ALIGN_TOP; ALIGN_LEFT; 
      SELECTION_NONE; 
      
      GROUP IDC_OPT_MAP_OPTIMALCUBIC_GROUP
      {
        NAME IDS_STATIC8; ALIGN_TOP; ALIGN_LEFT; 
        BORDERSIZE 0, 0, 0, 0; 
        COLUMNS 1;
        SPACE 4, 4;
        
        GROUP IDC_STATIC
        {
          NAME IDS_STATIC9; ALIGN_TOP; ALIGN_LEFT; 
          BORDERSIZE 0, 0, 0, 0; 
          COLUMNS 1;
          SPACE 4, 4;
          
          GROUP IDC_STATIC
          {
            NAME IDS_STATIC10; ALIGN_TOP; ALIGN_LEFT; 
            BORDERSIZE 0, 0, 0, 0; 
            COLUMNS 1;
            SPACE 4, 4;
            
            CHECKBOX IDC_OPT_MAP_OPTIMALCUBIC_PRESERVE_ORIENTATION_CHK { NAME IDS_OPT_MAP_PRESERVE_ORIENTATION1; CENTER_V; ALIGN_LEFT;  }
            CHECKBOX IDC_OPT_MAP_OPTIMALCUBIC_STRETCH_FIT_CHK { NAME IDS_OPT_MAP_STRETCH_TO_FIT1; CENTER_V; ALIGN_LEFT;  }
            CHECKBOX IDC_OPT_MAP_OPTIMALCUBIC_2D_CHK { NAME IDS_CHECK; ALIGN_TOP; ALIGN_LEFT;  }
          }
          GROUP 
          {
            ALIGN_TOP; FIT_H; SCALE_H; 
            BORDERSIZE 0, 0, 0, 0; 
            COLUMNS 2;
            SPACE 4, 2;
            
            STATICTEXT  { NAME IDS_OPT_MAP_MIN_DIST1; CENTER_V; ALIGN_LEFT; }
            EDITNUMBERARROWS IDC_OPT_MAP_OPTIMALCUBIC_AREA_EDIT
            { FIT_V; SCALE_V; FIT_H; SCALE_H; SIZE 60, 10; }
            STATICTEXT IDC_STATIC { NAME IDS_STATIC18; CENTER_V; ALIGN_LEFT; }
            EDITNUMBERARROWS IDC_OPT_MAP_OPTIMALCUBIC_RELAX_EDIT
            { CENTER_V; FIT_H; SCALE_H; SIZE 60, 10; }
            STATICTEXT  { NAME IDS_OPT_MAP_SPACING1; CENTER_V; ALIGN_LEFT; }
            EDITNUMBERARROWS IDC_OPT_MAP_OPTIMALCUBIC_SPACING_EDIT
            { CENTER_V; FIT_H; SCALE_H; SIZE 60, 10; }
          }
        }
      }
      GROUP IDC_OPT_MAP_OPTIMAL_GROUP
      {
        NAME IDS_STATIC6; ALIGN_TOP; ALIGN_LEFT; 
        BORDERSIZE 0, 0, 0, 0; 
        COLUMNS 1;
        SPACE 4, 4;
        
        GROUP IDC_STATIC
        {
          NAME IDS_STATIC3; ALIGN_TOP; ALIGN_LEFT; 
          BORDERSIZE 0, 0, 0, 0; 
          COLUMNS 1;
          SPACE 4, 4;
          
          GROUP IDC_STATIC
          {
            NAME IDS_STATIC2; ALIGN_TOP; ALIGN_LEFT; 
            BORDERSIZE 0, 0, 0, 0; 
            COLUMNS 1;
            SPACE 4, 4;
            
            CHECKBOX IDC_OPT_MAP_OPTIMAL_PRESERVE_ORIENTATION_CHK { NAME IDS_OPT_MAP_PRESERVE_ORIENTATION; CENTER_V; ALIGN_LEFT;  }
            CHECKBOX IDC_OPT_MAP_OPTIMAL_STRETCH_FIT_CHK { NAME IDS_OPT_MAP_STRETCH_TO_FIT; CENTER_V; ALIGN_LEFT;  }
          }
          GROUP 
          {
            ALIGN_TOP; FIT_H; SCALE_H; 
            BORDERSIZE 0, 0, 0, 0; 
            COLUMNS 2;
            SPACE 4, 2;
            
            STATICTEXT IDC_STATIC { NAME IDS_OPT_MAP_MIN_DIST; CENTER_V; ALIGN_LEFT; }
            EDITNUMBERARROWS IDC_OPT_MAP_OPTIMAL_MAX_DIST_EDIT
            { FIT_V; SCALE_V; FIT_H; SCALE_H; SIZE 60, 10; }
            STATICTEXT IDC_STATIC { NAME IDS_STATIC19; CENTER_V; ALIGN_LEFT; }
            EDITNUMBERARROWS IDC_OPT_MAP_OPTIMAL_RELAX_EDIT
            { CENTER_V; FIT_H; SCALE_H; SIZE 60, 10; }
            STATICTEXT IDC_STATIC { NAME IDS_OPT_MAP_SPACING; CENTER_V; ALIGN_LEFT; }
            EDITNUMBERARROWS IDC_OPT_MAP_OPTIMAL_SPACING_EDIT
            { CENTER_V; FIT_H; SCALE_H; SIZE 60, 10; }
          }
        }
      }
      GROUP IDC_OPT_MAP_REALIGN_GROUP
      {
        NAME IDS_STATIC14; ALIGN_TOP; ALIGN_LEFT; 
        BORDERSIZE 0, 0, 0, 0; 
        COLUMNS 1;
        SPACE 4, 4;
        
        GROUP IDC_STATIC
        {
          NAME IDS_STATIC15; ALIGN_TOP; ALIGN_LEFT; 
          BORDERSIZE 0, 0, 0, 0; 
          COLUMNS 1;
          SPACE 4, 4;
          
          CHECKBOX IDC_OPT_MAP_REALIGN_PRESERVE_ORIENTATION_CHK { NAME IDS_OPT_MAP_PRESERVE_ORIENTATION1; ALIGN_TOP; ALIGN_LEFT;  }
          CHECKBOX IDC_OPT_MAP_REALIGN_STRETCHTOFIT_CHK { NAME IDS_OPT_MAP_REALIGN_STRETCHTOFIT; ALIGN_TOP; ALIGN_LEFT;  }
          CHECKBOX IDC_OPT_MAP_REALIGN_EQUALIZEAREA_CHK { NAME IDS_OPT_MAP_EQUALIZEAREA; ALIGN_TOP; ALIGN_LEFT;  }
          GROUP 
          {
            ALIGN_TOP; FIT_H; SCALE_H; 
            BORDERSIZE 0, 0, 0, 0; 
            COLUMNS 2;
            SPACE 4, 2;
            
            STATICTEXT  { NAME IDS_OPT_MAP_SPACING2; CENTER_V; ALIGN_LEFT; }
            EDITNUMBERARROWS IDC_OPT_MAP_REALIGN_SPACING_EDIT
            { CENTER_V; FIT_H; SCALE_H; SIZE 60, 10; }
          }
        }
      }
    }
  }
}