DIALOG IDD_RELAXUV_WORKING
{
	NAME TDLG;
	SCALE_H;
	
	GROUP
	{
		SCALE_H; 
		COLUMNS 1;
		BORDERSTYLE BORDER_NONE;
		BORDERSIZE 10,10,10,10;
		
		BUTTON IDC_RELAX_UV_STOP_BTN { SCALE_H; NAME T1; };				
	}
}