enum
{
	GV_STATUS_STRING = 1000,

	// OP Classes&Groups
	IDS_TP_OPCLASS,
	IDS_TP_OPGROUP_CONDITION,
	IDS_TP_OPGROUP_HELPER,
	IDS_TP_OPGROUP_INITIATOR,
	IDS_TP_OPGROUP_GENERATOR,
	IDS_TP_OPGROUP_STANDARD,
	IDS_TP_OPGROUP_DYNAMIC,
	/////


/// IF ParticleAge
	IDS_IF_PARTICLEAGE_NAME,
	IDS_IF_PARTICLEAGE_DESCRIPTION,
///

/// IF_Light
	IDS_IF_LIGHT_NAME,
	IDS_IF_LIGHT_DESCRIPTION,
///

/// HP_ParticleData
	IDS_HP_PARTICLEDATA_NAME,
	IDS_HP_PARTICLEDATA_DESCRIPTION,
///
/// HP_SpinConvert
	IDS_HP_SPINCONVERT_NAME,
	IDS_HP_SPINCONVERT_DESCRIPTION,
///
/// HP_SpinConvert
	IDS_HP_VELOCITYCONVERT_NAME,
	IDS_HP_VELOCITYCONVERT_DESCRIPTION,
///
/// HP_PGroup
	IDS_HP_PGROUP_NAME,
	IDS_HP_PGROUP_DESCRIPTION,
///

/// HP_Timer
	IDS_HP_TIMER_NAME,
	IDS_HP_TIMER_DESCRIPTION,
///

/// HP_TimeBase
	IDS_HP_CHRONOMETER_NAME,
	IDS_HP_CHRONOMETER_DESCRIPTION,
///

/// HP_SurfacePosition
	IDS_HP_SURFACEPOSITION_NAME,
	IDS_HP_SURFACEPOSITION_DESCRIPTION,
///

/// HP_VolumePosition
	IDS_HP_VOLUMEPOSITION_NAME,
	IDS_HP_VOLUMEPOSITION_DESCRIPTION,
///

/// IN_Selfdynamic
	IDS_IN_SELFDYNAMIC_NAME,
	IDS_IN_SELFDYNAMIC_DESCRIPTION,
///

/// IN_Selfdynamic
	IDS_IN_INTERACT_NAME,
	IDS_IN_INTERACT_DESCRIPTION,
///

/// OP_ParticleData
	IDS_OP_PARTICLEDATA_NAME,
	IDS_OP_PARTICLEDATA_DESCRIPTION,
///

/// OP_ObjectShape
	IDS_OP_OBJECTSHAPE_NAME,
	IDS_OP_OBJECTSHAPE_DESCRIPTION,
///

/// OP_Deflector
	IDS_OP_DEFLECTOR_NAME,
	IDS_OP_DEFLECTOR_DESCRIPTION,
///

/// OP_PosFollow
	IDS_OP_POSFOLLOW_NAME,
	IDS_OP_POSFOLLOW_DESCRIPTION,
///

/// OP_Spin
	IDS_OP_SPIN_NAME,
	IDS_OP_SPIN_DESCRIPTION,
///

/// OP_Alignment
	IDS_OP_ALIGNMENT_NAME,
	IDS_OP_ALIGNMENT_DESCRIPTION,
///

/// OP_Rolling
	IDS_OP_ROLLING_NAME,
	IDS_OP_ROLLING_DESCRIPTION,
///

/// OP_PGroup
	IDS_OP_PGROUP_NAME,
	IDS_OP_PGROUP_DESCRIPTION,
///

/// OP_Size
	IDS_OP_SIZE_NAME,
	IDS_OP_SIZE_DESCRIPTION,
///

/// OP_Mass
	IDS_OP_MASS_NAME,
	IDS_OP_MASS_DESCRIPTION,
///

/// OP_Freeze
	IDS_OP_FREEZE_NAME,
	IDS_OP_FREEZE_DESCRIPTION,
///

/// OP_RepulsBounce
	IDS_OP_REPULSEBOUNCE_NAME,
	IDS_OP_REPULSEBOUNCE_DESCRIPTION,
///

/// OP_Scale
	IDS_OP_SCALE_NAME,
	IDS_OP_SCALE_DESCRIPTION,
///

/// OP_Friction
	IDS_OP_FRICTION_NAME,
	IDS_OP_FRICTION_DESCRIPTION,
///

/// OP_Velocity
	IDS_OP_VELOCITY_NAME,
	IDS_OP_VELOCITY_DESCRIPTION,
///

/// OP_Buuble
	IDS_OP_BUBBLE_NAME,
	IDS_OP_BUBBLE_DESCRIPTION,
///

/// OP_MotionInheri
	IDS_OP_MOTIONINHERI_NAME,
	IDS_OP_MOTIONINHERI_DESCRIPTION,
///

/// OP_Die
	IDS_OP_DIE_NAME,
	IDS_OP_DIE_DESCRIPTION,
///

/// OP_Gravity
	IDS_OP_GRAVITY_NAME,
	IDS_OP_GRAVITY_DESCRIPTION,
///

/// OP_Wind
	IDS_OP_WIND_NAME,
	IDS_OP_WIND_DESCRIPTION,
///

/// OP_Storm
	IDS_OP_STORM_NAME,
	IDS_OP_STORM_DESCRIPTION,
///////

/// OP_Fragment
	IDS_OP_FRAGMENT_NAME,
	IDS_OP_FRAGMENT_DESCRIPTION,
	IDS_OP_FRAGMENT_EDGESSELECTION,
	IDS_OP_FRAGMENT_BACKSELECTION,
	IDS_OP_FRAGMENT_REDGESSELECTION,
	IDS_OP_FRAGMENT_RBACKSELECTION,
///

/// OP_Blurp
	IDS_OP_BLURP_NAME,
	IDS_OP_BLURP_DESCRIPTION,
	IDS_OP_BLURP_EDGESSELECTION,
	IDS_OP_BLURP_BACKSELECTION,
	IDS_OP_BLURP_REDGESSELECTION,
	IDS_OP_BLURP_RBACKSELECTION,
///

/// OP_Born
	IDS_OP_BORN_NAME,
	IDS_OP_BORN_DESCRIPTION,
///

/// OP_ParticleDraw
	IDD_OP_PARTICLEDRAWTOOL,
	IDS_OP_PARTICLEDRAW_NAME,
	IDS_OP_PARTICLEDRAW_DESCRIPTION,
	IDS_OP_PARTICLEDRAWTOOL_NAME,
	IDC_OP_PARTICLEDRAWTOOL_REMOVE,
	IDC_OP_PARTICLEDRAWTOOL_LIST,
///

/// OP_MatterWaves
	IDS_OP_MATTERWAVES_NAME,
	IDS_OP_MATTERWAVES_DESCRIPTION,
///


	_DEFDUMMY_
};

