CONTAINER ToolEdgeSelection
{
	NAME ToolEdgeSelection;
	INCLUDE ToolBase;

	GROUP MDATA_MAINGROUP
	{
		LONG MDATA_MWS_EDGEMODE { 
		   ALIGN_LEFT; CYCLE { 
		      MDATA_MWS_EDGEMODE_LOOP; 
		      MDATA_MWS_EDGEMODE_GUIDED; 
		      MDATA_MWS_EDGEMODE_LINE;
		      MDATA_MWS_EDGEMODE_LINE2;
		   } 
		}			   

	   SEPARATOR { LINE; }		   
		   
		//REAL MDATA_MWS_SP_LENWEIGHT { CUSTOMGUI REALSLIDER; MIN 0; MAX 1; STEP 0.01; }
		//REAL MDATA_MWS_SP_ANGLEWEIGHT { CUSTOMGUI REALSLIDER; MIN 0; MAX 1; STEP 0.01; }
		//REAL MDATA_MWS_SP_QUADWEIGHT { CUSTOMGUI REALSLIDER; MIN 0; MAX 1; STEP 0.01; }
		
		//SEPARATOR { LINE; }	
		
		BOOL MDATA_MWS_ADD_TO_SEL {}
	}
	
	GROUP MWS_TAG_GROUP
	{
		STRING MWS_TAG_LINK {}
		BOOL MWS_TAG_AUTO_SET_SEL {}
		BUTTON MWS_TAG_SET_SEL {}
		BUTTON MWS_TAG_ADD_SEL {}
		BUTTON MWS_TAG_REM_SEL {}		
	}
	
	HIDE MDATA_COMMANDGROUP;
}
