CONTAINER xuvpeelertool
{
	NAME xuvpeelertool;

	GROUP MDATA_UVPEELER_GROUP_OPTIONS
	{
		DEFAULT 1;

		GROUP
		{
			COLUMNS 1;

			REAL MDATA_UVPEELER_MIN_U { UNIT REAL; MIN 0.0; MAX 1.0; MINSLIDER 0.0; MAXSLIDER 1.0; STEP 0.01; CUSTOMGUI REALSLIDER; }
			REAL MDATA_UVPEELER_MAX_U { UNIT REAL; MIN 0.0; MAX 1.0; MINSLIDER 0.0; MAXSLIDER 1.0; STEP 0.01; CUSTOMGUI REALSLIDER; }
			REAL MDATA_UVPEELER_MIN_V { UNIT REAL; MIN 0.0; MAX 1.0; MINSLIDER 0.0; MAXSLIDER 1.0; STEP 0.01; CUSTOMGUI REALSLIDER; }
			REAL MDATA_UVPEELER_MAX_V { UNIT REAL; MIN 0.0; MAX 1.0; MINSLIDER 0.0; MAXSLIDER 1.0; STEP 0.01; CUSTOMGUI REALSLIDER; }
			REAL MDATA_UVPEELER_U_UNIFORMITY { UNIT PERCENT; MIN 0; MAX 100; MINSLIDER 0; MAXSLIDER 100; CUSTOMGUI REALSLIDER; }
			REAL MDATA_UVPEELER_V_UNIFORMITY { UNIT PERCENT; MIN 0; MAX 100; MINSLIDER 0; MAXSLIDER 100; CUSTOMGUI REALSLIDER; }
		}

		SEPARATOR { LINE; }

		GROUP 
		{
			LAYOUTGROUP; COLUMNS 2;

			GROUP
			{
				BOOL MDATA_UVPEELER_U_INVERT { }
				BOOL MDATA_UVPEELER_FIXED_RING_LENGTHS { }
			}

			GROUP
			{
				BOOL MDATA_UVPEELER_V_INVERT { }
				BOOL MDATA_UVPEELER_EQUIDISTANT_UNIFORMITY { }
			}
		}

		SEPARATOR { LINE; }

		LONG MDATA_UVPEELER_UV_ISLAND_STORAGE
		{
			CYCLE
			{
				MDATA_UVPEELER_SINGLE_UV_TILE;
				MDATA_UVPEELER_MULTIPLE_UV_TILES;
			}
			CUSTOMGUI RADIOBUTTONS; COLUMNS 2;
			ANIM OFF;
		}

		SEPARATOR { LINE; }

		BOOL MDATA_UVPEELER_RESTRICT_TO_TILES { }
	}

	GROUP MDATA_UVPEELER_GROUP_COMMANDGROUP
	{
		DEFAULT 1;

		GROUP
		{
			GROUP
			{
				COLUMNS 2;
				BOOL MDATA_UVPEELER_INTERACTIVE { }
				STATICTEXT MDATA_UVPEELER_INFOS_SEAMS {ANIM OFF; }
			}

			GROUP
			{
				COLUMNS 2;
				BUTTON MDATA_UVPEELER_APPLY { FIT_H; }
				BUTTON MDATA_UVPEELER_RESET { FIT_H; }
			}
		}
	}
}
		
