CONTAINER HP_Chronometer
{
	NAME HP_Chronometer;
	INCLUDE GVbase;

	GROUP ID_GVPROPERTIES
	{
	}

	GROUP ID_GVPORTS
	{
		LONG	CHR_TYPE			{ INPORT; EDITPORT;
													CYCLE
													{
														CHR_TYPE_RESET;
														CHR_TYPE_SUM;
													}
												}
		REAL	CHR_TFAC		{ INPORT; EDITPORT; UNIT PERCENT; }
		REAL	CHR_TVAR		{ INPORT; EDITPORT; UNIT PERCENT; MIN 0.0; MAX 100.0; }

		BOOL      	IN_CHR_ON				{ INPORT; PORTONLY; STATICPORT; CREATEPORT;  }
		TP_PARTICLE	IN_CHR_PARTICLE	{ INPORT; PORTONLY; }
		BASETIME   	IN_CHR_ATIME		{ INPORT; PORTONLY; }

		BASETIME		OUT_CHR_TIME    { OUTPORT;  PORTONLY; STATICPORT; CREATEPORT; }
	}
}
