CONTAINER HP_PGroup
{
	NAME HP_PGroup;
	INCLUDE GVbase;

	GROUP ID_GVPROPERTIES
	{
	}

	GROUP ID_GVPORTS
	{
		LINK			OUT_PG_LINK	{ INPORT;  EDITPORT; ACCEPT{ 1001381; }}
		
		TP_GROUP	OUT_PG_GROUP					{ OUTPORT; PORTONLY; CREATEPORT; }
		LONG			OUT_PG_PARTICLECOUNT	{ OUTPORT; PORTONLY; }
	}
}
