CONTAINER HP_SpinConvert
{
	NAME HP_SpinConvert;
	INCLUDE GVbase;

	GROUP ID_GVPROPERTIES
	{
	}

	GROUP ID_GVPORTS
	{
		REAL		IN_SPCON_SPEED	{ INPORT; EDITPORT; STATICPORT; CREATEPORT; }
		NORMAL	IN_SPCON_AXIS		{ INPORT; EDITPORT; STATICPORT; CREATEPORT; }
		
		TP_SPIN	OUT_SPCON_SPIN	{ OUTPORT; PORTONLY; STATICPORT; CREATEPORT; }
	}
}
