CONTAINER HP_Timer
{
	NAME HP_Timer;
	INCLUDE GVbase;

	GROUP ID_GVPROPERTIES
	{
	}

	GROUP ID_GVPORTS
	{
		BASETIME		TIM_TIME  { INPORT; EDITPORT; MIN 0; }
		BOOL				TIM_EXTEND{ INPORT; EDITPORT; }
		BOOL				TIM_SINGLE{ INPORT; EDITPORT; }

		TP_PARTICLE	IN_TIM_PARTICLE{ INPORT; PORTONLY; }
		BASETIME		IN_TIM_ATIME   { INPORT; PORTONLY; }
		BOOL				IN_TIM_START   { INPORT; STATICPORT; NEEDCONNECTION; CREATEPORT; PORTONLY; }


		BOOL				OUT_TIM_ON			{ OUTPORT; CREATEPORT; PORTONLY; ITERATOR; }
		BASETIME		OUT_TIM_TIME		{ OUTPORT; PORTONLY; ITERATOR;             }	
		REAL				OUT_TIM_PERCENT	{ OUTPORT; PORTONLY; ITERATOR;             }
		TP_PARTICLE	OUT_TIM_PARTICLE{ OUTPORT; PORTONLY; ITERATOR;             }
	}
}
