CONTAINER IF_Light
{
	NAME IF_Light;
	INCLUDE GVbase;

	GROUP ID_GVPROPERTIES
	{
	}

	GROUP ID_GVPORTS
	{
		LINK				TP_IF_LIGHT_LIGHT{ INPORT; EDITPORT; ACCEPT{ Olight; } }
		
	
		REAL				TP_IF_LIGHT_THRESH{ INPORT; EDITPORT; STEP 0.01;}
		BOOL				TP_IF_LIGHT_COLON	{ INPORT; EDITPORT; }
		COLOR				TP_IF_LIGHT_COLOR	{ INPORT; EDITPORT; }
		REAL				TP_IF_LIGHT_COLVAR{ INPORT; EDITPORT; UNIT PERCENT; MIN 0.0; MAX 100.0; STEP 0.01; }
	
		VECTOR			TP_IF_LIGHT_POSITION{ INPORT; EDITPORT; CREATEPORT;}
		NORMAL			TP_IF_LIGHT_NORMAL	{ INPORT; EDITPORT; }
		
		
		BASETIME   	TP_IF_LIGHT_ATIME		{ INPORT; PORTONLY; }

		BOOL				TP_OUT_IF_LIGHT_ON				{ OUTPORT; PORTONLY; CREATEPORT; }
		REAL				TP_OUT_IF_LIGHT_INTENSITY	{ OUTPORT; PORTONLY; }
		COLOR				TP_OUT_IF_LIGHT_COLOR			{ OUTPORT; PORTONLY; }
		NORMAL			TP_OUT_IF_LIGHT_DIRECTION	{ OUTPORT; PORTONLY; }
	}
}
