CONTAINER IF_ParticleAge
{
	NAME IF_ParticleAge;
	INCLUDE GVbase;

	GROUP ID_GVPROPERTIES
	{
	}

	GROUP ID_GVPORTS
	{
		LONG				PAGE_TYPE		{ INPORT; EDITPORT;  
															CYCLE
															{
																PAGE_TYPE_BORN;
																PAGE_TYPE_DIE;
																PAGE_TYPE_ENTERSGROUP;
																PAGE_TYPE_RELATIVE;
																PAGE_TYPE_ABSOLUTE;
															}
														}
	
		REAL				PAGE_T1			{ INPORT; EDITPORT; UNIT PERCENT; MIN 0.0; MAX 100.0; STEP 1.0;}
		REAL				PAGE_T2			{ INPORT; EDITPORT; UNIT PERCENT; MIN 0.0; MAX 100.0; STEP 1.0;}
		BASETIME		PAGE_ABST1  { INPORT; EDITPORT; MIN 0; STEP 1;}
		BASETIME		PAGE_ABST2  { INPORT; EDITPORT; MIN 0; STEP 1;}

		TP_PARTICLE	IN_PAGE_PARTICLE	{ INPORT; PORTONLY; STATICPORT; NEEDCONNECTION; CREATEPORT; }
		BASETIME   	IN_PAGE_ATIME			{ INPORT; PORTONLY; }

		BOOL				OUT_PAGE_ON				{ OUTPORT; PORTONLY; STATICPORT; CREATEPORT;}
	}
}
