CONTAINER IN_Interact
{
	NAME IN_Interact;
	INCLUDE GVbase;

	GROUP ID_GVPROPERTIES
	{
	}

	GROUP ID_GVPORTS
	{
		LINK		INT_GROUPA	{ INPORT; EDITPORT; ACCEPT{ 1001381; }}
		LINK		INT_GROUPB	{ INPORT; EDITPORT; ACCEPT{ 1001381; }}

		LONG		INT_DTYPE 	{ INPORT; EDITPORT; CYCLE
													{
														INTERACT_DTYPE_NONE;
														INTERACT_DTYPE_INSIDE;
														INTERACT_DTYPE_OUTSIDE;
													}
												}
		REAL		INT_DISTANCE{ INPORT; EDITPORT; MIN 0.0; STEP 0.1;}

		
		TP_PARTICLE	OUT_INTERACT_PARTICLE_A     	{ OUTPORT; PORTONLY; CREATEPORT; ITERATOR;}
		TP_PARTICLE	OUT_INTERACT_PARTICLE_B      	{ OUTPORT; PORTONLY; CREATEPORT; ITERATOR;}
		LONG				OUT_INTERACT_PARTICLECOUNT_A	{ OUTPORT; PORTONLY; ITERATOR;}
		LONG				OUT_INTERACT_PARTICLECOUNT_B	{ OUTPORT; PORTONLY; ITERATOR;}
		VECTOR			OUT_INTERACT_POSITION_A	      { OUTPORT; PORTONLY; ITERATOR;}
		VECTOR			OUT_INTERACT_POSITION_B	      { OUTPORT; PORTONLY; ITERATOR;}
		VECTOR			OUT_INTERACT_VECTOR_AB	      { OUTPORT; PORTONLY; ITERATOR;}
		REAL  			OUT_INTERACT_DISTANCE_AB      { OUTPORT; PORTONLY; ITERATOR;}
	}
}
