CONTAINER IN_Selfdynamic
{
	NAME IN_Selfdynamic;
	INCLUDE GVbase;

	GROUP ID_GVPROPERTIES
	{
	}

	GROUP ID_GVPORTS
	{
		LINK		SELF_LINK	{ INPORT; EDITPORT; ACCEPT { 1001381; } }
		
		TP_PARTICLE	OUT_SELF_PARTICLE	      { OUTPORT; PORTONLY; CREATEPORT; ITERATOR; }
		LONG				OUT_SELF_PARTICLECOUNT	{ OUTPORT; PORTONLY; ITERATOR; }
		LONG				OUT_SELF_INDEX					{ OUTPORT; PORTONLY; ITERATOR; }
	}
}
