CONTAINER OP_Bubble
{
	NAME OP_Bubble;
	INCLUDE GVbase;

	GROUP ID_GVPROPERTIES
	{
	}

	GROUP ID_GVPORTS
	{
		REAL				BUB_AMP						{ INPORT; EDITPORT; MIN 0.0; STEP 0.1; }
		REAL				BUB_AMPVAR				{ INPORT; EDITPORT; UNIT PERCENT; MIN 0.0; MAX 100.0; STEP 1.0; }
		REAL				BUB_PERIOD				{ INPORT; EDITPORT; UNIT PERCENT; MIN 0.0; STEP 1.0; }
		REAL				BUB_PERIODVAR			{ INPORT; EDITPORT; UNIT PERCENT; MIN 0.0; MAX 100.0; STEP 1.0; }
		REAL				BUB_PHASEVAR			{ INPORT; EDITPORT; UNIT DEGREE;  MIN 0.0; STEP 1.0; }

		
		BOOL      	IN_BUB_ON				{ INPORT; PORTONLY; }
		BASETIME   	IN_BUB_ATIME		{ INPORT; PORTONLY; }
		TP_PARTICLE	IN_BUB_PARTICLE	{ INPORT; PORTONLY; STATICPORT; NEEDCONNECTION; CREATEPORT; }
	}
}
