CONTAINER OP_Born
{
	NAME OP_Born;
	INCLUDE GVbase;

	GROUP ID_GVPROPERTIES
	{
		LONG OP_BORN_SEED { MIN 0; }
	}

	GROUP ID_GVPORTS
	{
		LONG	OP_BORN_BTYPE{	INPORT; EDITPORT; 
													CYCLE
													{
														OP_BORN_BTYPE_COUNT;
														OP_BORN_BTYPE_RATE;
														OP_BORN_BTYPE_SHOT;
													}
												}
	
		LONG			OP_BORN_COUNT		  { INPORT; EDITPORT; MIN 0;   }
		REAL			OP_BORN_RATE			{ INPORT; EDITPORT; MIN 0.0; }
		LONG			OP_BORN_SHOT			{ INPORT; EDITPORT; MIN 0;   }
		BASETIME	OP_BORN_LIFE			{ INPORT; EDITPORT; MIN 0.0; MINEX; }
		REAL      OP_BORN_LIFEVAR	  { INPORT; EDITPORT; UNIT PERCENT; MIN 0.0; MAX 100.0; }

		BOOL      	OP_BORN_IN_ON			{ INPORT; PORTONLY; }
		BASETIME   	OP_BORN_IN_ATIME	{ INPORT; PORTONLY; }
		
		TP_PARTICLE OP_BORN_OUT_PARTICLE     { OUTPORT; PORTONLY; CREATEPORT; ITERATOR; }
		LONG				OP_BORN_OUT_PARTICLECOUNT{ OUTPORT; PORTONLY; ITERATOR; }
		LONG				OP_BORN_OUT_PARTICLENUM  { OUTPORT; PORTONLY; ITERATOR; }
	}
}
