CONTAINER OP_Blurp
{
	NAME OP_Blurp;
	INCLUDE GVbase;

	GROUP ID_GVPROPERTIES
	{
	}

	GROUP ID_GVPORTS
	{
		SCALE_V;
		IN_EXCLUDE  OP_BLURP_OBJECTS  {  NUM_FLAGS 0; SEND_SELCHNGMSG 1; INIT_STATE 0; IMAGE_01_ON 1009316; IMAGE_01_OFF 1009320; ACCEPT { Obase; } REFUSE { 1001414;} }
		
		REAL				OP_BLURP_PHASE		{ INPORT; UNIT PERCENT; MIN 0.0; MAX 100.0; STEP 1.0; EDITPORT; }
		
		REAL				OP_BLURP_STAY			{ UNIT PERCENT; MIN 0.0; }
		REAL				OP_BLURP_FRAG			{ UNIT PERCENT; MIN 0.0; }
		REAL				OP_BLURP_NEXT			{ UNIT PERCENT; MIN 0.0; }
		
		REAL				OP_BLURP_INTANGENT { MIN 0.0; EDITPORT; }
		REAL				OP_BLURP_OUTTANGENT{ MIN 0.0; EDITPORT; }
		
		LONG				OP_BLURP_FROMTO		{ CYCLE 
																		{ 
																			OP_BLURP_FROMTO_NZ_PZ;
																			OP_BLURP_FROMTO_PZ_NZ;
																			OP_BLURP_FROMTO_NY_PY;
																			OP_BLURP_FROMTO_PY_NY;
																			OP_BLURP_FROMTO_NX_PX;
																			OP_BLURP_FROMTO_PX_NX;
																		}
																	}
		LONG				OP_BLURP_TYPE			{ CYCLE 
																		{ 
																			OP_BLURP_TYPE_FACE; 
																			OP_BLURP_TYPE_SMOOTH;
																			OP_BLURP_TYPE_COUNT;
																		}
																	}
		REAL				OP_BLURP_SANGLE		{ UNIT DEGREE; MIN 0.0; MAX 180; STEP 1.0; }
		REAL				OP_BLURP_SRAD			{ UNIT PERCENT; MIN 0.0; STEP 1.0; }
		LONG				OP_BLURP_COUNT		{ MIN 0; }
		REAL				OP_BLURP_THICK		{ UNIT PERCENT; STEP 0.1; MIN 0.0; }
		BOOL				OP_BLURP_NOFRAG		{  }

		
		LONG				OP_BLURP_RTYPE		{ CYCLE 
																		{ 
																			OP_BLURP_RTYPE_NONE;
																			OP_BLURP_RTYPE_HOLLOW;
																			OP_BLURP_RTYPE_SOLID;
																		}
																	}

		REAL				OP_BLURP_RTHICK				{ UNIT PERCENT; STEP 0.1; MIN 0.0; }
	

		BOOL      	OP_BLURP_IN_ON				{ INPORT; PORTONLY; }
		BASETIME   	OP_BLURP_IN_ATIME			{ INPORT; PORTONLY; }

		TP_PARTICLE	OP_BLURP_OUT_REMAINING			{ OUTPORT; PORTONLY; ITERATOR;}
		LONG				OP_BLURP_OUT_REMAININGCOUNT	{	OUTPORT; PORTONLY; ITERATOR;}
		LONG        OP_BLURP_OUT_REMAININGNUM		{ OUTPORT; PORTONLY; ITERATOR;}
		
		TP_PARTICLE	OP_BLURP_OUT_FRAGMENT				{ OUTPORT; PORTONLY; ITERATOR;}
		LONG				OP_BLURP_OUT_FRAGMENTCOUNT	{	OUTPORT; PORTONLY; ITERATOR;}
		LONG        OP_BLURP_OUT_FRAGMENTNUM		{ OUTPORT; PORTONLY; ITERATOR;}
	}
}
