CONTAINER OP_Die
{
	NAME OP_Die;
	INCLUDE GVbase;

	GROUP ID_GVPROPERTIES
	{
	}

	GROUP ID_GVPORTS
	{
		REAL				DIE_TIME					{ INPORT; EDITPORT; MIN 0.0; STEP 0.01; }
		REAL				DIE_VAR						{ INPORT; EDITPORT; UNIT PERCENT; MIN 0.0; MAX 100.0; STEP 1.0; }

		TP_PARTICLE	IN_DIE_PARTICLE	{ INPORT; PORTONLY; STATICPORT; NEEDCONNECTION; CREATEPORT; }
		BOOL      	IN_DIE_ON				{ INPORT; PORTONLY; }
		BASETIME   	IN_DIE_ATIME		{ INPORT; PORTONLY; }
	}
}
