CONTAINER OP_Friction
{
	NAME OP_Friction;
	INCLUDE GVbase;

	GROUP ID_GVPROPERTIES
	{
	}

	GROUP ID_GVPORTS
	{
		REAL				FRIC_FRIC					{ INPORT; EDITPORT; }
		REAL				FRIC_SPINFRIC			{ INPORT; EDITPORT; }
		REAL				FRIC_MASSDEP			{ INPORT; EDITPORT; UNIT PERCENT; MIN -100.0; MAX 100.0; }
		REAL				FRIC_SIZEDEP			{ INPORT; EDITPORT; UNIT PERCENT; MIN -100.0; MAX 100.0; }

		BOOL      	IN_FRIC_ON				{ INPORT; PORTONLY; }
		BASETIME   	IN_FRIC_ATIME			{ INPORT; PORTONLY; }
		TP_PARTICLE	IN_FRIC_PARTICLE	{ INPORT; PORTONLY; STATICPORT; NEEDCONNECTION; CREATEPORT; }
	}
}
