CONTAINER OP_Freeze
{
	NAME OP_Freeze;
	INCLUDE GVbase;

	GROUP ID_GVPROPERTIES
	{
	}

	GROUP ID_GVPORTS
	{
		REAL				FREEZE_FREEZE		{ INPORT; EDITPORT; UNIT PERCENT; MIN 0.0; MAX 100.0; }
		REAL				FREEZE_VAR			{ INPORT; EDITPORT; UNIT PERCENT; MIN 0.0; MAX 100.0; }
		BOOL        FREEZE_OVERAGE	{ INPORT; EDITPORT; }
		GRADIENT		FREEZE_AGEGRAD	{ INPORT; EDITPORT; ALPHA; }

		BOOL      	IN_FREEZE_ON				{ INPORT; PORTONLY; }
		BASETIME   	IN_FREEZE_ATIME			{ INPORT; PORTONLY; }
		TP_PARTICLE	IN_FREEZE_PARTICLE	{ INPORT; PORTONLY; STATICPORT; NEEDCONNECTION; CREATEPORT; }
	}
}
