CONTAINER OP_Gravity
{
	NAME OP_Gravity;
	INCLUDE GVbase;

	GROUP ID_GVPROPERTIES
	{
		REAL  GRAV_ICONSIZE   { MIN 0.0; }
	}

	GROUP ID_GVPORTS
	{
		LINK				GRAV_OBJECT       { INPORT; EDITPORT; ACCEPT{ Obase; }}
		
		LONG        GRAV_TYPE         { INPORT; EDITPORT; 
																		CYCLE
																		{
																			GRAV_TYPE_PLANAR;	
																			GRAV_TYPE_SPHERICAL;
																		}
																	}
		REAL				GRAV_STRENGTH			{ INPORT; EDITPORT; }
		REAL				GRAV_DECAY				{ INPORT; EDITPORT; MIN 0.0; }
		
		REAL				GRAV_MASSDEP			{ INPORT; EDITPORT; UNIT PERCENT; MIN -100.0; MAX 100.0; }
		REAL				GRAV_SIZEDEP			{ INPORT; EDITPORT; UNIT PERCENT; MIN -100.0; MAX 100.0; }

		BOOL      	IN_GRAV_ON				{ INPORT; PORTONLY; }
		BASETIME   	IN_GRAV_ATIME			{ INPORT; PORTONLY; }
		TP_PARTICLE	IN_GRAV_PARTICLE	{ INPORT; PORTONLY; STATICPORT; NEEDCONNECTION; CREATEPORT; }
	}
}
