CONTAINER OP_MatterWaves
{
	NAME OP_MatterWaves;
	INCLUDE GVbase;

	GROUP ID_GVPROPERTIES
	{
		LONG OP_MATTERWAVES_SEED { MIN 0; }
	}

	GROUP ID_GVPORTS
	{
		SCALE_V;
		LINK			OP_MATTERWAVES_OBJECT	  { INPORT; EDITPORT; ACCEPT{ Obase; } }
		STRING		OP_MATTERWAVES_SELECTION{ INPORT; EDITPORT; }
		STRING		OP_MATTERWAVES_UVW			{ INPORT; EDITPORT; }
		LONG			OP_MATTERWAVES_UVWTYPE	{	INPORT; EDITPORT; 
																				CYCLE
																				{
																					OP_MATTERWAVES_UVWTYPE_CLAMP;
																					OP_MATTERWAVES_UVWTYPE_UNCLAMP;
																				}
																			}
		
		IN_EXCLUDE  OP_MATTERWAVES_LIGHTLIST{ INPORT; EDITPORT; NUM_FLAGS 0; INIT_STATE 0; IMAGE_01_ON 1009316; IMAGE_01_OFF 1009320; ACCEPT { Olight; } }

		SEPARATOR { LINE; }

		LONG	OP_MATTERWAVES_BTYPE{	INPORT; EDITPORT; 
																CYCLE
																{
																	OP_MATTERWAVES_BTYPE_COUNT;
																	OP_MATTERWAVES_BTYPE_RATE;
																	OP_MATTERWAVES_BTYPE_SHOT;
																}
															}
	
		LONG			OP_MATTERWAVES_COUNT		{ INPORT; EDITPORT; MIN 0;   }
		REAL			OP_MATTERWAVES_RATE			{ INPORT; EDITPORT; MIN 0.0; }
		LONG			OP_MATTERWAVES_SHOT			{ INPORT; EDITPORT; MIN 0;   }

		LONG			OP_MATTERWAVES_BIRTHTYPE {	INPORT; EDITPORT;
																					CYCLE
																					{
																						OP_MATTERWAVES_BIRTHTYPE_CONSTANT;
																						OP_MATTERWAVES_BIRTHTYPE_MAP;
																						OP_MATTERWAVES_BIRTHTYPE_LIGHT;
																						OP_MATTERWAVES_BIRTHTYPE_MAPLIGHT;
																					}	
																			 }

		SHADERLINK	OP_MATTERWAVES_BIRTHTEX { INPORT; EDITPORT; }
		GRADIENT	OP_MATTERWAVES_BIRTHGRAD{INPORT; EDITPORT; ALPHA;}
		
		SEPARATOR { LINE; }

		BASETIME	OP_MATTERWAVES_LIFE			{ INPORT; EDITPORT; MIN 0.0; MINEX; }
		REAL      OP_MATTERWAVES_LIFEVAR	{ INPORT; EDITPORT; UNIT PERCENT; MIN 0.0; MAX 100.0; }
		LONG			OP_MATTERWAVES_LIFETYPE { INPORT; EDITPORT;
																				CYCLE
																				{
																					OP_MATTERWAVES_LIFETYPE_CONSTANT;
																					OP_MATTERWAVES_LIFETYPE_MAP;
																					OP_MATTERWAVES_LIFETYPE_LIGHT;
																					OP_MATTERWAVES_LIFETYPE_MAPLIGHT;
																				}	
																			}
		SHADERLINK	OP_MATTERWAVES_LIFETEX {INPORT; EDITPORT; }
		GRADIENT	OP_MATTERWAVES_LIFEGRAD{INPORT; EDITPORT; ALPHA;}

		SEPARATOR { LINE; }

		REAL			OP_MATTERWAVES_SPEED		{ INPORT; EDITPORT; }
		REAL      OP_MATTERWAVES_SPEEDVAR	{ INPORT; EDITPORT; UNIT PERCENT; MIN 0.0; MAX 100.0; }
		LONG			OP_MATTERWAVES_SPEEDTYPE{ INPORT; EDITPORT;
																				CYCLE
																				{
																					OP_MATTERWAVES_SPEEDTYPE_CONSTANT;
																					OP_MATTERWAVES_SPEEDTYPE_MAP;
																					OP_MATTERWAVES_SPEEDTYPE_LIGHT;
																					OP_MATTERWAVES_SPEEDTYPE_MAPLIGHT;
																				}	
																			}
		SHADERLINK	OP_MATTERWAVES_SPEEDTEX {INPORT; EDITPORT; }
		GRADIENT	OP_MATTERWAVES_SPEEDGRAD{INPORT; EDITPORT; ALPHA;}	
		
		SEPARATOR { LINE; }

		REAL			OP_MATTERWAVES_SIZE		 { INPORT; EDITPORT; }
		REAL      OP_MATTERWAVES_SIZEVAR { INPORT; EDITPORT; UNIT PERCENT; MIN 0.0; MAX 100.0; }
		LONG			OP_MATTERWAVES_SIZETYPE{ INPORT; EDITPORT;
																				CYCLE
																				{
																					OP_MATTERWAVES_SIZETYPE_CONSTANT;
																					OP_MATTERWAVES_SIZETYPE_MAP;
																					OP_MATTERWAVES_SIZETYPE_LIGHT;
																					OP_MATTERWAVES_SIZETYPE_MAPLIGHT;
																				}	
																			}
		SHADERLINK	OP_MATTERWAVES_SIZETEX {INPORT; EDITPORT; }
		GRADIENT	OP_MATTERWAVES_SIZEGRAD{INPORT; EDITPORT; ALPHA;}

		SEPARATOR { LINE; }
		
		REAL			OP_MATTERWAVES_DISTANCE	{ INPORT; EDITPORT; }
		REAL      OP_MATTERWAVES_DISTVAR	{ INPORT; EDITPORT; UNIT PERCENT; MIN 0.0; MAX 100.0; }
		LONG			OP_MATTERWAVES_DISTTYPE {	INPORT; EDITPORT;
																				CYCLE
																				{
																					OP_MATTERWAVES_DISTTYPE_CONSTANT;
																					OP_MATTERWAVES_DISTTYPE_MAP;
																					OP_MATTERWAVES_DISTTYPE_LIGHT;
																					OP_MATTERWAVES_DISTTYPE_MAPLIGHT;
																				}	
																			}
		SHADERLINK	OP_MATTERWAVES_DISTTEX {INPORT; EDITPORT; }
		GRADIENT	OP_MATTERWAVES_DISTGRAD{INPORT; EDITPORT; ALPHA;}
		
		SEPARATOR { LINE; }

		REAL			OP_MATTERWAVES_DIRINTENS{ INPORT; EDITPORT; UNIT PERCENT; MIN 0.0;}
		REAL      OP_MATTERWAVES_DIRVAR 	{ INPORT; EDITPORT; UNIT DEGREE; MIN 0.0; MAX 180.0; }

		LONG			OP_MATTERWAVES_DIRTYPE { INPORT; EDITPORT;
																			 CYCLE
																			 {
																					OP_MATTERWAVES_DIRTYPE_NORMAL;
																					OP_MATTERWAVES_DIRTYPE_MAP;
																					OP_MATTERWAVES_DIRTYPE_LIGHTDIR;
																					OP_MATTERWAVES_DIRTYPE_LIGHTREF;
																			 }	
																		 }
		SHADERLINK	OP_MATTERWAVES_DIRTEX {INPORT; EDITPORT; }
		GRADIENT	OP_MATTERWAVES_DIRGRAD{INPORT; EDITPORT; ALPHA;}


		BOOL      	OP_MATTERWAVES_IN_ON			{ INPORT; PORTONLY; }
		BASETIME   	OP_MATTERWAVES_IN_ATIME		{ INPORT; PORTONLY; }
		TP_PARTICLE	OP_MATTERWAVES_IN_PARTICLE{ INPORT; PORTONLY; }
		
		TP_PARTICLE OP_MATTERWAVES_OUT_PARTICLE     { OUTPORT; PORTONLY; CREATEPORT; ITERATOR; }
		LONG				OP_MATTERWAVES_OUT_PARTICLECOUNT{ OUTPORT; PORTONLY; ITERATOR; }
		LONG				OP_MATTERWAVES_OUT_PARTICLENUM  { OUTPORT; PORTONLY; ITERATOR; }
		VECTOR			OP_MATTERWAVES_OUT_UVW				  { OUTPORT; PORTONLY; ITERATOR; }
	}
}
