CONTAINER OP_MotionInheritance
{
	NAME OP_MotionInheritance;
	INCLUDE GVbase;

	GROUP ID_GVPROPERTIES
	{
	}

	GROUP ID_GVPORTS
	{
		LINK				MINH_OBJECT		{ INPORT; EDITPORT; ACCEPT{ Obase; }}
		
		REAL				MINH_INHERI		{ INPORT; EDITPORT; UNIT PERCENT; }
		REAL				MINH_VAR			{ INPORT; EDITPORT; UNIT PERCENT; MIN 0.0; MAX 100.0; }
		REAL        MINH_ROTINHERI{ INPORT; EDITPORT; UNIT PERCENT; }
		REAL				MINH_ROTVAR		{ INPORT; EDITPORT; UNIT PERCENT; MIN 0.0; MAX 100.0; }
		REAL				MINH_DIRVAR		{ INPORT; EDITPORT; UNIT DEGREE; MIN 0.0; }
		LONG        MINH_DTYPE		{ INPORT; EDITPORT; 
																CYCLE
																{
																	MINH_DTYPE_NONE;
																	MINH_DTYPE_SPHERE;
																	MINH_DTYPE_CYLINDER;
																}
															}	
		REAL				MINH_DIST			{ INPORT; EDITPORT; MIN 0.0; }
		GRADIENT		MINH_DGRAD		{ INPORT; EDITPORT; ALPHA; }
		LONG				MINH_CAXIS		{ INPORT; EDITPORT; 
																CYCLE
																{
																	MINH_CAXIS_X;
																	MINH_CAXIS_Y;
																	MINH_CAXIS_Z;
																}
															}	

		REAL				MINH_CHEIGHT	{ INPORT; EDITPORT; MIN 0.0; }
		GRADIENT		MINH_CGRAD		{ INPORT; EDITPORT; ALPHA; }
		GRADIENT		MINH_SGRAD		{ INPORT; EDITPORT; ALPHA; }
	

		BOOL      	IN_MINH_ON				{ INPORT; PORTONLY; }
		BASETIME   	IN_MINH_ATIME			{ INPORT; PORTONLY; }
		TP_PARTICLE	IN_MINH_PARTICLE	{ INPORT; PORTONLY; STATICPORT; NEEDCONNECTION; CREATEPORT; }
	}
}
