CONTAINER OP_Mass
{
	NAME OP_Mass;
	INCLUDE GVbase;

	GROUP ID_GVPROPERTIES
	{
	}

	GROUP ID_GVPORTS
	{
		REAL				MASS_MASS			{ INPORT; EDITPORT; MIN 0.0; }
		REAL				MASS_VAR      { INPORT; EDITPORT; UNIT PERCENT; MIN 0.0; MAX 100.0; }
		BOOL        MASS_OVERAGE	{ INPORT; EDITPORT; }
		GRADIENT		MASS_AGEGRAD	{ INPORT; EDITPORT; ALPHA; }

		BOOL      	IN_MASS_ON				{ INPORT; PORTONLY; }
		BASETIME   	IN_MASS_ATIME			{ INPORT; PORTONLY; }
		TP_PARTICLE	IN_MASS_PARTICLE	{ INPORT; PORTONLY; STATICPORT; NEEDCONNECTION; CREATEPORT; }
	}
}
