CONTAINER OP_ObjectShape
{
	NAME OP_ObjectShape;
	INCLUDE GVbase;

	GROUP ID_GVPROPERTIES
	{
	}

	GROUP ID_GVPORTS
	{
		LINK	OSHAPE_OBJECT							{ INPORT; EDITPORT; ACCEPT{ Obase; } }
		REAL	OSHAPE_RADIUS							{ INPORT; EDITPORT; MIN 0.0; }
		BOOL  OSHAPE_RENDERINSTANCE			{ INPORT; EDITPORT; }
	
		BOOL      	IN_OSHAPE_ON				{ INPORT; PORTONLY; }
		BASETIME   	IN_OSHAPE_ATIME			{ INPORT; PORTONLY; }
		TP_PARTICLE	IN_OSHAPE_PARTICLE	{ INPORT; PORTONLY; STATICPORT; NEEDCONNECTION; CREATEPORT; }
	}
}
