CONTAINER OP_ParticleDraw
{
	NAME OP_ParticleDraw;
	INCLUDE GVbase;

	GROUP ID_GVPROPERTIES
	{
		LONG	OP_PARTICLEDRAW_TYPE{
																CYCLE
																{
																	OP_PARTICLEDRAW_TYPE_POINT;
																	OP_PARTICLEDRAW_TYPE_SPHERICAL;
																}
															}

		REAL	 OP_PARTICLEDRAW_RADIUS{ MIN 0.0; }
		LONG	 OP_PARTICLEDRAW_COUNT	{ MIN 1; }
		VECTOR OP_PARTICLEDRAW_DRAWPOS{}

		BASETIME	OP_PARTICLEDRAW_LIFE   { MIN 0.0; MINEX;}
		REAL      OP_PARTICLEDRAW_LIFEVAR{ UNIT PERCENT; MIN 0.0; MAX 100.0; STEP 1.0; }

		LONG OP_PARTICLEDRAW_SEED { MIN 0; }

		BUTTON OP_PARTICLEDRAW_REMOVE {}
	}

	GROUP ID_GVPORTS
	{
	
		BOOL      	OP_PARTICLEDRAW_ON		{ INPORT; PORTONLY; }
		BASETIME   	OP_PARTICLEDRAW_ATIME	{ INPORT; PORTONLY; }

		TP_PARTICLE OP_PARTICLEDRAW_OUT_PARTICLE     { OUTPORT; PORTONLY; ITERATOR; }
		LONG				OP_PARTICLEDRAW_OUT_PARTICLECOUNT{ OUTPORT; PORTONLY; ITERATOR; }
		LONG				OP_PARTICLEDRAW_OUT_PARTICLENUM  { OUTPORT; PORTONLY; ITERATOR; }
	}
}
