CONTAINER OP_PGroup
{
	NAME OP_PGroup;
	INCLUDE GVbase;

	GROUP ID_GVPROPERTIES
	{
	}

	GROUP ID_GVPORTS
	{
		LINK				IN_PG_LINK		{ INPORT; EDITPORT; ACCEPT{ 1001381;} }
				
		BOOL      	IN_PG_ON				{ INPORT; PORTONLY; }
		TP_PARTICLE	IN_PG_PARTICLE	{ INPORT; PORTONLY; STATICPORT; NEEDCONNECTION; CREATEPORT; }
	}
}
