CONTAINER OP_PosFollow
{
	NAME OP_PosFollow;
	INCLUDE GVbase;

	GROUP ID_GVPROPERTIES
	{
	}

	GROUP ID_GVPORTS
	{
		LONG					PFO_TYPE    {INPORT; EDITPORT; 
																CYCLE
																{
																	PFO_TYPE_CONST;
																	PFO_TYPE_SPRING;
																}
															} 	
		
		REAL					PFO_CONSTSPEED {INPORT; EDITPORT; MIN 0.0; STEP 0.1; }
		REAL					PFO_SPRINGSPEED{INPORT; EDITPORT; UNIT PERCENT; MIN 0.0; MAX 100.0; STEP 1.0; }
	
		VECTOR     		PFO_POSITION	{INPORT; EDITPORT; }


		BOOL      	IN_PFO_ON				{ INPORT; PORTONLY; }
		BASETIME   	IN_PFO_ATIME		{ INPORT; PORTONLY; }
		TP_PARTICLE	IN_PFO_PARTICLE	{ INPORT; PORTONLY; STATICPORT; NEEDCONNECTION; CREATEPORT; }
	}
}
