CONTAINER OP_RepulseBounce
{
	NAME OP_RepulseBounce;
	INCLUDE GVbase;

	GROUP ID_GVPROPERTIES
	{
	}

	GROUP ID_GVPORTS
	{
		REAL				RB_REPULSION	{ INPORT; EDITPORT; UNIT PERCENT;}
		REAL				RB_BOUNCE			{ INPORT; EDITPORT; UNIT PERCENT; MIN 0.0; }
		REAL				RB_ELAST			{ INPORT; EDITPORT; UNIT PERCENT; MIN 0.0; }
		REAL				RB_MASS				{ INPORT; EDITPORT; UNIT PERCENT; MIN 0.0; }

		BOOL      	IN_RB_ON				{ INPORT; PORTONLY; }
		BASETIME   	IN_RB_ATIME			{ INPORT; PORTONLY; }
		TP_PARTICLE	IN_RB_PARTICLEA	{ INPORT; PORTONLY; STATICPORT; NEEDCONNECTION; CREATEPORT; }
		TP_PARTICLE	IN_RB_PARTICLEB	{ INPORT; PORTONLY; STATICPORT; NEEDCONNECTION; CREATEPORT; }
	}
}
