CONTAINER OP_Wind
{
	NAME OP_Wind;
	INCLUDE GVbase;

	GROUP ID_GVPROPERTIES
	{
		REAL  WIND_ICONSIZE   { MIN 0.0; }
	}

	GROUP ID_GVPORTS
	{
		LINK	WIND_OBJECT			{ INPORT; EDITPORT; ACCEPT{ Obase; }}
		
		LONG	WIND_TYPE				{ INPORT; EDITPORT; 
														CYCLE
														{
															WIND_TYPE_PLANAR;
															WIND_TYPE_SPHERICAL;
														}
													}

		REAL	WIND_STRENGTH		{ INPORT; EDITPORT; }
		REAL	WIND_DECAY			{ INPORT; EDITPORT; MIN 0.0; }

		REAL	WIND_MASSDEP		{ INPORT; EDITPORT; UNIT PERCENT; MIN -100.0; MAX 100.0; }
		REAL	WIND_SIZEDEP		{ INPORT; EDITPORT; UNIT PERCENT; MIN -100.0; MAX 100.0; }
		

		
		REAL	WIND_TURBULENCE { INPORT; EDITPORT; MIN 0.0; }
		REAL  WIND_FREQUENCY	{ INPORT; EDITPORT; MIN 0.0; }
		REAL  WIND_SCALE			{ INPORT; EDITPORT; MIN 0.0; }




		BOOL      	IN_WIND_ON				{ INPORT; PORTONLY; }
		BASETIME   	IN_WIND_ATIME			{ INPORT; PORTONLY; }
		TP_PARTICLE	IN_WIND_PARTICLE	{ INPORT; PORTONLY; STATICPORT; NEEDCONNECTION; CREATEPORT; }
	}
}
