enum
{
	// IDs for the global string table
	STRING_CMD_SETTINGS = 10000,
	STRING_CMD_OKINO_NAME,

	// definitions for matrix dialog
	DLG_LISTVIEW,
	GADGET_LISTVIEW_GROUP,
	GADGET_LISTVIEW,
	SELECT_ALL,
	DESELECT_ALL,

	DLG_OVERWRITE,
	CMD_OVERWRITE,
	CMD_CANCEL,
	STRING_TMP_FILE_EXISTS,
	STRING_TMP_PART1,
	STRING_TMP_PART2,

	DLG_DEMOALERT,

	DUMMY_

};
