CONTAINER TLMarker
{
	NAME TLMarker;
	INCLUDE Obaselist;

	GROUP Obaselist
	{
		BASETIME	TLMARKER_TIME {ANIM OFF;}
		BASETIME	TLMARKER_LENGTH {ANIM OFF; MIN 0;}
		COLOR		TLMARKER_COLOR {ANIM OFF;}
		GROUP
		{
			COLUMNS 2;
			BOOL		TLMARKER_TASK {ANIM OFF;}
			BOOL		TLMARKER_DONE {ANIM OFF;}
		}
		STRING		TLMARKER_TEXT {CUSTOMGUI MULTISTRING; ANIM OFF;}

	}
}
