enum
{
	//global
	IDS_TITLE								= 10000,

	VIEWDATADIALOG = 50000,
	IDC_VIEW_DIALOG_GROUP,
	IDC_HISTORIYVIEWER,

	OPTINDIALOG = 51000,
	OPTINDIALOG_FINAL,
	IDC_OPTIN_GROUP,
	IDC_VIEWER,
	IDC_DECISSION,
	IDC_RADIO_PARTICIPATE,
	IDC_RADIO_NOT_PARTICIPATE,

	IDC_BUTTON_OK,
	IDC_BUTTON_REMIND_LATER,

	IDS_DESCRIPTION_HEADLINE,
	IDS_DESCRIPTION_PARAGRAPH,
	IDS_DESCRIPTION_SUBLINE,

	IDS_RADIO_PARTICIPATE,
	IDS_RADIO_NOT_PARTICIPATE,
	IDS_BUTTON_ACCEPT,
	IDS_BUTTON_REMIND_LATER,


	IDS_CONNECTING_TO_SERVER,
	IDS_SERVER_NOT_REACHABLE,

	METRICSPREFERENCES_MAIN_GROUP	= 60000,
	ENABLE_CHECKBOX,
	PREFSMETRICSPREFERENCES,
	ENABLE_COMMANDS_CHECKBOX,
	ENABLE_PREFERENCES_CHECKBOX,
	ENABLE_SYSTEM_INFO_CHECKBOX,
	GOTO_PREFERENCE_DIRECTORY,
	GOTO_SERVER_LOCATION,
	GOTO_HELP,
	DUMMY
};
