CONTAINER Osculptlayer
{
	NAME Osculptlayer;
	GROUP
	{
		REAL MDATA_STRENGTH { ANIM OFF; MIN -1000.0; MAX 1000.0; MINSLIDER 0.0; MAXSLIDER 100.0; UNIT PERCENT; STEP 1; CUSTOMGUI REALSLIDER; FIT_H; SCALE_H; }	
	}
}
