  CONTAINER Sculptprefs
  {
    NAME Sculptprefs;
  
    GROUP PREF_SCULPTPREF_MAIN_GROUP
    {
		DEFAULT 1;
		LAYOUTGROUP; COLUMNS 1;

		GROUP PREF_SCULPTPREF_BRUSH_STAMP_GROUP
		{
			DEFAULT 1;  
			REAL   PREF_SCULPTPREF_BRUSH_STAMP_GREYVALUE_DEFAULT { UNIT REAL; MIN 0.0; MAX 1.0; STEP 0.01; }
			BOOL   PREF_SCULPTPREF_BRUSH_STAMP_GREYVALUE_TOPLEFTPIXEL { }
			LONG   PREF_SCULPTPREF_BRUSH_STAMP_MATERIAL_SAMPLERES { }
		}

		GROUP PREF_SCULPTPREF_BRUSH_STENCIL_GROUP
		{
			DEFAULT 1;  
			REAL   PREF_SCULPTPREF_BRUSH_STENCIL_GREYVALUE_DEFAULT { UNIT REAL; MIN 0.0; MAX 1.0; STEP 0.01; }
			BOOL   PREF_SCULPTPREF_BRUSH_STENCIL_GREYVALUE_TOPLEFTPIXEL { }
			LONG   PREF_SCULPTPREF_BRUSH_STENCIL_MATERIAL_SAMPLERES { }
		}

		GROUP PREF_SCULPTPREF_POLYGONOBJECT_GROUP
		{
			DEFAULT 1;
			LONG PREF_SCULPTPREF_DISPLAY_POLYGONOBJECT_NORMALS_THRESHOLD { }
		}

		GROUP PREF_SCULPTPREF_OTHER_GROUP
		{
			DEFAULT 1;  
			BOOL PREF_SCULPTPREF_ALWAYS_UPDATE { }
			BOOL PREF_SCULPTPREF_RESPECT_SELECTIONS { }
		}
   }
 }