CONTAINER toolsculptbrushbase
{
	NAME toolsculptbrushbase;
	INCLUDE ToolBase;
  
	HIDE MDATA_COMMANDGROUP;

	GROUP
	{
		COLUMNS 4;
		BOOL MDATA_SCULPTBRUSH_SETTINGS_RADIUS_LINK { }				
		BOOL MDATA_SCULPTBRUSH_SETTINGS_STRENGTH_LINK {}
		BOOL MDATA_SCULPTBRUSH_MIRRORING_LINK { }
		BOOL MDATA_SCULPTBRUSH_SETTINGS_BACKFACE { }
	}

	GROUP
	{
		COLUMNS 3;							

		SEPARATOR { LINE; }
		STATICTEXT { JOINENDSCALE; }
		STATICTEXT { JOINEND; }
		
		BOOL MDATA_SCULPTBRUSH_SETTINGS_USEZOOMSCALE{ }
		LONG MDATA_SCULPTBRUSH_SETTINGS_PREVIEWMODE
		{
			CYCLE
			{
				MDATA_SCULPTBRUSH_SETTINGS_PREVIEWMODE_OFF;
				MDATA_SCULPTBRUSH_SETTINGS_PREVIEWMODE_SCREEN;
				MDATA_SCULPTBRUSH_SETTINGS_PREVIEWMODE_SURFACE;
			}
		}
		STATICTEXT { DUMMY; }
	}
	
	GROUP MDATA_SCULPTBRUSH_SETTINGS_GROUP
	{
		COLUMNS 3;

		GROUP
		{
			LAYOUTGROUP;
			COLUMNS 2;
			GROUP
			{
				STATICTEXT MDATA_SCULPTBRUSH_SETTINGS_BRUSHPRESET { NOTEXT; }
			}
			GROUP
			{
				COLUMNS 3;
				BUTTON MDATA_SCULPTBRUSH_SETTINGS_LOADBRUSHPRESET { }
				BUTTON MDATA_SCULPTBRUSH_SETTINGS_ADDBRUSHPRESET {  }
				BUTTON MDATA_SCULPTBRUSH_SETTINGS_RESET {  }
			}
		}

		SEPARATOR { LINE; }
		STATICTEXT { JOINENDSCALE; }
		STATICTEXT { JOINEND; }
			
		REAL MDATA_SCULPTBRUSH_SETTINGS_RADIUS { MIN 0.1; MINSLIDER 1; MAXSLIDER 100; CUSTOMGUI REALSLIDER; SCALE_H; }
		STATICTEXT { JOINENDSCALE; }
		BUTTON MDATA_SCULPTBRUSH_SETTINGS_RADIUS_MOD { ALIGN_LEFT; }

		REAL MDATA_SCULPTBRUSH_SETTINGS_STRENGTH { MIN 0.01; STEP 0.1; MINSLIDER 0.1; MAXSLIDER 100; CUSTOMGUI REALSLIDER; UNIT PERCENT; SCALE_H; }
		STATICTEXT { JOINENDSCALE; }
		BUTTON MDATA_SCULPTBRUSH_SETTINGS_STRENGTH_MOD { ALIGN_LEFT; }

		SEPARATOR MDATA_SCULPTBRUSH_SETTINGS_STRENGTH_LINE { LINE; }
		STATICTEXT { JOINENDSCALE; }
		STATICTEXT { JOINEND; }

		BOOL MDATA_SCULPTBRUSH_SETTINGS_STEADYSTROKE { }
		STATICTEXT { DUMMY; }
		STATICTEXT { DUMMY; }

		REAL MDATA_SCULPTBRUSH_SETTINGS_STEADYSTROKE_VALUE { MIN 0; MAX 100; CUSTOMGUI REALSLIDER; FIT_H; SCALE_H; }
		STATICTEXT { JOINENDSCALE; }
		STATICTEXT { JOINEND; }

		SEPARATOR MDATA_SCULPTBRUSH_SETTINGS_STEADYSTROKE_LINE { LINE; }
		STATICTEXT { JOINENDSCALE; }
		STATICTEXT { JOINEND; }

		BOOL MDATA_SCULPTBRUSH_SETTINGS_STAMPSPACING { }
		STATICTEXT { DUMMY; }
		STATICTEXT { DUMMY; }

		REAL MDATA_SCULPTBRUSH_SETTINGS_STAMPSPACING_VALUE { MIN 0.001; MAX 1000; STEP 0.1; MINSLIDER 0.1; MAXSLIDER 100; CUSTOMGUI REALSLIDER; FIT_H; SCALE_H; }
		STATICTEXT { JOINENDSCALE; }
		STATICTEXT { JOINEND; }

		SEPARATOR MDATA_SCULPTBRUSH_SETTINGS_STAMPSPACING_LINE { LINE; }
		STATICTEXT { JOINENDSCALE; }
		STATICTEXT { JOINEND; }

		GROUP MDATA_SCULPTBRUSH_SETTINGS_EDGE_GROUP
		{
			COLUMNS 1;
			BOOL MDATA_SCULPTBRUSH_SETTINGS_EDGE { }
			REAL MDATA_SCULPTBRUSH_SETTINGS_EDGE_ANGLE { UNIT DEGREE; MIN 1; MAX 90; CUSTOMGUI REALSLIDER; SCALE_H; FIT_H;}
		}
		STATICTEXT { JOINENDSCALE; }
		STATICTEXT { JOINEND; }

		SEPARATOR MDATA_SCULPTBRUSH_SETTINGS_EDGE_LINE { LINE; }
		STATICTEXT { JOINENDSCALE; }
		STATICTEXT { JOINEND; }

		GROUP
		{
			COLUMNS 3;
			LONG MDATA_SCULPTBRUSH_SETTINGS_DRAWMODE
			{
				CYCLE
				{
					MDATA_SCULPTBRUSH_SETTINGS_DRAWMODE_FREEHAND;
					MDATA_SCULPTBRUSH_SETTINGS_DRAWMODE_LINE;
					MDATA_SCULPTBRUSH_SETTINGS_DRAWMODE_LASSO_FILL;
					MDATA_SCULPTBRUSH_SETTINGS_DRAWMODE_POLY_FILL;
					MDATA_SCULPTBRUSH_SETTINGS_DRAWMODE_RECTANGLE_FILL;
				}
			}
			BOOL MDATA_SCULPTBRUSH_SETTINGS_DRAWMODE_FILL_SYMMETRY { }
			BOOL MDATA_SCULPTBRUSH_SETTINGS_FILL_BACKFACES { }
		}
		STATICTEXT { JOINENDSCALE; }
		STATICTEXT { JOINEND; }

		GROUP MDATA_SCULPTBRUSH_SETTINGS_DRAWDIR_GROUP
		{
			SEPARATOR { LINE; }
			GROUP 
			{
				LONG MDATA_SCULPTBRUSH_SETTINGS_DRAWDIR
				{
					CYCLE
					{
						MDATA_SCULPTBRUSH_SETTINGS_DRAWDIR_AVERAGENORMAL;
						MDATA_SCULPTBRUSH_SETTINGS_DRAWDIR_X;
						MDATA_SCULPTBRUSH_SETTINGS_DRAWDIR_Y;
						MDATA_SCULPTBRUSH_SETTINGS_DRAWDIR_Z;
						MDATA_SCULPTBRUSH_SETTINGS_DRAWDIR_CAMERA;
					}
				}
			}
		}
		STATICTEXT { JOINENDSCALE; }
		STATICTEXT { JOINEND; }

		SEPARATOR { LINE; }
		STATICTEXT { JOINENDSCALE; }
		STATICTEXT { JOINEND; }
	}

	GROUP MDATA_SCULPTBRUSH_FALLOFF_GROUP
	{
		GROUP
		{
			COLUMNS 1;
			BUTTON MDATA_SCULPTBRUSH_FALLOFF_RESET { }
		}
		SPLINE MDATA_SCULPTBRUSH_FALLOFF_SPLINE
		{ 
			SHOWGRID_H; SHOWGRID_V; GRIDSIZE_H 8; GRIDSIZE_V 8; EDIT_H; EDIT_V; LABELS_H; LABELS_V; HAS_PRESET_BTN; HAS_ROUND_SLIDER; 
		}
	}

	GROUP MDATA_SCULPTBRUSH_STAMP_GROUP
	{
		COLUMNS 3;

		GROUP
		{
			LAYOUTGROUP;
			COLUMNS 2;
			GROUP
			{
				STATICTEXT MDATA_SCULPTBRUSH_STAMP_PRESET { NOTEXT; }
			}
			GROUP
			{
				COLUMNS 3;
				BUTTON MDATA_SCULPTBRUSH_STAMP_LOADPRESET { }
				BUTTON MDATA_SCULPTBRUSH_STAMP_ADDPRESET {  }
				BUTTON MDATA_SCULPTBRUSH_STAMP_RESET {  }
			}
		}

		SEPARATOR { LINE; }
		STATICTEXT { JOINENDSCALE; }
		STATICTEXT { JOINEND; }

		BOOL MDATA_SCULPTBRUSH_STAMP  { }
		STATICTEXT {DUMMY;}
		STATICTEXT {DUMMY;}

		FILENAME MDATA_SCULPTBRUSH_STAMP_TEXTUREFILENAME { FIT_H; SCALE_H; }
		STATICTEXT {JOINENDSCALE;}
		STATICTEXT {JOINEND;}

		LINK MDATA_SCULPTBRUSH_STAMP_MATERIAL_LINK
		{ 
			ACCEPT { Mmaterial; } 
		}
		STATICTEXT { JOINENDSCALE; }
		STATICTEXT { JOINEND; }

		SEPARATOR { LINE; }
		STATICTEXT {JOINENDSCALE;}
		STATICTEXT {JOINEND;}					

		REAL MDATA_SCULPTBRUSH_STAMP_ROTATION_VALUE { UNIT DEGREE; MIN 0; MAX 360; CUSTOMGUI REALSLIDER; SCALE_H; FIT_H;}
		STATICTEXT { JOINENDSCALE; }
		BUTTON MDATA_SCULPTBRUSH_STAMP_ROTATION_VALUE_MOD { ALIGN_LEFT; }

		BOOL MDATA_SCULPTBRUSH_STAMP_SYMMETRICAL { }
		STATICTEXT {DUMMY;}
		STATICTEXT {DUMMY;}

		BOOL MDATA_SCULPTBRUSH_STAMP_FLIP_X { }
		STATICTEXT {DUMMY;}
		STATICTEXT {DUMMY;}

		BOOL MDATA_SCULPTBRUSH_STAMP_FLIP_Y { }
		STATICTEXT {DUMMY;}
		STATICTEXT {DUMMY;}

		SEPARATOR { LINE; }
		STATICTEXT {JOINENDSCALE;}
		STATICTEXT {JOINEND;}					

		REAL MDATA_SCULPTBRUSH_STAMP_MIDVALUE { MIN 0; MAX 1.0; STEP 0.01; }
		STATICTEXT {JOINENDSCALE;}
		STATICTEXT {JOINEND;}
			
		BOOL MDATA_SCULPTBRUSH_STAMP_FOLLOW	{ }
		STATICTEXT {DUMMY;}
		STATICTEXT {DUMMY;}

		BOOL MDATA_SCULPTBRUSH_STAMP_USEFALLOFF	{ }
		STATICTEXT {DUMMY;}
		STATICTEXT {DUMMY;}

		BOOL MDATA_SCULPTBRUSH_STAMP_USEALPHA { }
		STATICTEXT {DUMMY;}
		STATICTEXT {DUMMY;}

		BOOL MDATA_SCULPTBRUSH_STAMP_SHOWDEPTH { }
		STATICTEXT {DUMMY;}
		STATICTEXT {DUMMY;}

		BOOL MDATA_SCULPTBRUSH_STAMP_INTERPOLATE { }
		STATICTEXT {DUMMY;}
		STATICTEXT {DUMMY;}

		BOOL MDATA_SCULPTBRUSH_STAMP_ENCLOSE { }
		STATICTEXT {DUMMY;}
		STATICTEXT {DUMMY;}

		SCULPTSTAMPPREVIEW MDATA_SCULPTBRUSH_STAMP_PREVIEW { CUSTOMGUI SCULPTSTAMPPREVIEW;  }
		STATICTEXT {DUMMY;}
		STATICTEXT {DUMMY;}
	}


	GROUP MDATA_SCULPTBRUSH_MIRRORING_GROUP
	{		
		LONG MDATA_SCULPTBRUSH_MIRRORING_AXIS
		{
			CYCLE
			{
				MDATA_SCULPTBRUSH_MIRRORING_AXIS_OFF;
				MDATA_SCULPTBRUSH_MIRRORING_AXIS_LOCAL;
				MDATA_SCULPTBRUSH_MIRRORING_AXIS_WORKPLANE;
			}
			ANIM OFF;
		}
		
		GROUP
		{
			COLUMNS 3;
			BOOL MDATA_SCULPTBRUSH_MIRRORING_X { }
			BOOL MDATA_SCULPTBRUSH_MIRRORING_Y { }
			BOOL MDATA_SCULPTBRUSH_MIRRORING_Z { }
		}

		SEPARATOR { LINE; }

		BOOL MDATA_SCULPTBRUSH_MIRRORING_RADIAL { }
			
		LONG MDATA_SCULPTBRUSH_MIRRORING_RADIAL_MODE
		{
			CYCLE
			{
				MDATA_SCULPTBRUSH_MIRRORING_RADIAL_MODE_X;
				MDATA_SCULPTBRUSH_MIRRORING_RADIAL_MODE_Y;
				MDATA_SCULPTBRUSH_MIRRORING_RADIAL_MODE_Z;
				MDATA_SCULPTBRUSH_MIRRORING_RADIAL_MODE_POINT;
			}
			CUSTOMGUI RADIOBUTTONS; COLUMNS 4; SCALE_H;
			ANIM OFF;
		}

		BOOL MDATA_SCULPTBRUSH_MIRRORING_RADIAL_CUSTOMPOINT { }
			
		LONG MDATA_SCULPTBRUSH_MIRRORING_RADIAL_VALUE { MIN 2; MAXSLIDER 50; CUSTOMGUI LONGSLIDER; SCALE_H; }
		REAL MDATA_SCULPTBRUSH_MIRRORING_RADIAL_GAP { UNIT DEGREE; MIN 0; MAX 90; CUSTOMGUI REALSLIDER; SCALE_H; }
			
		SCULPTRADIALPREVIEW MDATA_SCULPTBRUSH_MIRRORING_RADIAL_PREVIEW { CUSTOMGUI SCULPTRADIALPREVIEW; }
	}

	GROUP MDATA_SCULPTBRUSH_STENCIL_GROUP
	{

		GROUP
		{
			LAYOUTGROUP;
			COLUMNS 2;
			GROUP
			{
				STATICTEXT MDATA_SCULPTBRUSH_STENCIL_PRESET { NOTEXT; }
			}
			GROUP
			{
				COLUMNS 3;
				BUTTON MDATA_SCULPTBRUSH_STENCIL_LOADPRESET { }
				BUTTON MDATA_SCULPTBRUSH_STENCIL_ADDPRESET {  }
				BUTTON MDATA_SCULPTBRUSH_STENCIL_RESET {  }
			}
		}

		SEPARATOR { LINE; }

		GROUP
		{
			COLUMNS 3;
			BOOL MDATA_SCULPTBRUSH_STENCIL { }
			BOOL MDATA_SCULPTBRUSH_STENCIL_VISIBLE { }
			BOOL MDATA_SCULPTBRUSH_STENCIL_HIDEONSTROKE { }
		}
		FILENAME MDATA_SCULPTBRUSH_STENCIL_FILENAME { FIT_H; SCALE_H; }
		LINK MDATA_SCULPTBRUSH_STENCIL_MATERIAL_LINK 
		{  
			ACCEPT { Mmaterial; } 
		}
		//SHADERLINK MDATA_SCULPTBRUSH_STENCIL_SHADER_LINK  {  }
		SEPARATOR { LINE; }

		REAL MDATA_SCULPTBRUSH_STENCIL_TRANSPARENCY { MIN 0; MAX 1; STEP 0.01; CUSTOMGUI REALSLIDER; }
		REAL MDATA_SCULPTBRUSH_STENCIL_ANGLE { UNIT DEGREE; MIN 0; MAX 360; CUSTOMGUI REALSLIDER; }
		REAL MDATA_SCULPTBRUSH_STENCIL_SCALE { MIN 0.01; MAXSLIDER 2; MAX 100; STEP 0.01; CUSTOMGUI REALSLIDER; }
		VECTOR MDATA_SCULPTBRUSH_STENCIL_TRANSLATE { UNIT REAL; MIN 0.0; MAX 1.0; STEP 0.01; CUSTOMGUI VECTOR2D; }
		BOOL MDATA_SCULPTBRUSH_STENCIL_TILEX { }
		BOOL MDATA_SCULPTBRUSH_STENCIL_TILEY { }
		BOOL MDATA_SCULPTBRUSH_STENCIL_FLIP_X { }
		BOOL MDATA_SCULPTBRUSH_STENCIL_FLIP_Y { }
		REAL MDATA_SCULPTBRUSH_STENCIL_MIDVALUE { MIN 0; MAX 1.0; STEP 0.01; }
		
		SCULPTSTENCILPREVIEW MDATA_SCULPTBRUSH_STENCIL_PREVIEW { CUSTOMGUI SCULPTSTENCILPREVIEW; }
	}

	GROUP MDATA_SCULPTBRUSH_MODIFIER_GROUP
	{
		COLUMNS 2;
		BOOL MDATA_SCULPTBRUSH_MODIFIER_ENABLE { }
		STATICTEXT { JOINENDSCALE; }

		SEPARATOR { LINE; }
		STATICTEXT { JOINENDSCALE; }
	}
}
