CONTAINER Tmograph_cache
{
	NAME		Tmograph_cache;

	INCLUDE Tbase;

	GROUP		ID_TAGPROPERTIES
	{
		BOOL	MGCACHETAG_ACTIVE {}
		GROUP
		{
			COLUMNS 2;

			BUTTON	MGCACHETAG_BAKESEQUENCE {}
			BUTTON	MGCACHETAG_BAKEFRAME {}
			BUTTON	MGCACHETAG_CLEARCACHE {}
			BUTTON	MGCACHETAG_CLEARFRAME {}
		}
		BOOL	MGCACHETAG_BAKESEQUENCE_ACTIVE { ANIM OFF; }
		BASETIME	MGCACHETAG_BAKEFROM {}
		BASETIME	MGCACHETAG_BAKETO {}
	
		SEPARATOR { LINE; }
	
		BASETIME MGCACHETAG_OFFSET {}
		BOOL MGCACHETAG_LOOP {} 
		REAL MGCACHETAG_LOOP_BLEND { MIN 0.0; MAX 100.0; UNIT PERCENT; }

		SEPARATOR { LINE; }
		STATICTEXT	MGCACHETAG_MEMORYUSED {}
	}
}
