CONTAINER DynBinForce
{
	INCLUDE DynInteraction;

	GROUP ID_OBJECTPROPERTIES
	{
		LONG FORCE_APPLY {CYCLE {FORCE_APPLY_A; FORCE_APPLY_B; FORCE_APPLY_BOTH;};} STATICTEXT {JOINENDSCALE;} STATICTEXT {JOINENDSCALE;}
	}
}
