CONTAINER DynConstraintObject
{
	NAME name;
	INCLUDE DynInteraction;

	GROUP ID_OBJECTPROPERTIES
	{
		LONG FORCE_TYPE {CYCLE {CONSTRAINT_JOINT_TYPE_HINGE~180000011; CONSTRAINT_JOINT_TYPE_CARDAN~180000161; CONSTRAINT_JOINT_TYPE_BALLSOCKET~180000162; CONSTRAINT_JOINT_TYPE_RAGDOLL~180000163;
														CONSTRAINT_JOINT_TYPE_SLIDER~180000164; CONSTRAINT_JOINT_TYPE_ROT_SLIDER~180000165; CONSTRAINT_JOINT_TYPE_PLANAR~180000166; CONSTRAINT_JOINT_TYPE_BOX~180000167;
														CONSTRAINT_JOINT_TYPE_WHEEL~180000168; CONSTRAINT_JOINT_TYPE_FIXED~180000169;};}

		BOOL CONSTRAINT_IGNORE_COLLISIONS {} STATICTEXT {JOINENDSCALE;} STATICTEXT {JOINENDSCALE;}

		REAL CONSTRAINT_CONE_LIMIT_RADIUS {UNIT DEGREE; MIN 0.1; MAX 89.9;} STATICTEXT {JOINENDSCALE;} STATICTEXT {JOINENDSCALE;}

		BOOL CONSTRAINT_CONE_LIMIT_ELLIPTICAL {}
		REAL CONSTRAINT_CONE_LIMIT_RADIUS2 {UNIT DEGREE; MIN 0.1; MAX 89.9;}
		STATICTEXT {JOINENDSCALE;}

		REAL CONSTRAINT_WHEEL_ANGLE {UNIT DEGREE;} STATICTEXT {JOINENDSCALE;} STATICTEXT {JOINENDSCALE;}
		REAL CONSTRAINT_WHEEL_REST_POSITION {UNIT METER;} STATICTEXT {JOINENDSCALE;} STATICTEXT {JOINENDSCALE;}
		REAL CONSTRAINT_WHEEL_STIFFNESS {MIN 0.0;} STATICTEXT {JOINENDSCALE;} STATICTEXT {JOINENDSCALE;}
		REAL CONSTRAINT_WHEEL_DAMPING {MIN 0.0; UNIT PERCENT; STEP 1.0;} STATICTEXT {JOINENDSCALE;} STATICTEXT {JOINENDSCALE;}

		REAL CONSTRAINT_LIMIT_RESTITUTION {MIN 0.0; UNIT PERCENT;} STATICTEXT {JOINENDSCALE;} STATICTEXT {JOINENDSCALE;}

		BOOL CONSTRAINT_TRANS2_LIMIT_USE_MIN {}
		REAL CONSTRAINT_TRANS2_LIMIT_MIN {UNIT METER;}
		STATICTEXT {JOINENDSCALE;}

		BOOL CONSTRAINT_TRANS2_LIMIT_USE_MAX {}
		REAL CONSTRAINT_TRANS2_LIMIT_MAX {UNIT METER;}
		STATICTEXT {JOINENDSCALE;}

		BOOL CONSTRAINT_TRANS3_LIMIT_USE_MIN {}
		REAL CONSTRAINT_TRANS3_LIMIT_MIN {UNIT METER;}
		STATICTEXT {JOINENDSCALE;}

		BOOL CONSTRAINT_TRANS3_LIMIT_USE_MAX {}
		REAL CONSTRAINT_TRANS3_LIMIT_MAX {UNIT METER;}
		STATICTEXT {JOINENDSCALE;}

		BOOL CONSTRAINT_TRANS1_LIMIT_USE_MIN {}
		REAL CONSTRAINT_TRANS1_LIMIT_MIN {UNIT METER;}
		STATICTEXT {JOINENDSCALE;}

		BOOL CONSTRAINT_TRANS1_LIMIT_USE_MAX {}
		REAL CONSTRAINT_TRANS1_LIMIT_MAX {UNIT METER;}
		STATICTEXT {JOINENDSCALE;}

		BOOL CONSTRAINT_TRANS1_USE_BREAKING_FORCE {}
		REAL CONSTRAINT_TRANS1_BREAKING_FORCE {MIN 0.0; UNIT METER;}
		STATICTEXT {JOINENDSCALE;}

		BOOL CONSTRAINT_ROT1_LIMIT {}
		REAL CONSTRAINT_ROT1_LIMIT_MIN {UNIT DEGREE;}
		REAL CONSTRAINT_ROT1_LIMIT_MAX {UNIT DEGREE;}

		BOOL CONSTRAINT_ROT1_USE_BREAKING_TORQUE {}
		REAL CONSTRAINT_ROT1_BREAKING_TORQUE {MIN 0.0;}
		STATICTEXT {JOINENDSCALE;}

		BOOL CONSTRAINT_ROT2_LIMIT {}
		REAL CONSTRAINT_ROT2_LIMIT_MIN {UNIT DEGREE;}
		REAL CONSTRAINT_ROT2_LIMIT_MAX {UNIT DEGREE;}
	}

	GROUP CONSTRAINT_GROUP_CACHE
	{
		DEFAULT 0;
		COLUMNS 2;

		BOOL CONSTRAINT_CACHE_LOCAL {} STATICTEXT {JOINEND;}
		BUTTON CONSTRAINT_CACHE_CLEAR {} STATICTEXT {JOINEND;}
		STATICTEXT CONSTRAINT_CACHE_MEMORY {} STATICTEXT {JOINEND;}

		SEPARATOR {LINE;} STATICTEXT {JOINEND;}

		BOOL CONSTRAINT_CACHE_USE {} STATICTEXT {JOINEND;}
	}
}
