CONTAINER DynForce
{
	NAME name;
	INCLUDE Obase;

	GROUP ID_OBJECTPROPERTIES
	{
		REAL FORCE_STRENGTH {UNIT METER;}
		REAL FORCE_DAMPING {MIN 0;}
		BOOL FORCE_RESPECT_MASS {}

		SEPARATOR {LINE;}

		LONG FORCE_FALLOFF {CYCLE {FORCE_FALLOFF_LINEAR; FORCE_FALLOFF_INV; FORCE_FALLOFF_INV_SQR; FORCE_FALLOFF_INV_CUBIC; FORCE_FALLOFF_STEP;}}
		REAL FORCE_INNER_DISTANCE {MIN 0; UNIT METER;}
		REAL FORCE_OUTER_DISTANCE {MIN 0; UNIT METER;}
	}
}
