CONTAINER DynInteraction
{
	INCLUDE Obase;

	GROUP ID_OBJECTPROPERTIES
	{
		COLUMNS 3;

		LONG FORCE_TYPE {CYCLE {FORCE_TYPE_LINEAR~180000010; FORCE_TYPE_ANGULAR~180000181; FORCE_TYPE_BOTH~180000182;};}
		STATICTEXT {JOINENDSCALE;} STATICTEXT {JOINENDSCALE;}

		SEPARATOR {LINE;} STATICTEXT {JOINENDSCALE;} STATICTEXT {JOINENDSCALE;}

		LINK FORCE_OBJECT_A {ACCEPT {Obase;};} STATICTEXT {JOINENDSCALE;} STATICTEXT {JOINENDSCALE;}
		LONG FORCE_REFERENCE_A {CYCLE {FORCE_REFERENCE_X; FORCE_REFERENCE_Y; FORCE_REFERENCE_Z; FORCE_REFERENCE_DIRECTION;};} STATICTEXT {JOINENDSCALE;} STATICTEXT {JOINENDSCALE;}
		LONG FORCE_APPLICATION_A {CYCLE {FORCE_APPLICATION_COM; FORCE_APPLICATION_OFFSET; FORCE_APPLICATION_POLYPOINT; FORCE_APPLICATION_POINT_SELECTION;};} STATICTEXT {JOINENDSCALE;} STATICTEXT {JOINENDSCALE;}
		VECTOR FORCE_OFFSET_A {UNIT METER;} STATICTEXT {JOINENDSCALE;} STATICTEXT {JOINENDSCALE;}

		LONG FORCE_POINT_A {} STATICTEXT {JOINENDSCALE;} STATICTEXT {JOINENDSCALE;}
		LINK FORCE_POINT_SELECTION_A {ACCEPT {5682; 5674;}; ANIM OFF;} STATICTEXT {JOINENDSCALE;} STATICTEXT {JOINENDSCALE;}
		REAL FORCE_REGION_A {MIN 1.0; MAX 1000.0; UNIT PERCENT; STEP 1.0;} STATICTEXT {JOINENDSCALE;} STATICTEXT {JOINENDSCALE;}

		REAL FORCE_POINT_SELECTION_SHAPE_CONSERVATION_A {MIN 0.0;} STATICTEXT {JOINENDSCALE;} STATICTEXT {JOINENDSCALE;}
		REAL FORCE_POINT_SELECTION_SHAPE_CONSERVATION_DAMPING_A {MIN 0.0; UNIT PERCENT; STEP 1.0;} STATICTEXT {JOINENDSCALE;} STATICTEXT {JOINENDSCALE;}

		SEPARATOR {LINE;} STATICTEXT {JOINENDSCALE;} STATICTEXT {JOINENDSCALE;}

		LINK FORCE_OBJECT_B {ACCEPT {Obase;};} STATICTEXT {JOINENDSCALE;} STATICTEXT {JOINENDSCALE;}
		LONG FORCE_REFERENCE_B {CYCLE {FORCE_REFERENCE_X; FORCE_REFERENCE_Y; FORCE_REFERENCE_Z; FORCE_REFERENCE_DIRECTION;};} STATICTEXT {JOINENDSCALE;} STATICTEXT {JOINENDSCALE;}
		LONG FORCE_APPLICATION_B {CYCLE {FORCE_APPLICATION_COM; FORCE_APPLICATION_OFFSET; FORCE_APPLICATION_POLYPOINT; FORCE_APPLICATION_POINT_SELECTION;};} STATICTEXT {JOINENDSCALE;} STATICTEXT {JOINENDSCALE;}
		VECTOR FORCE_OFFSET_B {UNIT METER;} STATICTEXT {JOINENDSCALE;} STATICTEXT {JOINENDSCALE;}

		LONG FORCE_POINT_B {} STATICTEXT {JOINENDSCALE;} STATICTEXT {JOINENDSCALE;}
		LINK FORCE_POINT_SELECTION_B {ACCEPT {5682; 5674;}; ANIM OFF;} STATICTEXT {JOINENDSCALE;} STATICTEXT {JOINENDSCALE;}
		REAL FORCE_REGION_B {MIN 1.0; MAX 1000.0; UNIT PERCENT; STEP 1.0;} STATICTEXT {JOINENDSCALE;} STATICTEXT {JOINENDSCALE;}

		REAL FORCE_POINT_SELECTION_SHAPE_CONSERVATION_B {MIN 0.0;} STATICTEXT {JOINENDSCALE;} STATICTEXT {JOINENDSCALE;}
		REAL FORCE_POINT_SELECTION_SHAPE_CONSERVATION_DAMPING_B {MIN 0.0; UNIT PERCENT; STEP 1.0;} STATICTEXT {JOINENDSCALE;} STATICTEXT {JOINENDSCALE;}

		SEPARATOR {LINE;} STATICTEXT {JOINENDSCALE;} STATICTEXT {JOINENDSCALE;}
	}

	GROUP FORCE_GROUP_DISPLAY
	{
		DEFAULT 0;

		BOOL FORCE_ALWAYS_VISIBLE {}
		REAL FORCE_SIZE {MIN 0.0; MINEX; UNIT METER;}
	}
}
