CONTAINER DynMotorObject
{
	NAME name;
	INCLUDE DynBinForce;

	GROUP ID_OBJECTPROPERTIES
	{
		LONG FORCE_TYPE {CYCLE {FORCE_TYPE_LINEAR~180000185; FORCE_TYPE_ANGULAR~180000012; FORCE_TYPE_BOTH~180000186;};}

		LONG MOTOR_MODE {CYCLE {MOTOR_MODE_REGULATE_SPEED; MOTOR_MODE_APPLY_FORCE;};} STATICTEXT {JOINENDSCALE;} STATICTEXT {JOINENDSCALE;}

		SEPARATOR {LINE;} STATICTEXT {JOINENDSCALE;} STATICTEXT {JOINENDSCALE;}

		REAL MOTOR_LINEAR_SPEED {UNIT METER;} STATICTEXT {JOINENDSCALE;} STATICTEXT {JOINENDSCALE;}
		REAL MOTOR_FORCE {} STATICTEXT {JOINENDSCALE;} STATICTEXT {JOINENDSCALE;}

		SEPARATOR {LINE;} STATICTEXT {JOINENDSCALE;} STATICTEXT {JOINENDSCALE;}

		REAL MOTOR_ANGULAR_SPEED {UNIT DEGREE;} STATICTEXT {JOINENDSCALE;} STATICTEXT {JOINENDSCALE;}
		REAL MOTOR_TORQUE {} STATICTEXT {JOINENDSCALE;} STATICTEXT {JOINENDSCALE;}
	}
}
