CONTAINER DynRigidBodyTag
{
	NAME name;
	INCLUDE Tbase;

	GROUP RIGID_BODY_GROUP_DYNAMICS
	{
		DEFAULT 1;

		GROUP
		{
			COLUMNS 2;

			BOOL RIGID_BODY_ENABLED {}
			LINK RIGID_BODY_ENABLED_SELECTION {ACCEPT {1021338;};}
			STATICTEXT RIGID_BODY_ENABLED_FILL {}

			LONG RIGID_BODY_DYNAMIC {CYCLE {RIGID_BODY_DYNAMIC_OFF; RIGID_BODY_DYNAMIC_ON; RIGID_BODY_DYNAMIC_GHOST;};}
			LINK RIGID_BODY_DYNAMIC_SELECTION {ACCEPT {1021338;};}
			STATICTEXT RIGID_BODY_DYNAMIC_FILL {}
		}

		GROUP
		{
			COLUMNS 2;

			BUTTON RIGID_BODY_SET_INITIAL_STATE {}
			BUTTON RIGID_BODY_CLEAR_INITIAL_STATE {}
		}

		BOOL RIGID_BODY_SHOW {}

		SEPARATOR {LINE;}

		LONG RIGID_BODY_TRIGGER {CYCLE {RIGID_BODY_TRIGGER_IMMEDIATELY; RIGID_BODY_TRIGGER_AT_PEAK; RIGID_BODY_TRIGGER_ON_COLLISION; RIGID_BODY_TRIGGER_XPRESSO;};}
		REAL RIGID_BODY_TRIGGER_ON_COLLISION_VELOCITY {UNIT METER;}

		BOOL RIGID_BODY_USE_INITIAL_VELOCITY {}
		
		VECTOR RIGID_BODY_INITIAL_LINEAR_VELOCITY {UNIT METER;}
		VECTOR RIGID_BODY_INITIAL_ANGULAR_VELOCITY {UNIT DEGREE;}
		BOOL RIGID_BODY_LOCAL_INITIAL_VELOCITY {ANIM OFF;}

		SEPARATOR {LINE;}

		BOOL RIGID_BODY_DYNAMIC_TRANSITION {}
		BASETIME RIGID_BODY_TRANSITION_TIME {MIN 0.0;}

		SEPARATOR RIGID_BODY_GROUP_DEACTIVATION {}

		REAL RIGID_BODY_SLEEPING_LINEAR_VELOCITY {MIN 0.0; UNIT METER;}
		REAL RIGID_BODY_SLEEPING_ANGULAR_VELOCITY {MIN 0.0; UNIT DEGREE;}
	}

	GROUP RIGID_BODY_GROUP_COLLISION
	{
		DEFAULT 1;
		COLUMNS 2;

		LONG RIGID_BODY_HIERARCHY {CYCLE {RIGID_BODY_HIERARCHY_NONE; RIGID_BODY_HIERARCHY_APPLY_TAG; RIGID_BODY_HIERARCHY_COMPOUND_SHAPE;};} STATICTEXT {JOINENDSCALE;}
		LONG RIGID_BODY_SPLIT_CACHE {CYCLE {RIGID_BODY_SPLIT_CACHE_OFF; RIGID_BODY_SPLIT_CACHE_TOP_LEVEL; RIGID_BODY_SPLIT_CACHE_SECOND_LEVEL; RIGID_BODY_SPLIT_CACHE_ON;};} STATICTEXT {JOINENDSCALE;}

		SEPARATOR {LINE;} STATICTEXT {JOINENDSCALE;}

		BOOL RIGID_BODY_SELF_COLLISIONS {} STATICTEXT {JOINENDSCALE;}

		LONG RIGID_BODY_SHAPE {CYCLE {RIGID_BODY_SHAPE_DEFAULT; RIGID_BODY_SHAPE_DEFAULT_MODYNAMICS; RIGID_BODY_SHAPE_BOX; RIGID_BODY_SHAPE_ELLIPSOID; RIGID_BODY_SHAPE_CYLINDER_X; RIGID_BODY_SHAPE_CYLINDER_Y; RIGID_BODY_SHAPE_CYLINDER_Z;
																	RIGID_BODY_SHAPE_CONVEX_HULL; RIGID_BODY_SHAPE_KINETIC_MESH; RIGID_BODY_SHAPE_STATIC_MESH; RIGID_BODY_SHAPE_REFERENCE; RIGID_BODY_SHAPE_NO_SHAPE;};} STATICTEXT {JOINENDSCALE;}

		REAL RIGID_BODY_SHAPE_SIZE_INCREMENT {UNIT METER;} STATICTEXT {JOINENDSCALE;}

		BOOL RIGID_BODY_SPECIFIC_MARGIN {ANIM OFF;}
		REAL RIGID_BODY_MARGIN {MIN 0.0; UNIT METER;}

		LINK RIGID_BODY_REFERENCE_SHAPE {ACCEPT {Obase;}} STATICTEXT {JOINENDSCALE;}
		BOOL RIGID_BODY_SB_KEEP_SHAPE {} STATICTEXT {JOINENDSCALE;}

		SEPARATOR {LINE;} STATICTEXT {JOINENDSCALE;}

		REAL RIGID_BODY_RESTITUTION {MIN 0.0; UNIT PERCENT; STEP 5.0;} STATICTEXT {JOINENDSCALE;}
		REAL RIGID_BODY_FRICTION {MIN 0.0; UNIT PERCENT; STEP 5.0;} STATICTEXT {JOINENDSCALE;}
		REAL RIGID_BODY_COLLISION_NOISE {MIN 0.0; MAX 90.0; UNIT PERCENT; STEP 0.1;} STATICTEXT {JOINENDSCALE;}
	}

	GROUP RIGID_BODY_GROUP_MASS
	{
		DEFAULT 0;

		LONG RIGID_BODY_MASS_SWITCH {CYCLE {RIGID_BODY_MASS_SWITCH_DEFAULT; RIGID_BODY_MASS_SWITCH_DENSITY; RIGID_BODY_MASS_SWITCH_MASS;}; ANIM OFF;}
		REAL RIGID_BODY_DENSITY {MINEX; MIN 0.0;}
		REAL RIGID_BODY_MASS {MINEX; MIN 0.0;}

		REAL RIGID_BODY_INERTIA_FACTOR {MIN 1; MAX 10000; UNIT PERCENT;}

		SEPARATOR {LINE;}

		BOOL RIGID_BODY_USE_CENTER_OF_MASS {ANIM OFF;}
		VECTOR RIGID_BODY_CENTER_OF_MASS {UNIT METER;}
	}

	GROUP RIGID_BODY_GROUP_FORCE
	{
		DEFAULT 0;

		REAL RIGID_BODY_LINEAR_FOLLOW_STRENGTH {MIN 0.0; MAX 100.0;}
		REAL RIGID_BODY_ANGULAR_FOLLOW_STRENGTH {MIN 0.0; MAX 100.0;}

		SEPARATOR {LINE;}

		REAL RIGID_BODY_LINEAR_DAMPING {MIN 0.0; UNIT PERCENT; STEP 1.0;}
		REAL RIGID_BODY_ANGULAR_DAMPING {MIN 0.0; UNIT PERCENT; STEP 1.0;}

		SEPARATOR {LINE;}

		LONG RIGID_BODY_FORCE_MODE {CYCLE {RIGID_BODY_FORCE_MODE_INCLUDE; RIGID_BODY_FORCE_MODE_EXCLUDE;}}
		IN_EXCLUDE RIGID_BODY_FORCE_INCLUDE_LIST {NUM_FLAGS 0; INIT_STATE 0; SEND_SELCHNGMSG 1; ACCEPT {Obase;};}

		SEPARATOR RIGID_BODY_AERODYNAMICS_GROUP {}

		REAL RIGID_BODY_AERODYNAMICS_DRAG {MIN 0.0; UNIT PERCENT; STEP 0.1;}
		REAL RIGID_BODY_AERODYNAMICS_LIFT {MIN 0.0; UNIT PERCENT; STEP 0.1;}
		BOOL RIGID_BODY_AERODYNAMICS_TWO_SIDED {}
	}

	GROUP RIGID_BODY_GROUP_SOFT
	{
		COLUMNS 2;

		LONG RIGID_BODY_SOFT {CYCLE {RIGID_BODY_SOFT_OFF; RIGID_BODY_SOFT_ON; RIGID_BODY_SOFT_OF_CLONES;}} STATICTEXT {JOINENDSCALE;}

		LINK RIGID_BODY_SB_REST_STATE {ACCEPT {Obase;};} STATICTEXT {JOINENDSCALE;}

		LINK RIGID_BODY_SB_MASS_MAP {ACCEPT {5682; 5674;};} STATICTEXT {JOINENDSCALE;}
		BOOL RIGID_BODY_SB_ACCURATE_SOLVER {} STATICTEXT {JOINENDSCALE;}

		SEPARATOR RIGID_BODY_SB_SPRING_GROUP {} STATICTEXT {JOINENDSCALE;}

		REAL RIGID_BODY_SB_STRUCTURAL {MIN 0.0;}
		LINK RIGID_BODY_SB_STRUCTURAL_MAP {ACCEPT {5682; 5674;}}
		REAL RIGID_BODY_SB_STRUCTURAL_DAMPING {MIN 0.0; UNIT PERCENT; STEP 1.0;}
		LINK RIGID_BODY_SB_STRUCTURAL_DAMPING_MAP {ACCEPT {5682; 5674;}}
		REAL RIGID_BODY_SB_ELASTIC_LIMIT {MIN 0.0; UNIT PERCENT; STEP 1.0;}
		LINK RIGID_BODY_SB_ELASTIC_LIMIT_MAP {ACCEPT {5682; 5674;}}

		SEPARATOR {LINE;} STATICTEXT {JOINENDSCALE;}

		REAL RIGID_BODY_SB_SHEAR {MIN 0.0;}
		LINK RIGID_BODY_SB_SHEAR_MAP {ACCEPT {5682; 5674;}}
		REAL RIGID_BODY_SB_SHEAR_DAMPING {MIN 0.0; UNIT PERCENT; STEP 1.0;}
		LINK RIGID_BODY_SB_SHEAR_DAMPING_MAP {ACCEPT {5682; 5674;}}

		SEPARATOR {LINE;} STATICTEXT {JOINENDSCALE;}

		REAL RIGID_BODY_SB_FLEXION {MIN 0.0;}
		LINK RIGID_BODY_SB_FLEXION_MAP {ACCEPT {5682; 5674;}}
		REAL RIGID_BODY_SB_FLEXION_DAMPING {MIN 0.0; UNIT PERCENT; STEP 1.0;}
		LINK RIGID_BODY_SB_FLEXION_DAMPING_MAP {ACCEPT {5682; 5674;}}
		REAL RIGID_BODY_SB_FLEXION_ELASTIC_LIMIT {MIN 0.0; MAX 180.0; UNIT DEGREE; STEP 1.0;}
		LINK RIGID_BODY_SB_FLEXION_ELASTIC_LIMIT_MAP {ACCEPT {5682; 5674;}}

		SEPARATOR {LINE;} STATICTEXT {JOINENDSCALE;}

		REAL RIGID_BODY_SB_REST_LENGTH {MIN 1.0; UNIT PERCENT; STEP 1.0;}
		LINK RIGID_BODY_SB_REST_LENGTH_MAP {ACCEPT {5682; 5674;}}
		REAL RIGID_BODY_SB_TEAR_OUT_LENGTH {MIN 1.0; UNIT PERCENT; STEP 1.0;}
		LINK RIGID_BODY_SB_TEAR_OUT_LENGTH_MAP {ACCEPT {5682; 5674;}}

		SEPARATOR RIGID_BODY_SB_CLONE_ROTATION_SEPARATOR {LINE;} STATICTEXT {JOINENDSCALE;}

		REAL RIGID_BODY_SB_CLONE_ROTATION {MIN 0.0;}
		LINK RIGID_BODY_SB_CLONE_ROTATION_MAP {ACCEPT {5682; 5674;}}
		REAL RIGID_BODY_SB_CLONE_ROTATION_DAMPING {MIN 0.0; UNIT PERCENT; STEP 1.0;}
		LINK RIGID_BODY_SB_CLONE_ROTATION_DAMPING_MAP {ACCEPT {5682; 5674;}}

		SEPARATOR RIGID_BODY_SB_SHAPE_CONSERVATION_GROUP {} STATICTEXT {JOINENDSCALE;}

		REAL RIGID_BODY_SB_SHAPE_CONSERVATION {MIN 0.0;}
		LINK RIGID_BODY_SB_SHAPE_CONSERVATION_MAP {ACCEPT {5682; 5674;}}

		REAL RIGID_BODY_SB_SHAPE_VOLUME_CONSERVATION {MIN 0.0; MAX 100.0; UNIT PERCENT; STEP 1.0;}
		STATICTEXT {JOINENDSCALE;}

		REAL RIGID_BODY_SB_SHAPE_CONSERVATION_DAMPING {MIN 0.0; UNIT PERCENT; STEP 1.0;}
		LINK RIGID_BODY_SB_SHAPE_CONSERVATION_DAMPING_MAP {ACCEPT {5682; 5674;}}

		REAL RIGID_BODY_SB_SHAPE_CONSERVATION_ELASTIC_LIMIT {MIN 0.0; UNIT METER; STEP 1.0;}
		LINK RIGID_BODY_SB_SHAPE_CONSERVATION_ELASTIC_LIMIT_MAP {ACCEPT {5682; 5674;}}

		SEPARATOR RIGID_BODY_SB_PRESSURE_GROUP {} STATICTEXT {JOINENDSCALE;}

		REAL RIGID_BODY_SB_PRESSURE {} STATICTEXT {JOINENDSCALE;}
		REAL RIGID_BODY_SB_VOLUME_CONSERVATION {MIN 0.0;} STATICTEXT {JOINENDSCALE;}
		REAL RIGID_BODY_SB_PRESSURE_DAMPING {MIN 0.0; UNIT PERCENT; STEP 1.0;} STATICTEXT {JOINENDSCALE;}
	}

	GROUP RIGID_BODY_GROUP_CACHE
	{
		COLUMNS 2;
		DEFAULT 0;

		BOOL RIGID_BODY_CACHE_LOCAL {} STATICTEXT {JOINENDSCALE;}
		BOOL RIGID_BODY_CACHE_INCLUDE_COLLISIONS {} STATICTEXT {JOINENDSCALE;}
		BUTTON RIGID_BODY_CACHE_BAKE {}
		BUTTON RIGID_BODY_CACHE_BAKE_ALL {}
		BUTTON RIGID_BODY_CACHE_CLEAR {}
		BUTTON RIGID_BODY_CACHE_CLEAR_ALL {}
		STATICTEXT RIGID_BODY_CACHE_MEMORY {} STATICTEXT {JOINENDSCALE;}

		SEPARATOR {LINE;} STATICTEXT {JOINENDSCALE;}

		BOOL RIGID_BODY_CACHE_USE {} STATICTEXT {JOINENDSCALE;}
	}
}
