CONTAINER DynSpringObject
{
	NAME name;
	INCLUDE DynBinForce;

	GROUP ID_OBJECTPROPERTIES
	{
		SEPARATOR {LINE;}
		STATICTEXT {JOINENDSCALE;}
		STATICTEXT {JOINENDSCALE;}

		REAL SPRING_LINEAR_REST_LENGTH {MIN 0.0; UNIT METER;}
		BUTTON SPRING_LINEAR_SET_REST_LENGTH {}
		STATICTEXT {JOINENDSCALE;}

		REAL SPRING_LINEAR_STIFFNESS {MIN 0.0;}
		STATICTEXT {JOINENDSCALE;}
		STATICTEXT {JOINENDSCALE;}

		REAL SPRING_LINEAR_DAMPING {MIN 0.0; UNIT PERCENT; STEP 1.0;}
		STATICTEXT {JOINENDSCALE;}
		STATICTEXT {JOINENDSCALE;}

		BOOL SPRING_LINEAR_USE_ELASTIC_STRETCH_LIMIT {}
		REAL SPRING_LINEAR_ELASTIC_STRETCH_LIMIT {MIN 0.0; UNIT METER;}
		STATICTEXT {JOINENDSCALE;}

		BOOL SPRING_LINEAR_USE_ELASTIC_COMPRESSION_LIMIT {}
		REAL SPRING_LINEAR_ELASTIC_COMPRESSION_LIMIT {MIN 0.0; UNIT METER;}
		STATICTEXT {JOINENDSCALE;}

		BOOL SPRING_LINEAR_USE_BREAK_STRETCH {}
		REAL SPRING_LINEAR_BREAK_STRETCH {MIN 0.0; UNIT METER;}
		STATICTEXT {JOINENDSCALE;}

		BOOL SPRING_LINEAR_USE_BREAK_COMPRESSION {}
		REAL SPRING_LINEAR_BREAK_COMPRESSION {MIN 0.0; UNIT METER;}
		STATICTEXT {JOINENDSCALE;}

		SEPARATOR {LINE;}
		STATICTEXT {JOINENDSCALE;}
		STATICTEXT {JOINENDSCALE;}

		REAL SPRING_ANGULAR_REST_LENGTH {UNIT DEGREE;}
		BUTTON SPRING_ANGULAR_SET_REST_LENGTH {}
		STATICTEXT {JOINENDSCALE;}

		REAL SPRING_ANGULAR_STIFFNESS {MIN 0.0;}
		STATICTEXT {JOINENDSCALE;}
		STATICTEXT {JOINENDSCALE;}

		REAL SPRING_ANGULAR_DAMPING {MIN 0.0; UNIT PERCENT; STEP 1.0;}
		STATICTEXT {JOINENDSCALE;}
		STATICTEXT {JOINENDSCALE;}

		BOOL SPRING_ANGULAR_USE_ELASTIC_STRETCH_LIMIT {}
		REAL SPRING_ANGULAR_ELASTIC_STRETCH_LIMIT {MIN 0.0; UNIT DEGREE;}
		STATICTEXT {JOINENDSCALE;}

		BOOL SPRING_ANGULAR_USE_ELASTIC_COMPRESSION_LIMIT {}
		REAL SPRING_ANGULAR_ELASTIC_COMPRESSION_LIMIT {MIN 0.0; UNIT DEGREE;}
		STATICTEXT {JOINENDSCALE;}

		BOOL SPRING_ANGULAR_USE_BREAK_STRETCH {}
		REAL SPRING_ANGULAR_BREAK_STRETCH {MIN 0.0; UNIT DEGREE;}
		STATICTEXT {JOINENDSCALE;}

		BOOL SPRING_ANGULAR_USE_BREAK_COMPRESSION {}
		REAL SPRING_ANGULAR_BREAK_COMPRESSION {MIN 0.0; UNIT DEGREE;}
		STATICTEXT {JOINENDSCALE;}
	}
}
