CONTAINER DynWorldObject
{
	NAME name;

	GROUP WORLD_GROUP_DYNAMICS
	{
		DEFAULT 1;

		BOOL WORLD_ENABLED {}
		BOOL WORLD_DISABLE_DURING_LEAP {ANIM OFF;}

		SEPARATOR {LINE;}

		REAL WORLD_TIMESCALE {MIN 0; UNIT PERCENT;}
		REAL WORLD_GRAVITY {UNIT METER;}
		REAL WORLD_DENSITY {MINEX; MIN 0.0;}
		REAL WORLD_AIR_DENSITY {MIN 0.0;}
	}

	GROUP WORLD_GROUP_CACHE
	{
		DEFAULT 0;

		BUTTON WORLD_CACHE_BAKE {}
		BUTTON WORLD_CACHE_CLEAR {}

		STATICTEXT WORLD_CACHE_MEMORY {}

		SEPARATOR {LINE;}

		BOOL WORLD_CACHE_USE {}
		BOOL WORLD_CACHE_DISABLE_BAKED_OBJECTS {}

		GROUP
		{
			COLUMNS 2;
			BOOL WORLD_CACHE_USE_TIME {}
			BASETIME WORLD_CACHE_TIME {}
		}
	}

	GROUP WORLD_GROUP_EXPERT
	{
		DEFAULT 0;

		REAL WORLD_MARGIN {MIN 0.0; ANIM OFF; UNIT METER;}
		REAL WORLD_SCALE {MIN 0.0; MINEX; ANIM OFF; UNIT METER;}
		REAL WORLD_CONTACT_RESTITUTION_LIFETIME {MINEX; MIN 0.0;}
		LONG WORLD_SEED {ANIM OFF;}

		SEPARATOR {LINE;}

		LONG WORLD_SUBSTEPS {MIN 1; MAX 1000;}
		LONG WORLD_ITERATIONS {MIN 3; MAX 10000;}
		REAL WORLD_ERROR_THRESHOLD {MIN 0.1; MAX 100; UNIT PERCENT;}
	}

	GROUP WORLD_GROUP_VISUALIZATION
	{
		DEFAULT 0;

		BOOL WORLD_VISUALIZE {ANIM OFF;}
		BOOL WORLD_VISUALIZE_SHAPES {ANIM OFF;}
		BOOL WORLD_VISUALIZE_AABBS {ANIM OFF;}
		BOOL WORLD_VISUALIZE_CONTACT_POINTS {ANIM OFF;}
		BOOL WORLD_VISUALIZE_CONSTRAINTS {ANIM OFF;}
	}
}
