CONTAINER GVdyncollision
{
	NAME name;
	INCLUDE GVbase;

	GROUP ID_GVPROPERTIES
	{
		LINK COLLISION_NODE_OBJECT_A {ACCEPT {Obase;};}
		LINK COLLISION_NODE_OBJECT_B {ACCEPT {Obase;};}
		BOOL COLLISION_NODE_SINGLE_COLLISION {}
	}

	GROUP ID_GVPORTS
	{
		LONG COLLISION_NODE_INPUT_COLLISION_INDEX {INPORT; STATICPORT; CREATEPORT; MIN 0;}
		GVGENERALOBJECT COLLISION_NODE_INPUT_OBJECT_A {INPORT; STATICPORT; CREATEPORT;}
		LONG COLLISION_NODE_INPUT_INDEX_A {INPORT; MIN 0;}
		GVGENERALOBJECT COLLISION_NODE_INPUT_OBJECT_B {INPORT; STATICPORT; CREATEPORT;}
		LONG COLLISION_NODE_INPUT_INDEX_B {INPORT; MIN 0;}

		GVGENERALOBJECT COLLISION_NODE_OUTPUT_OBJECT_A {OUTPORT; STATICPORT; CREATEPORT;}
		GVGENERALTAG COLLISION_NODE_OUTPUT_TAG_A {OUTPORT;}
		LONG COLLISION_NODE_OUTPUT_INDEX_A {OUTPORT;}
		GVGENERALOBJECT COLLISION_NODE_OUTPUT_OBJECT_B {OUTPORT; STATICPORT; CREATEPORT;}
		GVGENERALTAG COLLISION_NODE_OUTPUT_TAG_B {OUTPORT;}
		LONG COLLISION_NODE_OUTPUT_INDEX_B {OUTPORT;}

		LONG COLLISION_NODE_OUTPUT_COUNT {OUTPORT; STATICPORT; CREATEPORT;}
		BOOL COLLISION_NODE_OUTPUT_GHOST {OUTPORT;}
		VECTOR COLLISION_NODE_OUTPUT_POINT_A {OUTPORT;}
		VECTOR COLLISION_NODE_OUTPUT_LOCAL_POINT_A {OUTPORT;}
		VECTOR COLLISION_NODE_OUTPUT_POINT_B {OUTPORT;}
		VECTOR COLLISION_NODE_OUTPUT_LOCAL_POINT_B {OUTPORT;}
		NORMAL COLLISION_NODE_OUTPUT_NORMAL {OUTPORT;}
		REAL COLLISION_NODE_OUTPUT_SPEED {OUTPORT;}
		REAL COLLISION_NODE_OUTPUT_DISTANCE {OUTPORT;}
		REAL COLLISION_NODE_OUTPUT_FORCE {OUTPORT;}
		VECTOR COLLISION_NODE_OUTPUT_FORCE_FOR_PAIR {OUTPORT;}
	}
}
