CONTAINER GVdyninteraction
{
	NAME name;
	INCLUDE GVbase;

	GROUP ID_GVPROPERTIES
	{
		LINK DYNAMICS_INTERACTION_NODE_OBJECT {ACCEPT {Obase;};}
	}

	GROUP ID_GVPORTS
	{
		BOOL DYNAMICS_INTERACTION_NODE_INPUT_ON {INPORT;}
		GVGENERALOBJECT DYNAMICS_INTERACTION_NODE_INPUT_OBJECT {INPORT; CREATEPORT;}
		LONG DYNAMICS_INTERACTION_NODE_INPUT_INDEX {INPORT; MIN 0;}

		LONG DYNAMICS_INTERACTION_NODE_OUTPUT_COUNT {OUTPORT;}
		GVGENERALOBJECT DYNAMICS_INTERACTION_NODE_OUTPUT_OBJECT {OUTPORT;}

		GVGENERALOBJECT DYNAMICS_INTERACTION_NODE_OUTPUT_OBJECT_A {OUTPORT;}
		GVGENERALTAG DYNAMICS_INTERACTION_NODE_OUTPUT_TAG_A {OUTPORT;}
		LONG DYNAMICS_INTERACTION_NODE_OUTPUT_INDEX_A {OUTPORT;}
		GVGENERALOBJECT DYNAMICS_INTERACTION_NODE_OUTPUT_OBJECT_B {OUTPORT;}
		GVGENERALTAG DYNAMICS_INTERACTION_NODE_OUTPUT_TAG_B {OUTPORT;}
		LONG DYNAMICS_INTERACTION_NODE_OUTPUT_INDEX_B {OUTPORT;}
	}
}
