CONTAINER GVdynspring
{
	NAME name;
	INCLUDE GVdyninteraction;

	GROUP ID_GVPORTS
	{
		REAL SPRING_NODE_INPUT_LINEAR_PLASTIC_ELONGATION {INPORT; UNIT METER;}
		REAL SPRING_NODE_INPUT_ANGULAR_PLASTIC_ELONGATION {INPORT; UNIT DEGREE;}
		BOOL DYNAMICS_INTERACTION_NODE_INPUT_BROKEN {INPORT; }

		REAL SPRING_NODE_OUTPUT_LINEAR_PLASTIC_ELONGATION {OUTPORT; UNIT METER;}
		REAL SPRING_NODE_OUTPUT_ANGULAR_PLASTIC_ELONGATION {OUTPORT; UNIT DEGREE;}
		BOOL DYNAMICS_INTERACTION_NODE_OUTPUT_BROKEN {OUTPORT;}
	}
}
