CONTAINER GVdynconstraint
{
	NAME name;
	INCLUDE GVdyninteraction;

	GROUP ID_GVPORTS
	{
		BOOL DYNAMICS_INTERACTION_NODE_INPUT_BROKEN {INPORT; }

		BOOL DYNAMICS_INTERACTION_NODE_OUTPUT_BROKEN {OUTPORT;}
	}
}
