CONTAINER GVdynbody
{
	NAME name;
	INCLUDE GVbase;

	GROUP ID_GVPROPERTIES
	{
		LINK DYNAMICS_BODY_NODE_OBJECT {ACCEPT {Obase;};}
	}

	GROUP ID_GVPORTS
	{
		BOOL DYNAMICS_BODY_NODE_INPUT_ON {INPORT;}
		GVGENERALOBJECT DYNAMICS_BODY_NODE_INPUT_OBJECT {INPORT; STATICPORT; CREATEPORT;}
		LONG DYNAMICS_BODY_NODE_INPUT_INDEX {INPORT; MIN 0;}
		LONG DYNAMICS_BODY_NODE_INPUT_POINT_INDEX {INPORT; MIN 0;}
		BOOL DYNAMICS_BODY_NODE_INPUT_TRIGGER {INPORT;}
		REAL DYNAMICS_BODY_NODE_INPUT_MASS {INPORT;}
		VECTOR DYNAMICS_BODY_NODE_INPUT_POSITION {INPORT;}
		VECTOR DYNAMICS_BODY_NODE_INPUT_LOCAL_POSITION {INPORT;}
		VECTOR DYNAMICS_BODY_NODE_INPUT_ROTATION {INPORT;}
		MATRIX DYNAMICS_BODY_NODE_INPUT_MATRIX {INPORT;}
		VECTOR DYNAMICS_BODY_NODE_INPUT_LINEAR_VELOCITY {INPORT;}
		VECTOR DYNAMICS_BODY_NODE_INPUT_ANGULAR_VELOCITY {INPORT;}
		VECTOR DYNAMICS_BODY_NODE_INPUT_ADD_LINEAR_ACCELERATION {INPORT;}
		VECTOR DYNAMICS_BODY_NODE_INPUT_ADD_ANGULAR_ACCELERATION {INPORT;}
		VECTOR DYNAMICS_BODY_NODE_INPUT_ADD_FORCE {INPORT;}
		VECTOR DYNAMICS_BODY_NODE_INPUT_ADD_TORQUE {INPORT;}
		VECTOR DYNAMICS_BODY_NODE_INPUT_POINT_OF_APPLICATION {INPORT;}
		VECTOR DYNAMICS_BODY_NODE_INPUT_LOCAL_POINT_OF_APPLICATION {INPORT;}

		LONG DYNAMICS_BODY_NODE_OUTPUT_COUNT {OUTPORT;}
		GVGENERALOBJECT DYNAMICS_BODY_NODE_OUTPUT_OBJECT {OUTPORT;}
		LONG DYNAMICS_BODY_NODE_OUTPUT_INDEX {OUTPORT;}
		GVGENERALTAG DYNAMICS_BODY_NODE_OUTPUT_TAG {OUTPORT;}
		REAL DYNAMICS_BODY_NODE_OUTPUT_MASS {OUTPORT;}
		BOOL DYNAMICS_BODY_NODE_OUTPUT_DYNAMIC {OUTPORT;}
		VECTOR DYNAMICS_BODY_NODE_OUTPUT_POSITION {OUTPORT;}
		VECTOR DYNAMICS_BODY_NODE_OUTPUT_LOCAL_POSITION {OUTPORT;}
		VECTOR DYNAMICS_BODY_NODE_OUTPUT_ROTATION {OUTPORT;}
		MATRIX DYNAMICS_BODY_NODE_OUTPUT_MATRIX {OUTPORT;}
		VECTOR DYNAMICS_BODY_NODE_OUTPUT_LINEAR_VELOCITY {OUTPORT;}
		VECTOR DYNAMICS_BODY_NODE_OUTPUT_ANGULAR_VELOCITY {OUTPORT;}
		VECTOR DYNAMICS_BODY_NODE_OUTPUT_LINEAR_ACCELERATION {OUTPORT;}
		VECTOR DYNAMICS_BODY_NODE_OUTPUT_ANGULAR_ACCELERATION {OUTPORT;}
		VECTOR DYNAMICS_BODY_NODE_OUTPUT_FORCE {OUTPORT;}
		VECTOR DYNAMICS_BODY_NODE_OUTPUT_TORQUE {OUTPORT;}
	}
}
