CONTAINER GVdynproximity
{
	NAME name;
	INCLUDE GVbase;

	GROUP ID_GVPROPERTIES
	{
		LINK DYNAMICS_PROXIMITY_NODE_OBJECT {ACCEPT {Obase;};}
		LINK DYNAMICS_PROXIMITY_NODE_EXCLUDE_OBJECT {ACCEPT {Obase;};}
		LONG DYNAMICS_PROXIMITY_NODE_MODE {CYCLE {DYNAMICS_PROXIMITY_NODE_MODE_CENTER; DYNAMICS_PROXIMITY_NODE_MODE_BOUNDING_BOX; DYNAMICS_PROXIMITY_NODE_MODE_SHAPE;};}
	}

	GROUP ID_GVPORTS
	{
		GVGENERALOBJECT DYNAMICS_PROXIMITY_NODE_INPUT_OBJECT {INPORT;}
		LONG DYNAMICS_PROXIMITY_NODE_INPUT_INDEX {INPORT; MIN 0;}
		GVGENERALOBJECT DYNAMICS_PROXIMITY_NODE_INPUT_EXCLUDE_OBJECT {INPORT;}
		LONG DYNAMICS_PROXIMITY_NODE_INPUT_EXCLUDE_INDEX {INPORT; MIN 0;}
		VECTOR DYNAMICS_PROXIMITY_NODE_INPUT_POINT {INPORT; STATICPORT; CREATEPORT;}

		GVGENERALOBJECT DYNAMICS_PROXIMITY_NODE_OUTPUT_OBJECT {OUTPORT;}
		GVGENERALTAG DYNAMICS_PROXIMITY_NODE_OUTPUT_TAG {OUTPORT;}
		LONG DYNAMICS_PROXIMITY_NODE_OUTPUT_INDEX {OUTPORT;}
		REAL DYNAMICS_PROXIMITY_NODE_OUTPUT_DISTANCE {OUTPORT;}
		VECTOR DYNAMICS_PROXIMITY_NODE_OUTPUT_POSITION {OUTPORT; CREATEPORT;}
		VECTOR DYNAMICS_PROXIMITY_NODE_OUTPUT_LOCAL_POSITION {OUTPORT;}
		LONG DYNAMICS_PROXIMITY_NODE_OUTPUT_POINT_INDEX {OUTPORT;}
	}
}
