CONTAINER fobjexport2
{
	NAME		fobjexport2;
	INCLUDE Fbase;

	GROUP OBJEXPORTOPTIONS_GROUP
	{
		SEPARATOR OBJEXPORTOPTIONS_GROUP_PRESETS { }

		LONG OBJEXPORTOPTIONS_PRESETS
		{	
			CYCLE { }	
		}

		SEPARATOR OBJEXPORTOPTIONS_GROUP_GENERAL { }

		UNITSCALE OBJEXPORTOPTIONS_SCALE	{ }
		LONG			OBJEXPORTOPTIONS_NORMALS
		{
			CYCLE
			{
				OBJEXPORTOPTIONS_NORMALS_NONE;				
				OBJEXPORTOPTIONS_NORMALS_VERTEX;
			}
		}
		BOOL OBJEXPORTOPTIONS_TEXTURECOORDINATES { }

		SEPARATOR OBJEXPORTOPTIONS_GROUP_MATERIAL { }

		LONG OBJEXPORTOPTIONS_MATERIAL
		{
			CYCLE
			{
				OBJEXPORTOPTIONS_MATERIAL_NONE;
				OBJEXPORTOPTIONS_MATERIAL_NAMEANDDEFAULT;
				OBJEXPORTOPTIONS_MATERIAL_MATERIAL;
			}
		}

		LONG OBJEXPORTOPTIONS_DEFAULTMATERIAL
		{
			CYCLE
			{
				OBJEXPORTOPTIONS_DEFAULTMATERIAL_WHITE;
				OBJEXPORTOPTIONS_DEFAULTMATERIAL_RANDOMCOLORS;
			}
		}

		BOOL OBJEXPORTOPTIONS_INVERT_TRANSPARENCY { }

		SEPARATOR OBJEXPORTOPTIONS_GROUP_OPTIONAL { }

		GROUP
		{
			COLUMNS 2;
			BOOL OBJEXPORTOPTIONS_POINTTRANSFORM_FLIPX { }
			BOOL OBJEXPORTOPTIONS_POINTTRANSFORM_SWAPXY { }
			BOOL OBJEXPORTOPTIONS_POINTTRANSFORM_FLIPY { }
			BOOL OBJEXPORTOPTIONS_POINTTRANSFORM_SWAPXZ { }
			BOOL OBJEXPORTOPTIONS_POINTTRANSFORM_FLIPZ { }
			BOOL OBJEXPORTOPTIONS_POINTTRANSFORM_SWAPYZ { }
		}		

		GROUP
		{
			COLUMNS 2;
			BOOL OBJEXPORTOPTIONS_FLIPFACES { }
			BOOL OBJEXPORTOPTIONS_FLIPUVW   { }
		}
		
		BOOL OBJEXPORTOPTIONS_OBJECTS_AS_GROUPS { }
		BOOL OBJEXPORTOPTIONS_EXPORT_DUPLICATE_VERTICES { }
	}
}