CONTAINER Fribexport
{
	NAME Fribexport;
	INCLUDE Fbase;

	GROUP RIBEXPORT_GROUP
	{
		DEFAULT 1;
		COLUMNS 2;
//		LONG RIBEXPORT_RENDERSETTINGS 
//		{
//			CYCLE 
//			{
//				RIBEXPORT_RENDERSETTINGS_CURRENT;
//			}
//		}


		LONG RIBEXPORT_EXPORTAS
		{
			CYCLE
			{
				RIBEXPORT_EXPORTAS_FULLSCENE;
				RIBEXPORT_EXPORTAS_ARCHIVEGEOANDLIGHTS;
				RIBEXPORT_EXPORTAS_ARCHIVEGEOONLY;
				RIBEXPORT_EXPORTAS_ARCHIVELIGHTSONLY;
			}
			
			DEFAULT RIBEXPORT_EXPORTAS_FULLSCENE;
		}
		STATICTEXT {}

		LONG RIBEXPORT_RIBSTYLE
		{
			CYCLE
			{
				RIBEXPORT_RIBSTYLE_ARCHIVES;
				RIBEXPORT_RIBSTYLE_FLAT;
			}
			
			DEFAULT RIBEXPORT_RIBSTYLE_ARCHIVES;
		}
		STATICTEXT {}
		
		SEPARATOR { LINE; }
		STATICTEXT {JOINENDSCALE;}
		
//		STRING RIBEXPORT_DISPLAYNAME { }

		LONG RIBEXPORT_DISPLAYPRESET 
		{
			CYCLE 
			{
				RIBEXPORT_DISPLAYPRESET_CUSTOM;
				RIBEXPORT_DISPLAYPRESET_FRAMEBUFFER;
				RIBEXPORT_DISPLAYPRESET_FILE;
			}
			
			DEFAULT RIBEXPORT_DISPLAYPRESET_FRAMEBUFFER;
		}
		STATICTEXT {}
		
		STRING RIBEXPORT_DISPLAYDRIVER { }
		STATICTEXT {}
		
		SEPARATOR { LINE; }
		STATICTEXT {JOINENDSCALE;}

		BOOL RIBEXPORT_EXPORTMAINRIB { DEFAULT 1;}
		STATICTEXT {}
		BOOL RIBEXPORT_EXPORTARCHIVES {DEFAULT 1; }
		STATICTEXT {}
		BOOL RIBEXPORT_EXPORTSHADERS { DEFAULT 1;}
		STATICTEXT {}
		BOOL RIBEXPORT_EXPORTCOMPILESHADERS { PARENTID RIBEXPORT_EXPORTSHADERS; DEFAULT 1;}
		STATICTEXT {}
		BOOL RIBEXPORT_EXPORTTEXTURES { DEFAULT 1;}
		STATICTEXT {}
		BOOL RIBEXPORT_EXPORTMAKETEXTURES { PARENTID RIBEXPORT_EXPORTTEXTURES; DEFAULT 1;}
		STATICTEXT {}

		//SEPARATOR { LINE; }
		
		//BOOL RIBEXPORT_COPYAUXFILES { }
		//BOOL RIBEXPORT_ONLYSELECTED { }
		//BOOL RIBEXPORT_EXPORTASARCHIVE { }
		//BOOL RIBEXPORT_FLATDIRECTORY { }
	}
}	