CONTAINER Mrenderman
{
	NAME Mrenderman;

	INCLUDE Mpreview;
	INCLUDE Mbase;
	
	GROUP Obaselist
	{
		BOOL MATERIAL_PAGE_PROPERTIES { HIDDEN; PAGE; PARENTMSG ID_MATERIALPROPERTIES; }
		BOOL RIBMATERIAL_PAGE_SHADERPARAMS { HIDDEN; PAGE; PARENTMSG ID_SHADERPARAMS; }
		
	}
	
	GROUP ID_MATERIALPROPERTIES
	{
		DEFAULT 1;
		FILENAME RIBMATERIAL_SHADERFILE { }
		STRING RIBMATERIAL_SHADERNAME { }
//		BUTTON RIBMATERIAL_RELOAD { }
		LONG RIBMATERIAL_SHADERTYPE 
		{
			CYCLE
			{
				RIBMATERIAL_SHADERTYPE_SURFACE;
				RIBMATERIAL_SHADERTYPE_DISPLACEMENT;
				RIBMATERIAL_SHADERTYPE_VOLUME;
				RIBMATERIAL_SHADERTYPE_LIGHTSOURCE;
			}
			
		}
		
		BUTTON RIBMATERIAL_RELOAD { }
		
		SEPARATOR { LINE; }
	}
	
	GROUP ID_SHADERPARAMS
	{
		DEFAULT 1;
//		COLOR RIBMATERIAL_COLOR	 { }
	}

//	GROUP GROUP_SURFACE
//	{
//		COLOR RIBMATERIAL_COLOR	 { }
//		COLOR RIBMATERIAL_OPACITY { }
		
//		LONG RIBMATERIAL_SSPACE
//		{
//			CYCLE
//			{
//				RIBMATERIAL_SSPACE_TEXTURE;
//				RIBMATERIAL_SSPACE_SPECIFY;
//			}
//		}

//		GROUP GROUP_SURFACECOORDINATES
//		{
//			LAYOUTGROUP; COLUMNS 3;
//			GROUP { VECTOR RIBMATERIAL_SPOSITION { UNIT METER;  CUSTOMGUI SUBDESCRIPTION; } }
//			GROUP { VECTOR RIBMATERIAL_SSIZE     { UNIT METER; STEP 0.01;   CUSTOMGUI SUBDESCRIPTION; } }
//			GROUP { VECTOR RIBMATERIAL_SROTATION { UNIT DEGREE; CUSTOMGUI SUBDESCRIPTION; } }
//		}
		
//	}
	
//	GROUP GROUP_DISPLACEMENT
//	{
//		FILENAME RIBMATERIAL_DISPLACEMENTFILE { }
//		STRING RIBMATERIAL_DISPLACEMENTNAME { }
//		REAL RIBMATERIAL_DISPLACEMENTBOUND { UNIT METER; MIN 0; MINEX; MAX 100000000; }

//		LONG RIBMATERIAL_DSPACE
//		{
//			CYCLE
//			{
//				RIBMATERIAL_DSPACE_TEXTURE;
//				RIBMATERIAL_DSPACE_SPECIFY;
//			}
//		}
		
//		GROUP GROUP_DISPLACEMENTCOORDINATES
//		{
//			LAYOUTGROUP; COLUMNS 3;
//			GROUP { VECTOR RIBMATERIAL_DPOSITION { UNIT METER;  CUSTOMGUI SUBDESCRIPTION; } }
//			GROUP { VECTOR RIBMATERIAL_DSIZE     { UNIT METER; STEP 0.01;   CUSTOMGUI SUBDESCRIPTION; } }
//			GROUP { VECTOR RIBMATERIAL_DROTATION { UNIT DEGREE; CUSTOMGUI SUBDESCRIPTION; } }
//		}
//	}

	INCLUDE Massign;
}