CONTAINER Prefscineman
{
	NAME Prefscineman;
	GROUP PREF_CINEMAN_MAIN_GROUP
	{
		DEFAULT 1;
		COLUMNS 2;
		
		LONG PREF_CINEMAN_RENDERER 
		{ 
			ANIM OFF; 
			CYCLE 
			{ 
				PREF_CINEMAN_RENDERER_PRMAN;
				PREF_CINEMAN_RENDERER_AIR;
				PREF_CINEMAN_RENDERER_3D;
			} 
		}
		STATICTEXT{}
		
		FILENAME PREF_CINEMAN_DIRECTORY {DIRECTORY; ANIM OFF;}
		STATICTEXT {JOINENDSCALE;}
		
		LONG PREF_CINEMAN_TEMP 
		{ 
			ANIM OFF; 
			CYCLE 
			{ 
				PREF_CINEMAN_TEMP_PRJ;
				PREF_CINEMAN_TEMP_LCL;
			} 
		}
		STATICTEXT{}		
	}
}
