CONTAINER SHrenderman
{
	NAME SHrenderman;
	//INCLUDE VPbase;

	GROUP ID_OUTPUT
	{
		LONG CINEMAN_XRES { MIN 1; MAX 10000; STEP 1; }
		LONG CINEMAN_YRES { MIN 1; MAX 10000; STEP 1; }
		REAL CINEMAN_PIXELASPECT { MIN 0; MINEX; MAX 10; STEP 0.1; }
		BASETIME CINEMAN_FRAMEFROM { MIN 0; MAX 10000; STEP 1; }
		BASETIME CINEMAN_FRAMETO  { MIN 0; MAX 10000; STEP 1; }
		BUTTON CINEMAN_GETFROMRENDERSETTINGS { }
		
		SEPARATOR { LINE; }

		STRING CINEMAN_DISPLAYNAME { }
		LONG CINEMAN_DISPLAYPRESETS
		{
			CYCLE
			{
				CINEMAN_DISPLAY_CINEMAN;
				CINEMAN_DISPLAY_FRAMEBUFFER;
				CINEMAN_DISPLAY_FILE;
				CINEMAN_DISPLAY_CUSTOM;
			}
		}
		STRING CINEMAN_DISPLAYDRIVER { }
		STRING CINEMAN_DISPLAYMODE { }

		LONG CINEMAN_QUANTIZE
		{
			CYCLE
			{
				CINEMAN_QUANTIZE_CUSTOM;
				CINEMAN_QUANTIZE_8BIT;
				CINEMAN_QUANTIZE_16BIT;
				CINEMAN_QUANTIZE_16BITHEAD;
				CINEMAN_QUANTIZE_FLOAT;
			}
		}
		
		LONG CINEMAN_QUANTIZEONE { PARENTID CINEMAN_QUANTIZE; MIN 0; MAX 65535; STEP 1; }
		LONG CINEMAN_QUANTIZEMIN { PARENTID CINEMAN_QUANTIZE; MIN 0; MAX 65535; STEP 1; }
		LONG CINEMAN_QUANTIZEMAX { PARENTID CINEMAN_QUANTIZE; MIN 0; MAX 65535; STEP 1; }
		REAL CINEMAN_QUANTIZEDITHER { PARENTID CINEMAN_QUANTIZE; MIN 0; MAX 1; STEP 0.1; }
		
		SEPARATOR { LINE; }
		
		BUTTON CINEMAN_DISPLAYADD_ADD { }
		
		SEPARATOR { LINE; }
	
		BOOL CINEMAN_EXPORTCOMPILESHADERS { }
		BOOL CINEMAN_EXPORTMAKETEXTURES { }
		BOOL CINEMAN_EXPORTARCHIVES { }
		BOOL CINEMAN_EXPORTASARCHIVE { }
		BUTTON CINEMAN_EXPORTSTART { }
	}

	GROUP ID_SETTINGS
	{
		LONG CINEMAN_RENDERER
		{
			CYCLE
			{
				CINEMAN_RENDERER_PRMAN;
				CINEMAN_RENDERER_AIR;
				
			}
		}
		
		STRING CINEMAN_COMMANDOPTION { }
		
		SEPARATOR { LINE; }
		
		STRING CINEMAN_SHADERPATH { }
		STRING CINEMAN_TEXTUREPATH { }
		STRING CINEMAN_ARCHIVEPATH { }
		STRING CINEMAN_DISPLAYPATH { }
		STRING CINEMAN_PROCEDURALPATH { }
	}

	GROUP ID_QUALITY
	{
		LONG CINEMAN_PIXELSAMPLESX { MIN 1; MAX 64; STEP 1; }
		LONG CINEMAN_PIXELSAMPLESY { MIN 1; MAX 64; STEP 1; }

		LONG CINEMAN_PIXELFILTER
		{
			CYCLE
			{
				CINEMAN_PIXELFILTER_BOX;
				CINEMAN_PIXELFILTER_TRIANGLE;
				CINEMAN_PIXELFILTER_CATMULLROM;
				CINEMAN_PIXELFILTER_GAUSSIAN;
				CINEMAN_PIXELFILTER_SINC;
			}
		}
		REAL CINEMAN_XFILTERWIDTH { MIN 0; MINEX; MAX 32; STEP 0.25; }
		REAL CINEMAN_YFILTERWIDTH { MIN 0; MINEX; MAX 32; STEP 0.25; }
		
		REAL CINEMAN_SHADINGRATE { MIN 0; MINEX; MAX 256; STEP 0.25; }
		
		SEPARATOR { LINE; }

		LONG CINEMAN_MOTIONBLUR
		{
			CYCLE
			{
				CINEMAN_MOTIONBLUR_NONE;
				CINEMAN_MOTIONBLUR_TAGGED;
				CINEMAN_MOTIONBLUR_ALWAYS;
			}
		}
		LONG CINEMAN_MBLURTYPE
		{
			PARENTID CINEMAN_MOTIONBLUR;
			CYCLE
			{
				CINEMAN_MBLURTYPE_TRANSFORM;
				CINEMAN_MBLURTYPE_TRANSDEFORM;
			}
		}
		REAL CINEMAN_MBLURLENGTH { PARENTID CINEMAN_MOTIONBLUR; MIN 0; MAX 10.0; STEP 0.1; }
		REAL CINEMAN_MOTIONFACTOR { PARENTID CINEMAN_MOTIONBLUR; MIN 0; MINEX; MAX 10; }

		SEPARATOR { LINE; }
		
		REAL CINEMAN_FLATNESS { }
		
		SEPARATOR { LINE; }
		
		BOOL CINEMAN_DOF { }
		BOOL CINEMAN_FROMCAMERA { PARENTID CINEMAN_DOF; }
		REAL CINEMAN_FOCALDISTANCE { PARENTID CINEMAN_DOF; UNIT METER; }
		REAL CINEMAN_FOCALLENGTH { PARENTID CINEMAN_DOF; UNIT METER; }
		REAL CINEMAN_FSTOP { PARENTID CINEMAN_DOF; }
		
		SEPARATOR { LINE; }
		
		REAL CINEMAN_RAYSHADOWBIAS { MIN 0; MINEX; MAX 10000; STEP 0.1; UNIT METER; }
		LONG CINEMAN_TEXTUREMEMORY { MIN 1000; MAX 2000000; STEP 1000; }

		SEPARATOR { LINE; }
		
		LONG CINEMAN_HYPERNURBS
		{
			CYCLE
			{
				CINEMAN_HYPERNURBS_POLYMESH;
				CINEMAN_HYPERNURBS_CATMULLCLARK;
			}
		}
		
		LONG CINEMAN_INSTANCES
		{
			CYCLE
			{
				CINEMAN_INSTANCES_UNFOLD;
				CINEMAN_INSTANCES_READARCHIVE;
			}
		}
		
		SEPARATOR { LINE; }
		
		LONG CINEMAN_GI_INDIRECT
		{
			CYCLE
			{
				CINEMAN_GI_INDIRECT_NONE;
				CINEMAN_GI_INDIRECT_INDIRECT;
				CINEMAN_GI_INDIRECT_ENVLIGHT;
			}
		}
	
		REAL CINEMAN_GI_INTENSITY { PARENTID CINEMAN_GI_INDIRECT; UNIT PERCENT; MIN 0; MAX 1000; STEP 1; }
		BOOL CINEMAN_GI_PREPASS { PARENTID CINEMAN_GI_INDIRECT; }
		REAL CINEMAN_GI_PREPASSFACTOR { PARENTID CINEMAN_GI_INDIRECT; MIN 0; MINEX; MAX 1; STEP 0.1; }
		REAL CINEMAN_GI_MAXERROR { PARENTID CINEMAN_GI_INDIRECT; MIN 0; MAX 1; STEP 0.05; }
		REAL CINEMAN_GI_MAXPIXDIST { PARENTID CINEMAN_GI_INDIRECT; MIN 0; MINEX; MAX 256; STEP 1; }
		LONG CINEMAN_GI_NSAMPLES { PARENTID CINEMAN_GI_INDIRECT; MIN 1; MAX 1024; STEP 1; }
		LONG CINEMAN_GI_MAXBOUNCE { PARENTID CINEMAN_GI_INDIRECT; MIN 1; MAX 4; STEP 1; }
		BOOL CINEMAN_GI_ADAPTIVESAMPLING { PARENTID CINEMAN_GI_INDIRECT; }
		REAL CINEMAN_GI_MAXVARIANCE { PARENTID CINEMAN_GI_INDIRECT; MIN 0; MINEX; MAX 1; STEP 0.05; }
	}
	
	GROUP ID_ATMOSPHERE
	{
		LONG CINEMAN_ATMOSPHERE_SAMPLING
		{
			CYCLE
			{
				CINEMAN_ATMOSPHERE_SAMPLING_AVERAGE;
				CINEMAM_ATMOSPHERE_SAMPLING_USEMIN;
				CINEMAN_ATMOSPHERE_SAMPLING_USEMAX;
				CINEMAN_ATMOSPHERE_SAMPLING_SPECIFY;
			}
		}
		REAL CINEMAN_ATMOSPHERE_STEPSIZE { UNIT METER; MIN 0; MINEX; MAX 100000; STEP 5; }
				
	}
}
