CONTAINER Tribattributes
{
	NAME Tribattributes;
	INCLUDE Tbase;

	GROUP ID_TAGPROPERTIES
	{
		GROUP GROUP_GENERAL
		{
			DEFAULT 1;
			
			GROUP
			{
				LAYOUTGROUP;
				COLUMNS 2;
				
				GROUP
				{
					BOOL RIBATTRIBUTES_USESHADINGRATE { }
					BOOL RIBATTRIBUTES_USESHADINGINTERPOLATION { }
					BOOL RIBATTRIBUTES_USESIDES { }
				}
				
				GROUP
				{
					REAL RIBATTRIBUTES_SHADINGRATE { MIN 0; MINEX; MAX 1024; STEP 0.25; }
					LONG RIBATTRIBUTES_SHADINGINTERPOLATION
					{
						CYCLE
						{
							RIBATTRIBUTES_SHADINGINTERPOLATION_CONSTANT;
							RIBATTRIBUTES_SHADINGINTERPOLATION_SMOOTH;		
						}
					}
					LONG RIBATTRIBUTES_SIDES { MIN 1; MAX 2; STEP 1; }
					
				}
			}

			SEPARATOR { LINE; }
	
			GROUP
			{
				LAYOUTGROUP;
				COLUMNS 2;

				GROUP
				{
					BOOL RIBATTRIBUTES_PRM_USEMOTIONFACTOR { }
					BOOL RIBATTRIBUTES_PRM_USEFOCUSFACTOR { }

					BOOL RIBATTRIBUTES_AIR_USEMOTIONFACTOR { }
					BOOL RIBATTRIBUTES_AIR_USEFLATNESS { }
					BOOL RIBATTRIBUTES_AIR_RENDER_USETRUEDISPLACEMENT { }
					BOOL RIBATTRIBUTES_AIR_RENDER_USETRIANGLEDISPLACEMENT { }

					BOOL RIBATTRIBUTES_3DL_USEMOTIONFACTOR { }
					BOOL RIBATTRIBUTES_3DL_USEFOCUSFACTOR { }
				}
				
				GROUP
				{
					REAL RIBATTRIBUTES_PRM_MOTIONFACTOR { MIN 0; MAX 32; STEP 0.1; }
					REAL RIBATTRIBUTES_PRM_FOCUSFACTOR { MIN 0; MAX 32; STEP 0.1; }

					REAL RIBATTRIBUTES_AIR_MOTIONFACTOR { MIN 0; MAX 32; STEP 0.1; }
					REAL RIBATTRIBUTES_AIR_FLATNESS { MIN 0; MINEX; MAX 1; STEP 0.1; }
					BOOL RIBATTRIBUTES_AIR_RENDER_TRUEDISPLACEMENT { }
					BOOL RIBATTRIBUTES_AIR_RENDER_TRIANGLEDISPLACEMENT { }

					REAL RIBATTRIBUTES_3DL_MOTIONFACTOR { MIN 0; MAX 32; STEP 0.1; }
					REAL RIBATTRIBUTES_3DL_FOCUSFACTOR { MIN 0; MAX 32; STEP 0.1; }
				}
			}
		}

		GROUP GROUP_TRACE
		{
			DEFAULT 0;
			COLUMNS 2;
	
			BOOL RIBATTRIBUTES_PRM_TRACE_USEBIAS { }
			REAL RIBATTRIBUTES_PRM_TRACE_BIAS { MIN 0; MAX 1000000; STEP 0.01; UNIT METER; }

			BOOL RIBATTRIBUTES_PRM_TRACE_USESAMPLEMOTION { }
			BOOL RIBATTRIBUTES_PRM_TRACE_SAMPLEMOTION { }

			BOOL RIBATTRIBUTES_PRM_TRACE_USEDISPLACEMENTS { }
			BOOL RIBATTRIBUTES_PRM_TRACE_DISPLACEMENTS { }
			
			BOOL RIBATTRIBUTES_PRM_TRACE_USEMAXDIFFUSEDEPTH { }
			LONG RIBATTRIBUTES_PRM_TRACE_MAXDIFFUSEDEPTH { MIN 0; MAX 64; STEP 1; }
			
			BOOL RIBATTRIBUTES_PRM_TRACE_USEMAXSPECULARDEPTH { }
			LONG RIBATTRIBUTES_PRM_TRACE_MAXSPECULARDEPTH { MIN 0; MAX 64; STEP 1; }
			
			
			BOOL RIBATTRIBUTES_AIR_TRACE_USEBIAS { }
			REAL RIBATTRIBUTES_AIR_TRACE_BIAS { MIN 0; MAX 1000000; STEP 0.01; UNIT METER; }

			BOOL RIBATTRIBUTES_AIR_TRACE_USEMOTIONBLUR { }
			BOOL RIBATTRIBUTES_AIR_TRACE_MOTIONBLUR { }

			BOOL RIBATTRIBUTES_AIR_TRACE_USEDISPLACEMENTS { }
			BOOL RIBATTRIBUTES_AIR_TRACE_DISPLACEMENTS { }


			BOOL RIBATTRIBUTES_3DL_TRACE_USEBIAS { }
			REAL RIBATTRIBUTES_3DL_TRACE_BIAS { MIN 0; MAX 1000000; STEP 0.01; UNIT METER; }
			
			BOOL RIBATTRIBUTES_3DL_TRACE_USESAMPLEMOTION { }
			BOOL RIBATTRIBUTES_3DL_TRACE_SAMPLEMOTION { }
			
			BOOL RIBATTRIBUTES_3DL_TRACE_USEDISPLACEMENTS { }
			BOOL RIBATTRIBUTES_3DL_TRACE_DISPLACEMENTS { }
		}

		GROUP GROUP_GI
		{
			DEFAULT 0;
			COLUMNS 2;

			BOOL RIBATTRIBUTES_PRM_GI_USEMAXERROR { }
			REAL RIBATTRIBUTES_PRM_GI_MAXERROR { MIN 0; MAX 100; STEP 1; UNIT PERCENT; }

			BOOL RIBATTRIBUTES_PRM_GI_USEMAXPIXELDIST { }
			REAL RIBATTRIBUTES_PRM_GI_MAXPIXELDIST { MIN 0; MAX 1000; STEP 1; }

			BOOL RIBATTRIBUTES_AIR_GI_USEMAXERROR { }
			REAL RIBATTRIBUTES_AIR_GI_MAXERROR { MIN 0; MAX 100; STEP 1; UNIT PERCENT; }
			
			BOOL RIBATTRIBUTES_AIR_GI_USEMAXPIXELDIST { }
			REAL RIBATTRIBUTES_AIR_GI_MAXPIXELDIST { MIN 0; MAX 1000; STEP 1; }
			
			BOOL RIBATTRIBUTES_AIR_GI_USENSAMPLES { }
			LONG RIBATTRIBUTES_AIR_GI_NSAMPLES { MIN 1; MAX 1024; STEP 1; }
			
			BOOL RIBATTRIBUTES_AIR_GI_USEADAPTIVESAMPLING { }
			BOOL RIBATTRIBUTES_AIR_GI_ADAPTIVESAMPLING { }
			
			BOOL RIBATTRIBUTES_AIR_GI_USEMAXHITDIST	{ }
 			REAL RIBATTRIBUTES_AIR_GI_MAXHITDIST  { MIN 0; MAX 1000000; STEP 0.01; UNIT METER; }


			BOOL RIBATTRIBUTES_3DL_GI_USESHADINGRATE { }
			REAL RIBATTRIBUTES_3DL_GI_SHADINGRATE { MIN 0; MINEX; MAX 1024; STEP 0.25; }

			BOOL RIBATTRIBUTES_3DL_GI_USEMAXERROR { }
			REAL RIBATTRIBUTES_3DL_GI_MAXERROR  { MIN 0; MAX 100; STEP 1; UNIT PERCENT; }
		}
	}
}
