CONTAINER Tribcontainer
{
	NAME Tribcontainer;
	INCLUDE Tbase;

	GROUP ID_TAGPROPERTIES
	{
		SCALE_V;
		BOOL RIBCONTAINER_ENABLED { }
		STRING RIBCONTAINER_ASCII { CUSTOMGUI MULTISTRING; SCALE_V; }
		LONG RIBCONTAINER_POS
		{
			CYCLE
			{
				RIBCONTAINER_POS_BEFORE;
				RIBCONTAINER_POS_AFTER;
				RIBCONTAINER_POS_REPLACE;
			}
		}
	}
}
