CONTAINER VPrenderman
{
	NAME VPrenderman;
	INCLUDE VPbase;

	GROUP ID_TRANSLATION
	{
		GROUP GROUP_TRANSLATION
		{
			DEFAULT 1;

//			LONG CINEMAN_HYPERNURBS
//			{
//				ANIM OFF;
//				CYCLE
//				{
//					CINEMAN_HYPERNURBS_POLYMESH;
//					CINEMAN_HYPERNURBS_CATMULLCLARK;
//				}
//			}
			
//			LONG CINEMAN_METABALLS
//			{
//				ANIM OFF;
//				CYCLE
//				{
//					CINEMAN_METABALLS_POLYMESH;
//					CINEMAN_METABALLS_BLOBBYS;
//				}
//			}
			
//			LONG CINEMAN_INSTANCES
//			{
//				ANIM OFF;
//				CYCLE
//				{
//					CINEMAN_INSTANCES_UNFOLD;
//					CINEMAN_INSTANCES_READARCHIVE;
//				}
//			}
		}
		
		GROUP GROUP_PATHS
		{
			DEFAULT 0;

			PATHLIST CINEMAN_SHADERPATH { ANIM OFF; }
			PATHLIST CINEMAN_TEXTUREPATH { ANIM OFF; }
			PATHLIST CINEMAN_ARCHIVEPATH { ANIM OFF; }
			PATHLIST CINEMAN_PROCEDURALPATH { ANIM OFF; }
		}
		
//		GROUP GROUP_PLATFORMS
//		{
//			PATHLIST CINEMAN_DIRMAPS { DIRMAP; ANIM OFF; }
//		}
		
		GROUP GROUP_RIB
		{
			DEFAULT 0;

			LONG CINEMAN_RIBSTYLE
			{
				ANIM OFF;
				CYCLE
				{
					CINEMAN_RIBSTYLE_ARCHIVES;
					CINEMAN_RIBSTYLE_FLAT;
				}
			}
//			LONG CINEMAN_RIBFORMAT
//			{
//				ANIM OFF;
//				CYCLE
//				{
//					CINEMAN_RIBFORMAT_ASCII;
//					CINEMAN_RIBFORMAT_BINARY;
//					CINEMAN_RIBFORMAT_GZIP_ASCII;
//					CINEMAN_RIBFORMAT_GZIP_BINARY;
//				}
//			}

			SEPARATOR { LINE; }

			BOOL CINEMAN_EXPORTMAINRIB { ANIM OFF; }
			BOOL CINEMAN_EXPORTARCHIVES { ANIM OFF; }
			BOOL CINEMAN_EXPORTSHADERS { ANIM OFF; }
			BOOL CINEMAN_EXPORTCOMPILESHADERS { ANIM OFF; PARENTID CINEMAN_EXPORTSHADERS; }
			BOOL CINEMAN_EXPORTTEXTURES { ANIM OFF; }
			BOOL CINEMAN_EXPORTMAKETEXTURES	{ ANIM OFF; PARENTID CINEMAN_EXPORTTEXTURES; }

			//SEPARATOR { LINE; }

			//BOOL CINEMAN_FLATDIRECTORY { }
			//BOOL CINEMAN_COPYAUXFILES { }
		}

	}

//	GROUP ID_VIDEOPOSTPROPERTIES
//	{
//	}
	
	GROUP ID_QUALITY
	{
		GROUP GROUP_SAMPLING
		{
			DEFAULT 1;

			LONG CINEMAN_PIXELSAMPLESX { ANIM OFF; MIN 1; MAX 64; STEP 1; }
			LONG CINEMAN_PIXELSAMPLESY { ANIM OFF; MIN 1; MAX 64; STEP 1; }
			BOOL CINEMAN_AIR_RENDER_EDGEMASK { ANIM OFF; }

			SEPARATOR { LINE; }

			LONG CINEMAN_PIXELFILTER
			{
				ANIM OFF;
				CYCLE
				{
					CINEMAN_PIXELFILTER_BOX;
					CINEMAN_PIXELFILTER_TRIANGLE;
					CINEMAN_PIXELFILTER_CATMULLROM;
					CINEMAN_PIXELFILTER_GAUSSIAN;
					CINEMAN_PIXELFILTER_SINC;
				}
			}
			REAL CINEMAN_XFILTERWIDTH { ANIM OFF; MIN 0; MINEX; MAX 32; STEP 0.25; }
			REAL CINEMAN_YFILTERWIDTH { ANIM OFF; MIN 0; MINEX; MAX 32; STEP 0.25; }
			
			SEPARATOR { LINE; }
			
			REAL CINEMAN_SHADINGRATE { ANIM OFF; MIN 0; MINEX; MAX 256; STEP 0.25; }
			LONG CINEMAN_SHADINGINTERPOLATION
			{
				ANIM OFF;
				CYCLE
				{
					CINEMAN_SHADINGINTERPOLATION_CONSTANT;
					CINEMAN_SHADINGINTERPOLATION_SMOOTH;
				}
			}
			
		}

		GROUP GROUP_GEOMETRY
		{
			DEFAULT 1;

			LONG CINEMAN_SIDES { ANIM OFF; MIN 1; MAX 2; STEP 1; }
			REAL CINEMAN_AIR_FLATNESS { ANIM OFF; }
			
			SEPARATOR { LINE; }
			
			BOOL CINEMAN_AIR_RENDER_TRUEDISPLACEMENT { ANIM OFF; }
			BOOL CINEMAN_AIR_RENDER_TRIANGLEDISPLACEMENT { ANIM OFF; PARENTID CINEMAN_AIR_RENDER_TRUEDISPLACEMENT; }
//			LONG CINEMAN_PRM_LIMITS_EXTREMEDISPLACEMENT { ANIM OFF; MIN 1; MAX 1024; STEP 1; }
			
		}
	}

	GROUP ID_FEATURES
	{
		GROUP GROUP_MOTIONBLUR
		{
			DEFAULT 1;

			LONG CINEMAN_MOTIONBLUR
			{
				ANIM OFF;
				CYCLE
				{
					CINEMAN_MOTIONBLUR_NONE;
					CINEMAN_MOTIONBLUR_TRANSFORM;
					CINEMAN_MOTIONBLUR_TRANSDEFORM;
					CINEMAN_MOTIONBLUR_DEFORM;
				}
			}

			REAL CINEMAN_MBLURLENGTH { ANIM OFF; PARENTID CINEMAN_MOTIONBLUR; MIN 0; MAX 1.0; STEP 0.1; }
			REAL CINEMAN_PRM_MOTIONFACTOR { ANIM OFF; PARENTID CINEMAN_MOTIONBLUR; MIN 0; MAX 10; STEP 0.1; }
			REAL CINEMAN_AIR_MOTIONFACTOR { ANIM OFF; PARENTID CINEMAN_MOTIONBLUR; MIN 0; MAX 10; STEP 0.1; }
			REAL CINEMAN_3DL_MOTIONFACTOR { ANIM OFF; PARENTID CINEMAN_MOTIONBLUR; MIN 0; MAX 10; STEP 0.1; }
		}

		
		GROUP GROUP_DOF
		{
			DEFAULT 1;

			BOOL CINEMAN_DOF { ANIM OFF; }
			BOOL CINEMAN_FROMCAMERA { ANIM OFF; PARENTID CINEMAN_DOF; }
			REAL CINEMAN_FOCALDISTANCE { ANIM OFF; PARENTID CINEMAN_DOF; UNIT METER; }
			REAL CINEMAN_FOCALLENGTH { ANIM OFF; PARENTID CINEMAN_DOF; }
			REAL CINEMAN_FSTOP { ANIM OFF; PARENTID CINEMAN_DOF; }
			REAL CINEMAN_PRM_FOCUSFACTOR { ANIM OFF; PARENTID CINEMAN_DOF; MIN 0; MAX 32; STEP 0.1; }
			REAL CINEMAN_3DL_FOCUSFACTOR { ANIM OFF; PARENTID CINEMAN_DOF; MIN 0; MAX 32; STEP 0.1; }
		}
		
		GROUP GROUP_RAYTRACING
		{
			DEFAULT 0;

			LONG CINEMAN_PRM_TRACE_MAXDEPTH { ANIM OFF; MIN 1; MAX 64; STEP 1; }
			LONG CINEMAN_PRM_TRACE_MAXDIFFUSEDEPTH { ANIM OFF; MIN 1; MAX 64; STEP 1; }
			LONG CINEMAN_PRM_TRACE_MAXSPECULARDEPTH	{ ANIM OFF; MIN 1; MAX 64; STEP 1; }
			REAL CINEMAN_PRM_TRACE_BIAS { ANIM OFF; MIN 0; MINEX; MAX 10000; STEP 0.1; UNIT METER; }
			BOOL CINEMAN_PRM_TRACE_SAMPLEMOTION { ANIM OFF; }
			BOOL CINEMAN_PRM_TRACE_DISPLACEMENTS { ANIM OFF; }
			REAL CINEMAN_PRM_TRACE_SPECULARTHRESHOLD { ANIM OFF; MIN 0; MAX 180; UNIT DEGREE; }
			
			LONG CINEMAN_AIR_TRACE_MAXDEPTH { ANIM OFF; MIN 1; MAX 64; STEP 1; }
			REAL CINEMAN_AIR_TRACE_BIAS { ANIM OFF; MIN 0; MINEX; MAX 10000; STEP 0.1; UNIT METER; }
			BOOL CINEMAN_AIR_TRACE_MOTIONBLUR { ANIM OFF; }
			BOOL CINEMAN_AIR_TRACE_DISPLACEMENTS { ANIM OFF; }
//			REAL CINEMAN_AIR_TRACE_MINWEIGHT { ANIM OFF; MIN 0; MAX 100; STEP 1; UNIT PERCENT; }
//			REAL CINEMAN_AIR_TRACE_REDUCESAMPLES { ANIM OFF; MIN 0; MAX 100; STEP 1; UNIT PERCENT; }

			LONG CINEMAN_3DL_TRACE_MAXDEPTH	{ ANIM OFF; MIN 1; MAX 64; STEP 1; }
			REAL CINEMAN_3DL_TRACE_BIAS { ANIM OFF; MIN 0; MINEX; MAX 10000; STEP 0.1; UNIT METER; }
			BOOL CINEMAN_3DL_TRACE_SAMPLEMOTION { ANIM OFF; }
			BOOL CINEMAN_3DL_TRACE_DISPLACEMENTS { ANIM OFF; }
		}
	}
		
	GROUP ID_GLOBALILLUMINATION
	{
		GROUP GROUP_GIQUALITY 
		{	
			DEFAULT 1;

			//
			// PRMan
			//
			REAL CINEMAN_PRM_GI_MAXERROR { ANIM OFF; MIN 0; MAX 100; STEP 5; UNIT PERCENT; }
			REAL CINEMAN_PRM_GI_MAXPIXELDIST { ANIM OFF; MIN 0; MAX 256; STEP 1; }

			//
			// AIR
			//
			LONG CINEMAN_AIR_GI_MAXBOUNCE { ANIM OFF; MIN 1; MAX 4; STEP 1; }
			REAL CINEMAN_AIR_GI_MAXHITDIST { ANIM OFF; MIN 0; MAX 100000000; STEP 1; UNIT METER; }
			BOOL CINEMAN_AIR_GI_MOVING { ANIM OFF; }

			SEPARATOR { LINE; }

			REAL CINEMAN_AIR_GI_MAXERROR { ANIM OFF; MIN 0; MAX 100; STEP 5; UNIT PERCENT; }
			REAL CINEMAN_AIR_GI_MAXPIXELDIST { ANIM OFF; MIN 0; MAX 256; STEP 1; }

			SEPARATOR { LINE; }

			BOOL CINEMAN_AIR_GI_PREPASS { ANIM OFF; }
			REAL CINEMAN_AIR_GI_PREPASSFACTOR { ANIM OFF; PARENTID CINEMAN_AIR_GI_PREPASS; MIN 1; MAX 100; STEP 1; UNIT PERCENT;}

			SEPARATOR { LINE; }

			LONG CINEMAN_AIR_GI_NSAMPLES { ANIM OFF; MIN 1; MAX 1024; STEP 1; }
			BOOL CINEMAN_AIR_GI_ADAPTIVESAMPLING { ANIM OFF; }
			REAL CINEMAN_AIR_GI_MAXVARIANCE { ANIM OFF; PARENTID CINEMAN_AIR_GI_ADAPTIVESAMPLING; MIN 0; MINEX; MAX 1; STEP 0.05; }

			//
			// 3Delight
			//
			REAL CINEMAN_3DL_GI_SHADINGRATE { ANIM OFF; MIN 0; MINEX; MAX 1024; STEP 0.25; }
			REAL CINEMAN_3DL_GI_MAXERROR { ANIM OFF; MIN 0; MAX 100; STEP 1; UNIT PERCENT; }
			
		}
		
		GROUP GROUP_GICACHE
		{
			DEFAULT 0;

			FILENAME CINEMAN_AIR_GI_SAVEFILE { ANIM OFF; }
			FILENAME CINEMAN_AIR_GI_SEEDFILE { ANIM OFF; }
		}

		GROUP GROUP_ENVIRONMENT
		{
			DEFAULT 0;

			COLOR CINEMAN_AIR_GI_BACKGROUND { ANIM OFF; }
			
			//SEPARATOR { LINE; }
			
			STRING CINEMAN_AIR_GI_ENVNAME { ANIM OFF; }
			REAL CINEMAN_AIR_GI_ENVSTRENGTH { ANIM OFF; MIN 0; MAX 1000; STEP 1; UNIT PERCENT; }
			REAL CINEMAN_AIR_GI_ENVBLUR { ANIM OFF; MIN 0; MAX 1000; STEP 1; UNIT PERCENT; }
		}
		
	}
	
	GROUP ID_ADVANCEDOPTIONS
	{
		GROUP GROUP_STRATEGY 
		{
			DEFAULT 1;

			//
			// PRMan
			//
			LONG CINEMAN_PRM_LIMITS_BUCKETSIZEX { ANIM OFF; MIN 2; MAX 128; STEP 1; }
			LONG CINEMAN_PRM_LIMITS_BUCKETSIZEY { ANIM OFF; MIN 2; MAX 128; STEP 1; }
			LONG CINEMAN_PRM_LIMITS_GRIDSIZE { ANIM OFF; MIN 4; MAX 4096; STEP 1; }

			//
			// AIR
			//
			LONG CINEMAN_AIR_LIMITS_BUCKETSIZEX { ANIM OFF; MIN 2; MAX 128; STEP 1; }
			LONG CINEMAN_AIR_LIMITS_BUCKETSIZEY { ANIM OFF; MIN 2; MAX 128; STEP 1; }
			LONG CINEMAN_AIR_RENDER_BUCKETORDER
			{
				ANIM OFF;
				CYCLE
				{
					CINEMAN_AIR_RENDER_BUCKETORDER_VERTICAL;
					CINEMAN_AIR_RENDER_BUCKETORDER_HORIZONTAL;
					CINEMAN_AIR_RENDER_BUCKETORDER_SPIRAL;
				}
			}

			//
			// 3Delight
			//
			LONG CINEMAN_3DL_LIMITS_BUCKETSIZEX { ANIM OFF; MIN 2; MAX 128; STEP 1; }
			LONG CINEMAN_3DL_LIMITS_BUCKETSIZEY { ANIM OFF; MIN 2; MAX 128; STEP 1; }
			LONG CINEMAN_3DL_RENDER_BUCKETORDER
			{
				ANIM OFF;
				CYCLE
				{
					CINEMAN_3DL_RENDER_BUCKETORDER_HORIZONTAL;
					CINEMAN_3DL_RENDER_BUCKETORDER_ZIGZAG;
					CINEMAN_3DL_RENDER_BUCKETORDER_VERTICAL;
					CINEMAN_3DL_RENDER_BUCKETORDER_SPIRAL;
					CINEMAN_3DL_RENDER_BUCKETORDER_CIRCLE;
					CINEMAN_3DL_RENDER_BUCKETORDER_RANDOM;
				}
			}
			LONG CINEMAN_3DL_LIMITS_GRIDSIZE { ANIM OFF; MIN 4; MAX 4096; STEP 1; }
			LONG CINEMAN_3DL_LIMITS_EYESPLITS { ANIM OFF; MIN 0; MAX 64; STEP 1; }
		}

		GROUP GROUP_MEMORY
		{
			DEFAULT 1;

			//
			// PRMan
			//
			LONG CINEMAN_PRM_LIMITS_TEXTUREMEMORY { ANIM OFF; MIN 100; MAX 2000000; STEP 1000; }
			LONG CINEMAN_PRM_LIMITS_BRICKMEMORY { ANIM OFF; MIN 100; MAX 2000000; STEP 1000; }
			LONG CINEMAN_PRM_LIMITS_GEOCACHEMEMORY { ANIM OFF; MIN 100; MAX 2000000; STEP 1000; }

			//
			// AIR
			//
			LONG CINEMAN_AIR_LIMITS_TEXTUREMEMORY { ANIM OFF; MIN 1000; MAX 2000000; STEP 1000; }

			//
			// 3Delight
			//
			LONG CINEMAN_3DL_LIMITS_TEXTUREMEMORY { ANIM OFF; MIN 1000; MAX 2000000; STEP 1000; }
		}
	
	}
	
	GROUP ID_ATMOSPHERE
	{
		LONG CINEMAN_ATMOSPHERE_SAMPLING
		{
			ANIM OFF;
			CYCLE
			{
				CINEMAN_ATMOSPHERE_SAMPLING_AVERAGE;
				CINEMAM_ATMOSPHERE_SAMPLING_USEMIN;
				CINEMAN_ATMOSPHERE_SAMPLING_USEMAX;
				CINEMAN_ATMOSPHERE_SAMPLING_SPECIFY;
			}
		}
		REAL CINEMAN_ATMOSPHERE_STEPSIZE { ANIM OFF; UNIT METER; MIN 0; MINEX; MAX 100000; STEP 5; }

	}
}
