CONTAINER CBcircular
{
	NAME CBcircular;
	INCLUDE Obasecurve;

	GROUP ID_CURVEPROPERTIES
	{
		VECTOR CIRCULARCURVE_CENTER {}
		VECTOR CIRCULARCURVE_P1 {}
		VECTOR CIRCULARCURVE_P2 {}
	}
}
