CONTAINER CBconic
{
	NAME CBconic;
	INCLUDE Obasecurve;

	GROUP ID_CURVEPROPERTIES
	{
		LONG CONICCURVE_TYPE
		{
			CYCLE
			{
		    CONICCURVE_DEPRECIATED;
		    CONICCURVE_ELLIPSE;
		    CONICCURVE_HYPERBOLA;
		    CONICCURVE_PARABOLA;
      }
    }

		SEPARATOR { }

  	VECTOR CONICCURVE_ABC {}
	  VECTOR CONICCURVE_DEF {}
		
    SEPARATOR { }

		VECTOR CONICCURVE_P1 {}
		VECTOR CONICCURVE_P2 {}
	}
}
