CONTAINER CBnurbs
{
	NAME CBnurbs;
	INCLUDE Obasecurve;

	GROUP ID_CURVEPROPERTIES
	{
		LONG NURBSCURVE_DEGREE { MIN 1; MAX 5; }
		LONG NURBSCURVE_POINTCOUNT { MIN 2; }

		SEPARATOR { }

	  REAL NURBSCURVE_TMIN { }
	  REAL NURBSCURVE_TMAX { }

		SEPARATOR { }

		BOOL NURBSCURVE_CLOSED {}
		BOOL NURBSCURVE_POLYNOMIAL {}
		BOOL NURBSCURVE_PERIODICITY {}
	}
}

