CONTAINER CBpolynom
{
	NAME CBpolynom;
	INCLUDE Obasecurve;

	GROUP ID_CURVEPROPERTIES
	{
		LONG POLYNOMCURVE_DEGREE { MIN 1; MAX 3; }
		LONG POLYNOMCURVE_POINTCOUNT { MIN 2; }

		SEPARATOR { }

		BOOL POLYNOMCURVE_CLOSED {}
	}
}

