CONTAINER Obasesurface
{
	NAME Obasesurface;
	INCLUDE Obase;

	GROUP ID_OBJECTPROPERTIES
	{
		LONG BASESURFACE_TYPE
		{
			CYCLE
			{
        BASESURFACE_TYPE_UNKNOWN;
        BASESURFACE_TYPE_NURBS;
        BASESURFACE_TYPE_POLYNOMIAL;
        BASESURFACE_TYPE_PLANE;
        BASESURFACE_TYPE_EXTRUDE;
        BASESURFACE_TYPE_ROTATE;
			}
		}

		SEPARATOR { HIDDEN; }

    BUTTON BASESURFACE_MAKENURBS { HIDDEN; }

		SEPARATOR { HIDDEN; }

    LONG BASESURFACE_OUTPUT
    { HIDDEN;
			CYCLE
			{
		    BASESURFACE_OUTPUT_LINEAR;
		    BASESURFACE_OUTPUT_BSPLINE;
		    BASESURFACE_OUTPUT_HYPERNURBS;
        BASESURFACE_OUTPUT_CONVERT;
      }
    }

	  LONG BASESURFACE_USUB { MIN 1; MAX 5000; }
	  LONG BASESURFACE_VSUB { MIN 1; MAX 5000; }

	  BOOL BASESURFACE_NORMALS	{ }
	  BOOL BASESURFACE_SWAPNORMALS { }
	}

	GROUP ID_SURFACEPROPERTIES
	{
		DEFAULT	1;
	}

	GROUP ID_SURFACETEST
	{
  		BOOL BASESURFACE_TESTON {}
      REAL BASESURFACE_TESTUPOINT { UNIT PERCENT; MIN 0.0; MAX 100.0; }
      REAL BASESURFACE_TESTVPOINT { UNIT PERCENT; MIN 0.0; MAX 100.0; }
  }
}
