CONTAINER Obasegroup
{
	NAME Obasegroup;
	INCLUDE Obase;

	GROUP ID_OBJECTPROPERTIES
	{
    GROUP ID_BASEGROUP_SUBFACTOR
    { 
      DEFAULT 1; COLUMNS 2;
      REAL BASEGROUP_SUBFACTOR_CURVE_SLIDER { CUSTOMGUI REALSLIDERONLY; MINSLIDER -7.0; MAXSLIDER 7.0; SCALE_H; } 
      REAL BASEGROUP_SUBFACTOR_CURVE { HIDDEN; DEFAULT 1.0; MIN 0.125; MAX 8.0; } 
      REAL BASEGROUP_SUBFACTOR_CURVE_REAL { DEFAULT 1.0; MIN 0.125; MAX 8.0; } 

      REAL BASEGROUP_SUBFACTOR_SURFACE_U_SLIDER { CUSTOMGUI REALSLIDERONLY; MINSLIDER -7.0; MAXSLIDER 7.0; SCALE_H; }
      REAL BASEGROUP_SUBFACTOR_SURFACE_U { HIDDEN; DEFAULT 1.0; MIN 0.125; MAX 8.0; }
      REAL BASEGROUP_SUBFACTOR_SURFACE_U_REAL { DEFAULT 1.0; MIN 0.125; MAX 8.0; }

      REAL BASEGROUP_SUBFACTOR_SURFACE_V_SLIDER { CUSTOMGUI REALSLIDERONLY; MINSLIDER -7.0; MAXSLIDER 7.0; SCALE_H; }
      REAL BASEGROUP_SUBFACTOR_SURFACE_V { HIDDEN; DEFAULT 1.0; MIN 0.125; MAX 8.0; }
      REAL BASEGROUP_SUBFACTOR_SURFACE_V_REAL { DEFAULT 1.0; MIN 0.125; MAX 8.0; }

      STATICTEXT { SCALE_H; }
      STATICTEXT { FIT_H; }

      STATICTEXT { SCALE_H; }
      BUTTON BASEGROUP_SUBFACTOR_BUTTON { FIT_H; }

      STATICTEXT { SCALE_H; }
      STATICTEXT { FIT_H; }
    }

    GROUP ID_BASEGROUP_SELECT
    { 
      DEFAULT 1;
      LONG BASEGROUP_SELECT_TYPE { CYCLE { };  SCALE_H; }
      LONG BASEGROUP_SELECT_SUBTYPE { CYCLE { };  SCALE_H; }
      STATICTEXT { }

      GROUP 
      {
        DEFAULT 1; COLUMNS 3;
        STATICTEXT { SCALE_H; }
        BUTTON BASEGROUP_DESELECT_BUTTON { }
        BUTTON BASEGROUP_SELECT_BUTTON { }
        STATICTEXT { SCALE_H; }
        STATICTEXT { SCALE_H; }
        BUTTON BASEGROUP_SELECTONLY_BUTTON { }
      }

      STATICTEXT { }
    }

    GROUP ID_BASEGROUP_CONVERT
    { 
      DEFAULT 1; COLUMNS 2;
      STATICTEXT { SCALE_H; }
      BUTTON BASEGROUP_CONVERT_TOPOLYS { }
      STATICTEXT { SCALE_H; }
      BUTTON BASEGROUP_CONVERT_TOGROUPS { }
      STATICTEXT { SCALE_H; }
      BUTTON BASEGROUP_CONVERT_TOONE { }
    }
  }
}

