CONTAINER Obasecurve
{
	NAME Obasecurve;
	INCLUDE Obase;

	GROUP ID_OBJECTPROPERTIES
	{
		LONG BASECURVE_TYPE
		{
			CYCLE
			{
		    BASECURVE_TYPE_UNKNOWN;
		    BASECURVE_TYPE_NURBS;
		    BASECURVE_TYPE_POLYNOMIAL;
		    BASECURVE_TYPE_LINE;
		    BASECURVE_TYPE_CIRCULAR;
		    BASECURVE_TYPE_CONIC;
		    BASECURVE_TYPE_COMPOSITE;
			}
		}

		SEPARATOR { HIDDEN; }

    BUTTON BASECURVE_MAKENURBS { HIDDEN; }

		SEPARATOR { HIDDEN; }

    LONG BASECURVE_OUTPUT
    { HIDDEN;
			CYCLE
			{
		      BASECURVE_OUTPUT_LINEAR;
		      BASECURVE_OUTPUT_BSPLINE;
		      BASECURVE_OUTPUT_BEZIER;
          BASECURVE_OUTPUT_CONVERT;
      }
    }
		LONG BASECURVE_SUB { MIN 1; MAX 5000; }

		SEPARATOR { }

    LONG BASECURVE_FLATNESS
    {
			CYCLE
			{
		      BASECURVE_PLANAR;
		      BASECURVE_NONPLANAR;
      }
    }
	}

	GROUP ID_CURVEPROPERTIES
	{
		DEFAULT	1;
	}

	GROUP ID_CURVETEST
	{
  		BOOL BASECURVE_TESTON {}
      REAL BASECURVE_TESTPOINT { UNIT PERCENT; MIN 0.0; MAX 100.0; }
  }
}
