CONTAINER Otrimmedsurface
{
	NAME Otrimmedsurface;
	INCLUDE Obase;

	GROUP ID_OBJECTPROPERTIES
	{
		LONG TRIMMEDSURFACE_TYPE
		{
			CYCLE
			{
        TRIMMEDSURFACE_TYPE_UNKNOWN;
        TRIMMEDSURFACE_TYPE_STANDARD;
			}
		}

		REAL TRIMMEDSURFACE_PRECISION   { MIN 0.0001; MAX 1000.0; }
	}

	GROUP ID_TRIMMEDSURFACEPROPERTIES
	{
		DEFAULT	1;
	}
}
