CONTAINER SBnurbs
{
	NAME SBnurbs;
	INCLUDE Obasesurface;

	GROUP ID_SURFACEPROPERTIES
	{

  	LONG NURBSSURFACE_UDEGREE { MIN 1; MAX 5; }
  	LONG NURBSSURFACE_VDEGREE { MIN 1; MAX 5; }
	  LONG NURBSSURFACE_UPOINTCOUNT { MIN 2; }
	  LONG NURBSSURFACE_VPOINTCOUNT { MIN 2; }

 		SEPARATOR { }

  	REAL NURBSSURFACE_UMIN { }
	  REAL NURBSSURFACE_UMAX { }
	  REAL NURBSSURFACE_VMIN { }
	  REAL NURBSSURFACE_VMAX { }

 		SEPARATOR { }

		GROUP
		{
			COLUMNS 2;
		  BOOL NURBSSURFACE_UCLOSED {}
		  BOOL NURBSSURFACE_VCLOSED {}
		  BOOL NURBSSURFACE_UPERIODICITY {}
		  BOOL NURBSSURFACE_VPERIODICITY {}

  	  BOOL NURBSSURFACE_POLYNOMIAL {}
    }
	}
}
