CONTAINER SBplane
{
	NAME SBplane;
	INCLUDE Obasesurface;

	GROUP ID_SURFACEPROPERTIES
	{
		VECTOR PLANESURFACE_DISPLAY_POS {}
		REAL PLANESURFACE_DISPLAY_SIZE { MIN 0.001; MAX 1000.0; }

		SEPARATOR { }

		LONG PLANESURFACE_TYPE
		{
			CYCLE
			{
		    PLANESURFACE_BOUNDED;
		    PLANESURFACE_UNBOUNDED;
      }
    }

		SEPARATOR { }

		REAL PLANESURFACE_A {}
		REAL PLANESURFACE_B {}
		REAL PLANESURFACE_C {}
		REAL PLANESURFACE_D {}

		SEPARATOR { }

	  REAL PLANESURFACE_LIMIT	{}
	}
}
