CONTAINER SBpolynom
{
	NAME SBpolynom;
	INCLUDE Obasesurface;

	GROUP ID_SURFACEPROPERTIES
	{

  	LONG POLYNOMSURFACE_UDEGREE { MIN 1; MAX 5; }
  	LONG POLYNOMSURFACE_VDEGREE { MIN 1; MAX 5; }
	  LONG POLYNOMSURFACE_UPOINTCOUNT { MIN 1; }
	  LONG POLYNOMSURFACE_VPOINTCOUNT { MIN 1; }

 		SEPARATOR { }

		GROUP
		{
			COLUMNS 2;
		  BOOL POLYNOMSURFACE_UCLOSED {}
		  BOOL POLYNOMSURFACE_VCLOSED {}
    }
	}
}
