CONTAINER SBrotate
{
	NAME SBrotate;
	INCLUDE Obasesurface;

	GROUP ID_SURFACEPROPERTIES
	{
		REAL ROTATESURFACE_ANGLE_START {}
		REAL ROTATESURFACE_ANGLE_END {}

		SEPARATOR { }

		LINK ROTATESURFACE_LINK_AXIS
    { 
      ACCEPT { Obase; } 
    }

    BOOL ROTATESURFACE_INVERT_AXIS {}
	}
}
