#ifndef C4D_SYMBOLS_H
#define C4D_SYMBOLS_H

enum
{
	__FIRST_ELEMENT__ = 10000,

	IDS_HOUDINI_ENGINE,
	IDS_MENU_PIPELINE,

	IDS_COMMAND_GET_HOUDINI_INSTALLER_NAME,
	IDS_COMMAND_GET_HOUDINI_INSTALLER_HELP,

	IDS_PREFS_INSTALLATION_STATUS_FOUND,
	IDS_PREFS_INSTALLATION_STATUS_NOT_FOUND,

	IDS_PREFS_LICENSE_TYPE_UNCONFIRMED,

	IDS_PREFS_LICENSE_STATUS_UNINITIALIZED,
};

#endif /* C4D_SYMBOLS_H */