CONTAINER Ohoudinigenerator
{
	NAME Ohoudinigenerator;
	INCLUDE Obase;

	GROUP HOUDINI_PARAMETERS_GROUP
	{
		COLUMNS 1;

		UNITSCALE HOUDINI_UNIT_SCALE { ANIM OFF; }

		SEPARATOR { LINE; }

		GROUP
		{
			COLUMNS 1;

			GROUP HOUDINI_ASSET_CONTROLS
			{
				GROUP
				{
					COLUMNS 5;

					BUTTON HOUDINI_SELECT_GENERATORS {}
					BUTTON HOUDINI_UPDATE_GENERATORS { }
					BUTTON HOUDINI_UPDATE_MATERIALS_ALL { }
					BUTTON HOUDINI_RESET_SIMULATION { }
					BUTTON HOUDINI_COOK_ASSET { }
				}

				SEPARATOR { LINE; }

				GROUP
				{
					COLUMNS 2;

					LONG HOUDINI_PRIORITY
					{
						CYCLE
						{
							HOUDINI_PRIORITY_AUTOMATIC;
							HOUDINI_PRIORITY_MANUAL;
						}
						CUSTOMGUI RADIOBUTTONS; COLUMNS 2;
						ANIM OFF;
					}

					PRIORITY HOUDINI_PRIORITY_SETTINGS { NOCAMERA; ANIM OFF; }
				}
			}

			GROUP HOUDINI_OUTPUT_CONTROLS
			{
				COLUMNS 3;
				BUTTON HOUDINI_SELECT_ASSET {}
				BUTTON HOUDINI_UPDATE_ASSET {}
				BUTTON HOUDINI_UPDATE_MATERIALS_GEN { }
			}

			GROUP HOUDINI_INFOS
			{
				DEFAULT 1;

				STATICTEXT HOUDINI_PATH { BORDER; SCALE_H; }
				STATICTEXT HOUDINI_ASSET_IDENTIFIER { BORDER; SCALE_H; }
				STATICTEXT HOUDINI_OBJECT_IDENTIFIER { BORDER; SCALE_H; }
				STATICTEXT HOUDINI_ASSET_INFORMATION { BORDER; SCALE_H; }
				STATICTEXT HOUDINI_OBJECT_INFORMATION { BORDER; SCALE_H; }
			}

			GROUP HOUDINI_STREAMING_OPTIONS
			{
				DEFAULT 1;
				COLUMNS 1;

				BOOL HOUDINI_STREAMING_UPDATE_PSR { ANIM OFF; }
				BOOL HOUDINI_STREAMING_UPDATE_GEOMETRY { ANIM OFF; }
				BOOL HOUDINI_STREAMING_NORMALS { ANIM OFF; }
				BOOL HOUDINI_STREAMING_UVS { ANIM OFF; }
				BOOL HOUDINI_STREAMING_TEXTURES { ANIM OFF; }
				BOOL HOUDINI_STREAMING_TEXTURES_UPDATE_ON_PARAMETER_CHANGE { ANIM OFF; }
			}
		}
	}
}
