enum
{
	// string table definitions
	IDS_DUMMY1 = 10000,

	IDS_RIGID_BODY_TAG,
	IDS_WORLD_HOOK,
	IDS_SPRING_OBJECT,
	IDS_MOTOR_OBJECT,
	IDS_CONSTRAINT_OBJECT,
	IDS_FORCE_OBJECT,

	IDS_COLLISION_NODE,
	IDS_DYNAMICS_BODY_NODE,
	IDS_DYNAMICS_PROXIMITY_NODE,
	IDS_DYNAMICS_SPRING_NODE,
	IDS_DYNAMICS_CONSTRAINT_NODE,

	IDS_BAKE_DIALOG,

	IDS_BULLET_EXPORT,

	IDS_RIGID_BODY_CMD,
	IDS_RIGID_BODY_CMD_HELP,
	IDS_SOFT_BODY_CMD,
	IDS_SOFT_BODY_CMD_HELP,
	IDS_COLLIDER_CMD,
	IDS_COLLIDER_CMD_HELP,
	IDS_GHOST_CMD,
	IDS_GHOST_CMD_HELP,

	IDS_NO_DYNAMICS_MSG,

// End of symbol definition
	_DUMMY_ELEMENT_
};
