CONTAINER ToolExtrudeInner
{
  NAME ToolExtrudeInner;
	INCLUDE ToolBase;

  GROUP MDATA_MAINGROUP
  {
		COLUMNS 2;

		REAL MDATA_EXTRUDEINNER_ANGLE { UNIT DEGREE; MIN 0; MAX 180; }
		STATICTEXT { JOINEND; }

		REAL MDATA_EXTRUDEINNER_OFFSET { UNIT METER; }
		REAL MDATA_EXTRUDEINNER_VARIANCE { UNIT PERCENT; MIN 0; MAX 200; }

		LONG MDATA_EXTRUDEINNER_SUBDIVISION { MIN 1; }
		BOOL MDATA_EXTRUDEINNER_CREATENGONS { }

		BOOL MDATA_EXTRUDEINNER_PRESERVEGROUPS {}
		STATICTEXT { JOINEND; }
	}
}
