CONTAINER ToolEdgeCut
{
  NAME ToolEdgeCut;
	INCLUDE ToolBase;

  GROUP MDATA_MAINGROUP
  {
		GROUP
		{
			COLUMNS 2;

			REAL MDATA_EDGECUT_OFFSET { UNIT PERCENT; MIN 0; MAX 100; }
			STATICTEXT { JOINEND; }

			REAL MDATA_EDGECUT_SCALE  { UNIT PERCENT; MIN 0.01; }
			STATICTEXT { JOINEND; }

			LONG MDATA_EDGECUT_SUBDIV { MIN 1; MAX 100; }
			BOOL MDATA_EDGECUT_CREATENGONS { }
		}
	}
}
