CONTAINER ToolIron
{
	NAME ToolIron;
	INCLUDE ToolBase;

	//HIDE MDATA_COMMANDGROUP;

	GROUP MDATA_MAINGROUP
	{
		REAL MDATA_IRON_ANGLE { UNIT DEGREE; MIN 0.0; MAX 180.0;}
		REAL MDATA_IRON_PERCENT { UNIT PERCENT; MIN -100.0; MAX 100.0;}
	}
}
