CONTAINER ToolSmoothShift
{
  NAME ToolSmoothShift;
	INCLUDE ToolBase;

  GROUP MDATA_MAINGROUP
  {
		COLUMNS 2;

		REAL MDATA_SMOOTHSHIFT_ANGLE { UNIT DEGREE; MIN 0; MAX 180; }
		STATICTEXT { JOINEND; }

		REAL MDATA_SMOOTHSHIFT_OFFSET { UNIT METER; }
		REAL MDATA_SMOOTHSHIFT_VARIANCE { UNIT PERCENT; MIN 0; MAX 200; }

		LONG MDATA_SMOOTHSHIFT_SUBDIVISION { MIN 1; }
		BOOL MDATA_SMOOTHSHIFT_CREATENGONS { }
  }
}
