CONTAINER ToolBrush
{
	NAME ToolBrush;
	INCLUDE ToolBase;

	HIDE MDATA_COMMANDGROUP;

	GROUP MDATA_MAINGROUP
	{
		GROUP
		{
			COLUMNS 3;

			BOOL MDATA_BRUSH_CONNECTED { }
			BOOL MDATA_BRUSH_PREVIEW { }
			STATICTEXT { JOINEND; }

			LONG MDATA_BRUSH_FALLOFF_MODE
			{
				ALIGN_LEFT;
				CYCLE
				{
					MDATA_BRUSH_MODE_CONSTANT;
					MDATA_BRUSH_MODE_LINEAR;
					MDATA_BRUSH_MODE_DOME;
					MDATA_BRUSH_MODE_BELL;
					MDATA_BRUSH_MODE_CIRCLE;
					MDATA_BRUSH_MODE_NEEDLE;
					MDATA_BRUSH_MODE_USER;
				}
			}
			LONG MDATA_BRUSH_MODE
			{
				ALIGN_LEFT;
				CYCLE
				{
					MDATA_BRUSH_MODE_SMEAR;
					MDATA_BRUSH_MODE_PULL;
					MDATA_BRUSH_MODE_SURFACE;
					MDATA_BRUSH_MODE_NORMAL;
					MDATA_BRUSH_MODE_SPREAD;
					MDATA_BRUSH_MODE_SPIN;
					MDATA_BRUSH_MODE_TWIST;
					MDATA_BRUSH_MODE_VORTEX;
					MDATA_BRUSH_MODE_SMOOTH;
					MDATA_BRUSH_MODE_PAINT;
					MDATA_BRUSH_MODE_BLUR;
					MDATA_BRUSH_MODE_BLEED;
					MDATA_BRUSH_MODE_INTENSITY;
				}
			}
			BOOL MDATA_BRUSH_UPDATENORMALS { }

			REAL MDATA_BRUSH_FALLOFF_STRENGTH  { UNIT PERCENT; }
			REAL MDATA_BRUSH_FALLOFF_RADIUS  { UNIT METER; MIN 0.0; }
			REAL MDATA_BRUSH_FALLOFF_WIDTH  { UNIT PERCENT;  MIN 0.0; }
		}

		GROUP
		{
			SPLINE MDATA_BRUSH_FALLOFF
			{ 
			}
		}
	}
}
