enum
{
	// string table definitions
	IDS_TMOTIONCAM	= 10000,
	IDS_TMORPHCAM,
	IDS_TCRANE,
	IDS_CCREATEMOTIONCAM,
	IDS_CCREATEMORPHCAM,
	IDS_CCREATECAMERACRANE,

	IDS_OP_MOTIONCAMPARENT,
	IDS_OP_MOTIONCAMPATH,
	IDS_OP_MOTIONCAMTARGET,
	IDS_OP_MOTIONCAMCAMERA,
	IDS_OP_MORPHPARENT,
	IDS_OP_MORPHCAMERA,
	IDS_OP_CRANEPARENT,

	IDS_MSG_CCREATEMOTIONCAM,
	IDS_MSG_CCREATEMORPHCAM,
	IDS_MSG_CCREATECAMERACRANE,

	IDS_VIS_TARGETDISTANCE,

	// End of symbol definition
	_DUMMY_ELEMENT_
};
