CONTAINER Prefsbrowser
{
	NAME Prefsbrowser;

	GROUP PREF_BROWSER_MAIN_GROUP
	{
	
		DEFAULT 1;
		COLUMNS 2;

		SEPARATOR  PREF_BROWSER_BASICGROUP {}
		STATICTEXT{JOINENDSCALE;}
		
		//BOOL PREF_BROWSER_SCAN {ANIM OFF;}
		//STATICTEXT{}
		BOOL PREF_BROWSER_SHOWFOLDER {ANIM OFF;}
		STATICTEXT{}
		BOOL PREF_BROWSER_SORTRESULT {ANIM OFF;}
		STATICTEXT{}
		REAL	PREF_BROWSER_PREVIEWTIMEOUT 
		{
			ANIM OFF;
			MIN 10.0;
			MAX 600.0;
		}
		STATICTEXT{}
		SEPARATOR  PREF_BROWSER_PREVIEWGROUP {}
		STATICTEXT{JOINENDSCALE;}
		BOOL PREF_BROWSER_PREVIEWDISPLAY {ANIM OFF;}
		STATICTEXT{}
		LONG	PREF_BROWSER_PREVIEWWIDTH 
		{
			ANIM OFF;
			MIN 128;
			MAX 1024;
		}	
		STATICTEXT{}
		LONG	PREF_BROWSER_PREVIEWHEIGHT
		{
			ANIM OFF;
			MIN 128;
			MAX 1024;
		}	
		STATICTEXT{}
		LONG PREF_BROWSER_PREVIEWCOMP
		{
			ANIM OFF;
			CYCLE
			{
				PREF_BROWSER_PREVIEWCOMP_LOW;
				PREF_BROWSER_PREVIEWCOMP_MED;
				PREF_BROWSER_PREVIEWCOMP_HIGH;

			}
		}
		STATICTEXT{}
		BOOL PREF_BROWSER_PREVIEWRENDER {ANIM OFF;}
		STATICTEXT{}
		
	}
}
