#ifndef C4D_SYMBOLS_H__
#define C4D_SYMBOLS_H__



enum
{
	// plugin IDs
	PLUGIN_ID_SPACEMOUSE = 1016707,
	PLUGIN_ID_NAVIGATE   = 1016708,
	PLUGIN_ID_FLY        = 1016709,
	PLUGIN_ID_MOVE       = 1016710,
	PLUGIN_ID_TOGGLE     = 1019601,

	// dummy for enumeration start
	start = 1000,

	// names and descriptions of command plugins
	IDS_SPACEMOUSE,
	IDS_SPACEMOUSE_DESCR,
	IDS_TOGGLE,
	IDS_TOGGLE_DESCR,
	IDS_NAVIGATE,
	IDS_NAVIGATE_DESCR,
	IDS_FLY,
	IDS_FLY_DESCR,
	IDS_MOVE,
	IDS_MOVE_DESCR,

	// dialog ID and title ID and toggle
	DLG_SPACEMOUSE,
	IDS_DLG_TITEL,
	IDC_ENABLED,
	IDC_REDUCE_ANGLES,
	IDC_MODES,

	// tab (/mode) IDs
	IDC_NAVIGATE,
	IDC_FLY,
	IDC_MOVE,

	// space IDs
	IDC_SPACE_CAM,
	IDC_SPACE_AXIS,
	IDC_SPACE_WORLD,

	// gadget IDs for navigate mode
	IDC_NAVI_MOVE,
	IDC_NAVI_MOVE_INV,
	IDC_NAVI_MOVE_X,
	IDC_NAVI_MOVE_Y,
	IDC_NAVI_MOVE_Z,
	IDC_NAVI_MOVE_SPACE,
	IDC_NAVI_MOVE_SPEED,
	IDC_NAVI_ROT,
	IDC_NAVI_ROT_INV,
	IDC_NAVI_ROT_H,
	IDC_NAVI_ROT_P,
	IDC_NAVI_ROT_B,
	IDC_NAVI_ROT_SPACE,
	IDC_NAVI_ROT_SPEED,

	// gadget IDs for fly mode
	IDC_FLY_MOVE,
	IDC_FLY_MOVE_INV,
	IDC_FLY_MOVE_X,
	IDC_FLY_MOVE_Y,
	IDC_FLY_MOVE_Z,
	IDC_FLY_MOVE_SPACE,
	IDC_FLY_MOVE_SPEED,
	IDC_FLY_ROT,
	IDC_FLY_ROT_H,
	IDC_FLY_ROT_P,
	IDC_FLY_ROT_B,
	IDC_FLY_ROT_INV,
	IDC_FLY_ROT_SPACE,
	IDC_FLY_ROT_SPEED,

	// gadget IDs for move mode
	IDC_MOVE_MOVE,
	IDC_MOVE_MOVE_INV,
	IDC_MOVE_MOVE_X,
	IDC_MOVE_MOVE_Y,
	IDC_MOVE_MOVE_Z,
	IDC_MOVE_MOVE_SPACE,
	IDC_MOVE_MOVE_SPEED,
	IDC_MOVE_ROT,
	IDC_MOVE_ROT_INV,
	IDC_MOVE_ROT_H,
	IDC_MOVE_ROT_P,
	IDC_MOVE_ROT_B,
	IDC_MOVE_ROT_SPACE,
	IDC_MOVE_ROT_SPEED,

	ID_END
};



#endif	// C4D_SYMBOLS_H__
