// C4D-DialogResource
DIALOG IDD_LEASELICENSE
{
  NAME IDS_DIALOG; CENTER_V; CENTER_H; 
  
  GROUP IDC_STATIC
  {
    NAME IDS_STATIC6; ALIGN_TOP; CENTER_H; 
    BORDERSIZE 2, 2, 2, 2; 
    COLUMNS 1;
    SPACE 4, 8;
    
    GROUP IDC_STATIC
    {
      ALIGN_TOP; SCALE_H; 
      BORDERSIZE 0, 0, 0, 0; 
      COLUMNS 3;
      SPACE 4, 4;
      
      STATICTEXT IDC_STATIC { NAME IDS_STATIC3; CENTER_V; ALIGN_LEFT; }
      SLIDER IDC_LEASE_DAYS { ALIGN_TOP; SCALE_H; SIZE 333, 0; }
      STATICTEXT IDC_LEASE_NEW { NAME IDS_STATIC2; CENTER_V; ALIGN_LEFT; }
      STATICTEXT IDC_STATIC { NAME IDS_STATIC9; CENTER_V; ALIGN_LEFT; }
      GROUP IDC_STATIC
      {
        NAME IDS_STATIC7; ALIGN_TOP; SCALE_H; 
        BORDERSTYLE BORDER_NONE; BORDERSIZE 0, 0, 0, 0; 
        ROWS 1;
        
        STATICTEXT IDC_LEASE_MIN { NAME IDS_STATIC1; CENTER_V; SCALE_H; }
        STATICTEXT IDC_LEASE_MAX { NAME IDS_STATIC8; CENTER_V; SCALE_H; }
      }
      STATICTEXT IDC_STATIC { NAME IDS_STATIC10; CENTER_V; ALIGN_LEFT; }
    }
    SEPARATOR { SCALE_H; }
    DLGGROUP { OK; CANCEL; }
  }
}