// C4D-DialogResource

DIALOG R_MODELING_SUBDIVIDE
{
  NAME T1;
  GROUP
  {
    COLUMNS 2;
    
    STATICTEXT { NAME T2; }
    EDITNUMBERARROWS IDC_SUBDIVIDE_SUB { NAME T3; }
  }
	CHECKBOX IDC_SUBDIVIDE_HYPER { NAME T4; }
  GROUP
  {
    COLUMNS 2;
    
    STATICTEXT { NAME T5; }
    EDITNUMBERARROWS IDC_SUBDIVIDE_ANGLE { NAME T3; }
  }

  DLGGROUP { OK;CANCEL;HELP; }
}
