// C4D-DialogResource
DIALOG R_REGISTER
{
  NAME T1; SCALE_V; SCALE_H; 
  
  GROUP 
  {
    SCALE_V; SCALE_H; 
    BORDERSIZE 0, 0, 0, 0; 
    COLUMNS 2;
    SPACE 4, 4;
    
    GROUP IDC_REGISTER_PERSONALIZE_GROUP
    {
      NAME IDS_STATIC2; SCALE_V; SCALE_H; 
      BORDERSTYLE BORDER_GROUP_IN; BORDERSIZE 4, 4, 4, 4; 
      COLUMNS 1;
      SPACE 4, 4;
      
      GROUP IDC_STATIC
      {
        SCALE_V; SCALE_H; 
        BORDERSIZE 4, 4, 4, 4; 
        COLUMNS 2;
        SPACE 4, 4;
        
        STATICTEXT  { NAME T3; CENTER_V; FIT_H; }
        EDITTEXT IDC_REGISTER_NAME_EDIT
        { CENTER_V; FIT_H; SIZE 300, 0; }
        STATICTEXT  { NAME T4; CENTER_V; FIT_H; }
        EDITTEXT IDC_REGISTER_COMPANY_EDIT
        { CENTER_V; FIT_H; SIZE 300, 0; }
        STATICTEXT  { NAME T5; CENTER_V; FIT_H; }
        EDITTEXT IDC_REGISTER_STREET_EDIT
        { CENTER_V; FIT_H; SIZE 300, 0; }
        STATICTEXT  { NAME T6; CENTER_V; FIT_H; }
        EDITTEXT IDC_REGISTER_CITY_EDIT
        { CENTER_V; FIT_H; SIZE 300, 0; }
        STATICTEXT  { NAME T7; CENTER_V; FIT_H; }
        EDITTEXT IDC_REGISTER_COUNTRY_EDIT
        { CENTER_V; FIT_H; SIZE 300, 0; }
      }
      GROUP IDC_REGISTER_EDIT_GROUP
      {
        NAME IDS_STATIC5; ALIGN_TOP; FIT_H; 
        BORDERSIZE 4, 4, 4, 4; 
        COLUMNS 1;
        SPACE 4, 4;
        
        SEPARATOR { SCALE_H; }
        GROUP IDC_STATIC
        {
          NAME IDS_STATIC35; ALIGN_TOP; SCALE_H; 
          BORDERSTYLE BORDER_NONE; BORDERSIZE 0, 0, 0, 0; 
          COLUMNS 2;
          
          STATICTEXT IDC_STATIC { NAME IDS_STATIC3; CENTER_V; SCALE_H; }
          BUTTON IDC_REGISTER_PASTE_BTN { NAME IDS_REGISTER_PASTE; ALIGN_TOP; ALIGN_RIGHT; }
        }
        MULTILINEEDIT IDC_REGISTER_SERIALS_EDIT
        { CENTER_V; SCALE_H; SIZE 70, 130; }
      }
    }
    GROUP IDC_REGISTER_RIGHT_GROUP
    {
      NAME IDS_STATIC21; SCALE_V; SCALE_H; 
      BORDERSIZE 0, 0, 0, 0; 
      COLUMNS 2;
      SPACE 4, 4;
      
      GROUP IDC_REGISTER_LICENSESERVER_GROUP
      {
        NAME IDS_STATIC6; ALIGN_TOP; ALIGN_LEFT; 
        BORDERSTYLE BORDER_GROUP_IN; BORDERSIZE 4, 4, 4, 4; 
        COLUMNS 2;
        SPACE 4, 4;
        
        STATICTEXT IDC_STATIC { NAME IDS_STATIC7; CENTER_V; ALIGN_LEFT; }
        STATICTEXT IDC_REGISTER_LSERVER_ADDRESS_STATIC { NAME IDS_STATIC8; CENTER_V; ALIGN_LEFT; SIZE 350, 0; BORDERSTYLE BORDER_THIN_IN; }
        STATICTEXT IDC_STATIC { NAME IDS_STATIC9; CENTER_V; ALIGN_LEFT; }
        STATICTEXT IDC_REGISTER_LSERVER_PORT_STATIC { NAME IDS_STATIC10; CENTER_V; ALIGN_LEFT; SIZE 350, 0; BORDERSTYLE BORDER_THIN_IN; }
        STATICTEXT IDC_REGISTER_LSERVER_ERROR_LABEL_STATIC { NAME IDS_STATIC11; CENTER_V; ALIGN_LEFT; }
        STATICTEXT IDC_REGISTER_LSERVER_ERROR_STATIC { NAME IDS_STATIC12; CENTER_V; ALIGN_LEFT; SIZE 350, 0; BORDERSTYLE BORDER_THIN_IN; }
        STATICTEXT IDC_REGISTER_LSERVER_INFO_LABEL0_STATIC { NAME IDS_STATIC18; CENTER_V; ALIGN_LEFT; }
        STATICTEXT IDC_REGISTER_LSERVER_INFO0_STATIC { NAME IDS_STATIC19; CENTER_V; ALIGN_LEFT; SIZE 350, 0; BORDERSTYLE BORDER_THIN_IN; }
        STATICTEXT IDC_REGISTER_LSERVER_INFO_LABEL1_STATIC { NAME IDS_STATIC26; CENTER_V; ALIGN_LEFT; }
        STATICTEXT IDC_REGISTER_LSERVER_INFO1_STATIC { NAME IDS_STATIC27; CENTER_V; ALIGN_LEFT; SIZE 350, 0; BORDERSTYLE BORDER_THIN_IN; }
        STATICTEXT IDC_REGISTER_LSERVER_INFO_LABEL2_STATIC { NAME IDS_STATIC28; CENTER_V; ALIGN_LEFT; }
        STATICTEXT IDC_REGISTER_LSERVER_INFO2_STATIC { NAME IDS_STATIC29; CENTER_V; ALIGN_LEFT; SIZE 350, 0; BORDERSTYLE BORDER_THIN_IN; }
        STATICTEXT IDC_REGISTER_LSERVER_INFO_LABEL3_STATIC { NAME IDS_STATIC30; CENTER_V; ALIGN_LEFT; }
        STATICTEXT IDC_REGISTER_LSERVER_INFO3_STATIC { NAME IDS_STATIC31; CENTER_V; ALIGN_LEFT; SIZE 350, 0; BORDERSTYLE BORDER_THIN_IN; }
        STATICTEXT IDC_REGISTER_LSERVER_INFO_LABEL4_STATIC { NAME IDS_STATIC32; CENTER_V; ALIGN_LEFT; }
        STATICTEXT IDC_REGISTER_LSERVER_INFO4_STATIC { NAME IDS_STATIC33; CENTER_V; ALIGN_LEFT; SIZE 350, 0; BORDERSTYLE BORDER_THIN_IN; }
        BUTTON IDC_REGISTER_LSERVER_VALID_BTN { NAME IDS_BUTTON; ALIGN_TOP; ALIGN_LEFT; }
        STATICTEXT IDC_REGISTER_LSERVER_VALID_STATIC { NAME IDS_STATIC13; CENTER_V; ALIGN_LEFT; SIZE 350, 0; BORDERSTYLE BORDER_THIN_IN; }
        STATICTEXT IDC_STATIC { NAME IDS_STATIC14; CENTER_V; ALIGN_LEFT; }
        STATICTEXT IDC_REGISTER_LSERVER_LEASETIME_STATIC { NAME IDS_STATIC15; CENTER_V; ALIGN_LEFT; SIZE 350, 0; BORDERSTYLE BORDER_THIN_IN; }
        STATICTEXT IDC_STATIC { NAME IDS_STATIC16; CENTER_V; SCALE_H; }
        STATICTEXT IDC_REGISTER_LSERVER_STATE1_STATIC { NAME IDS_STATIC17; CENTER_V; SCALE_H; SIZE 350, 0; }
        STATICTEXT IDC_STATIC { NAME IDS_STATIC22; CENTER_V; ALIGN_LEFT; }
        STATICTEXT IDC_REGISTER_LSERVER_STATE2_STATIC { NAME IDS_STATIC23; CENTER_V; SCALE_H; }
        STATICTEXT IDC_STATIC { NAME IDS_STATIC24; CENTER_V; ALIGN_LEFT; }
        STATICTEXT IDC_REGISTER_LSERVER_STATE3_STATIC { NAME IDS_STATIC25; CENTER_V; SCALE_H; }
      }
      GROUP IDC_REGISTER_REGISTRATION_GROUP
      {
        NAME IDS_STATIC1; SCALE_V; SCALE_H; 
        BORDERSTYLE BORDER_GROUP_IN; BORDERSIZE 4, 4, 4, 4; 
        COLUMNS 1;
        SPACE 4, 4;
        
        GROUP IDC_REGISTER_SERIALS_GROUP
        {
          NAME IDS_STATIC4; ALIGN_TOP; ALIGN_LEFT; 
          BORDERSIZE 0, 0, 0, 0; 
          COLUMNS 1;
          SPACE 4, 4;
          
          
        }
      }
    }
  }
}