enum
{
	// string table definitions
	IDS_IGES = 10000,
	IDS_IGESIMPORTTAG,
	IDS_IGESENTITYTAG,

	STR_ERROR_IGES143_PSPACE,
	STR_ERROR_IGES143_MSPACE,
	STR_ERROR_IGES144_MSPACE,
	STR_ERROR_IGES186_UNKNOWN,
	STR_ERROR_IGES514_SHELL,
	STR_ERROR_IGES_UNKNOWN,
	STR_ERROR_IGES_UNSUPPORTED,
	STR_ERROR_IGES_EXPORTHELP,
	STR_ERROR_IGES_CANCEL,

	DUMMY_
};
