enum
{
	GV_STATUS_STRING = 0,

	// Data & Value Types
	IDS_TP_VALUE_TYPE_PARTICLE,
	IDS_TP_DATA_TYPE_PARTICLE,
	IDS_TP_VALUE_TYPE_SHAPE,
	IDS_TP_DATA_TYPE_SHAPE,
	IDS_TP_VALUE_TYPE_GROUP,
	IDS_TP_DATA_TYPE_GROUP,
	IDS_TP_VALUE_TYPE_SPIN,
	IDS_TP_DATA_TYPE_SPIN,
	////

	// Strings
	IDS_THINKING_NAMEVERS,
	IDS_THINKING_NAME,
	IDS_THINKING_HELP,
	IDS_THINKINGCOMMAND_NAME,
	IDS_THINKINGCOMMAND_HELP,
	IDS_THINKING_PREREMOVE_PGROUP,

	IDD_THINKING,
	IDC_TP_ADD,
	IDC_TP_REMOVE,

	IDS_VIEWTYPE_NONE,
	IDS_VIEWTYPE_FLAKES,
	IDS_VIEWTYPE_DOTS,
	IDS_VIEWTYPE_TICKS,
	IDS_VIEWTYPE_DROPS,
	IDS_VIEWTYPE_BOX,
	IDS_VIEWTYPE_GLOBAL,
	///////

/// PGroup
	IDS_PGROUP_NAME,
	IDS_PGROUP_ALL,
	IDS_PGROUP_GROUP,
	IDS_PGROUP_SETTINGS,
	IDS_PGROUP_ADD,
	IDS_PGROUP_REMOVE,
/// TP_ParticleGeometry
	IDS_TP_PARTICLEGEOMETRY_NAME,
	IDS_TP_PARTICLEGEOMETRY_DESCRIPTION,
	IDS_TPNAME,

	// Dialog definitions of idd_thinking_settings start here
	IDD_THINKING_SETTINGS,
	IDC_TAB1,
	IDC_TP_NUMLIMIT,
	IDC_TP_CTOTAL,
	IDC_TP_VIEWTYPE,
	IDC_TP_CTREE,
	IDC_TP_FORCETHIS,
	IDC_TP_CGROUP,
	IDC_TP_SHOWOBJECT,
	IDC_TP_GROUP,
	IDC_TP_GROUPSETTINGS,
	IDC_TAB2,
	IDC_TP_CHAN,
	IDC_TP_DATANAME,
	IDC_TP_DATAS,
	IDC_TP_ADDDATA,
	IDC_TP_REMOVEDATA,
	// Dialog definitions of idd_thinking_settings end here

	// End of symbol definition
	_DUMMY_ELEMENT_
};
