CONTAINER tcrane
{
	NAME tcrane;
	INCLUDE Texpression;

	GROUP Obaselist
	{
		GROUP TCRANE_VISUALIZATION
		{
			DEFAULT 1;

			BOOL				TCRANE_VISUALIZATION_ENABLED					{  }
			COLOR				TCRANE_VISUALIZATION_COLOR						{  }
			COLOR				TCRANE_VISUALIZATION_COLOR_T					{  }
		}
	}

	GROUP ID_TAGPROPERTIES
	{
		DEFAULT 1;

		SEPARATOR		TCRANE_BASE														{  }
		LINK				TCRANE_BASE_LINK											{ ACCEPT {  } }
		LINK				TCRANE_BASE_LINK_RAIL									{ ACCEPT {  } }
		REAL				TCRANE_BASE_LINK_POS									{ UNIT PERCENT; MIN 0.0; MAX 100.0; STEP 0.1; CUSTOMGUI REALSLIDER; }
		BOOL				TCRANE_BASE_LINK_TANGENTIAL						{  }
		REAL				TCRANE_BASE_HEADING										{ UNIT DEGREE; STEP 0.1; }
		REAL				TCRANE_BASE_HEIGHT										{ UNIT METER; MIN 0.0; }

		SEPARATOR		TCRANE_ARM														{  }
		REAL				TCRANE_ARM_LENGTH											{ UNIT METER; MIN 0.0; }
		REAL				TCRANE_ARM_PITCH											{ UNIT DEGREE; STEP 0.1; }
		LINK				TCRANE_ARM_TARGETLINK									{ ACCEPT {  } }

		SEPARATOR		TCRANE_HEAD														{  }
		REAL				TCRANE_HEAD_A_HEIGHT									{ UNIT METER; }
		REAL				TCRANE_HEAD_A_HEADING									{ UNIT DEGREE; STEP 0.1; }
		REAL				TCRANE_HEAD_B_LENGTH									{ UNIT METER; }
		LINK				TCRANE_HEAD_TARGETLINK								{ ACCEPT {  } }

		SEPARATOR		TCRANE_CAM														{  }
		REAL				TCRANE_CAM_PITCH											{ UNIT DEGREE; STEP 0.1; }
		REAL				TCRANE_CAM_BANKING										{ UNIT DEGREE; STEP 0.1; }
		REAL				TCRANE_CAM_PARALLAX										{ UNIT METER; }

		GROUP
		{
			COLUMNS 2;

			BOOL				TCRANE_CAM_COMPENSATE_PITCH						{  }
			BOOL				TCRANE_CAM_COMPENSATE_HEADING					{  }
		}
	}
}
