CONTAINER tmorphcam
{
	NAME tmorphcam;
	INCLUDE Texpression;

	GROUP Obaselist
	{
		GROUP TMORPHCAM_VISUALIZATION
		{
			DEFAULT 1;

			BOOL				TMORPHCAM_VISUALIZATION_POS					{  }
			BOOL				TMORPHCAM_VISUALIZATION_ALIGN				{  }
			BOOL				TMORPHCAM_VISUALIZATION_NAMES				{  }
			BOOL				TMORPHCAM_VISUALIZATION_CAM_ENABLED	{  }
			COLOR				TMORPHCAM_VISUALIZATION_CAM_COLOR		{  }
		}
	}

	GROUP ID_TAGPROPERTIES
	{
		COLUMNS 2;

		REAL				TMORPHCAM_BLEND												{ PARENTCOLLAPSE; UNIT PERCENT; STEP 0.1; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; }
		STATICTEXT	{ JOINENDSCALE; }
		SPLINE			TMORPHCAM_BLEND_CURVE									{ PARENTCOLLAPSE TMORPHCAM_BLEND; }
		STATICTEXT	{ PARENTCOLLAPSE TMORPHCAM_BLEND; JOINENDSCALE; }

		GROUP
		{
			COLUMNS 2;
			LONG				TMORPHCAM_INTERPOLATION
			{
				CYCLE
				{
					TMORPHCAM_INTERPOLATION_LINEAR;
					TMORPHCAM_INTERPOLATION_CUBIC;
					TMORPHCAM_INTERPOLATION_AKIMA;
				}
			}
			STATICTEXT	{  }
		}
		STATICTEXT	{ JOINENDSCALE; }

		BOOL				TMORPHCAM_STEADY											{  }
		STATICTEXT	{ JOINENDSCALE; }
		LINK				TMORPHCAM_STEADY_LINK									{ ACCEPT { Obase; } }
		STATICTEXT	{ JOINENDSCALE; }

		GROUP	TMORPHCAM_LIST
		{
			DEFAULT 1;
			COLUMNS 2;

			GROUP
			{
				COLUMNS 2;

				LONG		TMORPHCAM_LIST_MODE
				{
					CYCLE
					{
						TMORPHCAM_LIST_MODE_SIMPLE;
						TMORPHCAM_LIST_MODE_MULTI;
					}
				}
				STATICTEXT	{ }
			}
			STATICTEXT	{ JOINENDSCALE; }

			STATICTEXT	TMORPHCAM_INFOTEXT									{ ANIM OFF; }
			STATICTEXT	{ JOINENDSCALE; }

			LINK		TMORPHCAM_LIST_LINK_A										{ ACCEPT { Ocamera; 1028083; } }
			STATICTEXT	{ JOINENDSCALE; }
			LINK		TMORPHCAM_LIST_LINK_B										{ ACCEPT { Ocamera; 1028083; } }
			STATICTEXT	{ JOINENDSCALE; }

			IN_EXCLUDE	TMORPHCAM_LIST_LINKS								{ OPEN; NUM_FLAGS 0; ACCEPT { Ocamera; 1028083; } }
			STATICTEXT	{ JOINENDSCALE; }
		}
		STATICTEXT	{ JOINENDSCALE; }
	}

	GROUP TMORPHCAM_TRACK
	{
		BOOL				TMORPHCAM_TRACK_FOCALLENGTH					{  }
		BOOL				TMORPHCAM_TRACK_APERTURE						{  }
		BOOL				TMORPHCAM_TRACK_TARGETDIST					{  }
		BOOL				TMORPHCAM_TRACK_DOF									{  }
		BOOL				TMORPHCAM_TRACK_WB									{  }
		BOOL				TMORPHCAM_TRACK_STEREO							{  }

		SEPARATOR		TMORPHCAM_TRACK_PHY									{  }
		BOOL				TMORPHCAM_TRACK_PHY_FNUMBER					{  }
		BOOL				TMORPHCAM_TRACK_PHY_ISOGAIN					{  }
		BOOL				TMORPHCAM_TRACK_PHY_SHUTTER					{  }
		BOOL				TMORPHCAM_TRACK_PHY_LENSDIST				{  }
		BOOL				TMORPHCAM_TRACK_PHY_VIGNETTE				{  }
		BOOL				TMORPHCAM_TRACK_PHY_ABERRATION			{  }
	}
}
