CONTAINER Tmotioncam
{
	NAME Tmotioncam;
	INCLUDE Texpression;

	GROUP Obaselist
	{
		GROUP TMOTIONCAM_VIS
		{
			DEFAULT 1;

			SEPARATOR	TMOTIONCAM_VIS_CAM										{  }
			BOOL			TMOTIONCAM_VIS_CAM_ENABLED						{  }
			COLOR			TMOTIONCAM_VIS_CAM_COL								{  }

			SEPARATOR	TMOTIONCAM_VIS_RIG										{  }
			GROUP
			{
				COLUMNS 2;

				BOOL			TMOTIONCAM_VIS_RIG_ENABLED						{  }
				LONG			TMOTIONCAM_VIS_RIG_MODE
				{
					CYCLE
					{
						TMOTIONCAM_VIS_RIG_MODE_SIMPLE;
						TMOTIONCAM_VIS_RIG_MODE_FIGURE;
					}
				}
			}
			COLOR			TMOTIONCAM_VIS_RIG_COL								{  }

			SEPARATOR	TMOTIONCAM_VIS_TARGET									{  }
			GROUP
			{
				COLUMNS 3;

				BOOL			TMOTIONCAM_VIS_TARGET_ENABLED					{  }
				REAL			TMOTIONCAM_VIS_TARGET_RADIUS					{ UNIT REAL; MIN 0.0; STEP 1.0; }
				STATICTEXT	{  }
			}
			BOOL			TMOTIONCAM_VIS_TARGET_DRAWDISTTEXT			{  }
			BOOL			TMOTIONCAM_VIS_TARGET_DRAWABERRATION		{  }
			BOOL			TMOTIONCAM_VIS_TARGET_DRAWSINGLETARGETS	{  }
			COLOR			TMOTIONCAM_VIS_TARGET_COLOR							{  }
		}
	
		GROUP		TMOTIONCAM_EXPORT
		{
			DEFAULT  0;
			LINK				TMOTIONCAM_EXPORT_TARGETPOS_LINK			{ ACCEPT { Obase; } }
			VECTOR			TMOTIONCAM_EXPORT_TARGETPOS_VECTOR		{ ANIM OFF; UNIT METER; }
			SEPARATOR		{ LINE; }
			LINK				TMOTIONCAM_EXPORT_FOOTPOS_LINK				{ ACCEPT { Obase; } }
			VECTOR			TMOTIONCAM_EXPORT_FOOTPOS_VECTOR			{ ANIM OFF; UNIT METER; }
			SEPARATOR		{ LINE; }
			LINK				TMOTIONCAM_EXPORT_HEADPOS_LINK				{ ACCEPT { Obase; } }
			VECTOR			TMOTIONCAM_EXPORT_HEADPOS_VECTOR			{ ANIM OFF; UNIT METER; }
			SEPARATOR		{ LINE; }
			REAL				TMOTIONCAM_EXPORT_SPEED								{ ANIM OFF; UNIT METER; }
		}
	}

	HIDE ID_TAGPROPERTIES;
	
	GROUP TMOTIONCAM_RIG
	{
		DEFAULT 1;

		REAL			TMOTIONCAM_RIG_HEIGHT									{ UNIT METER; }
		VECTOR		TMOTIONCAM_RIG_PARALLAX								{ UNIT METER; }

		SEPARATOR	TMOTIONCAM_ROT_MANUAL									{  }

		VECTOR		TMOTIONCAM_ROT_MANUAL_HEAD						{ UNIT DEGREE; MIN -180.0; MAX 180.0; }
		VECTOR		TMOTIONCAM_ROT_MANUAL_CAM							{ UNIT DEGREE; MIN -180.0; MAX 180.0; }

		SEPARATOR	TMOTIONCAM_BASE												{  }

		LINK			TMOTIONCAM_BASE_LINK									{ ACCEPT { Obase; } }

		GROUP
		{
			COLUMNS 2;
			BOOL			TMOTIONCAM_BASE_INHERITPARAMS					{  }
			BOOL			TMOTIONCAM_BASE_OVERRIDE_RIGHEIGHT		{  }
		}
	}
	
	GROUP TMOTIONCAM_ANIMATION
	{
		GROUP TMOTIONCAM_SPLINE
		{
			DEFAULT 1;

			GROUP
			{
				COLUMNS 2;

				BOOL		TMOTIONCAM_SPLINE_ENABLED								{  }
				BOOL		TMOTIONCAM_SPLINE_TANGENTIAL						{  }
			}
			LINK		TMOTIONCAM_SPLINE_A											{ ACCEPT {  } REFUSE { 1018544; 1019396; } }
			LINK		TMOTIONCAM_SPLINE_A_RAIL								{ ACCEPT {  } REFUSE { 1018544; 1019396; } }
			LINK		TMOTIONCAM_SPLINE_B											{ ACCEPT {  } REFUSE { 1018544; 1019396; } }
			LINK		TMOTIONCAM_SPLINE_B_RAIL								{ ACCEPT {  } REFUSE { 1018544; 1019396; } }

			SEPARATOR																				{ LINE; }

			REAL		TMOTIONCAM_SPLINE_POS_A									{ PARENTCOLLAPSE; UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; }
			SPLINE	TMOTIONCAM_SPLINE_POS_A_SPLINE					{ PARENTCOLLAPSE TMOTIONCAM_SPLINE_POS_A; }
			GROUP
			{
				COLUMNS 3;
				PARENTCOLLAPSE TMOTIONCAM_SPLINE_POS_A;

				BOOL				TMOTIONCAM_SPLINE_AUTO_A_ENABLED		{ PARENTCOLLAPSE TMOTIONCAM_SPLINE_POS_A; }
				BASETIME		TMOTIONCAM_SPLINE_AUTO_A_START			{ PARENTCOLLAPSE TMOTIONCAM_SPLINE_POS_A; }
				BASETIME		TMOTIONCAM_SPLINE_AUTO_A_END				{ PARENTCOLLAPSE TMOTIONCAM_SPLINE_POS_A; }
			}
			SEPARATOR																				{ PARENTCOLLAPSE TMOTIONCAM_SPLINE_POS_A; }
			REAL		TMOTIONCAM_SPLINE_POS_B									{ PARENTCOLLAPSE; UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; }
			SPLINE	TMOTIONCAM_SPLINE_POS_B_SPLINE					{ PARENTCOLLAPSE TMOTIONCAM_SPLINE_POS_B; }
			GROUP
			{
				COLUMNS 3;
				PARENTCOLLAPSE TMOTIONCAM_SPLINE_POS_B;

				BOOL				TMOTIONCAM_SPLINE_AUTO_B_ENABLED		{ PARENTCOLLAPSE TMOTIONCAM_SPLINE_POS_B; }
				BASETIME		TMOTIONCAM_SPLINE_AUTO_B_START			{ PARENTCOLLAPSE TMOTIONCAM_SPLINE_POS_B; }
				BASETIME		TMOTIONCAM_SPLINE_AUTO_B_END				{ PARENTCOLLAPSE TMOTIONCAM_SPLINE_POS_B; }
			}
			SEPARATOR																				{ PARENTCOLLAPSE TMOTIONCAM_SPLINE_POS_B; }
			REAL		TMOTIONCAM_SPLINE_POS_BLEND							{ PARENTCOLLAPSE; UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; }
			SPLINE	TMOTIONCAM_SPLINE_POS_BLEND_SPLINE			{ PARENTCOLLAPSE TMOTIONCAM_SPLINE_POS_BLEND; }
			GROUP
			{
				COLUMNS 3;
				PARENTCOLLAPSE TMOTIONCAM_SPLINE_POS_BLEND;

				BOOL				TMOTIONCAM_SPLINE_AUTO_BLEND_ENABLED		{ PARENTCOLLAPSE TMOTIONCAM_SPLINE_POS_BLEND; }
				BASETIME		TMOTIONCAM_SPLINE_AUTO_BLEND_START			{ PARENTCOLLAPSE TMOTIONCAM_SPLINE_POS_BLEND; }
				BASETIME		TMOTIONCAM_SPLINE_AUTO_BLEND_END				{ PARENTCOLLAPSE TMOTIONCAM_SPLINE_POS_BLEND; }
			}

			SEPARATOR																				{ LINE; }

			REAL		TMOTIONCAM_SPLINE_INTENSITY							{ UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; }
		}
		
		GROUP	TMOTIONCAM_TARGET
		{
			DEFAULT 1;

			GROUP
			{
				COLUMNS 2;

				BOOL		TMOTIONCAM_TARGET_ENABLED							{  }
				BOOL		TMOTIONCAM_TARGET_COMPENSATE_PARALLAX	{  }
			}

			SEPARATOR																				{ LINE; }

			LINK		TMOTIONCAM_TARGET_A1										{ ACCEPT { Obase; } }
			GROUP
			{
				REAL		TMOTIONCAM_TARGET_SPLINE_A1_POS				{ UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; }
			}

			SEPARATOR																				{ LINE; }

			LINK		TMOTIONCAM_TARGET_A2										{ ACCEPT { Obase; } }
			GROUP
			{
				REAL		TMOTIONCAM_TARGET_SPLINE_A2_POS				{ UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; }
			}

			SEPARATOR																				{ LINE; }

			LINK		TMOTIONCAM_TARGET_B1										{ ACCEPT { Obase; } }
			GROUP
			{
				REAL		TMOTIONCAM_TARGET_SPLINE_B1_POS				{ UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; }
			}

			SEPARATOR																				{ LINE; }

			LINK		TMOTIONCAM_TARGET_B2										{ ACCEPT { Obase; } }
			GROUP
			{
				REAL		TMOTIONCAM_TARGET_SPLINE_B2_POS				{ UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; }
			}

			SEPARATOR																				{ LINE; }

			LINK		TMOTIONCAM_TARGET_UPVECTOR							{ ACCEPT { Obase; } }
			GROUP
			{
				REAL		TMOTIONCAM_TARGET_SPLINE_UPVECTOR_POS	{ UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; }
			}

			SEPARATOR																				{ LINE; }

			REAL		TMOTIONCAM_TARGET_BLEND_A								{ PARENTCOLLAPSE; UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; }
			SPLINE	TMOTIONCAM_TARGET_BLEND_A_SPLINE				{ PARENTCOLLAPSE TMOTIONCAM_TARGET_BLEND_A; }
			REAL		TMOTIONCAM_TARGET_BLEND_B								{ PARENTCOLLAPSE; UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; }
			SPLINE	TMOTIONCAM_TARGET_BLEND_B_SPLINE				{ PARENTCOLLAPSE TMOTIONCAM_TARGET_BLEND_B; }
			REAL		TMOTIONCAM_TARGET_BLEND_AB							{ PARENTCOLLAPSE; UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; }
			SPLINE	TMOTIONCAM_TARGET_BLEND_AB_SPLINE				{ PARENTCOLLAPSE TMOTIONCAM_TARGET_BLEND_AB; }

			SEPARATOR																				{ LINE; }

			REAL		TMOTIONCAM_TARGET_INTENSITY							{ PARENTCOLLAPSE; UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; }
			SPLINE	TMOTIONCAM_TARGET_INTENSITY_SPLINE			{ PARENTCOLLAPSE TMOTIONCAM_TARGET_INTENSITY; }
		}
		
		GROUP	TMOTIONCAM_FOLLOW
		{
			BOOL			TMOTIONCAM_FOLLOW_ENABLED							{  }
			LINK			TMOTIONCAM_FOLLOW_LINK								{ ACCEPT { Obase; } }
			REAL			TMOTIONCAM_FOLLOW_MAXDISTANCE					{ UNIT METER; MIN 0.0; }
			REAL			TMOTIONCAM_FOLLOW_MINDISTANCE					{ UNIT METER; MIN 0.0; }
		}

		GROUP	TMOTIONCAM_AUTOBANKING
		{
			BOOL			TMOTIONCAM_AUTOBANKING_ENABLED				{  }
			REAL			TMOTIONCAM_AUTOBANKING_INTENSITY			{ UNIT REAL; MIN 0.0; STEP 0.1; }
			REAL			TMOTIONCAM_AUTOBANKING_DAMPEN					{ UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; }
		}
	}
	
	GROUP TMOTIONCAM_DYNAMICS
	{
		SEPARATOR	TMOTIONCAM_FOOT_DYN										{  }
		BOOL			TMOTIONCAM_FOOT_DYN_ENABLED						{  }
		GROUP
		{
			COLUMNS 2;

			LONG			TMOTIONCAM_FOOT_DYN_MODE
			{
				CYCLE
				{
					TMOTIONCAM_DYN_MODE_DAMPEN;
					TMOTIONCAM_DYN_MODE_SPRING;
				}
			}
			STATICTEXT																		{  }
		}
		REAL		TMOTIONCAM_FOOT_DYN_DAMP_POS						{ UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; }
		REAL		TMOTIONCAM_FOOT_DYN_DAMP_ROT						{ UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; }
		REAL		TMOTIONCAM_FOOT_DYN_INERTIA_POS					{ UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; }
		REAL		TMOTIONCAM_FOOT_DYN_INERTIA_ROT					{ UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; }

		SEPARATOR	TMOTIONCAM_HEAD_DYN										{  }
		BOOL			TMOTIONCAM_HEAD_DYN_ENABLED						{  }
		GROUP
		{
			COLUMNS 2;
			
			LONG			TMOTIONCAM_HEAD_DYN_MODE
			{
				CYCLE
				{
					TMOTIONCAM_DYN_MODE_DAMPEN;
					TMOTIONCAM_DYN_MODE_SPRING;
				}
			}
			STATICTEXT																		{  }
		}
		REAL		TMOTIONCAM_HEAD_DYN_DAMP_POS						{ UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; }
		REAL		TMOTIONCAM_HEAD_DYN_DAMP_ROT						{ UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; }
		REAL		TMOTIONCAM_HEAD_DYN_INERTIA_POS					{ UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; }
		REAL		TMOTIONCAM_HEAD_DYN_INERTIA_ROT					{ UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; }

		SEPARATOR	TMOTIONCAM_CAM_DYN										{  }
		BOOL			TMOTIONCAM_CAM_DYN_ENABLED						{  }
		GROUP
		{
			COLUMNS 2;
			
			LONG			TMOTIONCAM_CAM_DYN_MODE
			{
				CYCLE
				{
					TMOTIONCAM_DYN_MODE_DAMPEN;
					TMOTIONCAM_DYN_MODE_SPRING;
				}
			}
			STATICTEXT																		{  }
		}
		REAL		TMOTIONCAM_CAM_DYN_DAMP_POS							{ UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; }
		REAL		TMOTIONCAM_CAM_DYN_DAMP_ROT							{ UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; }
		REAL		TMOTIONCAM_CAM_DYN_INERTIA_POS					{ UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; }
		REAL		TMOTIONCAM_CAM_DYN_INERTIA_ROT					{ UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; }

		SEPARATOR	TMOTIONCAM_FOCUS_DYN									{  }
		BOOL			TMOTIONCAM_FOCUS_DYN_ENABLED					{  }
		GROUP
		{
			COLUMNS 2;
			
			LONG			TMOTIONCAM_FOCUS_DYN_MODE
			{
				CYCLE
				{
					TMOTIONCAM_DYN_MODE_DAMPEN;
					TMOTIONCAM_DYN_MODE_SPRING;
				}
			}
			STATICTEXT																		{  }
		}
		REAL		TMOTIONCAM_FOCUS_DYN_DAMP								{ UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; }
		REAL		TMOTIONCAM_FOCUS_DYN_INERTIA						{ UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; }
	}
	
	GROUP TMOTIONCAM_NMOTION
	{
		GROUP
		{
			COLUMNS 2;

			LONG			TMOTIONCAM_NMOTION_PRESET
			{
				CYCLE
				{
					TMOTIONCAM_NMOTION_PRESET_CUSTOM;
					TMOTIONCAM_NMOTION_PRESET_QUIET;
					TMOTIONCAM_NMOTION_PRESET_STEADYCAM_1;
					TMOTIONCAM_NMOTION_PRESET_STEADYCAM_2;
					TMOTIONCAM_NMOTION_PRESET_EGO;
					TMOTIONCAM_NMOTION_PRESET_DOGMA;
				}
			}
			STATICTEXT																		{  }
		}

		SEPARATOR	TMOTIONCAM_NMOTION_FOOT								{  }
		REAL			TMOTIONCAM_NMOTION_FOOT_INTENSITY			{ PARENTCOLLAPSE; UNIT PERCENT; MIN 0.0; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }
		SEPARATOR																				{ PARENTCOLLAPSE TMOTIONCAM_NMOTION_FOOT_INTENSITY; }
		VECTOR		TMOTIONCAM_NMOTION_FOOT_SCALE					{ PARENTCOLLAPSE TMOTIONCAM_NMOTION_FOOT_INTENSITY; UNIT REAL; }
		REAL			TMOTIONCAM_NMOTION_FOOT_FREQ					{ PARENTCOLLAPSE TMOTIONCAM_NMOTION_FOOT_INTENSITY; UNIT REAL; }

		SEPARATOR	TMOTIONCAM_NMOTION_HEAD								{  }
		REAL			TMOTIONCAM_NMOTION_HEAD_ROT_INTENSITY	{ PARENTCOLLAPSE; UNIT PERCENT; MIN 0.0; MINSLIDER 0.0; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }
		SEPARATOR																				{ PARENTCOLLAPSE TMOTIONCAM_NMOTION_HEAD_ROT_INTENSITY; }
		VECTOR		TMOTIONCAM_NMOTION_HEAD_ROT_MAX				{ PARENTCOLLAPSE TMOTIONCAM_NMOTION_HEAD_ROT_INTENSITY; UNIT DEGREE; STEP 0.1; }
		VECTOR		TMOTIONCAM_NMOTION_HEAD_ROT_FREQ			{ PARENTCOLLAPSE TMOTIONCAM_NMOTION_HEAD_ROT_INTENSITY; UNIT REAL; }
		REAL			TMOTIONCAM_NMOTION_HEAD_ROT_OCT				{ PARENTCOLLAPSE TMOTIONCAM_NMOTION_HEAD_ROT_INTENSITY; UNIT REAL; MIN 0.0; MINSLIDER 0.0; MAXSLIDER 10.0; STEP 0.1; CUSTOMGUI REALSLIDER; }
		REAL			TMOTIONCAM_NMOTION_HEAD_ROT_DESYNC		{ PARENTCOLLAPSE TMOTIONCAM_NMOTION_HEAD_ROT_INTENSITY; UNIT REAL; MIN 0.0; MINSLIDER 0.0; MAXSLIDER 10.0; STEP 0.1; CUSTOMGUI REALSLIDER; }
		VECTOR		TMOTIONCAM_NMOTION_HEAD_ROT_OFFSET		{ PARENTCOLLAPSE TMOTIONCAM_NMOTION_HEAD_ROT_INTENSITY; UNIT METER; STEP 0.1; }

		SEPARATOR	TMOTIONCAM_NMOTION_CAM_ROT						{  }
		REAL			TMOTIONCAM_NMOTION_CAM_ROT_INTENSITY	{ PARENTCOLLAPSE; UNIT PERCENT; MIN 0.0; MINSLIDER 0.0; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }
		SEPARATOR																				{ PARENTCOLLAPSE TMOTIONCAM_NMOTION_CAM_ROT_INTENSITY; }
		VECTOR		TMOTIONCAM_NMOTION_CAM_ROT_MAX				{ PARENTCOLLAPSE TMOTIONCAM_NMOTION_CAM_ROT_INTENSITY; UNIT DEGREE; STEP 0.1; }
		VECTOR		TMOTIONCAM_NMOTION_CAM_ROT_FREQ				{ PARENTCOLLAPSE TMOTIONCAM_NMOTION_CAM_ROT_INTENSITY; UNIT REAL; }
		REAL			TMOTIONCAM_NMOTION_CAM_ROT_OCT				{ PARENTCOLLAPSE TMOTIONCAM_NMOTION_CAM_ROT_INTENSITY; UNIT REAL; MIN 0.0; MINSLIDER 0.0; MAXSLIDER 10.0; STEP 0.1; CUSTOMGUI REALSLIDER; }
		REAL			TMOTIONCAM_NMOTION_CAM_ROT_DESYNC			{ PARENTCOLLAPSE TMOTIONCAM_NMOTION_CAM_ROT_INTENSITY; UNIT REAL; MIN 0.0; MINSLIDER 0.0; MAXSLIDER 10.0; STEP 0.1; CUSTOMGUI REALSLIDER; }
		VECTOR		TMOTIONCAM_NMOTION_CAM_ROT_OFFSET			{ PARENTCOLLAPSE TMOTIONCAM_NMOTION_CAM_ROT_INTENSITY; UNIT METER; STEP 0.1; }

		SEPARATOR	TMOTIONCAM_NMOTION_CAM_POS						{  }
		REAL			TMOTIONCAM_NMOTION_CAM_POS_INTENSITY	{ PARENTCOLLAPSE; UNIT PERCENT; MIN 0.0; MINSLIDER 0.0; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }
		SEPARATOR																				{ PARENTCOLLAPSE TMOTIONCAM_NMOTION_CAM_POS_INTENSITY; }
		VECTOR		TMOTIONCAM_NMOTION_CAM_POS_MAX				{ PARENTCOLLAPSE TMOTIONCAM_NMOTION_CAM_POS_INTENSITY; UNIT METER; STEP 0.1; }
		VECTOR		TMOTIONCAM_NMOTION_CAM_POS_FREQ				{ PARENTCOLLAPSE TMOTIONCAM_NMOTION_CAM_POS_INTENSITY; UNIT REAL; }
		REAL			TMOTIONCAM_NMOTION_CAM_POS_OCT				{ PARENTCOLLAPSE TMOTIONCAM_NMOTION_CAM_POS_INTENSITY; UNIT REAL; MIN 0.0; MINSLIDER 0.0; MAXSLIDER 10.0; STEP 0.1; CUSTOMGUI REALSLIDER; }
		REAL			TMOTIONCAM_NMOTION_CAM_POS_DESYNC			{ PARENTCOLLAPSE TMOTIONCAM_NMOTION_CAM_POS_INTENSITY; UNIT REAL; MIN 0.0; MINSLIDER 0.0; MAXSLIDER 10.0; STEP 0.1; CUSTOMGUI REALSLIDER; }
		VECTOR		TMOTIONCAM_NMOTION_CAM_POS_OFFSET			{ PARENTCOLLAPSE TMOTIONCAM_NMOTION_CAM_POS_INTENSITY; UNIT METER; STEP 0.1; }
	}

	GROUP	TMOTIONCAM_FOCUS
	{
		BOOL			TMOTIONCAM_FOCUS_ENABLED							{  }

		REAL			TMOTIONCAM_FOCUS_FOCALLENGTH					{ MIN 1; MAX 10000; }
		REAL			TMOTIONCAM_FOCUS_APERTURE							{ MIN 1.0; MAX 2000.0; STEP 0.1; }

		SEPARATOR	TMOTIONCAM_FOCUS_DISTANCE							{  }
		BOOL			TMOTIONCAM_FOCUS_AUTO_ENABLED					{  }
		REAL			TMOTIONCAM_FOCUS_DISTANCE_DIST				{ UNIT METER; MIN 0.0; }
		REAL			TMOTIONCAM_FOCUS_DISTANCE_OFFSET			{ UNIT METER; }

		SEPARATOR	TMOTIONCAM_FOCUS_VERTIGO							{  }
		REAL			TMOTIONCAM_FOCUS_VERTIGO_INTENSITY		{ UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; }

		SEPARATOR	TMOTIONCAM_FOCUS_DEPTH								{  }
		GROUP
		{
			COLUMNS 2;

			BOOL			TMOTIONCAM_FOCUS_DEPTH_ENABLED			{  }
			STATICTEXT																		{  }
			LONG			TMOTIONCAM_FOCUS_DEPTH_MODE
			{
				CYCLE
				{
					TMOTIONCAM_FOCUS_DEPTH_MODE_STANDARD;
					TMOTIONCAM_FOCUS_DEPTH_MODE_FORPOST;
				}
			}
			STATICTEXT																		{  }
			REAL			TMOTIONCAM_FOCUS_DEPTH_AREA					{ UNIT METER; MIN 0.0; }
			STATICTEXT																		{  }
			REAL			TMOTIONCAM_FOCUS_DEPTH_SOFT					{ UNIT PERCENT; MIN 0.0; MAX 100.0; }
			STATICTEXT																		{  }
		}

	}
	
}