CONTAINER reeper{
	NAME reeper;	
	INCLUDE Obase;
		
	GROUP REEPER_GROUP_GEN
	{	
		DEFAULT 1;
		GROUP
		{
		COLUMNS 2;
		LONG REEPER_COILS	   			{ MIN 1; STEP 1;}		
		REAL REEPER_RAD  				{ UNIT METER; MIN 0.0; }	
			
		LONG REEPER_STRANDS	 			{ MIN 1; MAX 160; STEP 1;}
		REAL REEPER_DIS					{ UNIT METER; MIN 0.0; }	
		}		
		SEPARATOR 						{ LINE;  }	
		GROUP
		{
		LONG REEPER_MODE				{CYCLE	{REEPER_MODE_ROPE;	REEPER_MODE_BRAID; REEPER_MODE_LISSAJOUS_3; REEPER_MODE_LISSAJOUS_5;} }	
		}
		SEPARATOR 						{ LINE;  }	
		SEPARATOR 						{}
		GROUP
		{	
		STATICTEXT REEPER_MESSAGE_TEXT	{ ANIM OFF; }	
		}
	}
	
	GROUP REEPER_GROUP_OPT	
	{			
	
		GROUP
		{
			REAL REEPER_ROTA				{ UNIT DEGREE; }
			REAL REEPER_OFFSET				{ UNIT PERCENT; MIN 0.0; MAX 100.0; MINSLIDER 0.0; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }
			REAL REEPER_FROM				{ UNIT PERCENT; MIN 0.0; MAX 100.0; MINSLIDER 0.0; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }
			REAL REEPER_TO					{ UNIT PERCENT; MIN 0.0; MAX 100.0; MINSLIDER 0.0; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }
			SEPARATOR 						{ LINE;  }	
			SPLINE REEPER_FORM				{
											SHOWGRID_H;
											SHOWGRID_V;

											GRIDSIZE_H 8;
											GRIDSIZE_V 8;

											HAS_PRESET_BTN;

											MINSIZE_H 120;
											MINSIZE_V 90;

											EDIT_H;
											EDIT_V;

											LABELS_H;
											LABELS_V;

											HAS_ROUND_SLIDER;

											X_MIN 0;
											X_MAX 1;

											Y_MIN 0;
											Y_MAX 1;

											X_STEPS 0.01;
											Y_STEPS 0.01;						
											}
		}			
		SEPARATOR 							{ LINE;  }	
		GROUP
		{
			BOOL REEPER_MULTISHADE_MODE		{}
		}
	}		
		
	GROUP REEPER_GROUP_SWEEP
	{
		GROUP
		{
			LONG REEPER_SWEEPOBJECT_ISOPARM { MIN 2; MAX 10000; }
			REAL REEPER_SWEEPOBJECT_SCALE  { UNIT PERCENT; MIN 0.0; }
			REAL REEPER_SWEEPOBJECT_ROTATE { UNIT DEGREE; }
			REAL REEPER_SWEEPOBJECT_STARTGROWTH { UNIT PERCENT; MIN 0.0; MAX 100.0; }
			REAL REEPER_SWEEPOBJECT_GROWTH { UNIT PERCENT; MIN 0.0; MAX 100.0; }
		}
		GROUP
		{
			COLUMNS 2;
			BOOL REEPER_SWEEPOBJECT_PARALLEL {}
			BOOL REEPER_SWEEPOBJECT_CONSTANT {}
			BOOL REEPER_SWEEPOBJECT_BANKING {}
			BOOL REEPER_SWEEPOBJECT_KEEPSEGMENTS {}			
		}
	}
	
	GROUP REEPER_GROUP_CAPSANDROUNDING
	{
		GROUP
		{
			LAYOUTGROUP;
			COLUMNS 2;

			GROUP
			{
				LONG REEPER_CAP_START
				{
					CYCLE
					{
						REEPER_CAPTYPE_NOCAP;
						REEPER_CAPTYPE_CAP;
						REEPER_CAPTYPE_ROUNDING;
						REEPER_CAPTYPE_ROUNDINGANDCAP;
					}
				}
				LONG REEPER_CAP_STARTSTEPS  { PARENTID REEPER_CAP_START; MIN 1; MAX 100; }
				REAL REEPER_CAP_STARTRADIUS { PARENTID REEPER_CAP_START; UNIT METER; MIN 0.0; }
			}

			GROUP
			{
				LONG REEPER_CAP_END
				{
					CYCLE
					{
						REEPER_CAPTYPE_NOCAP;
						REEPER_CAPTYPE_CAP;
						REEPER_CAPTYPE_ROUNDING;
						REEPER_CAPTYPE_ROUNDINGANDCAP;
					}
				}
				LONG REEPER_CAP_ENDSTEPS   { PARENTID REEPER_CAP_END; MIN 1; MAX 100; }
				REAL REEPER_CAP_ENDRADIUS  { PARENTID REEPER_CAP_END; UNIT METER; MIN 0.0; }
			}
		}

		SEPARATOR {}

		LONG REEPER_CAP_ROUNDING
		{
			CYCLE
			{
				REEPER_CAP_ROUNDING_LINEAR;
				REEPER_CAP_ROUNDING_CONVEX;
				REEPER_CAP_ROUNDING_CONCAVE;
				REEPER_CAP_ROUNDING_HALFCIRCLE;
				REEPER_CAP_ROUNDING_STEP;
				REEPER_CAP_ROUNDING_2STEPS;
				REEPER_CAP_ROUNDING_ENGRAVED;
			}
		}
		REAL REEPER_CAP_PHONG { UNIT DEGREE; MIN 0.0; MAX 180.0; }

		SEPARATOR {}

		BOOL REEPER_CAP_HULLINWARD	{}
		BOOL REEPER_CAP_HOLEINWARD	{}
		BOOL REEPER_CAP_CONSTRAIN	{}
		BOOL REEPER_CAP_CONNECT		{}
		BOOL REEPER_CAP_UVWROUDING	{}

		SEPARATOR { }

		LONG REEPER_CAP_TYPE
		{ 
			CYCLE
			{
				REEPER_CAP_TYPE_TRI;
				REEPER_CAP_TYPE_QUAD;
				REEPER_CAP_TYPE_NGON;
			}			
		}

		BOOL REEPER_CAP_REGULAR    {}
		REAL REEPER_CAP_REGULARWIDTH { PARENTID REEPER_CAP_REGULAR; UNIT METER; MIN 0.01; }
	}
		
	GROUP REEPER_GROUP_INT	
	{					
		STATICTEXT REEPER_PATH_TEXT		{ ANIM OFF; }		

		LONG REEPER_INTERPOLATION
		{
			CYCLE
			{
				REEPER_INTERPOLATION_NONE;
				REEPER_INTERPOLATION_NATURAL;
				REEPER_INTERPOLATION_UNIFORM;
				REEPER_INTERPOLATION_ADAPTIVE;
				REEPER_INTERPOLATION_SUBDIV;
			}
		}

		LONG REEPER_SUB					{ MIN 0; MAX 5000; }
		REAL REEPER_ANGLE				{ UNIT DEGREE; MIN 0.0; MAX 90.0; }
		REAL REEPER_MAXIMUMLENGTH		{ UNIT METER; MIN 0.01; }
		
		SEPARATOR						{ LINE; }
		
		STATICTEXT REEPER_RAD_TEXT		{ ANIM OFF; }
		LONG REEPER_NSIDES				{ MIN 2; MAX 512; STEP 1;}
	}			
}
REEPER_RAD_TEXT
}