// C4D-DialogResource

DIALOG DLG_PREVIEW
{
	SCALE_H;
	SCALE_V;

  TAB GADGET_PREVIEW_TAB
  {
    SCALE_H; 
    SCALE_V;
    SELECTION_TABS; 
    
    GROUP GADGET_TAB_PREVIEW_GROUP
    {
      NAME STR_TAB_PREVIEW_GROUP;
      SCALE_H; 
      SCALE_V;
      BORDERSIZE 0, 0, 0, 0; 
      COLUMNS 1;
      SPACE 4, 4;
      
			GROUP GADGET_PREVIEW_PREVIEWGROUP
			{
				SCALE_H;
				SCALE_V;
				COLUMNS	1;
			}
			GROUP GADGET_TAB_PREVIEW_INSERT_GROUP
			{
				FIT_H;FIT_V; 
				COLUMNS	1;
			}
    }
    GROUP GADGET_TAB_INFO_GROUP
    {
      NAME STR_TAB_INFO_GROUP;
      BORDERSIZE 0, 0, 0, 0; 
      SCALE_H;
      SCALE_V;

			SCROLLGROUP GADGET_TAB_INFO_SCROLLER
			{
				SCALE_H;SCALE_V; 
				SCROLL_AUTO_H;
				SCROLL_AUTO_V;

				GROUP GADGET_TAB_INFO_SCROLL_GROUP
				{
					SCALE_H;SCALE_V; 
					COLUMNS	1;

					GROUP GADGET_TAB_INFO_TEXT_GROUP
					{
						SCALE_H;
			      COLUMNS 2;
			      SPACE 4, 4;

			      STATICTEXT GADGET_INFO_NODE_NAME_STR { NAME STR_INFO_NODE_NAME; ALIGN_RIGHT;  }
			      STATICTEXT GADGET_INFO_NODE_NAME { ALIGN_LEFT; SCALE_H; SIZE 5, 0; }

			      STATICTEXT GADGET_INFO_NODE_TYPE_STR { NAME STR_INFO_NODE_TYPE; ALIGN_RIGHT; }
			      STATICTEXT GADGET_INFO_NODE_TYPE { ALIGN_LEFT; SCALE_H; SIZE 5, 0; }

			      STATICTEXT GADGET_INFO_NODE_SIZE_STR { NAME STR_INFO_NODE_SIZE; ALIGN_RIGHT;  }
			      STATICTEXT GADGET_INFO_NODE_SIZE { ALIGN_LEFT; SCALE_H; SIZE 5, 0; }

			      STATICTEXT GADGET_INFO_NODE_CREATED_STR { NAME STR_INFO_NODE_CREATED; ALIGN_RIGHT;  }
			      STATICTEXT GADGET_INFO_NODE_CREATED { ALIGN_LEFT; SCALE_H; SIZE 5, 0; }

			      STATICTEXT GADGET_INFO_NODE_MODIFIED_STR { NAME STR_INFO_NODE_MODIFIED; ALIGN_RIGHT;  }
			      STATICTEXT GADGET_INFO_NODE_MODIFIED { ALIGN_LEFT; SCALE_H; SIZE 5, 0; }
					}

  			  MULTILINEEDIT GADGET_PREVIEW_ANNOTATION { SCALE_V; SCALE_H; SIZE -70, 0; WORDWRAP; }

					GROUP GADGET_TAB_INFO_INSERT_GROUP
					{
						FIT_H;FIT_V; 
						COLUMNS	1;
					}
				}
			}
    }
  }
}