// C4D-DialogResource

DIALOG DLG_CONTENTVIEW
{
	SCALE_H; SCALE_V;

	GROUP	GAGGET_CONTENTVIEW_BASE_GROUP
	{
		COLUMNS	1;
		SCALE_H; SCALE_V;

		GROUP	
		{
			COLUMNS	1;
			SCALE_H; SCALE_V;
			BORDERSTYLE BORDER_GROUP_IN;

			SCROLLGROUP GADGET_SCROLLVIEW
			{
				SCALE_H;SCALE_V; 
				SCROLL_AUTO_H;
				SCROLL_AUTO_V;

					
				GROUP	GADGET_SCROLLCONTENT
				{
					SCALE_H;SCALE_V; 
					
					COLUMNS	1;
				}
			}

			SEPARATOR GADGET_BOTTOM_SEPARATOR { SCALE_H; }

	    GROUP GADGET_BOTTOM_BAR_GROUP
	    {
	    	BORDERSIZE 0, 0, 0, 4;
	    	SCALE_H;
	      
	      GROUP GADGET_ACTIVITY_GROUP
	      {
	      	SIZE -32, -16;
		      BITMAPBUTTON GADGET_SCAN_ACTIVITY { TOGGLE; ALIGN_TOP; ALIGN_LEFT; SIZE -32, -16; }
		    }

				GROUP	GADGET_BOTTOM_SLIDER_GROUP
				{
					SCALE_H;
					COLUMNS	3;

					BITMAPBUTTON	GADGET_SMALLSIZE { }
					SLIDER GADGET_SIZESLIDER { SIZE 150,0; }
					BITMAPBUTTON	GADGET_BIGSIZE { }
				}
			}
		}

	}
}
