// C4D-DialogResource

DIALOG DLG_COPYMOVE
{
//  NAME TITLE_STR_NEW_CATALOG;
	SCALE_H; SCALE_V;
  
	GROUP
	{
		COLUMNS 1; 
		BORDERSIZE 8,8,8,8;
		SCALE_H;
		SCALE_V;
		
		STATICTEXT GADGET_COPYMOVE_TOTAL_TEXT {  ALIGN_LEFT; SCALE_H;  SIZE -300, 0; }
		STATICTEXT GADGET_COPYMOVE_CURRENT_TEXT { ALIGN_LEFT; SCALE_H; SIZE -300, 0; }

  	BUTTON GADGET_COPYMOVE_STOP { NAME STR_STOP; ALIGN_RIGHT; }
  }
}
