// C4D-DialogResource

DIALOG DLG_SET_DEFAULT_VIEW
{
  NAME TITLE_SET_DEFAULT_VIEW;
	SCALE_H; SCALE_V;

	GROUP
	{
		SCALE_H;
		SCALE_V;
		BORDERSIZE 8,8,8,8;
		COLUMNS	1;
  
  	CHECKBOX GAGDET_RECURSIVE_DEFAULT_VIEW { NAME STR_RECURSIVE_DEFAULT_VIEW; ALIGN_TOP; ALIGN_LEFT; SIZE -300, 10; }
	}
	
	DLGGROUP { OK; CANCEL; }
}
