// C4D-DialogResource
DIALOG DLG_VIEW_DEFAULTS
{
  NAME STR_VIEW_DEFAULTS; CENTER_V; CENTER_H; 
  
  TAB GADGET_VIEW_DEFAULTS_TAB
  {
    SCALE_H; 
    SCALE_V;
    SELECTION_TABS; 
	 
	  GROUP	GADGET_TAB_NORMAL_MODE_GROUP
	  {
			SIZE	-256, -128;
      NAME STR_TAB_NORMAL_MODE_GROUP;
	    ALIGN_TOP; ALIGN_LEFT; 
	    BORDERSTYLE BORDER_NONE; BORDERSIZE 4, 4, 4, 4; 
	    COLUMNS 1;
	    
	    GROUP
	    {
	      ALIGN_TOP; ALIGN_LEFT; 
	      BORDERSIZE 0, 0, 0, 0; 
	      COLUMNS 2;

	      STATICTEXT { NAME STR_VIEW_MODE; CENTER_V; ALIGN_LEFT; }
				GROUP
				{
					SCALE_H;
					COMBOBOX GADGET_DEFAULT_VIEW_MODE
					{
						CHILDS
						{
							GADGET_DEFAULT_VIEW_ICON, STR_VIEW_ICON;
							GADGET_DEFAULT_VIEW_LIST, STR_VIEW_LIST;
						}
					}
				}

	      STATICTEXT { NAME STR_SORT_MODE; CENTER_V; ALIGN_LEFT; }
				GROUP
				{
					SCALE_H;
					COMBOBOX GADGET_DEFAULT_SORT_MODE
					{
						CHILDS
						{
							GADGET_DEFAULT_SORTBY_NAME, STR_SORTBY_NAME;
							GADGET_DEFAULT_SORTBY_MDATE, STR_SORTBY_MDATE;
							GADGET_DEFAULT_SORTBY_CDATE, STR_SORTBY_CDATE;
							GADGET_DEFAULT_SORTBY_SIZE, STR_SORTBY_SIZE;
							GADGET_DEFAULT_SORTBY_KIND, STR_SORTBY_KIND;
						}
					}
				}

	      STATICTEXT { NAME STR_ICON_SIZE; CENTER_V; ALIGN_LEFT; }
				GROUP	GADGET_DEFAULT_ICON_SIZE_GROUP
				{
					SCALE_H;
		      EDITSLIDER GADGET_DEFAULT_ICON_SIZE { CENTER_V; SCALE_H; SIZE 70, 0; }
				}
	    }
	  }
	  GROUP	GADGET_TAB_SIMPLIFIED_MODE_GROUP
	  {
			SIZE	-256, -128;
      NAME STR_TAB_SIMPLIFIED_MODE_GROUP;
	    ALIGN_TOP; ALIGN_LEFT; 
	    BORDERSTYLE BORDER_NONE; BORDERSIZE 4, 4, 4, 4; 
	    COLUMNS 1;
	    
	    GROUP
	    {
	      ALIGN_TOP; ALIGN_LEFT; 
	      BORDERSIZE 0, 0, 0, 0; 
	      COLUMNS 2;

	      STATICTEXT { NAME STR_VIEW_MODE; CENTER_V; ALIGN_LEFT; }
				GROUP
				{
					SCALE_H;
					COMBOBOX GADGET_DEFAULT_SIMPLIFIED_VIEW_MODE
					{
						CHILDS
						{
							GADGET_DEFAULT_SIMPLIFIED_VIEW_ICON, STR_VIEW_ICON;
							GADGET_DEFAULT_SIMPLIFIED_VIEW_LIST, STR_VIEW_LIST;
						}
					}
				}

	      STATICTEXT { NAME STR_SORT_MODE; CENTER_V; ALIGN_LEFT; }
				GROUP
				{
					SCALE_H;
					COMBOBOX GADGET_DEFAULT_SIMPLIFIED_SORT_MODE
					{
						CHILDS
						{
							GADGET_DEFAULT_SIMPLIFIED_SORTBY_NAME, STR_SORTBY_NAME;
							GADGET_DEFAULT_SIMPLIFIED_SORTBY_MDATE, STR_SORTBY_MDATE;
							GADGET_DEFAULT_SIMPLIFIED_SORTBY_CDATE, STR_SORTBY_CDATE;
							GADGET_DEFAULT_SIMPLIFIED_SORTBY_SIZE, STR_SORTBY_SIZE;
							GADGET_DEFAULT_SIMPLIFIED_SORTBY_KIND, STR_SORTBY_KIND;
						}
					}
				}

	      STATICTEXT { NAME STR_ICON_SIZE; CENTER_V; ALIGN_LEFT; }
				GROUP	GADGET_DEFAULT_SIMPLIFIED_ICON_SIZE_GROUP
				{
					SCALE_H;
		      EDITSLIDER GADGET_DEFAULT_SIMPLIFIED_ICON_SIZE { CENTER_V; SCALE_H; SIZE 70, 0; }
				}
	    }
	  }
	}
  DLGGROUP { OK; CANCEL; }
}