// C4D-DialogResource

DIALOG IDD_SCULPT_DISPLACEMENT_BAKE_DIALOG
{
	CENTER_V; SCALE_H; 
  
	GROUP 
	{
		NAME IDS_EXTRACTION_OPTIONS;
		SCALE_H; SCALE_V;
		BORDERSIZE 4, 4, 4, 4; 
		COLUMNS 1;
		
		STATICTEXT { NAME IDS_EXTRACTION_TYPE; }
		STATICTEXT { NAME IDS_EXTRACTION_DEFINITION; }
		
		GROUP 
		{
			NAME IDS_EXTRACTION_OPTIONS;
			SCALE_H; 
			BORDERSIZE 4, 4, 4, 4; 
			BORDERSTYLE BORDER_GROUP_IN;
			COLUMNS 1;
			
			GROUP 
			{
				NAME IDS_TARGET_MODELS;
				SCALE_H; SCALE_V;
				BORDERSIZE 4, 4, 4, 4; 
				BORDERSTYLE BORDER_GROUP_IN;
				COLUMNS 1;
				
				GROUP 
				{
					SCALE_H; SCALE_V;
					COLUMNS 2;
					LISTVIEW IDC_DISPLACEMENT_TARGETMODELS { SCALE_H; SCALE_V; };
					GROUP 
					{
						COLUMNS 1;
						FIT_H; SCALE_V; 
						BUTTON IDC_DISPLACEMENT_TARGETMODELS_ADDALL { NAME IDS_ADDALL; }
						BUTTON IDC_DISPLACEMENT_TARGETMODELS_ADDSELECTED { NAME IDS_ADDSELECTED; }
						BUTTON IDC_DISPLACEMENT_TARGETMODELS_REMOVE { NAME IDS_REMOVE; }
					}
				}
				
				COMBOBOX IDC_DISPLACEMENT_TARGETMODELS_TYPE
				{
					SCALE_H; FIT_V;
					CHILDS
					{
						IDC_DISPLACEMENT_TARGETMODELS_TYPE_ONE_MAP_ALL_TARGETS, IDS_ONE_MAP_ALL_TARGETS;
					}
				}
				
				CHECKBOX IDC_DISPLACEMENT_TARGETMODELS_SMOOTH { NAME IDS_SMOOTH_TARGETMODELS; SCALE_H; }	
				CHECKBOX IDC_DISPLACEMENT_TARGETMODELS_SMOOTH_UVS { NAME IDS_SMOOTH_TARGETUVS; SCALE_H; }	
			}
			
			GROUP 
			{
				NAME IDS_SOURCE_MODELS;
				SCALE_H; SCALE_V;
				BORDERSIZE 4, 4, 4, 4; 
				BORDERSTYLE BORDER_GROUP_IN;
				COLUMNS 1;
				
				GROUP 
				{
					COLUMNS 2;
					SCALE_H; SCALE_V;
					LISTVIEW IDC_DISPLACEMENT_SOURCEMODELS { SCALE_H; SCALE_V; };
					GROUP 
					{
						COLUMNS 1;
						FIT_H; SCALE_V; 
						BUTTON IDC_DISPLACEMENT_SOURCEMODELS_ADDALL { NAME IDS_ADDALL; }
						BUTTON IDC_DISPLACEMENT_SOURCEMODELS_ADDSELECTED { NAME IDS_ADDSELECTED; }
						BUTTON IDC_DISPLACEMENT_SOURCEMODELS_REMOVE { NAME IDS_REMOVE; }
					}
				}
								
				CHECKBOX IDC_DISPLACEMENT_SOURCEMODELS_SMOOTH { NAME IDS_SMOOTH_SOURCEMODELS; SCALE_H; }	
			}
			
			SEPARATOR { SCALE_H; }
	
//			GROUP 
//			{
//				SCALE_H; SCALE_V;
//				BORDERSIZE 4, 4, 4, 4; 
//				COLUMNS 2;
//				
//				STATICTEXT { NAME IDS_METHOD; }
//				COMBOBOX IDC_DISPLACEMENT_METHOD
//				{
//					SCALE_H; FIT_V;
//					CHILDS
//					{
//						IDC_DISPLACEMENT_METHOD_RAYCASTING, IDS_METHOD_RAYCASTING;
//					}
//				}
//				
//				STATICTEXT { NAME IDS_CHOOSE_SAMPLES; }
//				COMBOBOX IDC_DISPLACEMENT_SAMPLES
//				{
//					SCALE_H; FIT_V;
//					CHILDS
//					{
//						IDC_DISPLACEMENT_SAMPLES_FURTHESTOUTSIDE, IDS_CHOOSE_SAMPLES_FURTHESTOUTSIDE;
//					}
//				}
//												
//				STATICTEXT { NAME IDS_CHOOSE_SAMPLES; }
//				GROUP
//				{
//					SCALE_H; SCALE_V;
//					COLUMNS 2;					
//					EDITNUMBER IDC_DISPLACEMENT_SEARCH_DISTANCE { }
//					BUTTON IDC_DISPLACEMENT_SEARCH_DISTANCE_BESTGUESS { }
//				}
//				
//				STATICTEXT { NAME IDS_TEST_BOTH_SIDES; }
//				CHECKBOX IDC_DISPLACEMENT_TEST_BOTH_SIDES { }	
//			}			
//			
//			SEPARATOR { SCALE_H; }
	
			GROUP 
			{
				NAME IDS_OUTPUT_OPTIONS;
				SCALE_H; SCALE_V;
				BORDERSIZE 4, 4, 4, 4; 
				COLUMNS 1;
				
				STATICTEXT  { NAME IDS_BASE_FILE_NAME; }
				EDITTEXT  IDC_DISPLACEMENT_BASEFILENAME
				{
					ALIGN_TOP; SCALE_H; 
				}
			}
		}
	}
}

