// C4D-DialogResource
DIALOG IDD_SCULPT_REPROJECT
{
  NAME IDS_DIALOG;  SCALE_H; SCALE_V;

  DESCRIPTION IDS_SCULPT_REPROJECT_SOURCEDEST
  {
	SCALE_H; 
	SCALE_V; 
	FIT_H;
	FIT_V;
	 
    NOUNDO;
    OBJECTSNOTINDOC;
	ALLOWFOLDING; 
  }
}