// C4D-DialogResource
DIALOG IDD_SCULPT_BAKE_DIALOG
{
  NAME IDS_SCULPT_BAKE_DIALOG;  
  SCALE_H; SCALE_V;
  
  GROUP IDC_STATIC
    {
	  ALIGN_TOP;
      SCALE_H; SCALE_V;
      FIT_V;
      BORDERSIZE 0, 0, 0, 0; 
      COLUMNS 2;
      SPACE 4, 4;
      
      STATICTEXT IDC_STATIC { NAME IDS_BAKE_OBJECT_FILENAME_EDIT; CENTER_V; ALIGN_LEFT; }
      FILENAME IDC_BAKE_OUTPUTDIR
      {
        ALIGN_TOP; SCALE_H; 
        DIRECTORY;
      }
    }
    
	GROUP
	 {     
		BORDERSIZE 4,4,4,4;
		BORDERSTYLE BORDER_GROUP_IN;

		COLUMNS 3;     
		SCALE_H; SCALE_V;		  
		ALIGN_TOP;
		FIT_V;
		LISTVIEW IDC_BAKE_OBJECT_MAPSTOCREATELIST { SCALE_H; SCALE_V; SIZE 150,100; };
	  }       

	GROUP IDC_BAKE_TEXTURE_OPTIONS_GROUP { }       
    
   DLGGROUP { OK; CANCEL; }
}