// C4D-DialogResource
DIALOG IDD_SCULPTLAYERS
{
  NAME IDS_DIALOG; SCALE_V; SCALE_H; 
    
  GROUP IDC_STATIC
  {
    NAME IDS_STATIC1; ALIGN_TOP; SCALE_H; 
    BORDERSIZE 4, 0, 4, 0; 
    ROWS 1;
    SPACE 4, 4;
    
    STATICTEXT { NAME IDS_CURRENTLEVEL; CENTER_V; ALIGN_LEFT; }
    STATICTEXT IDC_CURRENTLEVEL { SIZE 30,0; SCALE_H; }

    STATICTEXT { NAME IDS_POLYCOUNT; CENTER_V; ALIGN_LEFT; }
    STATICTEXT IDC_POLYCOUNT { SIZE 100,0; SCALE_H; }

    STATICTEXT { NAME IDS_MEMORY_USAGE; CENTER_V; ALIGN_LEFT; }
    STATICTEXT IDC_MEMORY_USAGE { SIZE 50,0; SCALE_H; }
  }

  SEPARATOR  { SCALE_H; }
 
  GROUP
  {
     BORDERSIZE 4, 0, 4, 0; 
	 SCALE_H; 
	 ROWS 1;
	 CHECKBOX IDC_LAYER_BROWSER_INCLUDETOPLEVELS  { NAME IDS_LAYER_BROWSER_INCLUDETOPLEVELS; SCALE_H; }
	 CHECKBOX IDC_LAYER_BROWSER_PHONG  { NAME IDS_LAYER_BROWSER_PHONG; SCALE_H; }
  }

  GROUP
  {
     BORDERSIZE 4, 0, 4, 0; 
	 SCALE_H; 
	 COLUMNS  2;
     STATICTEXT { NAME IDS_LAYER_BROWSER_LEVELSLIDER; ALIGN_LEFT; }
	 EDITSLIDER  IDC_LAYER_BROWSER_LEVELSLIDER { SCALE_H; }
  }

  SEPARATOR  { SCALE_H; }
 
  DESCRIPTION IDC_LAYER_BROWSER_DESC
  {
	SCALE_H; 
	FIT_H;
	FIT_V; 
    
    //SHOWTITLE;
    //NOUNDO;
    //OBJECTSNOTINDOC;
    MODALMODE;
	ALLOWFOLDING; 
}

  SEPARATOR  { SCALE_H; }

  GROUP
  {
     BORDERSIZE 4, 0, 4, 0; 
	 SCALE_H; 
	 COLUMNS  2;
	 STATICTEXT { NAME IDS_LAYER_BROWSER_MODE; CENTER_V; ALIGN_LEFT; }

	RADIOGROUP IDC_LAYER_BROWSER_MODE
	{
		GROUP
		{
			COLUMNS 2;
			RADIOGADGET IDC_LAYER_BROWSER_MODE_SCULPT { NAME IDS_LAYER_BROWSER_MODE_SCULPT; }
			RADIOGADGET IDC_LAYER_BROWSER_MODE_ANIMATE { NAME IDS_LAYER_BROWSER_MODE_ANIMATE; }  
		}
	}
  }

  SEPARATOR  { SCALE_H; }
 
	 GROUP IDC_LAYER_BROWSER_MODE_GROUP_SCULPT
	 {
		NAME IDS_STATIC2; SCALE_V; SCALE_H; 
		BORDERSIZE 4, 0, 4, 0; 
		ROWS 2;
		ALLOW_WEIGHTS; 
		SPACE 4, 4;

		TREEVIEW IDC_LAYER_BROWSER_TREE
		{
			SCALE_V; SCALE_H; 
			BORDER; 
			NO_MULTISELECT; 
			HAS_HEADER;
			MOVE_COLUMN;
			FIXED_LAYOUT;
			NO_BACK_DELETE;
			ALTERNATE_BG;
			RESIZE_HEADER;
			OUTSIDE_DROP;
		}
	}
}