// C4D-DialogResource

DIALOG IDD_SUBDIVIDEOPTIONS_DIALOG
{
  NAME TITLE;

  GROUP
  {
     BORDERSIZE 4, 0, 4, 0; 
	 SCALE_H; 
	 ROWS 1;
     STATICTEXT { NAME IDS_SUBDIVIDEOPTIONS_SMOOTHNESS; ALIGN_LEFT; }
	 EDITSLIDER IDC_SUBDIVIDEOPTIONS_SMOOTHNESS { SCALE_H; }
  }
  DLGGROUP { OK;CANCEL;HELP; }
}
