// C4D-DialogResource
DIALOG IDD_SCULPT_EXTRACT
{
  NAME IDS_DIALOG; SCALE_V; SCALE_H; 

  GROUP IDC_STATIC
  {
    ALIGN_TOP; SCALE_H; SCALE_V;
    BORDERSIZE 4, 4, 4, 4; 
	COLUMNS 2;
    SPACE 4, 4;
    
    STATICTEXT { NAME IDS_SCULPT_EXTRACT_THRESHOLD; CENTER_V; ALIGN_LEFT; }
    EDITSLIDER IDC_SCULPT_EXTRACT_THRESHOLD { SIZE 40,0; SCALE_H; }
    
    STATICTEXT { NAME IDS_SCULPT_EXTRACT_THICKNESS; CENTER_V; ALIGN_LEFT; }
    EDITSLIDER IDC_SCULPT_EXTRACT_THICKNESS { SIZE 40,0; SCALE_H; }

    STATICTEXT { NAME IDS_SCULPT_EXTRACT_THICKNESS_STEPS; CENTER_V; ALIGN_LEFT; }
    EDITSLIDER IDC_SCULPT_EXTRACT_THICKNESS_STEPS { SIZE 40,0; SCALE_H; }
    
	BUTTON IDC_SCULPT_EXTRACT_PREVIEW { NAME IDS_SCULPT_EXTRACT_PREVIEW; }   
    CHECKBOX IDC_SCULPT_EXTRACT_REALTIME_PREVIEW { NAME IDS_SCULPT_EXTRACT_REALTIME_PREVIEW; SCALE_H; }
  
    CHECKBOX IDC_SCULPT_EXTRACT_USEFALLOFF { NAME IDS_SCULPT_EXTRACT_USEFALLOFF; SCALE_H; }
     COMBOBOX IDC_SCULPT_EXTRACT_DIRECTION
	  {
		SCALE_H;
	  
		CHILDS
		{
		  IDC_SCULPT_EXTRACT_DIRECTION_AVERAGE, IDS_SCULPT_EXTRACT_DIRECTION_AVERAGE;
		  IDC_SCULPT_EXTRACT_DIRECTION_VERTEXNORMAL, IDS_SCULPT_EXTRACT_DIRECTION_VERTEXNORMAL;
		}
	  }
	  
    CHECKBOX IDC_SCULPT_EXTRACT_SCULPTTAG { NAME IDS_SCULPT_EXTRACT_SCULPTTAG; SCALE_H; }
	STATICTEXT { NAME IDS_DUMMY; } 
    //CHECKBOX IDC_SCULPT_EXTRACT_CLOSED { NAME IDS_SCULPT_EXTRACT_CLOSED; SCALE_H; }
   
    BUTTON IDC_SCULPT_EXTRACT_OK { NAME IDS_SCULPT_EXTRACT_OK; }
    BUTTON IDC_SCULPT_EXTRACT_CANCEL { NAME IDS_SCULPT_EXTRACT_CANCEL; }
  }
}