CONTAINER	Fokinoimport
{
	INCLUDE	Fbase;
	
	GROUP	FokinoimportGroup
	{
		NAME OKINO_STR_OPTIONS;
			BOOL OKINOCLEAR_TEMP { }
			BOOL OKINO_KEEP_IN_MEM{ }

		GROUP
		{	
			NAME OKINOIMPORT_STR_OPTIONS;
			BOOL OKINOSHOW_SETTINGS { }

			BUTTON OKINOIMPORT_FILTER_LIST { }
			BUTTON OKINOINTERMEDIATE_LWS_OPTIONS { }
		}
		
		GROUP
		{
			NAME OKINOEXPORT_STR_OPTIONS;
			BOOL OKINOSHOW_EXPORT_SETTINGS { }
			BUTTON OKINOINTERMEDIATE_FBX_OPTIONS { }
		}
	}
}
