CONTAINER TP_Group
{
	NAME TP_Group;
	INCLUDE Obaselist;

	HIDE ID_BASELIST_NAME;
	HIDE ID_LAYER_LINK;
	GROUP Obaselist
	{
		DEFAULT 1;
		STRING PGROUP_NAME { ANIM OFF; }
		LONG PGROUP_VIEWTYPE { ANIM OFF; CYCLE { PG_NONE; PG_FLAKES; PG_DOTS; PG_TICKS; PG_DROPS; PG_BOX; PG_GLOBAL; } }
		BOOL PGROUP_USE_COLOR { ANIM OFF; }
		COLOR PGROUP_COLOR { ANIM OFF; }
		BOOL PGROUP_SHOWOBJECT { ANIM OFF; }
	}
}
