CONTAINER Dgradient
{
	NAME Dgradient;

	LONG GRADIENTSUBCHANNEL_INTERPOLATION { CYCLE { GRADIENTSUBCHANNEL_INTERPOLATION_CUBICKNOT; GRADIENTSUBCHANNEL_INTERPOLATION_CUBICBIAS; GRADIENTSUBCHANNEL_INTERPOLATION_SMOOTHKNOT; GRADIENTSUBCHANNEL_INTERPOLATION_LINEARKNOT; GRADIENTSUBCHANNEL_INTERPOLATION_LINEAR; GRADIENTSUBCHANNEL_INTERPOLATION_NONE; GRADIENTSUBCHANNEL_INTERPOLATION_EXP_UP; GRADIENTSUBCHANNEL_INTERPOLATION_EXP_DOWN; } }
}
