CONTAINER Prefsopengl
{
	NAME Prefsopengl;
	SCALE_V;
	
	GROUP PREF_OPENGL_MAIN_GROUP
	{
		DEFAULT 1;
		SCALE_V;

		GROUP
		{		
			COLUMNS 2;

			BOOL PREF_OPENGL_HARDWARE	{ ANIM OFF; }
			STATICTEXT{}

			LONG PREF_OPENGL_TEXTUREMODE
			{
				ANIM OFF;
				CYCLE
				{
					PREF_OPENGL_TEXTUREMODE_NEAREST;
					PREF_OPENGL_TEXTUREMODE_LINEAR;
					PREF_OPENGL_TEXTUREMODE_MIPMAP;
				}
			}
			STATICTEXT{}

			LONG PREF_OPENGL_ANTIALIAS
			{
				ANIM OFF;
				CYCLE
				{
				}
			}
			STATICTEXT {JOINENDSCALE;}	

			LONG PREF_OPENGL_MAXTRANS  { ANIM OFF; MIN 0; MAX 10;}
			STATICTEXT{}
			LONG PREF_OPENGL_MAXLIGHT  { ANIM OFF;  MIN 1; MAX 20;}
			STATICTEXT{}
			LONG PREF_OPENGL_MAXSHAD  { ANIM OFF;  MIN 0; MAX 10;}
			STATICTEXT{}
			BOOL PREF_OPENGL_USE_SHADER_CACHE { ANIM OFF; }
			STATICTEXT{}
            BOOL PREF_OPENGL_VIEWPORT_DITHERING { ANIM OFF; }
			STATICTEXT{}
			BUTTON PREF_OPENGL_SHOWCAP {}
			STATICTEXT{}
		}
		SEPARATOR { LINE; }
		STRING PREF_OPENGL_WARNING { ANIM OFF; CUSTOMGUI MULTISTRING; WORDWRAP; READONLY; SCALE_V; }
	}
}
