CONTAINER Prefsview
{
	NAME Prefsview;

	GROUP PREFS_VIEW_GROUP
	{
		DEFAULT 1;
	
		GROUP
		{	
			LONG PREF_VIEW_REDRAWTIME  { ANIM OFF; MIN 0;}
			BOOL PREF_VIEW_FULLANIMREDRAW	{ ANIM OFF; }
			BOOL PREF_VIEW_REALTIME{ ANIM OFF; }
			
			SEPARATOR {LINE;}
			
			REAL PREF_VIEW_MONITORASPECT  { ANIM OFF; MIN 0.0; STEP 0.01;}
		
			COLORPROFILE PREF_VIEW_COLORPROFILE { DISPLAYMODE; SCALE_H; }
		}
		STATICTEXT PREF_VIEW_WARNING {}
	}
	
}
