CONTAINER Prefsfiles
{
	NAME Prefsfiles;
	GROUP PREF_FILE_MAIN_GROUP
	{
	
		DEFAULT 1;
		COLUMNS 1;
		

		SEPARATOR PREFS_FILE_BASIC {}
		LONG PREF_FILE_RECENT  { ANIM OFF; MIN 0; MAX 100; }			
		LONG PREF_FILE_BACKUP  { ANIM OFF; MIN 0; MAX 1000;}	
		BOOL PREF_FILE_QTIME {ANIM OFF;}
		BOOL PREF_FILE_MELANGE {ANIM OFF;}
		BOOL PREF_FILE_MELANGE_ANIM {ANIM OFF;}
		FILENAME PREF_FILE_HELP {DIRECTORY; ANIM OFF;}
		SEPARATOR PREFS_FILE_AUTOSAVE {}

		GROUP
		{
		
			DEFAULT 1;
			COLUMNS 2;
			
			BOOL PREF_FILE_AUTOEVERY{ ANIM OFF; }
			LONG PREF_FILE_AUTOMIN  { ANIM OFF; MIN 1; MAX 10000;}
			
			BOOL PREF_FILE_AUTOLIMIT	{ ANIM OFF; }
			LONG PREF_FILE_AUTOCOPIES { ANIM OFF; MIN 1; MAX 1000; }
			
		}
		
		GROUP
		{
			DEFAULT 1;
			COLUMNS 2;
			LONG PREF_FILE_AUTOSAVETO { ANIM OFF; CYCLE { PREF_FILE_AUTOSAVE_PRJ; PREF_FILE_AUTOSAVE_USR; PREF_FILE_AUTOSAVE_CST;} }
			FILENAME PREF_FILE_AUTOSAVEDIR { SCALE_H; DIRECTORY; ANIM OFF;}
		}
		
		SEPARATOR ID_FILES_GROUP_XREF{}
		
		GROUP 
		{
			DEFAULT 1;
			COLUMNS 1;	
			BOOL ID_FILES_XREFPREFS_DEFERRED_LOAD { }
			BOOL ID_FILES_XREFPREFS_REDUCED_SAVE { }
		}
		
		SEPARATOR PREFS_TERXPATH_GROUP {}
		FILENAME PREF_TEXPATH_PATH1 {DIRECTORY; ANIM OFF;}
		FILENAME PREF_TEXPATH_PATH2 {DIRECTORY; ANIM OFF;}
		FILENAME PREF_TEXPATH_PATH3 {DIRECTORY; ANIM OFF;}
		FILENAME PREF_TEXPATH_PATH4 {DIRECTORY; ANIM OFF;}
		FILENAME PREF_TEXPATH_PATH5 {DIRECTORY; ANIM OFF;}
		FILENAME PREF_TEXPATH_PATH6 {DIRECTORY; ANIM OFF;}
		FILENAME PREF_TEXPATH_PATH7 {DIRECTORY; ANIM OFF;}
		FILENAME PREF_TEXPATH_PATH8 {DIRECTORY; ANIM OFF;}
		FILENAME PREF_TEXPATH_PATH9 {DIRECTORY; ANIM OFF;}
		FILENAME PREF_TEXPATH_PATH10 {DIRECTORY; ANIM OFF;}
				
	}
}
