CONTAINER Prefstexpath
{
	NAME Prefstexpath;
	GROUP PREF_TEXPATH_MAIN_GROUP
	{
	
		DEFAULT 1;
		COLUMNS 1;
		
		
		FILENAME PREF_TEXPATH_PATH1 {DIRECTORY; ANIM OFF;}
		FILENAME PREF_TEXPATH_PATH2 {DIRECTORY; ANIM OFF;}
		FILENAME PREF_TEXPATH_PATH3 {DIRECTORY; ANIM OFF;}
		FILENAME PREF_TEXPATH_PATH4 {DIRECTORY; ANIM OFF;}
		FILENAME PREF_TEXPATH_PATH5 {DIRECTORY; ANIM OFF;}
		FILENAME PREF_TEXPATH_PATH6 {DIRECTORY; ANIM OFF;}
		FILENAME PREF_TEXPATH_PATH7 {DIRECTORY; ANIM OFF;}
		FILENAME PREF_TEXPATH_PATH8 {DIRECTORY; ANIM OFF;}
		FILENAME PREF_TEXPATH_PATH9 {DIRECTORY; ANIM OFF;}
		FILENAME PREF_TEXPATH_PATH10 {DIRECTORY; ANIM OFF;}
	}
}
