CONTAINER BMgravity
{
	NAME BMgravity;
	INCLUDE BMbase;
  
	GROUP
	{
		COLUMNS 2;
		BOOL MDATA_BRUSHMODIFIERBASE_ENABLED { PARENTCOLLAPSE; }
		REAL MDATA_BRUSHMODIFIERBASE_STRENGTH { MIN 0; MINSLIDER 1; MAXSLIDER 100; CUSTOMGUI REALSLIDER; UNIT PERCENT; SCALE_H;  }	
	}

	GROUP
	{
		VECTOR BM_GRAVITY_DIRECTION  { 	PARENTCOLLAPSE MDATA_BRUSHMODIFIERBASE_ENABLED; }
	}
}
