CONTAINER BMknife
{
  NAME BMknife;
  INCLUDE BMbase;

    GROUP
	{
		COLUMNS 2;
		BOOL MDATA_BRUSHMODIFIERBASE_ENABLED { PARENTCOLLAPSE; }
		REAL MDATA_BRUSHMODIFIERBASE_STRENGTH { MIN 0; MINSLIDER 1; MAXSLIDER 100; CUSTOMGUI REALSLIDER; UNIT PERCENT; SCALE_H;  }				
	}
	
	GROUP
	{
		BOOL BM_KNIFE_INVERT { PARENTCOLLAPSE MDATA_BRUSHMODIFIERBASE_ENABLED; } 
		REAL BM_KNIFE_PINCH { MIN 0; MAX 1; MINSLIDER 0; MAXSLIDER 1; STEP 0.01; CUSTOMGUI REALSLIDER; FIT_H; SCALE_H; PARENTCOLLAPSE MDATA_BRUSHMODIFIERBASE_ENABLED; }
		REAL BM_KNIFE_PUSH { MIN 0; MAX 100;  MINSLIDER 0; MAXSLIDER 1; STEP 0.01; CUSTOMGUI REALSLIDER; FIT_H; SCALE_H; PARENTCOLLAPSE MDATA_BRUSHMODIFIERBASE_ENABLED; }
	}
}
