CONTAINER toolsculptbrushrepeat
{
  NAME toolsculptbrushrepeat;
  INCLUDE toolsculptbrushbase;

	HIDE MDATA_SCULPTBRUSH_SETTINGS_STAMPSPACING_VALUE_MOD;
	HIDE MDATA_SCULPTBRUSH_SETTINGS_STAMPSPACING_VALUE;
	HIDE MDATA_SCULPTBRUSH_SETTINGS_STAMPSPACING;
	HIDE MDATA_SCULPTBRUSH_STAMP_ROTATION_VALUE_MOD;
	HIDE MDATA_SCULPTBRUSH_STAMP_ROTATION_VALUE;
	HIDE MDATA_SCULPTBRUSH_STAMP_FOLLOW;
	HIDE MDATA_SCULPTBRUSH_STAMP_ENCLOSE;
	HIDE MDATA_SCULPTBRUSH_STAMP_USEFALLOFF;
	HIDE MDATA_SCULPTBRUSH_SETTINGS_FILL_BACKFACES;
	HIDE MDATA_SCULPTBRUSH_SETTINGS_DRAWMODE_FILL_SYMMETRY;

  	GROUP MDATA_SCULPTBRUSH_SETTINGS_GROUP
	{
		COLUMNS 3;

		GROUP
		{
			COLUMNS 3;
			LONG MDATA_SCULPTBRUSH_SETTINGS_DRAWMODE
			{
				CYCLE
				{
					MDATA_SCULPTBRUSH_SETTINGS_DRAWMODE_FREEHAND;
					MDATA_SCULPTBRUSH_SETTINGS_DRAWMODE_LINE;
				}
			}
		}
		STATICTEXT { JOINENDSCALE; }
		STATICTEXT { JOINEND; }
		
		REAL MDATA_SCULPTBRUSH_SETTINGS_BUILDUP { MIN 1; MAX 100; MINSLIDER 1; MAXSLIDER 100; CUSTOMGUI REALSLIDER; FIT_H; SCALE_H; }
		STATICTEXT { JOINENDSCALE; }
		STATICTEXT { JOINEND; }
	
		BOOL MDATA_SCULPTBRUSH_SETTINGS_INVERT { }
		STATICTEXT { DUMMY; }				
		STATICTEXT { DUMMY; }				
	}
}
