CONTAINER toolsculptbrushfill
{
  NAME toolsculptbrushfill;
  INCLUDE toolsculptbrushbase;

  	HIDE MDATA_SCULPTBRUSH_SETTINGS_FILL_BACKFACES;
	HIDE MDATA_SCULPTBRUSH_SETTINGS_DRAWMODE_FILL_SYMMETRY;
  
  GROUP MDATA_SCULPTBRUSH_SETTINGS_GROUP
	{
		COLUMNS 3;

		GROUP
		{
			COLUMNS 3;
			LONG MDATA_SCULPTBRUSH_SETTINGS_DRAWMODE
			{
				CYCLE
				{
					MDATA_SCULPTBRUSH_SETTINGS_DRAWMODE_FREEHAND;
					MDATA_SCULPTBRUSH_SETTINGS_DRAWMODE_LINE;
				}
			}
		}
		STATICTEXT { JOINENDSCALE; }
		STATICTEXT { JOINEND; }

	}
}
