CONTAINER toolsculptbrushknife
{
  NAME toolsculptbrushknife;
  INCLUDE toolsculptbrushbase;
	HIDE MDATA_SCULPTBRUSH_SETTINGS_FILL_BACKFACES;
	HIDE MDATA_SCULPTBRUSH_SETTINGS_DRAWMODE_FILL_SYMMETRY;

	GROUP MDATA_SCULPTBRUSH_SETTINGS_GROUP
	{
		COLUMNS 3;

		GROUP
		{
			COLUMNS 3;
			LONG MDATA_SCULPTBRUSH_SETTINGS_DRAWMODE
			{
				CYCLE
				{
					MDATA_SCULPTBRUSH_SETTINGS_DRAWMODE_FREEHAND;
					MDATA_SCULPTBRUSH_SETTINGS_DRAWMODE_LINE;
				}
			}
		}
		STATICTEXT { JOINENDSCALE; }
		STATICTEXT { JOINEND; }
		
		BOOL MDATA_SCULPTBRUSH_SETTINGS_INVERT { }
		STATICTEXT { DUMMY; }
		STATICTEXT { DUMMY; }
		
		REAL MDATA_SCULPTBRUSH_KNIFE_PINCH { MIN 0; MAX 1; MINSLIDER 0; MAXSLIDER 1; STEP 0.01; CUSTOMGUI REALSLIDER; FIT_H; SCALE_H; }
		STATICTEXT { JOINENDSCALE; }
		STATICTEXT { JOINEND; }

		REAL MDATA_SCULPTBRUSH_KNIFE_PUSH { MIN 0; MAX 100;  MINSLIDER 0; MAXSLIDER 1; STEP 0.01; CUSTOMGUI REALSLIDER; FIT_H; SCALE_H; }
		STATICTEXT { JOINENDSCALE; }
		STATICTEXT { JOINEND; }
	}
}
