CONTAINER toolsculptbrushselect
{
  NAME toolsculptbrushselect;
  INCLUDE toolsculptbrushbase;
  HIDE MDATA_SCULPTBRUSH_STAMP_GROUP;
  HIDE MDATA_SCULPTBRUSH_STENCIL_GROUP;
  HIDE MDATA_SCULPTBRUSH_FALLOFF_GROUP;
  HIDE MDATA_SCULPTBRUSH_SETTINGS_STRENGTH;
  HIDE MDATA_SCULPTBRUSH_SETTINGS_STRENGTH_MOD;

	GROUP MDATA_SCULPTBRUSH_SETTINGS_GROUP
	{
		COLUMNS 3;		
	}

}
