CONTAINER toolsculptbrushgrab
{
	NAME toolsculptbrushgrab;
	INCLUDE  toolsculptbrushbase;  

	HIDE MDATA_SCULPTBRUSH_SETTINGS_STAMPSPACING;
	HIDE MDATA_SCULPTBRUSH_SETTINGS_STAMPSPACING_VALUE;
	HIDE MDATA_SCULPTBRUSH_SETTINGS_STRENGTH_MOD;
	HIDE MDATA_SCULPTBRUSH_SETTINGS_STRENGTH;
	HIDE MDATA_SCULPTBRUSH_SETTINGS_STEADYSTROKE;
	HIDE MDATA_SCULPTBRUSH_SETTINGS_STEADYSTROKE_VALUE;
	HIDE MDATA_SCULPTBRUSH_SETTINGS_DRAWMODE;
	HIDE MDATA_SCULPTBRUSH_STAMP_FOLLOW;
	HIDE MDATA_SCULPTBRUSH_SETTINGS_FILL_BACKFACES;
	HIDE MDATA_SCULPTBRUSH_SETTINGS_DRAWMODE_FILL_SYMMETRY;
	HIDE MDATA_SCULPTBRUSH_SETTINGS_EDGE;
	HIDE MDATA_SCULPTBRUSH_SETTINGS_EDGE_ANGLE;
	HIDE MDATA_SCULPTBRUSH_SETTINGS_EDGE_LINE;
	HIDE MDATA_SCULPTBRUSH_SETTINGS_STEADYSTROKE_LINE;
	HIDE MDATA_SCULPTBRUSH_SETTINGS_STAMPSPACING_LINE;
	HIDE MDATA_SCULPTBRUSH_SETTINGS_STRENGTH_LINE;

	GROUP MDATA_SCULPTBRUSH_SETTINGS_GROUP
	{
		COLUMNS 3;

		LONG MDATA_TOOLSCULPTBRUSHGRAB_DIRMODE
		{
			FIT_H; SCALE_H;
			CYCLE
			{
				MDATA_TOOLSCULPTBRUSHGRAB_DIRMODE_MOUSEDIR;
				MDATA_TOOLSCULPTBRUSHGRAB_DIRMODE_NORMAL;
				MDATA_TOOLSCULPTBRUSHGRAB_DIRMODE_X;
				MDATA_TOOLSCULPTBRUSHGRAB_DIRMODE_Y;
				MDATA_TOOLSCULPTBRUSHGRAB_DIRMODE_Z;
			}
		}
		STATICTEXT { DUMMY; }
		STATICTEXT { DUMMY; }

		BOOL MDATA_SCULPTBRUSH_USESURFACEDISTANCE { }
		STATICTEXT { DUMMY; }
		STATICTEXT { DUMMY; }
	}
}

