CONTAINER toolsculptbrushamplify
{
  NAME toolsculptbrushamplify;
  INCLUDE toolsculptbrushbase;
  HIDE MDATA_SCULPTBRUSH_SETTINGS_DRAWMODE_FILL_SYMMETRY;
  HIDE MDATA_SCULPTBRUSH_SETTINGS_FILL_BACKFACES;

  GROUP MDATA_SCULPTBRUSH_SETTINGS_GROUP
	{
		COLUMNS 3;

		COLUMNS 3;
		GROUP
		{
			COLUMNS 3;
			LONG MDATA_SCULPTBRUSH_SETTINGS_DRAWMODE
			{
				CYCLE
				{
					MDATA_SCULPTBRUSH_SETTINGS_DRAWMODE_FREEHAND;
					MDATA_SCULPTBRUSH_SETTINGS_DRAWMODE_LINE;
				}
			}
		}
		STATICTEXT { JOINENDSCALE; }
		STATICTEXT { JOINEND; }

		LONG MDATA_SCULPTBRUSH_AMPLIFY_MODE
		{
			FIT_H; SCALE_H;

			CYCLE
			{
				MDATA_SCULPTBRUSH_AMPLIFY_MODE_BOTH;
				MDATA_SCULPTBRUSH_AMPLIFY_MODE_CREVICE;
				MDATA_SCULPTBRUSH_AMPLIFY_MODE_RIDGE;
			}
		}
		STATICTEXT { DUMMY; }
		STATICTEXT { DUMMY; }
	}
}
