CONTAINER toolsculptbrushflatten
{
  NAME toolsculptbrushflatten;
  INCLUDE toolsculptbrushbase;

	GROUP MDATA_SCULPTBRUSH_SETTINGS_GROUP
	{
		COLUMNS 3;

		LONG MDATA_SCULPTBRUSH_SETTINGS_FIXEDPLANE
		{
			CYCLE
			{
				MDATA_SCULPTBRUSH_SETTINGS_FIXEDPLANE_OFF;
				MDATA_SCULPTBRUSH_SETTINGS_FIXEDPLANE_MOUSEDOWN;
				MDATA_SCULPTBRUSH_SETTINGS_FIXEDPLANE_WORKPLANE;
				MDATA_SCULPTBRUSH_SETTINGS_FIXEDPLANE_CUSTOM;
			}
		}
		BOOL MDATA_SCULPTBRUSH_SETTINGS_FIXEDPLANE_CUSTOM_HIDEONSTROKE { }
		STATICTEXT { DUMMY; }

		REAL MDATA_SCULPTBRUSH_SETTINGS_FIXEDPLANE_CUSTOM_SIZE { MIN 0; MAXSLIDER 100; CUSTOMGUI REALSLIDER; FIT_H; SCALE_H; }
		STATICTEXT { JOINENDSCALE; }
		STATICTEXT { JOINEND; }

		REAL MDATA_SCULPTBRUSH_SETTINGS_FIXEDPLANE_DEPTH { MINSLIDER -100; MAXSLIDER 100; STEP 1; CUSTOMGUI REALSLIDER; FIT_H; SCALE_H; }
		STATICTEXT { DUMMY; }
		STATICTEXT { DUMMY; }

		SEPARATOR { LINE; }
		STATICTEXT { JOINENDSCALE; }
		STATICTEXT { JOINEND; }

		BOOL MDATA_SCULPTBRUSH_FLATTEN_SMOOTH { }
		STATICTEXT { DUMMY; }
		STATICTEXT { DUMMY; }
	}
}
