CONTAINER toolsculptbrushscrape
{
  NAME toolsculptbrushscrape;
  INCLUDE toolsculptbrushbase;
   HIDE MDATA_SCULPTBRUSH_SETTINGS_DRAWMODE_FILL_SYMMETRY;
  HIDE MDATA_SCULPTBRUSH_SETTINGS_FILL_BACKFACES;

	GROUP MDATA_SCULPTBRUSH_SETTINGS_GROUP
	{
		COLUMNS 3;
		GROUP
		{
			COLUMNS 3;
			LONG MDATA_SCULPTBRUSH_SETTINGS_DRAWMODE
			{
				CYCLE
				{
					MDATA_SCULPTBRUSH_SETTINGS_DRAWMODE_FREEHAND;
					MDATA_SCULPTBRUSH_SETTINGS_DRAWMODE_LINE;
				}
			}
		}
		STATICTEXT { JOINENDSCALE; }
		STATICTEXT { JOINEND; }

		REAL MDATA_SCULPTBRUSH_SETTINGS_BUILDUP { MIN 1; MAX 100; MINSLIDER 1; MAXSLIDER 100; CUSTOMGUI REALSLIDER; FIT_H; SCALE_H; }
		STATICTEXT { JOINENDSCALE; }
		STATICTEXT { JOINEND; }
	}
}
