CONTAINER toolsculptbrushmask
{
  NAME toolsculptbrushmask;
  INCLUDE toolsculptbrushbase;
	
	GROUP MDATA_SCULPTBRUSH_SETTINGS_GROUP
	{
		COLUMNS 3;

		GROUP MDATA_SCULPTBRUSH_SETTINGS_EDGE_GROUP
		{
			COLUMNS 1;
			BOOL MDATA_SCULPTBRUSH_SETTINGS_EDGE { }
			BOOL MDATA_SCULPTBRUSH_SETTINGS_EDGE_INVERT { }
			REAL MDATA_SCULPTBRUSH_SETTINGS_EDGE_ANGLE { UNIT DEGREE; MIN 1; MAX 90; CUSTOMGUI REALSLIDER; SCALE_H; FIT_H;}
		}
		STATICTEXT { JOINENDSCALE; }
		STATICTEXT { JOINEND; }



		BOOL MDATA_SCULPTBRUSH_MASK_FILL { }
		STATICTEXT { DUMMY; }
		STATICTEXT { DUMMY; }

		REAL MDATA_SCULPTBRUSH_MASK_FILL_TOLERANCE { MIN 0; MAX 100.0; MINSLIDER 0; MAXSLIDER 100; STEP 1; CUSTOMGUI REALSLIDER; UNIT PERCENT; SCALE_H; }
		STATICTEXT { JOINENDSCALE; }
		STATICTEXT { JOINEND; }

		//BOOL MDATA_SCULPTBRUSH_MASK_FILL_SCULPTED { }
		//STATICTEXT { DUMMY; }
		//STATICTEXT { DUMMY; }
		
		SEPARATOR { LINE; }
		STATICTEXT { JOINENDSCALE; }
		STATICTEXT { JOINEND; }

		COLOR MDATA_SCULPTBRUSH_MASK_COLOR { ANIM OFF; }
		STATICTEXT { JOINENDSCALE; }
		STATICTEXT { JOINEND; }

		BOOL MDATA_SCULPTBRUSH_SETTINGS_INVERT { }
		STATICTEXT { DUMMY; }
		STATICTEXT { DUMMY; }
				
		SEPARATOR { LINE; }
		STATICTEXT { JOINENDSCALE; }
		STATICTEXT { JOINEND; }

		LONG MDATA_SCULPTBRUSH_MASK_MODE
		{
			FIT_H; SCALE_H;

			CYCLE
			{
				MDATA_SCULPTBRUSH_MASK_MODE_BOTH;
				MDATA_SCULPTBRUSH_MASK_MODE_CREVICE;
				MDATA_SCULPTBRUSH_MASK_MODE_RIDGE;
			}
		}
		STATICTEXT { DUMMY; }
		STATICTEXT { DUMMY; }

		GROUP
		{
			COLUMNS 2;
			BUTTON MDATA_SCULPTBRUSH_SETTINGS_FLOOD{ }
			BUTTON MDATA_SCULPTBRUSH_MASK_BLUR{ }
			//BUTTON MDATA_SCULPTBRUSH_MASK_SCULPTED{ }
			//BUTTON MDATA_SCULPTBRUSH_MASK_OCCLUDED{ }
		}
		STATICTEXT { JOINENDSCALE; }
		STATICTEXT { JOINEND; }

		SEPARATOR { LINE; }
		STATICTEXT { JOINENDSCALE; }
		STATICTEXT { JOINEND; }

		GROUP
		{
			COLUMNS 2;
			LINK MDATA_SCULPTBRUSH_MASK_SAMPLE_MATERIAL_LINK 
			{  
				ACCEPT { Mmaterial; } 
			}
			BUTTON MDATA_SCULPTBRUSH_MASK_SAMPLE_MATERIAL{ }
		}
		STATICTEXT { DUMMY; }
		STATICTEXT { DUMMY; }
	}
}
