CONTAINER toolsculptbrushinflate
{
  NAME toolsculptbrushinflate;
  INCLUDE toolsculptbrushbase;
 
  GROUP MDATA_SCULPTBRUSH_SETTINGS_GROUP
	{
		COLUMNS 3;

		BOOL MDATA_SCULPTBRUSH_SETTINGS_INVERT { }
		STATICTEXT { DUMMY; }
		STATICTEXT { DUMMY; }
				
		SEPARATOR { LINE; }
		STATICTEXT { JOINENDSCALE; }
		STATICTEXT { JOINEND; }

		BUTTON MDATA_SCULPTBRUSH_SETTINGS_FLOOD{ }
		STATICTEXT { DUMMY; }
		STATICTEXT { DUMMY; }

		REAL MDATA_SCULPTBRUSH_SETTINGS_INTERACTIVE_FLOOD { MIN -100; MAX 100; CUSTOMGUI REALSLIDER; SCALE_H; FIT_H;}
		STATICTEXT { JOINENDSCALE; }
		STATICTEXT { JOINEND; }

		SEPARATOR { LINE; }
		STATICTEXT { JOINENDSCALE; }
		STATICTEXT { JOINEND; }

		BOOL MDATA_SCULPTBRUSH_SETTINGS_INTERACTIVE_MATERIAL_FLOOD { }
		STATICTEXT { DUMMY; }
		STATICTEXT { DUMMY; }

		LINK MDATA_SCULPTBRUSH_SETTINGS_INTERACTIVE_MATERIAL_LINK
		{ 
			ACCEPT { Mmaterial; } 
		}
		STATICTEXT { JOINENDSCALE; }
		STATICTEXT { JOINEND; }
	}
}
