// C4D-DialogResource

DIALOG DLG_SCRIPTMANAGER
{
	NAME T1;
	
	SCALE_V;
	SCALE_H;
	
	GROUP
	{
		SCALE_H;
		SCALE_V;

		ROWS 2;
		SPACE 5,5;
		BORDERSIZE 5,5,5,5;
		
		GROUP
		{
			SCALE_H;
			COLUMNS 5;
			
			GROUP
			{
				FIT_V; FIT_H;
				BORDERSTYLE BORDER_OUT;
				
				BITMAPBUTTON SCRIPTMANAGER_BTN_ICON
				{
					ICONID1 1022749;
				}
			}
			
			BUTTON SCRIPTMANAGER_BTN_EXECUTE
			{
				NAME SCRIPTMANAGER_BTN_EXECUTE;
			}

			BUTTON SCRIPTMANAGER_BTN_RENDERICON
			{
				NAME SCRIPTMANAGER_BTN_RENDERICON;
			}

			BUTTON SCRIPTMANAGER_BTN_CREATESCRIPT
			{
				NAME SCRIPTMANAGER_BTN_CREATESCRIPT;
			}

			STATICTEXT SCRIPTMANAGER_TXT_SYNTAX
			{
				SCALE_H;
			}
		}

		MULTILINEEDIT SCRIPTMANAGER_TXT_SCRIPT
		{
			SCALE_H;
			SCALE_V;

			MONOSPACED;
			PYTHON;
			SYNTAXCOLOR;
			STATUSBAR;
		}
	}
}
