// C4D-DialogResource
DIALOG IDD_GL_CAPS_DIALOG
{
  NAME IDS_GL_CAPS_DIALOG; SCALE_V; SCALE_H; 
  
  TREEVIEW IDC_OGL_CAPS_TREE
  {
    SCALE_V; SCALE_H; 
    BORDER; 
    HIDE_LINES; 
    NO_MULTISELECT; 
    HAS_HEADER; 
    RESIZE_HEADER; 
  }
  STATICTEXT IDC_OGL_CAPS_STRING { NAME IDS_STATIC; ALIGN_BOTTOM; SCALE_H; }
}