DIALOG optindialog
{
	NAME IDS_TITLE;

	GROUP IDC_OPTIN_GROUP
	{
		COLUMNS 1;
		
		HTMLVIEWER IDC_VIEWER
		{
			CENTER_H;
			SIZE -800, -610;
		}

		RADIOGROUP IDC_DECISSION
		{
			CENTER_H;
			GROUP
			{
				COLUMNS 1;
	
				RADIOGADGET IDC_RADIO_PARTICIPATE { NAME IDS_RADIO_PARTICIPATE; }
				RADIOGADGET IDC_RADIO_NOT_PARTICIPATE { NAME IDS_RADIO_NOT_PARTICIPATE; }
			}
		}
		GROUP
		{
			CENTER_H;
			COLUMNS 2;
			EQUAL_COLS;
			
			BUTTON IDC_BUTTON_OK { NAME IDS_BUTTON_OK; SCALE_H;}
			BUTTON IDC_BUTTON_REMIND_LATER{ NAME IDS_BUTTON_REMIND_LATER; SCALE_H;}
		}
	}
}
