enum
{
	// IDs for the global string table
	STRING_CMD_OPENEXR_NAME = 10000,
	STRING_CMD_SETTINGS,

	DLG_GETSAVEOPTIONS,
	STR_OPENEXRSAVEOPTIONS,
	COMPRESSION_TYPE,
	NO_COMPRESSION_ID,
	RLE_COMPRESSION_ID,
	ZIPS_COMPRESSION_ID,
	ZIP_COMPRESSION_ID,
	PIZ_COMPRESSION_ID,
	PXR24_COMPRESSION_ID,
	B44_COMPRESSION_ID,
	B44A_COMPRESSION_ID,
	RLE_HF_COMPRESSION_ID,
	ZIPS_HF_COMPRESSION_ID,
	ZIP_HF_COMPRESSION_ID,
	PIZ_HF_COMPRESSION_ID,
	DUMMY_

};
