#ifndef TMOGRAPH_CACHE_H__
#define TMOGRAPH_CACHE_H__

enum
{
	MGCACHETAG_BAKESEQUENCE				= 1000,
	MGCACHETAG_BAKEFRAME,
	MGCACHETAG_CLEARFRAME,
	MGCACHETAG_CLEARCACHE,
	MGCACHETAG_BAKEFROM,
	MGCACHETAG_BAKETO,
	MGCACHETAG_BAKESEQUENCE_ACTIVE,
	MGCACHETAG_MEMORYUSED,
	MGCACHETAG_ACTIVE,
	MGCACHETAG_OFFSET,
	MGCACHETAG_LOOP,
	MGCACHETAG_LOOP_BLEND
};
#endif // TMOGRAPH_CACHE_H__
