CONTAINER Obend
{
	NAME Obend;
	INCLUDE Obasedeform;

	SHOW DEFORMOBJECT_SIZE;
	SHOW DEFORMOBJECT_MODE;
	SHOW DEFORMOBJECT_ANGLE;
	SHOW DEFORMOBJECT_STRENGTH;

	GROUP ID_OBJECTPROPERTIES
	{
		REAL   BENDOBJECT_STRENGTH { UNIT DEGREE; }
		BOOL BENDOBJECT_KEEPYAXIS { }
		SEPARATOR		{ LINE; }
		BUTTON	DEFORMOBJECT_FITTOPARENT	{  }
	}
}
