CONTAINER Oexplosion
{
	NAME Oexplosion;
	INCLUDE Obase;

	GROUP ID_OBJECTPROPERTIES
	{
		REAL EXPLOSIONOBJECT_STRENGTH { MIN 0.0; MAX 100.0; UNIT PERCENT; }
		REAL EXPLOSIONOBJECT_PSPEED   { UNIT METER; }
		REAL EXPLOSIONOBJECT_ASPEED	  { UNIT DEGREE; }
		REAL EXPLOSIONOBJECT_ENDSIZE  { MIN 0.0; MAX 1000.0; STEP 0.01; }
		REAL EXPLOSIONOBJECT_RANDOM   { MIN 0.0; MAX 100.0; UNIT PERCENT; }
	}
}
