CONTAINER Oloudspeaker
{
	NAME Oloudspeaker;
	INCLUDE Obase;

	GROUP ID_OBJECTPROPERTIES
	{
		BOOL LMOBJECT_SHOW {}

		GROUP CONE_GROUP
		{
			DEFAULT 1;
			BOOL LMOBJECT_OUTERCONE {}
			REAL LMOBJECT_OUTERANGLE { PARENTID LMOBJECT_OUTERCONE; MIN 0.0; MAX 179.0; UNIT DEGREE; }
			SEPARATOR { LINE; }
			BOOL LMOBJECT_INNERCONE {}
			REAL LMOBJECT_INNERANGLE { PARENTID LMOBJECT_INNERCONE; MIN 0.0; MAX 179.0; UNIT DEGREE; }
		}

		GROUP FALLOFF_GROUP
		{
			DEFAULT 1;
			LONG LMOBJECT_FALLOFF
			{
				CYCLE
				{
					LMOBJECT_FALLOFF_NONE;
					LMOBJECT_FALLOFF_LINEAR;
					LMOBJECT_FALLOFF_INVERSE;
					LMOBJECT_FALLOFF_INVERSESQUARE;
					LMOBJECT_FALLOFF_INVERSECUBIC;
				}
			}

			REAL LMOBJECT_INNERDIST { PARENTID LMOBJECT_FALLOFF; MIN 0.0; UNIT METER; }
			REAL LMOBJECT_OUTERDIST { PARENTID LMOBJECT_FALLOFF; MIN 0.0; UNIT METER; }
		}
	}
}
