CONTAINER Omelt
{
	NAME Omelt;
	INCLUDE Obase;

	GROUP ID_OBJECTPROPERTIES
	{
		REAL MELTOBJECT_STRENGTH   { MIN 0.0; MAX 100.0; UNIT PERCENT; }
		REAL MELTOBJECT_RADIUS     { MIN 0.0; UNIT METER; }
		REAL MELTOBJECT_VERTRANDOM { MIN 0.0; MAX 100.0; UNIT PERCENT; }
		REAL MELTOBJECT_RADRANDOM	 { MIN 0.0; MAX 100.0; UNIT PERCENT; }
		REAL MELTOBJECT_SIZE       { MIN 100.0; MAX 1000.0; UNIT PERCENT; }
		REAL MELTOBJECT_NOISESCALE { MIN 0.1; MAX 10000.0; UNIT PERCENT; }
	}
}
