CONTAINER Omicrophone
{
	NAME Omicrophone;
	INCLUDE Obase;

	GROUP ID_OBJECTPROPERTIES
	{
		BOOL MICROPHONEOBJECT_DOPPLER {}
		REAL MICROPHONEOBJECT_DFACTOR { PARENTID MICROPHONEOBJECT_DOPPLER; MIN 0.0; UNIT PERCENT; }
		SEPARATOR { LINE; }

		INCLUDE Oloudspeaker;
	}
}
