CONTAINER Opyramid
{
	NAME Opyramid;
	INCLUDE Obase;

	GROUP ID_OBJECTPROPERTIES
	{
		VECTOR PRIM_PYRAMID_LEN { UNIT METER; MIN 0.0; }
		LONG PRIM_PYRAMID_SUB { MIN 1; MAX 1000; }
	}
	INCLUDE Oprimitiveaxis;
}
