CONTAINER Oshatter
{
	NAME Oshatter;
	INCLUDE Obase;

	GROUP ID_OBJECTPROPERTIES
	{
		REAL SHATTEROBJECT_STRENGTH      { MIN 0.0; MAX 100.0; UNIT PERCENT; }
		REAL SHATTEROBJECT_ANGLESPEED	   { UNIT DEGREE; }
		REAL SHATTEROBJECT_SCALE				 { MIN 0.0; MAX 1000.0; STEP 0.01; }
		REAL SHATTEROBJECT_RANDOM        { MIN 0.0; MAX 100.0; UNIT PERCENT; }
	}
}
