CONTAINER Ospherify
{
	NAME Ospherify;
	INCLUDE Obase;

	GROUP ID_OBJECTPROPERTIES
	{
		REAL SPHERIFYOBJECT_RADIUS	   { UNIT METER; MIN 0.0; }
		REAL SPHERIFYOBJECT_STRENGTH	 { UNIT PERCENT; MIN 0.0; MAX 100.0; }
		SEPARATOR		{ LINE; }
		BUTTON	SPHERIFYOBJECT_FITTOPARENT	{  }
	}
}
