CONTAINER Otwist
{
	NAME Otwist;
	INCLUDE Obasedeform;

	SHOW DEFORMOBJECT_SIZE;
	SHOW DEFORMOBJECT_MODE;
	SHOW DEFORMOBJECT_ANGLE;
	
	GROUP ID_OBJECTPROPERTIES
	{
		SEPARATOR		{ LINE; }
		BUTTON	DEFORMOBJECT_FITTOPARENT	{  }
	}
}
