// C4D Dialog Resource

DIALOG IDD_OP_PARTICLEDRAWTOOL
{
	NAME TDLG;
	SCALE_H; SCALE_V;

	GROUP
	{
		COLUMNS 1;
		SCALE_H; SCALE_V;

		STATICTEXT {NAME FRAMEPARTICLES; }

		LISTVIEW IDC_OP_PARTICLEDRAWTOOL_LIST {}

		BUTTON IDC_OP_PARTICLEDRAWTOOL_REMOVE { NAME REMOVE; }
	}
}

