enum
{
	IDS_MESH_ERROR_NOMEMORY,
	IDS_MESH_ERROR_NOTAGCREATED,
	IDS_MESH_ERROR_NOBSCREATED,
	IDS_MESH_ERROR_CANTEXPORTDATA,
	IDS_MESH_ERROR_NOOBJECT,
	IDS_MESH_ERROR_CHANGE,
	IDS_SURFACE_INTERRORRESTRICTION,
	IDS_COPYERROR,

	IDS_MAYAEXCHANGE,
	IDS_MAYAEXCHANGE_SENT,
	IDS_MAYAEXCHANGE_ERROR_TEXPATHNOTFOUND,
	IDS_MAYAEXCHANGE_ERROR_NOXCHANGESCENE,
	IDS_MAYAEXCHANGE_ERROR_WRONGDOCPATH,
	IDS_MAYAEXCHANGE_ERROR_WRONGXCHANGEPATH,
	IDS_MAYAEXCHANGE_ERROR_WRONGXCHANGEORTEXPATH,
	IDS_MAYAEXCHANGE_ERROR_NODATAEXPORTED,
	IDS_MAYAEXCHANGE_ERROR_COULDNOTOPENFILE,

	IDS_XSIEXCHANGE,
	IDS_XSIEXCHANGE_SENT,
	IDS_XSIEXCHANGE_ERROR_TEXPATHNOTFOUND,
	IDS_XSIEXCHANGE_ERROR_NOXCHANGESCENE,
	IDS_XSIEXCHANGE_ERROR_WRONGDOCPATH,
	IDS_XSIEXCHANGE_ERROR_WRONGXCHANGEPATH,
	IDS_XSIEXCHANGE_ERROR_WRONGXCHANGEORTEXPATH,
	IDS_XSIEXCHANGE_ERROR_NODATAEXPORTED,
	IDS_XSIEXCHANGE_ERROR_COULDNOTOPENFILE,

	IDS_MAT_DEFAULT_LAYER_REFLECTION,
	IDS_MAT_DEFAULT_LAYER_SPECULAR,

	DUMMY_
};
