// C4D-DialogResource

DIALOG DLG_LISTVIEW
{
	NAME	STR_TITLE;
	
	GROUP
	{
		COLUMNS 1;
		BORDERSIZE 8,8,8,8;
		
		STATICTEXT { SIZE -320, -1; }
	
		LISTVIEW GADGET_LISTVIEW { 		SCALE_H;SCALE_V; SIZE 250,400; };
	
		GROUP
		{
			BUTTON SELECT_ALL { NAME STRING_SEL_ALL; }
			BUTTON DESELECT_ALL { NAME STRING_DESEL_ALL; }
		}
  }
	DLGGROUP { OK;CANCEL; }
}
