// C4D-DialogResource

DIALOG DLG_OVERWRITE
{
	NAME	STR_TITLE;
	
	GROUP
	{
		COLUMNS 1;
		STATICTEXT {NAME STR_EMPTY; }
		GROUP
		{
		STATICTEXT STRING_TMP_PART1 { NAME STR_TMP_PART1;}
		STATICTEXT STRING_TMP_FILE_EXISTS {NAME STR_TMP_FILE_EXISTS;}
		STATICTEXT STRING_TMP_PART2 { NAME STR_TMP_PART2;}
		}
		STATICTEXT {NAME STR_EMPTY; }
		
	}

	GROUP
	{
		CENTER_H;
		BUTTON CMD_OVERWRITE { NAME STRING_OVERWRITE; }
		BUTTON CMD_CANCEL { NAME STRING_CANCEL; }
	}
}
