CONTAINER Figes
{
	NAME Figes;
	INCLUDE Fbase;

	GROUP IGESFILTER_GROUP
	{
		DEFAULT 1;
		COLUMNS 2;
		SEPARATOR IGESFILTER_COMMONOPTIONS {}
		STATICTEXT{JOINENDSCALE;}
		LONG IGESFILTER_SORTORDER
		{
			  CYCLE
				  {
			  IGESFILTER_SORTNOTHING;
			  IGESFILTER_SORTBYLEVEL;
			  IGESFILTER_SORTBYCOLOR;
				}
				
				DEFAULT IGESFILTER_SORTBYLEVEL;
		}
		STATICTEXT{}

		BOOL IGESFILTER_POLYGONS { DEFAULT 1;}
		STATICTEXT{}
		BOOL IGESFILTER_SWAP_YZ { DEFAULT 1;}
		STATICTEXT{}
		BOOL IGESFILTER_CENTERAXIS { DEFAULT 1;}
		STATICTEXT{}
		BOOL IGESFILTER_MATERIALS { DEFAULT 1;}
		STATICTEXT{}

		SEPARATOR IGESFILTER_CURVEOPTIONS {}
		STATICTEXT{JOINENDSCALE;}
		
		LONG IGESFILTER_CURVE_OUTPUT
		{ HIDDEN;
			  CYCLE
			  {
				BASECURVE_OUTPUT_LINEAR;
				BASECURVE_OUTPUT_BSPLINE;
				BASECURVE_OUTPUT_BEZIER;
				BASECURVE_OUTPUT_CONVERT;
				}
		}
		REAL IGESFILTER_CURVE_SUBFACTOR   { MIN 0.01; MAX 100.0; DEFAULT 3.0;}
		STATICTEXT{}

		SEPARATOR IGESFILTER_SURFACEOPTIONS {}
		STATICTEXT{JOINENDSCALE;}
		
		LONG IGESFILTER_SURFACE_OUTPUT
		{ HIDDEN;
			  CYCLE
			  {
			  BASESURFACE_OUTPUT_LINEAR;
			  BASESURFACE_OUTPUT_BSPLINE;
			  BASESURFACE_OUTPUT_HYPERNURBS;
		  BASESURFACE_OUTPUT_CONVERT;
		}
		}
		REAL IGESFILTER_SURFACE_SUBFACTOR_U { MIN 0.01; MAX 100.0; DEFAULT 3.0;}
		STATICTEXT{}
		REAL IGESFILTER_SURFACE_SUBFACTOR_V { MIN 0.01; MAX 100.0; DEFAULT 3.0;}
		STATICTEXT{}

		BOOL IGESFILTER_SURFACE_NORMALS     { DEFAULT 1;}
		STATICTEXT{}
		BOOL IGESFILTER_SURFACE_SWAPNORMALS { DEFAULT 0;}
		STATICTEXT{}

		SEPARATOR IGESFILTER_TRIMMEDOPTIONS  {}
		STATICTEXT{JOINENDSCALE;}
		
		REAL IGESFILTER_TRIMMED_PRECISION   { HIDDEN; MIN 0.0001; MAX 1000.0; }
		STATICTEXT{JOINENDSCALE;}
		BOOL IGESFILTER_TRIMMED_DISABLE { HIDDEN; }
		BOOL IGESFILTER_TRIMMED_CURVES { DEFAULT 1;}
		STATICTEXT{JOINENDSCALE;}

		SEPARATOR IGESFILTER_EXPERTOPTIONS  {}
		STATICTEXT{JOINENDSCALE;}
  
		BOOL IGESFILTER_LOADHIDDEN { DEFAULT 0;}
		STATICTEXT{JOINENDSCALE;}
		BOOL IGESFILTER_DEBUG       { DEFAULT 0;}
		STATICTEXT{JOINENDSCALE;}
		BOOL IGESFILTER_LOADUNKNOWN { DEFAULT 0;}
		STATICTEXT{JOINENDSCALE;}
	}
}
