CONTAINER Tigesimport
{
	NAME Tigesimport;
	INCLUDE Texpression;

	GROUP ID_TAGPROPERTIES
	{
		BOOL IGESIMPORT_EXPERT_MODE { HIDDEN; DEFAULT 0; }
  }

	GROUP ID_IGESIMPORT_FILEINFO
	{
    SCALE_V;

		STRING IGESIMPORT_HEADER {CUSTOMGUI MULTISTRING; SCALE_V; }

		SEPARATOR { LINE; }
		GROUP
		{
	    STATICTEXT IGESIMPORT_PRODUCT { }
	    STATICTEXT IGESIMPORT_FILENAME { }
	    STATICTEXT IGESIMPORT_SYSTEM { }
	    STATICTEXT IGESIMPORT_PREPROCESSOR { }
	    STATICTEXT IGESIMPORT_RECEIVER { }

	    STATICTEXT IGESIMPORT_FILETIME { }
	    STATICTEXT IGESIMPORT_FILEAUTHOR { }
	    STATICTEXT IGESIMPORT_FILEORG { }

		  SEPARATOR { LINE; }
      STATICTEXT IGESIMPORT_IGESVERSION { }
      STATICTEXT IGESIMPORT_DRAFTSTANDARD { }

		  SEPARATOR { LINE; }
      STATICTEXT IGESIMPORT_MODIFIED { }
      STATICTEXT IGESIMPORT_PROTOCOL { }
    }
  }

	GROUP ID_IGESIMPORT_FILEDETAILS
	{
    STATICTEXT IGESIMPORT_PREC_SHORT { }
    STATICTEXT IGESIMPORT_PREC_LONG { }
    STATICTEXT IGESIMPORT_PREC_SINGLE { }
    STATICTEXT IGESIMPORT_PEXP_SINGLE { }
    STATICTEXT IGESIMPORT_PREC_DOUBLE { }
    STATICTEXT IGESIMPORT_PEXP_DOUBLE { }

    STATICTEXT IGESIMPORT_ASCII_SMAG { }
    STATICTEXT IGESIMPORT_ASCII_SSIG { }
    STATICTEXT IGESIMPORT_ASCII_DMAG { }
    STATICTEXT IGESIMPORT_ASCII_DSIG { }

    STATICTEXT IGESIMPORT_SCALE { }
    STATICTEXT IGESIMPORT_UNIT { }
    STATICTEXT IGESIMPORT_UNITDESC { }
    STATICTEXT IGESIMPORT_MAXLINEWEIGHT { }
    STATICTEXT IGESIMPORT_MAXLINEWIDTH { }
    STATICTEXT IGESIMPORT_MINRESOLUTION { }
    STATICTEXT IGESIMPORT_MAXCOORDINATE { }
  }

	GROUP ID_IGESIMPORT_LOG
	{
    SCALE_V; 
  	STRING IGESIMPORT_LOG { CUSTOMGUI MULTISTRING; SCALE_V; }
  }
}




