CONTAINER GVpython
{
	NAME GVpython;
	INCLUDE GVbase;

	GROUP ID_GVPROPERTIES
	{
		SCALE_V;
		BOOL GV_PYTHON_FRAME { }
		SEPARATOR { LINE; }
		BOOL GV_PYTHON_RESET { }
		
		STRING GV_PYTHON_CODE
		{
		  CUSTOMGUI MULTISTRING;
		  PYTHON;
		  SCALE_V;
		}
		
		SEPARATOR
		{
		  LINE;
		}
		
		BUTTON GV_PYTHON_OPENEDITOR { }
	}

	GROUP ID_GVPORTS
	{
		SEPARATOR { LINE; }

		BOOL GV_PYTHON_ON { INPORT; }
		
		LONG IN_LONG {INPORT; MULTIPLE;}
		LONG OUT_LONG {OUTPORT; MULTIPLE;}
		
		STRING IN_STRING {INPORT; MULTIPLE;}
		STRING OUT_STRING {OUTPORT; MULTIPLE;}
		
		REAL IN_REAL {INPORT; MULTIPLE; CREATEPORT 2; }
		REAL OUT_REAL {OUTPORT; MULTIPLE; CREATEPORT 1; }
		
		VECTOR IN_VECTOR {INPORT; MULTIPLE;}
		VECTOR OUT_VECTOR {OUTPORT; MULTIPLE;}
		
		MATRIX IN_MATRIX {INPORT; MULTIPLE;}
		MATRIX OUT_MATRIX {OUTPORT; MULTIPLE;}
		
		BASETIME IN_BASETIME {INPORT; MULTIPLE;}
		BASETIME OUT_BASETIME {OUTPORT; MULTIPLE;}
		
		BOOL IN_BOOL {INPORT; MULTIPLE;}
		BOOL OUT_BOOL {OUTPORT; MULTIPLE;}
		
		LINK IN_LINK {INPORT; MULTIPLE;}
		LINK OUT_LINK {OUTPORT; MULTIPLE;}
		
		FILENAME IN_FILENAME {INPORT; MULTIPLE;}
		FILENAME OUT_FILENAME {OUTPORT; MULTIPLE;}
		
		TP_PARTICLE IN_TP { INPORT; MULTIPLE; }
		TP_PARTICLE OUT_TP { OUTPORT; MULTIPLE; }
		
		GRADIENT IN_GRADIENT { INPORT; MULTIPLE; }
		GRADIENT OUT_GRADIENT { OUTPORT; MULTIPLE; }
		
		IN_EXCLUDE IN_INEXCLUDELIST { INPORT; MULTIPLE; }
		IN_EXCLUDE OUT_INEXCLUDELIST { OUTPORT; MULTIPLE; }
		
		SPLINE IN_SPLINEDATA { INPORT; MULTIPLE; }
		SPLINE OUT_SPLINEDATA { OUTPORT; MULTIPLE; }
	}
}
