// C4D Menu Resource

MENU M_VIEW_WINDOW
{
  SUBMENU IDS_MENU_VIEW
  {
    IDM_RENDERVIEW;
    SEPARATOR;
    IDM_UNDO_VIEW;
    IDM_REDO_VIEW;
    SEPARATOR;
    IDM_SHOWSCENEALL;
    IDM_SHOWSCENE;
    IDM_ORIGINALGROESSE;
    SEPARATOR;
    IDM_SHOWSELECTED;
    IDM_SHOWACTIVE;
    SEPARATOR;
    PLUGIN_CMD_1016007;
    IDM_NEUZEICHNEN;
  }
  SUBMENU IDS_VIEWWINDOW_PROJECTION
  {
  	SUBMENU IDS_EDITOR_NAVMODE
  	{
  		PLUGIN_CMD_440000092;
  		PLUGIN_CMD_440000093;
  		PLUGIN_CMD_440000094;
  		PLUGIN_CMD_440000095;
  	}
  
    SUBMENU IDS_EDITOR_SCAMS
    {
      IDM_EDITTOKAM;
      SEPARATOR;
      IDM_VIEWWIN_CAMERAS;
    }
    IDM_AKTUTOKAM;
    SEPARATOR;
    IDM_CENTRAL;
    IDM_PARALLEL;
    SEPARATOR;
    IDM_LEFT;
    IDM_RIGHT;
    SEPARATOR;
    IDM_FRONT;
    IDM_BACK;
    SEPARATOR;
    IDM_TOP;
    IDM_BOTTOM;
    SEPARATOR;
    SUBMENU IDS_MENU_AXONOMETRIC
    {
      IDM_ISOMETRIC;
      IDM_DIMETRIC;
      IDM_MILITARY;
      IDM_GENTLEMAN;
      IDM_BIRD;
      IDM_FROG;
    }
  }
  SUBMENU IDS_VIEWWINDOW_DISPLAY
  {
    IDM_A_GOURAUD;
    IDM_A_GOURAUD_WIREISO;
    IDM_A_QUICK;
    IDM_A_QUICK_WIREISO;
    IDM_A_FLATSHADING;
    IDM_A_FLATSHADING_WIREISO;
    IDM_A_HIDDENLINE;
    IDM_A_NOSHADING;
    SEPARATOR;
    IDM_A_WIRE;
    IDM_A_ISOBATH;
    IDM_A_BOX;
    IDM_A_SKELETON;
  }
  SUBMENU IDS_MENU_OPTIONS
  {
    SUBMENU IDS_LOD
    {
      IDM_LOD_LOW;
      IDM_LOD_MEDIUM;
      IDM_LOD_HIGH;
      SEPARATOR;
      IDM_RENDER_LOD;
    }
    SEPARATOR;
    IDM_VIEW_STEREO;
    IDM_A_USELWF;
    SEPARATOR;
    IDM_A_HQ_OPENGL;
    IDM_A_HQ_OPENGL_NOISES;
    IDM_A_HQ_OPENGL_POST_EFFECTS;
    IDM_A_HQ_OPENGL_SHADOWS;
    IDM_A_HQ_OPENGL_TRANSP;
    SEPARATOR;
    IDM_A_BACKFACE;
    PLUGIN_CMD_1016179;
    IDM_A_LAYERCOLOR;
    PLUGIN_CMD_440000101;
    IDM_A_USETAGS;
    IDM_A_TEXTURES;
    IDM_VIEW_XRAY;
    SEPARATOR;
    PLUGIN_CMD_200000031;
    IDM_DOPTIONEN;
    IDM_DOPTIONEN_ALL;
  }
  SUBMENU IDS_DISPLAYFILTER
  {
    IDM_DISPLAYFILTER;
  }
  SUBMENU IDS_EDITOR_CAMERAS
  {
    SUBMENU IDS_VIEWWINDOW_PANELS
    {
      IDM_VIEW_SINGLE;
      SEPARATOR;
      IDM_VIEW_2V;
      IDM_VIEW_2H;
      SEPARATOR;
      IDM_VIEW_2SPLIT_TOP;
      IDM_VIEW_2SPLIT_BOTTOM;
      IDM_VIEW_2SPLIT_LEFT;
      IDM_VIEW_2SPLIT_RIGHT;
      SEPARATOR;
      IDM_VIEW_4T;
      IDM_VIEW_3SPLIT_TOP;
      IDM_VIEW_3SPLIT_BOTTOM;
      IDM_VIEW_3SPLIT_LEFT;
      IDM_VIEW_3SPLIT_RIGHT;
      IDM_VIEW_4H;
      IDM_VIEW_4V;
    }
    IDM_NEWVIEW;
    IDM_VIEWTOGGLE;
    SEPARATOR;
    IDM_VIEW0;
    IDM_VIEW1;
    IDM_VIEW2;
    IDM_VIEW3;
    IDM_VIEW4;
  }
}
