// Menudefinition for M_COLORSETTINGS

MENU M_COLORSETTINGS
{
	SUBMENU IDS_PAINT_FILE
	{
	  	IDP_COLOR_ADDPRESET;
		IDP_COLOR_ADDPRESET_MULTI;
  		IDP_COLOR_OVERWRITE;
		SEPARATOR;
		IDM_CM_CLOSEWINDOW;
	}

	SUBMENU IDS_PAINT_EDIT
	{
		IDP_COLOR_COPY;
		IDP_COLOR_PASTE;
	}
}
