// Menudefinition for EDITOR_BP

MENU M_EDITOR_USER1
{
	SUBMENU IDS_EDITOR_FILE
	{
    PLUGIN_CMD_200000204;
		IDM_BEENDEN;
	}
	SUBMENU IDS_LAYOUT
	{
		IDM_CM_NEWPALETTE;
		IDM_CM_GROUPWINDOW;
		IDM_LOADPALETTE;
		IDM_CM_CUSTOMIZE;
		IDM_LOCK_LAYOUT;
		SEPARATOR;
		IDM_LOADLAYOUT;
		//IDM_RESETLAYOUT;
		IDM_SAVELAYOUT;
		IDM_SAVELAYOUTAS;
		SEPARATOR;
		PLUGIN_CMD_300000186;
		M_COFFEEMANAGER_MENUMANAGER;
		SEPARATOR;
		IDM_DEFAULT_LAYOUTS;
	}
}

MENU M_EDITOR_USER2
{
	SUBMENU IDS_EDITOR_FILE
	{
    PLUGIN_CMD_200000204;
		IDM_BEENDEN;
	}
	SUBMENU IDS_LAYOUT
	{
		IDM_CM_NEWPALETTE;
		IDM_CM_GROUPWINDOW;
		IDM_LOADPALETTE;
		IDM_CM_CUSTOMIZE;
		IDM_LOCK_LAYOUT;
		SEPARATOR;
		IDM_LOADLAYOUT;
		//IDM_RESETLAYOUT;
		IDM_SAVELAYOUT;
		IDM_SAVELAYOUTAS;
		SEPARATOR;
		PLUGIN_CMD_300000186;
		M_COFFEEMANAGER_MENUMANAGER;
		SEPARATOR;
		IDM_DEFAULT_LAYOUTS;
	}
}

MENU M_EDITOR_USER3
{
	SUBMENU IDS_EDITOR_FILE
	{
    PLUGIN_CMD_200000204;
		IDM_BEENDEN;
	}
	SUBMENU IDS_LAYOUT
	{
		IDM_CM_NEWPALETTE;
		IDM_CM_GROUPWINDOW;
		IDM_LOADPALETTE;
		IDM_CM_CUSTOMIZE;
		IDM_LOCK_LAYOUT;
		SEPARATOR;
		IDM_LOADLAYOUT;
		//IDM_RESETLAYOUT;
		IDM_SAVELAYOUT;
		IDM_SAVELAYOUTAS;
		SEPARATOR;
		PLUGIN_CMD_300000186;
		M_COFFEEMANAGER_MENUMANAGER;
		SEPARATOR;
		IDM_DEFAULT_LAYOUTS;
	}
}

MENU M_EDITOR_USER4
{
	SUBMENU IDS_EDITOR_FILE
	{
    PLUGIN_CMD_200000204;
		IDM_BEENDEN;
	}
	SUBMENU IDS_LAYOUT
	{
		IDM_CM_NEWPALETTE;
		IDM_CM_GROUPWINDOW;
		IDM_LOADPALETTE;
		IDM_CM_CUSTOMIZE;
		IDM_LOCK_LAYOUT;
		SEPARATOR;
		IDM_LOADLAYOUT;
		//IDM_RESETLAYOUT;
		IDM_SAVELAYOUT;
		IDM_SAVELAYOUTAS;
		SEPARATOR;
		PLUGIN_CMD_300000186;
		M_COFFEEMANAGER_MENUMANAGER;
		SEPARATOR;
		IDM_DEFAULT_LAYOUTS;
	}
}

MENU M_EDITOR_USER5
{
	SUBMENU IDS_EDITOR_FILE
	{
    PLUGIN_CMD_200000204;
		IDM_BEENDEN;
	}
	SUBMENU IDS_LAYOUT
	{
		IDM_CM_NEWPALETTE;
		IDM_CM_GROUPWINDOW;
		IDM_LOADPALETTE;
		IDM_CM_CUSTOMIZE;
		IDM_LOCK_LAYOUT;
		SEPARATOR;
		IDM_LOADLAYOUT;
		//IDM_RESETLAYOUT;
		IDM_SAVELAYOUT;
		IDM_SAVELAYOUTAS;
		SEPARATOR;
		PLUGIN_CMD_300000186;
		M_COFFEEMANAGER_MENUMANAGER;
		SEPARATOR;
		IDM_DEFAULT_LAYOUTS;
	}
}
