// C4D Menu Resource

MENU M_CONSOLE
{
  SUBMENU IDS_OUTWINDOW_FILE
  {
    IDM_CLEARCONSOLE;
    SEPARATOR;
    PLUGIN_CMD_1001083;
  }
  SUBMENU IDS_EDITOR_PLUGINS
  {
    IDM_RELOAD_PLUGINS;
    IDM_EXECUTE_LAST;
  }
}
