// C4D-DialogResource
DIALOG IDD_SERVERINFO
{
  NAME IDS_DIALOG; CENTER_V; CENTER_H; 
  
  GROUP IDC_STATIC
  {
    NAME IDS_STATIC; ALIGN_TOP; SCALE_H; 
    BORDERSTYLE BORDER_NONE; BORDERSIZE 4, 4, 4, 4; 
    COLUMNS 1;
    
    GROUP IDC_STATIC
    {
      NAME IDS_STATIC6; ALIGN_TOP; SCALE_H; 
      BORDERSTYLE BORDER_NONE; BORDERSIZE 0, 0, 0, 0; 
      COLUMNS 2;
      
      STATICTEXT IDC_STATIC { NAME IDS_STATIC1; CENTER_V; ALIGN_LEFT; }
      EDITTEXT IDC_SERVERINFO1
      { CENTER_V; SCALE_H; SIZE 70, 0; }
      STATICTEXT IDC_STATIC { NAME IDS_STATIC2; CENTER_V; ALIGN_LEFT; }
      EDITTEXT IDC_SERVERINFO2
      { CENTER_V; SCALE_H; SIZE 70, 0; }
      STATICTEXT IDC_STATIC { NAME IDS_STATIC3; CENTER_V; ALIGN_LEFT; }
      EDITTEXT IDC_SERVERINFO3
      { CENTER_V; SCALE_H; SIZE 70, 0; }
      STATICTEXT IDC_STATIC { NAME IDS_STATIC4; CENTER_V; ALIGN_LEFT; }
      EDITTEXT IDC_SERVERINFO4
      { CENTER_V; SCALE_H; SIZE 70, 0; }
      STATICTEXT IDC_STATIC { NAME IDS_STATIC5; CENTER_V; ALIGN_LEFT; }
      EDITTEXT IDC_SERVERINFO5
      { CENTER_V; SCALE_H; SIZE 70, 0; }
    }
    DLGGROUP { OK; CANCEL; }
  }
}