// C4D-DialogResource
DIALOG IDD_LICENSESERVER_SETUP
{
  NAME IDS_DIALOG; CENTER_V; CENTER_H; 
  
  GROUP IDC_STATIC
  {
    NAME IDS_STATIC2; ALIGN_TOP; SCALE_H; 
    BORDERSTYLE BORDER_NONE; BORDERSIZE 0, 0, 0, 0; 
    COLUMNS 2;
    
    STATICTEXT IDC_STATIC { NAME IDS_STATIC3; CENTER_V; ALIGN_LEFT; }
    EDITTEXT IDC_SETUP_LICSERVER_SERVER_EDIT
    { CENTER_V; SCALE_H; SIZE 70, 0; }
    STATICTEXT IDC_STATIC { NAME IDS_STATIC4; CENTER_V; ALIGN_LEFT; }
    EDITTEXT IDC_SETUP_LICSERVER_PORT_EDIT
    { CENTER_V; SCALE_H; SIZE 70, 0; }
  }
  BUTTON IDC_SETUP_LICSERVER_FILE_BTN { NAME IDS_SETUP_LICSERVER_FILE; ALIGN_TOP; ALIGN_LEFT; }
  DLGGROUP { OK; CANCEL; }
}