enum
{
	// string table definitions
	IDS_TEXMAN = 10000,

	IDS_TEXMAN_MENU_EDIT,
	IDS_TEXMAN_SELECTALL,
	IDS_TEXMAN_DESELECTALL,
	IDS_TEXMAN_SELECTALLMISSING,
	IDS_TEXMAN_SELECTALL_ACTIVE,
	IDS_TEXMAN_SHOWSELECTED,
	IDS_TEXMAN_INVERTSELECTION,
	IDS_TEXMAN_TOOL_TOLOCAL,
	IDS_TEXMAN_TOOL_TOGLOBAL,
	IDS_TEXMAN_RELINK_TEXTURES,
	IDS_TEXMAN_RELINK_FILESELECT,
	IDS_TEXMAN_RELINK_SEARCH_TXT,
	IDS_TEXMAN_REPLACE_TEXTURE,
	IDS_TEXMAN_REPLACE_FILESELECT,

	IDS_TEXMAN_MENU_VIEW,
	IDS_TEXMAN_SEARCHBAR,
	IDS_TEXMAN_STATUS,
	IDS_TEXMAN_TEXTURE,
	IDS_TEXMAN_CURRENTPATH,
	IDS_TEXMAN_GLOBALPATH,
	IDS_TEXMAN_NEWPATH,
	IDS_TEXMAN_MATERIALS,
	IDS_TEXMAN_CHANNEL,
	IDS_TEXMAN_LAYER,
	IDS_TEXMAN_UNKNOWN,

	IDS_TEXMAN_FILTER,
	IDS_TEXMAN_FILTER_MODE_0,
	IDS_TEXMAN_FILTER_MODE_1,
	IDS_TEXMAN_FILTER_MODE_2,
	IDS_TEXMAN_FILTER_MODE_3,
	IDS_TEXMAN_FILTER_MODE_4,
	IDS_TEXMAN_FILTER_MODE_5,
	IDS_TEXMAN_FILTER_MODE_6,

	IDS_TEXMAN_REPLACEINALL,
	IDS_TEXMAN_REPLACEINDIRECTORY,
	IDS_TEXMAN_REPLACEINFILENAME,

	IDS_TEXMAN_REPLACE_LABEL,
	IDS_TEXMAN_WITH_LABEL,
	IDS_TEXMAN_REPLACE_CMD,

	IDS_TEXMAN_NOLAYER,

	IDS_TEXMAN_INFO_TEXTURES,
	IDS_TEXMAN_INFO_MISSING,
	IDS_TEXMAN_INFO_SELECTED,
	IDS_TEXMAN_INFO_ERROR,

	// layout
	ID_TEXMAN_GROUP,

	ID_TEXMAN_STATUS,
	ID_TEXMAN_UNKNOWN,

	ID_TEXMAN_BUTTONS,
	ID_TEXMAN_UPDATE,
	ID_TEXMAN_EDITMODESTRING,

	ID_TEXMAN_GL_BUTTONS,

	ID_TEXMAN_TEXTUREPREVIEW,
	ID_TEXMAN_REPLACE_LABEL,
	ID_TEXMAN_REPLACE_CLEAR,
	ID_TEXMAN_REPLACE_STRING,
	ID_TEXMAN_WITH_LABEL,
	ID_TEXMAN_WITH_CLEAR,
	ID_TEXMAN_WITH_STRING,
	ID_TEXMAN_REPLACE_CMD,
	ID_TEXMAN_STRINGGROUP,

	ID_TEXMAN_FILTER_MODE,

	ID_TEXMAN_FILTER_MODE_0,
	ID_TEXMAN_FILTER_MODE_1,
	ID_TEXMAN_FILTER_MODE_2,
	ID_TEXMAN_FILTER_MODE_3,
	ID_TEXMAN_FILTER_MODE_4,
	ID_TEXMAN_FILTER_MODE_5,
	ID_TEXMAN_FILTER_MODE_6 ,

	ID_TEXMAN_TREE,
	ID_TEXMAN_REPLACEMODE,

	ID_TEXMAN_REPLACEINALL,
	ID_TEXMAN_REPLACEINDIRECTORY,
	ID_TEXMAN_REPLACEINFILENAME,
	// these 2 blocks (up and below) contain together
	ID_TEXMAN_REGEXP_REPLACEINALL,
	ID_TEXMAN_REGEXP_REPLACEINDIRECTORY,
	ID_TEXMAN_REGEXP_REPLACEINFILENAME,

	ID_TEXMAN_TABGROUP,
	ID_TEXMAN_VIEWMODE_TEXTURES,

	// MENU
	ID_TEXMAN_MENU_EDIT,
	ID_TEXMAN_INFO,
	ID_TEXMAN_ERRORS,

	ID_TEXMAN_PREVIEWMATERIALS,

	// COMMANDS
	ID_TEXMAN_MENU_VIEW,

	ID_TEXMAN_FILTERGROUP,
	ID_TEXMAN_FILTER,
	ID_TEXMAN_FILTER_CLEAR,
	ID_TEXMAN_FILTERSTRING,
	ID_TEXMAN_FILTER_BAR,

	ID_TEXMAN_TREE_VIEW_GUI,

	ID_TEXMAN_TREE_GROUP,
	ID_TEXMAN_BOTTOM_GROUP,
	ID_TEXMAN_REPLACE_GROUP,

	SEA_REFRESH,
	SEA_NAME,
	SEA_RESORT,
	SEA_SELECT,

	IDS_TEXMAN_NO_BITMAP,

	IDS_TEXMAN_POP_SHOW_IN_FINDEREXPLORER,
	IDS_TEXMAN_POP_OPEN_IN_FINDEREXPLORER,
	IDS_TEXMAN_POP_OPEN_IN_PICTUREVIEWER,

	IDS_TEXMAN_CLEAR_TEXTURES,

	_DUMMY_ELEMENT_
};
