CONTAINER prefshoudini
{
	NAME prefshoudini;
	GROUP PREFS_HOUDINI_MAIN_GROUP
	{
		DEFAULT 1;
		COLUMNS 1;

		STATICTEXT PREFS_HOUDINI_ENGINE_VERSION { ANIM OFF; BORDER; }
		STATICTEXT PREFS_HOUDINI_ENGINE_INSTALLATION_PATH { ANIM OFF; BORDER; }
		STATICTEXT PREFS_HOUDINI_ENGINE_INSTALLATION_STATUS { ANIM OFF; BORDER; }
		STATICTEXT PREFS_HOUDINI_ENGINE_LICENSE_TYPE { ANIM OFF; BORDER; }
		STATICTEXT PREFS_HOUDINI_ENGINE_STATUS { ANIM OFF; BORDER; }
		STATICTEXT PREFS_HOUDINI_ENGINE_API_VERSION { ANIM OFF; BORDER; }
		BUTTON PREFS_HOUDINI_ENGINE_GET_INSTALLER {}
	}
}
