CONTAINER Fdwg
{
	NAME Fdwg;

	INCLUDE Fbase;

	GROUP DWGFILTER_GROUP
	{
	  UNITSCALE DWGFILTER_SCALE { }
	  LONG DWGFILTER_CURVE_SUBDIVISION_FACTOR { MIN 1; }
		BOOL DWGFILTER_KEEP_IGES { }
  }
}
