CONTAINER FCollada14Import
{
	NAME FCollada14Import;

	INCLUDE Fbase;

	GROUP COLLADA_IMPORT_GROUP
	{
		//UNITSCALE COLLADA_IMPORT_SCALE { }
		LONG COLLADA_IMPORT_SPLINE_SUBDIVISION_FACTOR { MIN 1; }
		BOOL COLLADA_IMPORT_2D_GEOMETRY { }
		BOOL COLLADA_IMPORT_ANIMATION { }
		BOOL COLLADA_IMPORT_FORCE_TRANSPARENCY_OPAQUE_MODE_TO_RGB_ZERO  { }
	}
}
