// C4D-DialogResource

DIALOG DLG_TEXTUREMAP
{
	NAME	STR_TITLE;
	
	GROUP
	{
		COLUMNS 1;
		BORDERSIZE 8,8,8,8;
		
		STATICTEXT { SIZE -256, -1; }
		GROUP GADGET_TEXTUREMAP_PREVIEWGROUP
		{
			CENTER_H;
		}
		
		GROUP
		{
			COLUMNS 2;
			FIT_H;
			
			STATICTEXT { ALIGN_RIGHT; NAME STR_TEXNAME; }
			BUTTON GADGET_TEXTUREMAP_NAME { NAME STR_PRENAME; }

			STATICTEXT { ALIGN_RIGHT; NAME STR_DIRECTION; }
			COMBOBOX GADGET_TEXTUREMAP_DIRECTION_POPUP { CHILDS { 0, STR_E1; 1, STR_E2; 2, STR_E3; 3, STR_E4;}}		// Subid für Popupeinträge!

			STATICTEXT { ALIGN_RIGHT; NAME STR_DEPTH; }
			EDITSLIDER GADGET_TEXTUREMAP_SLIDER_DEPTH { SCALE_H; }

			STATICTEXT { ALIGN_RIGHT; NAME STR_MID; }
			EDITSLIDER GADGET_TEXTUREMAP_SLIDER_MID { SCALE_H; }
		}
	

		STATICTEXT { NAME STR_EMPTY; }
		CHECKBOX GADGET_TEXTUREMAP_TEXTURE_MODE { NAME STR_TEXTURE_MODE; }
		CHECKBOX GADGET_TEXTUREMAP_DOCUMENT_PREVIEW { NAME STR_PREVIEW; }
		STATICTEXT { NAME STR_EMPTY; }
  }
  
  DLGGROUP { OK;CANCEL; }
}