// C4D-DialogResource

DIALOG DLG_NOISE
{
	NAME	STR_TITLE;
	
	GROUP
	{
		COLUMNS 1;
		BORDERSIZE 8,8,8,8;
		
		STATICTEXT { SIZE -256, -1; }
		GROUP GADGET_NOISE_PREVIEWGROUP
		{
			CENTER_H;
		}
	
		GROUP
		{
			COLUMNS 2;
			FIT_H;
			
			STATICTEXT { ALIGN_RIGHT; NAME STR_LEVEL; }
			EDITSLIDER GADGET_NOISE_SLIDER_LEVEL { SCALE_H; }
		}
	
		STATICTEXT { NAME STR_EMPTY; }
		CHECKBOX GADGET_NOISE_IS_MONOCHROME { NAME STR_MONOCHROME; }
		CHECKBOX GADGET_NOISE_TEXTURE_MODE { NAME STR_TEXTURE_MODE; }
		CHECKBOX GADGET_NOISE_DOCUMENT_PREVIEW { NAME STR_PREVIEW; }
		STATICTEXT { NAME STR_EMPTY; }
  }
  
  DLGGROUP { OK;CANCEL; }
}