// C4D-DialogResource

DIALOG DLG_MATRIX
{
	NAME	STR_TITLE;
	
	GROUP
	{
		COLUMNS 1;
		BORDERSIZE 8,8,8,8;
		
		STATICTEXT { SIZE -256, -1; }
		GROUP GADGET_MATRIX_PREVIEWGROUP
		{
			CENTER_H;
		}
		
		GROUP
		{
			COLUMNS 2;
			FIT_H;
			
			STATICTEXT { ALIGN_RIGHT; NAME STR_WIDTH; }
			EDITSLIDER GADGET_MATRIX_SLIDER_WIDTH { SCALE_H; }

			STATICTEXT { ALIGN_RIGHT; NAME STR_HEIGHT; }
			EDITSLIDER GADGET_MATRIX_SLIDER_HEIGHT { SCALE_H; }
		}
		
		GROUP	GADGET_MATRIX_GROUP_MATRIX	
		{
			SCALE_H;
		}
		
		GROUP
		{
			COLUMNS 2;
			FIT_H;
			
			STATICTEXT { ALIGN_RIGHT; NAME STR_ANGLE; }
			EDITSLIDER GADGET_MATRIX_SLIDER_ANGLE { SCALE_H; }

			STATICTEXT { ALIGN_RIGHT; NAME STR_MIX; }
			EDITSLIDER GADGET_MATRIX_SLIDER_MIX { SCALE_H; }
		}
	
		STATICTEXT { NAME STR_EMPTY; }
		CHECKBOX GADGET_MATRIX_SCALE_MATRIX { NAME STR_SCALE_MATRIX; }
		CHECKBOX GADGET_MATRIX_TEXTURE_MODE { NAME STR_TEXTURE_MODE; }
		CHECKBOX GADGET_MATRIX_DOCUMENT_PREVIEW { NAME STR_PREVIEW; }
		STATICTEXT { NAME STR_EMPTY; }
  }
  
  DLGGROUP { OK;CANCEL; }
}