// C4D-DialogResource

DIALOG DLG_STRUCTURES
{
	NAME	STR_TITLE;
	
	GROUP
	{
		COLUMNS 1;
		BORDERSIZE 8,8,8,8;
		
		STATICTEXT { SIZE -256, -1; }
		GROUP GADGET_STRUCTURES_PREVIEWGROUP
		{
			CENTER_H;
		}
	
		GROUP
		{
			COLUMNS 2;
			FIT_H;
			
			STATICTEXT IDS_STRUCTURES_FILTERTYP { ALIGN_RIGHT; NAME STR_FILTERTYP; }
			COMBOBOX GADGET_STRUCTURES_TYPE_POPUP
			{
			 	CHILDS
			 	{
					0, STR_POPUP_ID0;
					1, STR_POPUP_ID1;
					2, STR_POPUP_ID2;
					3, STR_POPUP_ID3;
					4, STR_POPUP_ID4;
					5, STR_POPUP_ID5;
					6, STR_POPUP_ID6;
					7, STR_POPUP_ID7;
					8, STR_POPUP_ID8;
					9, STR_POPUP_ID9;
					10, STR_POPUP_ID11;
					11, STR_POPUP_ID10;
					12, STR_POPUP_ID12;
					13, STR_POPUP_ID13;
				}
			} 

			STATICTEXT { ALIGN_RIGHT; NAME STR_ANGLE; }
			EDITSLIDER GADGET_STRUCTURES_SLIDER_ANGLE { SCALE_H; }

			STATICTEXT { ALIGN_RIGHT; NAME STR_MIX; }
			EDITSLIDER GADGET_STRUCTURES_SLIDER_MIX { SCALE_H; }
		}
	
		STATICTEXT { NAME STR_EMPTY; }
		CHECKBOX GADGET_STRUCTURES_TEXTURE_MODE { NAME STR_TEXTURE_MODE; }
		CHECKBOX GADGET_STRUCTURES_DOCUMENT_PREVIEW { NAME STR_PREVIEW; }
		STATICTEXT { NAME STR_EMPTY; }
  }
  
  DLGGROUP { OK;CANCEL; }
}