// C4D-DialogResource

DIALOG DLG_SMOOTH
{
	NAME	STR_TITLE;
	
	GROUP
	{
		COLUMNS 1;
		BORDERSIZE 8,8,8,8;
		
		STATICTEXT { SIZE -256, -1; }
		GROUP GADGET_SMOOTH_PREVIEWGROUP
		{
			CENTER_H;
		}
		
		GROUP
		{
			COLUMNS 2;
			FIT_H;
			
			STATICTEXT { ALIGN_RIGHT; NAME STR_FILTERTYP; }
			COMBOBOX GADGET_SMOOTH_SMOOTH_POPUP { CHILDS { 0, STR_1; 1, STR_2; 2, STR_3;}}		// Subid für Popupeinträge!
	
			STATICTEXT { ALIGN_RIGHT; NAME STR_MIX; }
			EDITSLIDER GADGET_SMOOTH_SLIDER_MIX { SCALE_H; }
		}
	
		STATICTEXT { NAME STR_EMPTY; }
		CHECKBOX GADGET_SMOOTH_TEXTURE_MODE { NAME STR_TEXTURE_MODE; }
		CHECKBOX GADGET_SMOOTH_DOCUMENT_PREVIEW { NAME STR_PREVIEW; }
		STATICTEXT { NAME STR_EMPTY; }
  }
  
  DLGGROUP { OK;CANCEL; }
}