// C4D-DialogResource

DIALOG DLG_EMBOSS
{
	NAME	STR_TITLE;
	
	GROUP
	{
		COLUMNS 1;
		BORDERSIZE 8,8,8,8;
		
		STATICTEXT { SIZE -256, -1; }
		GROUP GADGET_EMBOSS_PREVIEWGROUP
		{
			CENTER_H;
		}
		
		GROUP
		{
			COLUMNS 2;
			FIT_H;
			
			STATICTEXT { ALIGN_RIGHT; NAME STR_FILTERTYP; }
			COMBOBOX GADGET_EMBOSS_EMBOSS_POPUP
			{
				CHILDS 
				{
					0,	STR_E1;
					1,	STR_E2;
					2,	STR_E3;
					3,	STR_E4;
					4,	STR_E5;
				}
			}
	
			STATICTEXT { ALIGN_RIGHT; NAME STR_ANGLE; }
			EDITSLIDER GADGET_EMBOSS_SLIDER_ANGLE { SCALE_H; }

			STATICTEXT { ALIGN_RIGHT; NAME STR_MIX; }
			EDITSLIDER GADGET_EMBOSS_SLIDER_MIX { SCALE_H; }
		}
	
		STATICTEXT { NAME STR_EMPTY; }
		CHECKBOX GADGET_EMBOSS_TEXTURE_MODE { NAME STR_TEXTURE_MODE; }
		CHECKBOX GADGET_EMBOSS_DOCUMENT_PREVIEW { NAME STR_PREVIEW; }
		STATICTEXT { NAME STR_EMPTY; }
  }
  
  DLGGROUP { OK;CANCEL; }
}