// C4D-DialogResource

DIALOG DLG_DETAILS
{
	NAME	STR_TITLE;
	
	GROUP
	{
		COLUMNS 1;
		BORDERSIZE 8,8,8,8;
		
		STATICTEXT { SIZE -256, -1; }
		GROUP GADGET_DETAILS_PREVIEWGROUP
		{
			CENTER_H;
		}
	
		GROUP
		{
			COLUMNS 2;
			FIT_H;
			
			STATICTEXT { ALIGN_RIGHT; NAME STR_FILTERTYP; }
			COMBOBOX GADGET_DETAILS_TYPE_POPUP
			{
			 	CHILDS
			 	{
					0, STR_POPUP_ID0;
					1, STR_POPUP_ID1;
					2, STR_POPUP_ID2;
					3, STR_POPUP_ID3;
					4, STR_POPUP_ID4;
					5, STR_POPUP_ID5;
				}
			} 
			STATICTEXT { ALIGN_RIGHT; NAME STR_MIX; }
			EDITSLIDER GADGET_DETAILS_SLIDER_MIX { SCALE_H; }
		}
	
		STATICTEXT { NAME STR_EMPTY; }
		CHECKBOX GADGET_DETAILS_TEXTURE_MODE { NAME STR_TEXTURE_MODE; }
		CHECKBOX GADGET_DETAILS_DOCUMENT_PREVIEW { NAME STR_PREVIEW; }
		STATICTEXT { NAME STR_EMPTY; }
  }
  
  DLGGROUP { OK;CANCEL; }
}