// C4D-DialogResource

DIALOG DLG_GAMMA
{
	NAME	STR_TITLE;
	
	GROUP
	{
		COLUMNS 1;
		BORDERSIZE 8,8,8,8;
		
		STATICTEXT { SIZE -256, -1; }
		GROUP GADGET_GAMMA_PREVIEWGROUP
		{
			CENTER_H;
		}
		
		GROUP
		{
			COLUMNS 2;
			FIT_H;
			
			STATICTEXT { ALIGN_RIGHT; NAME STR_GAMMA; }
			EDITSLIDER GADGET_GAMMA_SLIDER_GAMMA { SCALE_H; }

			STATICTEXT { ALIGN_RIGHT; NAME STR_CONTRAST; }
			EDITSLIDER GADGET_GAMMA_SLIDER_CONTRAST { SCALE_H; }

			STATICTEXT { ALIGN_RIGHT; NAME STR_BRIGHTNESS; }
			EDITSLIDER GADGET_GAMMA_SLIDER_BRIGHTNESS { SCALE_H; }
		}
	
		STATICTEXT { NAME STR_EMPTY; }
		CHECKBOX GADGET_GAMMA_DYNAMIC_COLOR { NAME STR_DYNAMIC_COLOR; }
		CHECKBOX GADGET_GAMMA_DOCUMENT_PREVIEW { NAME STR_PREVIEW; }
		STATICTEXT { NAME STR_EMPTY; }
  }
  
  DLGGROUP { OK;CANCEL; }
}