// C4D-DialogResource

DIALOG DLG_HSL
{
	NAME	STR_TITLE;
	
	GROUP
	{
		COLUMNS 1;
		BORDERSIZE 8,8,8,8;
		
		STATICTEXT { SIZE -256, -1; }
		GROUP GADGET_HSL_PREVIEWGROUP
		{
			CENTER_H;
		}
		
		GROUP
		{
			COLUMNS 2;
			FIT_H;
			
			STATICTEXT { ALIGN_RIGHT; NAME STR_H; }
			EDITSLIDER GADGET_HSL_SLIDER_H { SCALE_H; }

			STATICTEXT { ALIGN_RIGHT; NAME STR_S; }
			EDITSLIDER GADGET_HSL_SLIDER_S { SCALE_H; }

			STATICTEXT { ALIGN_RIGHT; NAME STR_L; }
			EDITSLIDER GADGET_HSL_SLIDER_L { SCALE_H; }
		}
	
		STATICTEXT { NAME STR_EMPTY; }
		CHECKBOX GADGET_HSL_COLORIZE { NAME STR_COLORIZE; }
		CHECKBOX GADGET_HSL_DOCUMENT_PREVIEW { NAME STR_PREVIEW; }
		STATICTEXT { NAME STR_EMPTY; }
  }
  
  DLGGROUP { OK;CANCEL; }
}