// C4D-DialogResource

DIALOG DLG_DESPECKLE
{
	NAME	STR_TITLE;
	
	GROUP
	{
		COLUMNS 1;
		BORDERSIZE 8,8,8,8;
		
		STATICTEXT { SIZE -256, -1; }
		GROUP GADGET_DESPECKLE_PREVIEWGROUP
		{
			CENTER_H;
		}
	
		GROUP
		{
			COLUMNS 2;
			FIT_H;
			
			STATICTEXT { ALIGN_RIGHT; NAME STR_RADIUS; }
			EDITSLIDER GADGET_DESPECKLE_SLIDER_RADIUS { SCALE_H; }

			STATICTEXT { ALIGN_RIGHT; NAME STR_FEEDBACK; }
			EDITSLIDER GADGET_DESPECKLE_SLIDER_FEEDBACK { SCALE_H; }

			STATICTEXT { ALIGN_RIGHT; NAME STR_BLEND; }
			EDITSLIDER GADGET_DESPECKLE_SLIDER_BLEND { SCALE_H; }
		}
	
		STATICTEXT { NAME STR_EMPTY; }
		CHECKBOX GADGET_DESPECKLE_TEXTURE_MODE { NAME STR_TEXTURE_MODE; }
		CHECKBOX GADGET_DESPECKLE_DOCUMENT_PREVIEW { NAME STR_PREVIEW; }
		STATICTEXT { NAME STR_EMPTY; }
  }
  
  DLGGROUP { OK;CANCEL; }
}