// C4D-DialogResource

DIALOG DLG_SELECTIVE
{
	NAME	STR_TITLE;
	
	GROUP
	{
		COLUMNS 1;
		BORDERSIZE 8,8,8,8;
		
		STATICTEXT { SIZE -256, -1; }
		GROUP GADGET_SELECTIVE_PREVIEWGROUP
		{
			CENTER_H;
		}
	
		GROUP
		{
			COLUMNS 2;
			FIT_H;
			
			STATICTEXT { ALIGN_RIGHT; NAME STR_RADIUS; }
			EDITSLIDER GADGET_SELECTIVE_SLIDER_RADIUS { SCALE_H; }

			STATICTEXT { ALIGN_RIGHT; NAME STR_DELTA; }
			EDITSLIDER GADGET_SELECTIVE_SLIDER_DELTA { SCALE_H; }
		}
	
		STATICTEXT { NAME STR_EMPTY; }
		CHECKBOX GADGET_SELECTIVE_TEXTURE_MODE { NAME STR_TEXTURE_MODE; }
		CHECKBOX GADGET_SELECTIVE_DOCUMENT_PREVIEW { NAME STR_PREVIEW; }
		STATICTEXT { NAME STR_EMPTY; }
  }
  
  DLGGROUP { OK;CANCEL; }
}