// C4D-DialogResource

DIALOG DLG_WHIRL
{
	NAME	STR_TITLE;
	
	GROUP
	{
		COLUMNS 1;
		BORDERSIZE 8,8,8,8;
		
		STATICTEXT { SIZE -256, -1; }
		GROUP GADGET_WHIRL_PREVIEWGROUP
		{
			CENTER_H;
		}
		
		GROUP
		{
			COLUMNS 2;
			FIT_H;
			
			STATICTEXT { ALIGN_RIGHT; NAME STR_WHIRL; }
			EDITSLIDER GADGET_WHIRL_SLIDER_WHIRL { SCALE_H; }

			STATICTEXT { ALIGN_RIGHT; NAME STR_PINCH; }
			EDITSLIDER GADGET_WHIRL_SLIDER_PINCH { SCALE_H; }

			STATICTEXT { ALIGN_RIGHT; NAME STR_RADIUS; }
			EDITSLIDER GADGET_WHIRL_SLIDER_RADIUS { SCALE_H; }
		}
	
		STATICTEXT { NAME STR_EMPTY; }
		CHECKBOX GADGET_WHIRL_TEXTURE_MODE { NAME STR_TEXTURE_MODE; }
		CHECKBOX GADGET_WHIRL_DOCUMENT_PREVIEW { NAME STR_PREVIEW; }
		STATICTEXT { NAME STR_EMPTY; }
  }
  
  DLGGROUP { OK;CANCEL; }
}