// C4D-DialogResource

DIALOG DLG_DIFFERENCE
{
	NAME	STR_TITLE;
	
	GROUP
	{
		COLUMNS 1;
		BORDERSIZE 8,8,8,8;
		
		STATICTEXT { SIZE -256, -1; }
		GROUP GADGET_DIFFERENCE_PREVIEWGROUP
		{
			CENTER_H;
		}
		
		GROUP
		{
			COLUMNS 2;
			FIT_H;
			
			STATICTEXT { ALIGN_RIGHT; NAME STR_FILTERTYP; }
			COMBOBOX GADGET_DIFFERENCE_TYPE_POPUP
			{
			 	CHILDS
			 	{
					0, STR_POPUP_ID0;
					1, STR_POPUP_ID1;
					2, STR_POPUP_ID2;
					3, STR_POPUP_ID3;
					4, STR_POPUP_ID4;
					5, STR_POPUP_ID5;
					6, STR_POPUP_ID6;
					7, STR_POPUP_ID7;
					8, STR_POPUP_ID8;
				}
			} 

			STATICTEXT { ALIGN_RIGHT; NAME STR_ANGLE; }
			EDITSLIDER GADGET_DIFFERENCE_SLIDER_ANGLE { SCALE_H; }

			STATICTEXT { ALIGN_RIGHT; NAME STR_MIX; }
			EDITSLIDER GADGET_DIFFERENCE_SLIDER_MIX { SCALE_H; }
		}
	
		STATICTEXT { NAME STR_EMPTY; }
		CHECKBOX GADGET_DIFFERENCE_TEXTURE_MODE { NAME STR_TEXTURE_MODE; }
		CHECKBOX GADGET_DIFFERENCE_DOCUMENT_PREVIEW { NAME STR_PREVIEW; }
		STATICTEXT { NAME STR_EMPTY; }
  }
  
  DLGGROUP { OK;CANCEL; }
}