// C4D-DialogResource

DIALOG DLG_UNSHARP
{
	NAME	STR_TITLE;
	
	GROUP
	{
		COLUMNS 1;
		BORDERSIZE 8,8,8,8;
		
		STATICTEXT { SIZE -256, -1; }
		GROUP GADGET_UNSHARP_PREVIEWGROUP
		{
			CENTER_H;
		}
		
		GROUP
		{
			COLUMNS 2;
			FIT_H;
			
			STATICTEXT { ALIGN_RIGHT; NAME STR_RADIUS; }
			EDITSLIDER GADGET_UNSHARP_SLIDER_RADIUS { SCALE_H; }

			STATICTEXT { ALIGN_RIGHT; NAME STR_AMOUNT; }
			EDITSLIDER GADGET_UNSHARP_SLIDER_AMOUNT { SCALE_H; }

			STATICTEXT { ALIGN_RIGHT; NAME STR_THRESHOLD; }
			EDITSLIDER GADGET_UNSHARP_SLIDER_THRESHOLD { SCALE_H; }
		}
	
		STATICTEXT { NAME STR_EMPTY; }
		CHECKBOX GADGET_UNSHARP_TEXTURE_MODE { NAME STR_TEXTURE_MODE; }
		CHECKBOX GADGET_UNSHARP_DOCUMENT_PREVIEW { NAME STR_PREVIEW; }
		STATICTEXT { NAME STR_EMPTY; }
  }
  
  DLGGROUP { OK;CANCEL; }
}