// C4D-DialogResource

DIALOG DLG_LEVELS
{
	NAME	STR_TITLE;
	
	GROUP
	{
		COLUMNS 1;
		BORDERSIZE 8,8,8,8;
		
		STATICTEXT { SIZE -256, -1; }
		GROUP GADGET_LEVELS_PREVIEWGROUP
		{
			CENTER_H;
		}
		

		GROUP
		{
			COLUMNS 1;
			CENTER_H;
			
			GROUP
			{
				COLUMNS 4;
				FIT_H;
				STATICTEXT { ALIGN_RIGHT; NAME STR_INPUT_LEVELS; }
				EDITNUMBER GADGET_LEVELS_IN_MIN { SCALE_H; }
				EDITNUMBER GADGET_LEVELS_IN_GAMMA { SCALE_H; }
				EDITNUMBER GADGET_LEVELS_IN_MAX { SCALE_H; }
			}

			GROUP GADGET_LEVELS_HISTOGRAMM_GROUP
			{
				COLUMNS 1;
				CENTER_H;
			}

			GROUP
			{
				COLUMNS 3;
				FIT_H;
				
				STATICTEXT { ALIGN_RIGHT; NAME STR_OUTPUT_LEVELS; }
				EDITNUMBER GADGET_LEVELS_OUT_MIN { SCALE_H; }
				EDITNUMBER GADGET_LEVELS_OUT_MAX { SCALE_H; }
			}
		}
	
		STATICTEXT { NAME STR_EMPTY; }
		CHECKBOX GADGET_LEVELS_DOCUMENT_PREVIEW { NAME STR_PREVIEW; }
		STATICTEXT { NAME STR_EMPTY; }
  }
  
  DLGGROUP { OK;CANCEL; }
}