// C4D-DialogResource

DIALOG DLG_LENS
{
	NAME	STR_TITLE;
	
	GROUP
	{
		COLUMNS 1;
		BORDERSIZE 8,8,8,8;
		
		STATICTEXT { SIZE -256, -1; }
		GROUP GADGET_LENS_PREVIEWGROUP
		{
			CENTER_H;
		}
		
		GROUP
		{
			COLUMNS 2;
			FIT_H;
			
			STATICTEXT { ALIGN_RIGHT; NAME STR_LENS_REFRACTION; }
			EDITSLIDER GADGET_LENS_SLIDER_REFRACTION { SCALE_H; }
		}
	
		STATICTEXT { NAME STR_EMPTY; }
		CHECKBOX GADGET_LENS_TEXTURE_MODE { NAME STR_TEXTURE_MODE; }
		CHECKBOX GADGET_LENS_DOCUMENT_PREVIEW { NAME STR_PREVIEW; }
		STATICTEXT { NAME STR_EMPTY; }
  }
  
  DLGGROUP { OK;CANCEL; }
}