// C4D-DialogResource

DIALOG DLG_TEXEMBOSS
{
	NAME	STR_TITLE;
	
	GROUP
	{
		COLUMNS 1;
		BORDERSIZE 8,8,8,8;
		
		STATICTEXT { SIZE -256, -1; }
		GROUP GADGET_TEXEMBOSS_PREVIEWGROUP
		{
			CENTER_H;
		}
		
		GROUP
		{
			COLUMNS 2;
			FIT_H;
			
			STATICTEXT { ALIGN_RIGHT; NAME STR_AZIMUTH; }
			EDITSLIDER GADGET_TEXEMBOSS_SLIDER_AZIMUTH { SCALE_H; }

			STATICTEXT { ALIGN_RIGHT; NAME STR_ELEVATION; }
			EDITSLIDER GADGET_TEXEMBOSS_SLIDER_ELEVATION { SCALE_H; }

			STATICTEXT { ALIGN_RIGHT; NAME STR_DEPTH; }
			EDITSLIDER GADGET_TEXEMBOSS_SLIDER_DEPTH { SCALE_H; }

			CHECKBOX GADGET_TEXEMBOSS_USE_TEXTURE { NAME STR_USE_TEXTURE; }
			BUTTON GADGET_TEXEMBOSS_NAME { NAME STR_PRENAME; }
		}
	
		STATICTEXT { NAME STR_EMPTY; }
		CHECKBOX GADGET_TEXEMBOSS_TEXTURE_MODE { NAME STR_TEXTURE_MODE; }
		CHECKBOX GADGET_TEXEMBOSS_DOCUMENT_PREVIEW { NAME STR_PREVIEW; }
		STATICTEXT { NAME STR_EMPTY; }
  }
  
  DLGGROUP { OK;CANCEL; }
}