// C4D-DialogResource

DIALOG DLG_SPREAD
{
	NAME	STR_TITLE;
	
	GROUP
	{
		COLUMNS 1;
		BORDERSIZE 8,8,8,8;
		
		STATICTEXT { SIZE -256, -1; }
		GROUP GADGET_SPREAD_PREVIEWGROUP
		{
			CENTER_H;
		}
	
		GROUP
		{
			COLUMNS 2;
			FIT_H;
			
			STATICTEXT { ALIGN_RIGHT; NAME STR_XAXIS; }
			EDITSLIDER GADGET_SPREAD_SLIDER_XAXIS { SCALE_H; }
	
			STATICTEXT { ALIGN_RIGHT; NAME STR_YAXIS; }
			EDITSLIDER GADGET_SPREAD_SLIDER_YAXIS { SCALE_H; }
		}
	
		STATICTEXT { NAME STR_EMPTY; }
		CHECKBOX GADGET_SPREAD_SYNC_SLIDERS { NAME STR_SYNC_SLIDERS; }
		CHECKBOX GADGET_SPREAD_TEXTURE_MODE { NAME STR_TEXTURE_MODE; }
		CHECKBOX GADGET_SPREAD_DOCUMENT_PREVIEW { NAME STR_PREVIEW; }
		STATICTEXT { NAME STR_EMPTY; }
  }
  
  DLGGROUP { OK;CANCEL; }
}