// C4D-DialogResource

DIALOG DLG_PIXELIZE
{
	NAME	STR_TITLE;
	
	GROUP
	{
		COLUMNS 1;
		BORDERSIZE 8,8,8,8;
		
		STATICTEXT { SIZE -256, -1; }

		GROUP GADGET_PIXELIZE_PREVIEWGROUP
		{
			CENTER_H;
		}
		
		GROUP
		{
			COLUMNS 2;
			FIT_H;
			
			STATICTEXT { ALIGN_RIGHT; NAME STR_PIXELIZE_PIXELSIZE; }
			EDITSLIDER GADGET_PIXELIZE_SLIDER_SIZE { SCALE_H; }
		}
	
		STATICTEXT { NAME STR_EMPTY; }
		CHECKBOX GADGET_PIXELIZE_DOCUMENT_PREVIEW { NAME STR_PREVIEW; }
		STATICTEXT { NAME STR_EMPTY; }
  }
  
  DLGGROUP { OK;CANCEL; }
}