// C4D-DialogResource

DIALOG DLG_BLUR
{
	NAME	STR_TITLE;
	
	GROUP
	{
		COLUMNS 1;
		BORDERSIZE 8,8,8,8;
		
		STATICTEXT { SIZE -256, -1; }
		GROUP GADGET_BLUR_PREVIEWGROUP
		{
			CENTER_H;
		}
		
		GROUP
		{
			COLUMNS 2;
			FIT_H;
			
			STATICTEXT { ALIGN_RIGHT; NAME STR_WIDTH; }
			EDITSLIDER GADGET_BLUR_SLIDER_WIDTH { SCALE_H; }

			STATICTEXT { ALIGN_RIGHT; NAME STR_HEIGHT; }
			EDITSLIDER GADGET_BLUR_SLIDER_HEIGHT { SCALE_H; }
		}
	
		STATICTEXT { NAME STR_EMPTY; }
		CHECKBOX GADGET_BLUR_SYNC_SLIDERS { NAME STR_SYNC_SLIDERS; }
		CHECKBOX GADGET_BLUR_TEXTURE_MODE { NAME STR_TEXTURE_MODE; }
		CHECKBOX GADGET_BLUR_DOCUMENT_PREVIEW { NAME STR_PREVIEW; }
		STATICTEXT { NAME STR_EMPTY; }
  }
  
  DLGGROUP { OK;CANCEL; }
}