// C4D-DialogResource

DIALOG DLG_WAVES
{
	NAME	STR_TITLE;
	
	GROUP
	{
		COLUMNS 1;
		BORDERSIZE 8,8,8,8;
		
		STATICTEXT { SIZE -256, -1; }
		GROUP GADGET_WAVES_PREVIEWGROUP
		{
			CENTER_H;
		}
	
		GROUP
		{
			COLUMNS 2;
			FIT_H;
			
			STATICTEXT { ALIGN_RIGHT; NAME STR_LENGTH; }
			EDITSLIDER GADGET_WAVES_SLIDER_LENGTH { SCALE_H; }

			STATICTEXT { ALIGN_RIGHT; NAME STR_AMPLITUDE; }
			EDITSLIDER GADGET_WAVES_SLIDER_AMPLITUDE { SCALE_H; }

			STATICTEXT { ALIGN_RIGHT; NAME STR_PHASE; }
			EDITSLIDER GADGET_WAVES_SLIDER_PHASE { SCALE_H; }

			STATICTEXT { ALIGN_RIGHT; NAME STR_REFLECTION; }
			EDITSLIDER GADGET_WAVES_SLIDER_REFLECTION { SCALE_H; }
		}
	
		STATICTEXT { NAME STR_EMPTY; }
		CHECKBOX GADGET_WAVES_ASPECT_RATIO { NAME STR_ASPECT_RATIO; }
		CHECKBOX GADGET_WAVES_TEXTURE_MODE { NAME STR_TEXTURE_MODE; }
		CHECKBOX GADGET_WAVES_DOCUMENT_PREVIEW { NAME STR_PREVIEW; }
		STATICTEXT { NAME STR_EMPTY; }
  }
  
  DLGGROUP { OK;CANCEL; }
}