// C4D-DialogResource

DIALOG DLG_OILIFY
{
	NAME	STR_TITLE;
	
	GROUP
	{
		COLUMNS 1;
		BORDERSIZE 8,8,8,8;
		
		STATICTEXT { SIZE -256, -1; }
		GROUP GADGET_OILIFY_PREVIEWGROUP
		{
			CENTER_H;
		}
		
		GROUP
		{
			COLUMNS 2;
			FIT_H;
			
			STATICTEXT { ALIGN_RIGHT; NAME STR_OILIFY_MASK_SIZE; }
			EDITSLIDER GADGET_OILIFY_SLIDER_MASK_SIZE { SCALE_H; }
		}
	
		STATICTEXT { NAME STR_EMPTY; }
		CHECKBOX GADGET_OILIFY_TEXTURE_MODE { NAME STR_TEXTURE_MODE; }
		CHECKBOX GADGET_OILIFY_DOCUMENT_PREVIEW { NAME STR_PREVIEW; }
		STATICTEXT { NAME STR_EMPTY; }
  }
  
  DLGGROUP { OK;CANCEL; }
}