CONTAINER Faiexport
{
	NAME Faiexport;
	INCLUDE Fbase;

	GROUP TUAIEXPORT_MAIN_GROUP
	{
		COLUMNS 2;
		SEPARATOR TUAIEXPORT_GROUP_BASIC {}
		STATICTEXT {JOINENDSCALE;}	
		LONG TUAIEXPORT_OUTPUTSIZE
		{
			CYCLE
			{
				TUAIEXPORT_OUTPUTSIZE_RENDER;
				TUAIEXPORT_OUTPUTSIZE_EDITOR;
				TUAIEXPORT_OUTPUTSIZE_CUSTOM;
			}
			
			DEFAULT TUAIEXPORT_OUTPUTSIZE_RENDER;
		}
		STATICTEXT{}
		LONG TUAIEXPORT_OUTPUTSIZE_WIDTH	{ MIN 8; DEFAULT 640;}
		STATICTEXT{}
		LONG TUAIEXPORT_OUTPUTSIZE_HEIGHT	{ MIN 8; DEFAULT 480;}
		STATICTEXT{}

		LONG TUAIEXPORT_ZSORT
		{
			CYCLE
			{
				TUAIEXPORT_ZSORT_BACK;
				TUAIEXPORT_ZSORT_CENTER;
				TUAIEXPORT_ZSORT_FRONT;
			}
			DEFAULT TUAIEXPORT_ZSORT_BACK;
		}
		STATICTEXT{}
		
		REAL TUAIEXPORT_SCALE	{ UNIT PERCENT; MIN 0.0; MAX 1000; DEFAULT 100;}
		STATICTEXT{}
		BOOL TUAIEXPORT_LAYERS {DEFAULT 1;}
		STATICTEXT{}
		
		SEPARATOR TUAIEXPORT_GROUP_LINES { }
		STATICTEXT {JOINENDSCALE;}	
		
		BOOL TUAIEXPORT_EXPORTLINES {DEFAULT 1;}
		STATICTEXT{}
		
		BOOL TUAIEXPORT_LINEOPACITY {DEFAULT 1;}
		STATICTEXT{}
		BOOL TUAIEXPORT_LINETHICKNESS {DEFAULT 1;}
		STATICTEXT{}
		BOOL TUAIEXPORT_LINEPATTERNS {DEFAULT 1;}
		STATICTEXT{}
		BOOL TUAIEXPORT_LINECONNECTIONS {DEFAULT 1;}
		STATICTEXT{}
		
		SEPARATOR TUAIEXPORT_GROUP_SURFACE { }
		STATICTEXT {JOINENDSCALE;}	
		
		BOOL TUAIEXPORT_EXPORTSURFACE {DEFAULT 1;}
		STATICTEXT{}
		BOOL TUAIEXPORT_POLYSUBDIV {DEFAULT 0;}
		STATICTEXT{}
		LONG TUAIEXPORT_POLYSUBDIV_LEVEL	{ MIN 1; MAX 8; DEFAULT 2;}
		STATICTEXT{}
		BOOL TUAIEXPORT_BACKFACECULL {DEFAULT 1;}
		STATICTEXT{}
		
		BOOL TUAIEXPORT_OVERFILL {DEFAULT 1;}
		STATICTEXT{}
		
		LONG TUAIEXPORT_SHADING
		{
			CYCLE
			{
				TUAIEXPORT_SHADING_OBJECTCOL;
				TUAIEXPORT_SHADING_UNIFORM;
				TUAIEXPORT_SHADING_FACETTED;
			}
			
			DEFAULT TUAIEXPORT_SHADING_FACETTED;
		}
		STATICTEXT{}
		
		SEPARATOR TUAIEXPORT_GROUP_ANIMATION { }
		STATICTEXT {JOINENDSCALE;}	
		BOOL TUAIEXPORT_ANIMATION {}
		STATICTEXT{}

		LONG TUAIEXPORT_ANIMTYPE
		{
			CYCLE
			{
				TUAIEXPORT_ANIMTYPE_FILES;
				TUAIEXPORT_ANIMTYPE_LAYERS;
			}
			
			DEFAULT TUAIEXPORT_ANIMTYPE_FILES;
		}
		STATICTEXT{}
		LONG TUAIEXPORT_FRAMES
		{
			CYCLE
			{
				TUAIEXPORT_FRAMES_ALL;
				TUAIEXPORT_FRAMES_RENDER;
				TUAIEXPORT_FRAMES_MANUAL;
			}
			DEFAULT TUAIEXPORT_FRAMES_RENDER;
		}
		STATICTEXT{}
		BASETIME TUAIEXPORT_FRAME_START	{ DEFAULT 0;}
		STATICTEXT{}
		BASETIME TUAIEXPORT_FRAME_END	{ DEFAULT 3;}
		STATICTEXT{}
		LONG TUAIEXPORT_FRAME_RATE	{ MIN 1; DEFAULT 30;}
		STATICTEXT{}
	}
}
