CONTAINER Moutliner
{
	NAME Moutliner;
	LAYOUTVERSION 2;

	INCLUDE Obaselist;

	GROUP Obaselist
	{	
		BOOL OUTLINEMAT_PAGE_BASIC		{ HIDDEN; PAGE; PARENTMSG OUTLINEMAT_GROUP_BASIC; }
		BOOL OUTLINEMAT_PAGE_STROKE		{ HIDDEN; PAGE; PARENTMSG OUTLINEMAT_GROUP_STROKE; }
		BOOL OUTLINEMAT_PAGE_ADJUSTMENT { HIDDEN; PAGE; PARENTMSG OUTLINEMAT_GROUP_ADJUSTMENT; }
		BOOL OUTLINEMAT_PAGE_DISTORTION { HIDDEN; PAGE; PARENTMSG OUTLINEMAT_GROUP_DISTORTION; }
		BOOL OUTLINEMAT_PAGE_BRUSH		{ HIDDEN; PAGE; PARENTMSG OUTLINEMAT_GROUP_BRUSH; }
		BOOL OUTLINEMAT_PAGE_THICKNESS	{ HIDDEN; PAGE; PARENTMSG OUTLINEMAT_GROUP_THICKNESS; }
		BOOL OUTLINEMAT_PAGE_OPACITY	{ HIDDEN; PAGE; PARENTMSG OUTLINEMAT_GROUP_OPACITY; }
		BOOL OUTLINEMAT_PAGE_SCENE		{ HIDDEN; PAGE; PARENTMSG OUTLINEMAT_GROUP_SCENE; }
		BOOL OUTLINEMAT_PAGE_CLONE		{ HIDDEN; PAGE; PARENTMSG OUTLINEMAT_GROUP_CLONE; }
		BOOL OUTLINEMAT_PAGE_ANIMATE	{ HIDDEN; PAGE; PARENTMSG OUTLINEMAT_GROUP_ANIMATE; }
		BOOL OUTLINEMAT_PAGE_ASSIGN		{ HIDDEN; PAGE; PARENTMSG OUTLINEMAT_GROUP_ASSIGN; }
	}

	GROUP OUTLINEMAT_GROUP_BASIC
	{
		COLUMNS 1;

		LONG OUTLINEMAT_PRESET
		{
			HIDDEN;

			CYCLE
			{
				OUTLINEMAT_PRESET_DEFAULTS;
			}
		}
		BUTTON OUTLINEMAT_PRESET_ADD { HIDDEN; }

		BUTTON OUTLINEMAT_PRESET_LOAD { }
		BUTTON OUTLINEMAT_PRESET_SAVE { }

		LONG OUTLINEMAT_PRIORITY	{ MIN 0; MAX 10000; }
	}

	GROUP OUTLINEMAT_GROUP_LINE
	{
		DEFAULT 1;

		GROUP OUTLINEMAT_GROUP_LINE_TYPES
		{
			COLUMNS 1; DEFAULT 1;

			GROUP
			{
				COLUMNS 2;

				BOOL OUTLINEMAT_LINE_OUTLINE {}
				BOOL OUTLINEMAT_LINE_FOLD {}
				BOOL OUTLINEMAT_LINE_OVERLAPS {}
				BOOL OUTLINEMAT_LINE_CREASE {}
				BOOL OUTLINEMAT_LINE_ANGLE {}
				BOOL OUTLINEMAT_LINE_BORDER {}
				BOOL OUTLINEMAT_LINE_MATERIAL {}
				BOOL OUTLINEMAT_LINE_EDGES {}
				BOOL OUTLINEMAT_LINE_INTERSECTION {}
				BOOL OUTLINEMAT_LINE_TRI {}
				BOOL OUTLINEMAT_LINE_MOTION {}
				BOOL OUTLINEMAT_LINE_CONTOUR {}
				BOOL OUTLINEMAT_LINE_ISOPARMS {}
				BOOL OUTLINEMAT_LINE_SPLINES {}
				BOOL OUTLINEMAT_LINE_PARTICLES {}
			}
			GROUP
			{
				COLUMNS 3;

				LONG OUTLINEMAT_LINE_COMBINEMODE
				{
					HIDDEN;

					CYCLE
					{
						OUTLINEMAT_LINE_COMBINEMODE_OFF;
						OUTLINEMAT_LINE_COMBINEMODE_ALL;
						OUTLINEMAT_LINE_COMBINEMODE_EXCLUSIVE;
						OUTLINEMAT_LINE_COMBINEMODE_INCLUSIVE;
					}
				}
				STATICTEXT { DUMMY; }
				STATICTEXT { DUMMY; }
	
				SEPARATOR { }
				STATICTEXT { JOINEND; }
				STATICTEXT { JOINENDSCALE; }

				LONG OUTLINEMAT_LINE_OUTLINE_SHOW_OBJS
				{
					CYCLE
					{
						OUTLINEMAT_LINE_OUTLINE_SHOW_OBJS_OBJECT;
						OUTLINEMAT_LINE_OUTLINE_SHOW_OBJS_WITHCHILD;
						OUTLINEMAT_LINE_OUTLINE_SHOW_OBJS_HIERARCHY;
						OUTLINEMAT_LINE_OUTLINE_SHOW_OBJS_SCENE;
						OUTLINEMAT_LINE_OUTLINE_SHOW_OBJS_OBJECTS;
					}
				}
				BOOL OUTLINEMAT_LINE_OUTLINE_SHOW_SELFOFF { }
				STATICTEXT { DUMMY; }

				IN_EXCLUDE  OUTLINEMAT_LINE_OUTLINE_SHOW_OBJECTS
				{
					NUM_FLAGS 1; INIT_STATE 1; SEND_SELCHNGMSG 1;
					IMAGE_01_ON 1009316; IMAGE_01_OFF 1009320;
					ACCEPT { Obase; };
				}
				STATICTEXT { JOINEND; }
				STATICTEXT { JOINENDSCALE; }

				LINK OUTLINEMAT_LINE_DEFAULT_MAT_V { ACCEPT { 1011014; } }
				STATICTEXT { JOINEND; }
				STATICTEXT { JOINENDSCALE; }

				LINK OUTLINEMAT_LINE_DEFAULT_MAT_H { ACCEPT { 1011014; } }
				STATICTEXT { JOINEND; }
				STATICTEXT { JOINENDSCALE; }

				LONG OUTLINEMAT_LINE_INDIVIDUALMATS
				{
					CYCLE
					{
						OUTLINEMAT_LINE_INDIVIDUALMATS_DEFAULTS;
						OUTLINEMAT_LINE_INDIVIDUALMATS_VISIBLE;
						OUTLINEMAT_LINE_INDIVIDUALMATS_HIDDEN;
						OUTLINEMAT_LINE_INDIVIDUALMATS_BOTH;
					}
				}
				STATICTEXT { DUMMY; }
				STATICTEXT { DUMMY; }
			}
		}
			
		GROUP OUTLINEMAT_GROUP_LINE_OUTLINE
		{
			COLUMNS 1; DEFAULT 1; HIDDEN;

			GROUP
			{
				COLUMNS 2;

				LONG OUTLINEMAT_LINE_OUTLINE_OUTLINE_OBJS
				{
					CYCLE
					{
						OUTLINEMAT_LINE_OUTLINE_SHOW_OBJS_OBJECT;
						OUTLINEMAT_LINE_OUTLINE_SHOW_OBJS_WITHCHILD;
						OUTLINEMAT_LINE_OUTLINE_SHOW_OBJS_HIERARCHY;
						OUTLINEMAT_LINE_OUTLINE_SHOW_OBJS_SCENE;
						OUTLINEMAT_LINE_OUTLINE_SHOW_OBJS_OBJECTS;
					}
				}

				BOOL OUTLINEMAT_LINE_OUTLINE_OUTLINE_SELFOFF { }
			}

			IN_EXCLUDE  OUTLINEMAT_LINE_OUTLINE_OUTLINE_OBJECTS
			{
				NUM_FLAGS 1; INIT_STATE 1; SEND_SELCHNGMSG 1;
				IMAGE_01_ON 1009316; IMAGE_01_OFF 1009320;
				ACCEPT { Obase; };
			}

			LINK OUTLINEMAT_LINE_OUTLINE_MAT_V { ACCEPT { 1011014; } }
			LINK OUTLINEMAT_LINE_OUTLINE_MAT_H { ACCEPT { 1011014; } }
		}
		
		GROUP OUTLINEMAT_GROUP_LINE_FOLD
		{		
			COLUMNS 1; DEFAULT 1; HIDDEN;
			
			LONG OUTLINEMAT_LINE_FOLDING
			{
				CYCLE
				{
					OUTLINEMAT_LINE_FOLDING_FRONTBACK;
					OUTLINEMAT_LINE_FOLDING_BACKFRONT;
					OUTLINEMAT_LINE_FOLDING_BOTH;
				}
			}

			LINK OUTLINEMAT_LINE_FOLD_MAT_V { ACCEPT { 1011014; } }
			LINK OUTLINEMAT_LINE_FOLD_MAT_H { ACCEPT { 1011014; } }
		}

		GROUP OUTLINEMAT_GROUP_LINE_OVERLAPS
		{
			COLUMNS 1; DEFAULT 1; HIDDEN;

			LINK OUTLINEMAT_LINE_OVERLAPS_MAT_V { ACCEPT { 1011014; } }
			LINK OUTLINEMAT_LINE_OVERLAPS_MAT_H { ACCEPT { 1011014; } }
		}

		GROUP OUTLINEMAT_GROUP_LINE_CREASE
		{
			COLUMNS 1; DEFAULT 1; HIDDEN;
		
			LINK OUTLINEMAT_LINE_CREASE_MAT_V { ACCEPT { 1011014; } }
			LINK OUTLINEMAT_LINE_CREASE_MAT_H { ACCEPT { 1011014; } }

			REAL OUTLINEMAT_LINE_CREASE_MINTHETA	{ UNIT DEGREE; MIN 0.0; MAX 180.0; CUSTOMGUI REALSLIDER;}
		}

		GROUP OUTLINEMAT_GROUP_LINE_ANGLE
		{
			COLUMNS 1; DEFAULT 1; HIDDEN;

			LINK OUTLINEMAT_LINE_ANGLE_MAT_V { ACCEPT { 1011014; } }
			LINK OUTLINEMAT_LINE_ANGLE_MAT_H { ACCEPT { 1011014; } }

			REAL OUTLINEMAT_LINE_ANGLE_MINTHETA	{ UNIT DEGREE; MIN 0.0; MAX 180.0; CUSTOMGUI REALSLIDER;}
			REAL OUTLINEMAT_LINE_ANGLE_MAXTHETA	{ UNIT DEGREE; MIN 0.0; MAX 180.0; CUSTOMGUI REALSLIDER;}
		}

		GROUP OUTLINEMAT_GROUP_LINE_BORDER
		{
			COLUMNS 1; DEFAULT 1; HIDDEN;

			LINK OUTLINEMAT_LINE_BORDER_MAT_V { ACCEPT { 1011014; } }
			LINK OUTLINEMAT_LINE_BORDER_MAT_H { ACCEPT { 1011014; } }
		}

		GROUP OUTLINEMAT_GROUP_LINE_MATERIAL
		{
			COLUMNS 1; DEFAULT 1; HIDDEN;

			LINK OUTLINEMAT_LINE_MATERIAL_MAT_V { ACCEPT { 1011014; } }
			LINK OUTLINEMAT_LINE_MATERIAL_MAT_H { ACCEPT { 1011014; } }

			GROUP
			{
				COLUMNS 2;

				LONG OUTLINEMAT_LINE_MATERIAL_MODE
				{
					CYCLE
					{
						OUTLINEMAT_LINE_MATERIAL_MODE_INCLUDE;
						OUTLINEMAT_LINE_MATERIAL_MODE_EXCLUDE;
					}
				}

				BOOL OUTLINEMAT_LINE_MATERIAL_COMBINE { }
			}

			IN_EXCLUDE  OUTLINEMAT_LINE_MATERIAL_TAGS
			{
				NUM_FLAGS 0; INIT_STATE 0; SEND_SELCHNGMSG 1;
				ACCEPT { Ttexture; };
			}
		}

		GROUP OUTLINEMAT_GROUP_LINE_EDGES
		{
			COLUMNS 1; DEFAULT 1; HIDDEN;

			LINK OUTLINEMAT_LINE_EDGES_MAT_V { ACCEPT { 1011014; } }
			LINK OUTLINEMAT_LINE_EDGES_MAT_H { ACCEPT { 1011014; } }
		}

		GROUP OUTLINEMAT_GROUP_LINE_INTERSECTION
		{
			DEFAULT 1; HIDDEN;

			LINK OUTLINEMAT_LINE_INTERSECTION_MAT_V { ACCEPT { 1011014; } }
			LINK OUTLINEMAT_LINE_INTERSECTION_MAT_H { ACCEPT { 1011014; } }

			GROUP
			{
				COLUMNS 2;

				LONG OUTLINEMAT_LINE_INTERESTION_OBJS
				{
					CYCLE
					{
						OUTLINEMAT_LINE_INTERESTION_OBJS_OBJECT;
						OUTLINEMAT_LINE_INTERESTION_OBJS_WITHCHILD;
						OUTLINEMAT_LINE_INTERESTION_OBJS_HIERARCHY;
						OUTLINEMAT_LINE_INTERESTION_OBJS_SCENE;
						OUTLINEMAT_LINE_INTERESTION_OBJS_OBJECTS;
					}
				}

				BOOL OUTLINEMAT_LINE_INTERESTION_SELF { }
			}

			IN_EXCLUDE  OUTLINEMAT_LINE_INTERESTION_OBJS_LIST
			{
				NUM_FLAGS 1; INIT_STATE 1; SEND_SELCHNGMSG 1;
				IMAGE_01_ON 1009316; IMAGE_01_OFF 1009320;
				ACCEPT { Obase; };
			}
		}

		GROUP OUTLINEMAT_GROUP_LINE_ZDELTA
		{
			DEFAULT 1; HIDDEN;

			LINK OUTLINEMAT_LINE_ZDELTA_MAT_V { ACCEPT { 1011014; } }
			LINK OUTLINEMAT_LINE_ZDELTA_MAT_H { ACCEPT { 1011014; } }

			GROUP
			{
				COLUMNS 2;

				REAL OUTLINEMAT_LINE_ZDELTA_MINZ	{ UNIT METER; MIN 0.0; MAX 100.0;}
				REAL OUTLINEMAT_LINE_ZDELTA_MAXZ	{ UNIT METER; MIN 0.0; }

				BOOL OUTLINEMAT_LINE_ZDELTA_INVERT {}
				BOOL OUTLINEMAT_LINE_ZDELTA_SILHOUETTE {}
			}
		}

		GROUP OUTLINEMAT_GROUP_LINE_TRI
		{
			COLUMNS 1; DEFAULT 1; HIDDEN;

			LINK OUTLINEMAT_LINE_TRI_MAT_V { ACCEPT { 1011014; } }
			LINK OUTLINEMAT_LINE_TRI_MAT_H { ACCEPT { 1011014; } }
		}

		GROUP OUTLINEMAT_GROUP_LINE_MOTION
		{
			COLUMNS 1; DEFAULT 1; HIDDEN;
		
			LINK OUTLINEMAT_LINE_MOTION_MAT_V { ACCEPT { 1011014; } }
			LINK OUTLINEMAT_LINE_MOTION_MAT_H { ACCEPT { 1011014; } }

			LONG OUTLINEMAT_LINE_MOTION_COUNT	{ MIN 1; MAX 1000; }

			SEPARATOR { }

			GROUP
			{
				COLUMNS 3;

				LONG OUTLINEMAT_LINE_MOTION_LINE_MODE
				{
					DEFAULT 1;

					CYCLE
					{
						OUTLINEMAT_LINE_MOTION_LINE_MODE_VELOCITY;
						OUTLINEMAT_LINE_MOTION_LINE_MODE_TRAIL;
					}
				}

				BOOL OUTLINEMAT_LINE_MOTION_TRAIL_LIMIT {}
				BASETIME OUTLINEMAT_LINE_MOTION_TRAIL	 { MIN 0; }

				REAL OUTLINEMAT_LINE_MOTION_THRESHOLD	{ UNIT METER; MIN 0.0; }
				BOOL OUTLINEMAT_LINE_MOTION_THRESHOLD_FROM { }
				SEPARATOR { }
			}

			SEPARATOR { }

			GROUP
			{
				COLUMNS 3;

				BOOL OUTLINEMAT_LINE_MOTION_LINE2D {}				
				BOOL OUTLINEMAT_LINE_MOTION_OUTLINES {}
				BOOL OUTLINEMAT_LINE_MOTION_CURVE {}
			}

			GROUP
			{
				COLUMNS 2;

				REAL OUTLINEMAT_LINE_MOTION_CURVEW	{ UNIT PERCENT; MIN -100.0; MAX 100.0;}
				REAL OUTLINEMAT_LINE_MOTION_CURVEH	{ UNIT PERCENT; MIN 0.0; MAX 200.0;}
			}

			BOOL OUTLINEMAT_LINE_MOTION_SHAPE {}
			LINK OUTLINEMAT_LINE_MOTION_LINK { ACCEPT { Ospline; } }

			SEPARATOR { }

			GROUP
			{
				COLUMNS 2;
				
				REAL OUTLINEMAT_LINE_MOTION_SCALE	{ UNIT PERCENT; MIN 0.0; }
				REAL OUTLINEMAT_LINE_MOTION_SCALE_VAR	{ UNIT PERCENT; MIN 0.0; }

				REAL OUTLINEMAT_LINE_MOTION_LINEH	{ UNIT PERCENT; MIN 0.0; }
				REAL OUTLINEMAT_LINE_MOTION_LINEW	{ UNIT PERCENT; MIN 0.0; }

				REAL OUTLINEMAT_LINE_MOTION_LINEOFFSET	{ }
				REAL OUTLINEMAT_LINE_MOTION_RELLINEOFFSET	{ UNIT PERCENT; HIDDEN; }
				BOOL OUTLINEMAT_LINE_MOTION_RELOFFSET {}
			}

			SEPARATOR { }

			GROUP
			{
				COLUMNS 2;

				BOOL OUTLINEMAT_LINE_MOTION_TAPER {}
				SEPARATOR { }

				REAL OUTLINEMAT_LINE_MOTION_TAPER_ANGLE	{ UNIT PERCENT; MIN -1000.0; MAX 100.0;}
				REAL OUTLINEMAT_LINE_MOTION_TAPER_W	{ UNIT PERCENT; MIN -1000.0; MAX 100.0;}
			}

			GROUP
			{
				COLUMNS 2;
				

				BOOL OUTLINEMAT_LINE_MOTION_FADE_OPACITY {}
				REAL OUTLINEMAT_LINE_MOTION_FADE_OPACITY_STRENGTH	{ UNIT PERCENT; MIN 0.0; MAX 100.0;}

				BOOL OUTLINEMAT_LINE_MOTION_FADE_THICKNESS {}
				REAL OUTLINEMAT_LINE_MOTION_FADE_THICKNESS_STRENGTH	{ UNIT PERCENT; MIN 0.0; MAX 100.0;}
			}
		}

		GROUP OUTLINEMAT_GROUP_LINE_CONTOUR 
		{
			DEFAULT 1; HIDDEN;

			LINK OUTLINEMAT_LINE_CONTOUR_MAT_V { ACCEPT { 1011014; } }
			LINK OUTLINEMAT_LINE_CONTOUR_MAT_H { ACCEPT { 1011014; } }

			LONG OUTLINEMAT_LINE_CONTOUR_MODE
			{
				CYCLE
				{
					OUTLINEMAT_LINE_CONTOUR_MODE_ANGLE;
					OUTLINEMAT_LINE_CONTOUR_MODE_POSITION;
					OUTLINEMAT_LINE_CONTOUR_MODE_UVW;
				}
			}

			SEPARATOR { }

			LONG OUTLINEMAT_LINE_CONTOUR_ANGLE
			{
				CYCLE
				{
					OUTLINEMAT_LINE_CONTOUR_OBJECT_X;
					OUTLINEMAT_LINE_CONTOUR_OBJECT_Y;
					OUTLINEMAT_LINE_CONTOUR_OBJECT_Z;
					OUTLINEMAT_LINE_CONTOUR_WORLD_X;
					OUTLINEMAT_LINE_CONTOUR_WORLD_Y;
					OUTLINEMAT_LINE_CONTOUR_WORLD_Z;
					OUTLINEMAT_LINE_CONTOUR_VIEW_X;
					OUTLINEMAT_LINE_CONTOUR_VIEW_Y;
					OUTLINEMAT_LINE_CONTOUR_VIEW_Z;
				}
			}

			GROUP
			{
				COLUMNS 3;

				REAL OUTLINEMAT_LINE_CONTOUR_ANGLE_MIN	{ UNIT DEGREE; MIN 0.0; MAX 180.0;}
				REAL OUTLINEMAT_LINE_CONTOUR_ANGLE_MAX	{ UNIT DEGREE; MIN 0.0; MAX 180.0;}
				REAL OUTLINEMAT_LINE_CONTOUR_ANGLE_STEPS { MIN 1; MAX 10000;}
			}
			
			GROUP
			{
				COLUMNS 3;

				LONG OUTLINEMAT_LINE_CONTOUR_POSITION
				{
					DEFAULT 1; HIDDEN;

					CYCLE
					{
						OUTLINEMAT_LINE_CONTOUR_OBJECT_X;
						OUTLINEMAT_LINE_CONTOUR_OBJECT_Y;
						OUTLINEMAT_LINE_CONTOUR_OBJECT_Z;
						OUTLINEMAT_LINE_CONTOUR_WORLD_X;
						OUTLINEMAT_LINE_CONTOUR_WORLD_Y;
						OUTLINEMAT_LINE_CONTOUR_WORLD_Z;
						OUTLINEMAT_LINE_CONTOUR_VIEW_X;
						OUTLINEMAT_LINE_CONTOUR_VIEW_Y;
						OUTLINEMAT_LINE_CONTOUR_VIEW_Z;
					}
				}

				LONG OUTLINEMAT_LINE_CONTOUR_POSITION_SPACING
				{
					DEFAULT 1; HIDDEN;

					CYCLE
					{
						OUTLINEMAT_LINE_CONTOUR_POSITION_SPACING_REL;
						OUTLINEMAT_LINE_CONTOUR_POSITION_SPACING_ABS;
					}
				}

				REAL OUTLINEMAT_LINE_CONTOUR_POSITION_VAR { UNIT METER; MIN 0; }
			}

			GROUP
			{
				COLUMNS 3;

				REAL OUTLINEMAT_LINE_CONTOUR_POSITION_OFF	{ UNIT METER; HIDDEN; }
				REAL OUTLINEMAT_LINE_CONTOUR_POSITION_SPACE { UNIT METER; HIDDEN; }
			}

			GROUP
			{
				COLUMNS 3;

				REAL OUTLINEMAT_LINE_CONTOUR_POSITION_MIN	{ DEFAULT 1; HIDDEN; UNIT PERCENT; MIN 0.0; MAX 100.0;}
				REAL OUTLINEMAT_LINE_CONTOUR_POSITION_MAX	{ DEFAULT 1; HIDDEN; UNIT PERCENT; MIN 0.0; MAX 100.0;}
				REAL OUTLINEMAT_LINE_CONTOUR_POSITION_STEPS { DEFAULT 1; HIDDEN; MIN 1; MAX 10000;}
			}

			REAL OUTLINEMAT_LINE_CONTOUR_POSITION_ROT {  HIDDEN; UNIT DEGREE; MIN -180.0; MAX 180.0; CUSTOMGUI REALSLIDER; }

			LONG OUTLINEMAT_LINE_CONTOUR_UVW
			{
				DEFAULT 1; HIDDEN;

				CYCLE
				{
					OUTLINEMAT_LINE_CONTOUR_UVW_U;
					OUTLINEMAT_LINE_CONTOUR_UVW_V;
				}
			}

			GROUP
			{
				COLUMNS 3;

				REAL OUTLINEMAT_LINE_CONTOUR_UVW_MIN	{ DEFAULT 1; HIDDEN; UNIT PERCENT; MIN 0.0; MAX 100.0;}
				REAL OUTLINEMAT_LINE_CONTOUR_UVW_MAX	{ DEFAULT 1; HIDDEN; UNIT PERCENT; MIN 0.0; MAX 100.0;}
				REAL OUTLINEMAT_LINE_CONTOUR_UVW_STEPS { DEFAULT 1; HIDDEN; MIN 1; MAX 10000;}
			}
		}

		GROUP OUTLINEMAT_GROUP_LINE_ISOPARMS
		{
			COLUMNS 1; DEFAULT 1; HIDDEN;

			LINK OUTLINEMAT_LINE_ISOPARMS_MAT_V { ACCEPT { 1011014; } }
			LINK OUTLINEMAT_LINE_ISOPARMS_MAT_H { ACCEPT { 1011014; } }
		}

		GROUP OUTLINEMAT_GROUP_LINE_SPLINES
		{
			COLUMNS 1; DEFAULT 1; HIDDEN;

			LINK OUTLINEMAT_LINE_SPLINES_MAT_V { ACCEPT { 1011014; } }
			LINK OUTLINEMAT_LINE_SPLINES_MAT_H { ACCEPT { 1011014; } }
		}

		GROUP OUTLINEMAT_GROUP_LINE_PARTICLES
		{
			COLUMNS 1; DEFAULT 1; HIDDEN;

			LINK OUTLINEMAT_LINE_PARTICLES_MAT_V { ACCEPT { 1011014; } }
			LINK OUTLINEMAT_LINE_PARTICLES_MAT_H { ACCEPT { 1011014; } }

			LONG OUTLINEMAT_LINE_PARTICLES_MODE
			{
				DEFAULT 1;

				CYCLE
				{
					OUTLINEMAT_LINE_PARTICLES_MODE_VELOCITY;
					OUTLINEMAT_LINE_PARTICLES_MODE_TRAIL;
				}
			}

			GROUP
			{
				COLUMNS 2;

				BOOL OUTLINEMAT_LINE_PARTICLES_TRAIL_LIMIT {}
				BASETIME OUTLINEMAT_LINE_PARTICLES_TRAIL	 { MIN 0; }
			}

			REAL OUTLINEMAT_LINE_PARTICLES_VSCALE	{ UNIT PERCENT; MIN 0.0; MAX 1000.0;}

			LONG OUTLINEMAT_LINE_PARTICLES_DEATH
			{
				DEFAULT 1;

				CYCLE
				{
					OUTLINEMAT_LINE_PARTICLES_DEATH_REMAIN;
					OUTLINEMAT_LINE_PARTICLES_DEATH_REMOVE;
					OUTLINEMAT_LINE_PARTICLES_DEATH_RUNOUT;
					OUTLINEMAT_LINE_PARTICLES_DEATH_FADEOUT;
				}
			}

			BASETIME OUTLINEMAT_LINE_PARTICLES_FADETIME	 { MIN 0; }
		}
	}

	GROUP OUTLINEMAT_GROUP_STROKE
	{
		COLUMNS 1;

		GROUP
		{
			COLUMNS 2;

			BOOL OUTLINEMAT_MULTCONNECTION { }
			BOOL OUTLINEMAT_CLOSECONNECTION { }
		}

		SEPARATOR { LINE; }

		GROUP
		{
			COLUMNS 3;

			LONG OUTLINEMAT_CONNECTIIONZ
			{
				CYCLE
				{
					OUTLINEMAT_CONNECTIIONZ_ALL;
					OUTLINEMAT_CONNECTIIONZ_CLOSEST;
					OUTLINEMAT_CONNECTIIONZ_THRESHOLD;
					OUTLINEMAT_CONNECTIIONZ_WORLD;
				}
			}
			STATICTEXT { NEWLINE; }

			
			REAL OUTLINEMAT_STROKE_CONNECTZ	{ UNIT METER; MIN 0.0; }
			REAL OUTLINEMAT_STROKE_CONNECTW	{ UNIT METER; MIN 0.0; }
			STATICTEXT { DUMMY; }

			REAL OUTLINEMAT_JOIN_ANGLE_LIMIT { UNIT DEGREE; MIN 0.0; MAX 180.0; CUSTOMGUI REALSLIDER; }
			STATICTEXT { JOINEND; }
			STATICTEXT { DUMMY; }

			SEPARATOR { LINE; }
			STATICTEXT { JOINEND; }
			STATICTEXT { JOINENDSCALE; }

			BOOL OUTLINEMAT_FILTER_STROKES {}
			STATICTEXT { NEWLINE; }


			LONG OUTLINEMAT_FILTER_STROKE_MODE
			{
				CYCLE
				{
					OUTLINEMAT_FILTER_STROKE_MODE_PIXEL;
					OUTLINEMAT_FILTER_STROKE_MODE_OBJECT;
					OUTLINEMAT_FILTER_STROKE_MODE_OVERLAP;
				}
			}
			STATICTEXT { NEWLINE; }

			REAL OUTLINEMAT_FILTER_STROKES_MINLEN	{ MIN 0.0; }
			STATICTEXT { NEWLINE; }
			
			REAL OUTLINEMAT_FILTER_STROKES_RELATIVE	{ UNIT PERCENT; MIN 0.0; HIDDEN; }
			STATICTEXT { NEWLINE; }

			REAL OUTLINEMAT_FILTER_STROKES_OVERLAPLEN	{ UNIT PERCENT; MIN 0.0; HIDDEN; }
			REAL OUTLINEMAT_FILTER_STROKES_OVERLAPDIST	{ UNIT PERCENT; MIN 0.0; HIDDEN; }
			STATICTEXT { NEWLINE; }

			SEPARATOR { LINE; }
			STATICTEXT { JOINEND; }
			STATICTEXT { JOINENDSCALE; }

			LONG OUTLINEMAT_START
			{
				CYCLE
				{
					OUTLINEMAT_START_SCREEN;
					OUTLINEMAT_START_OBJECT;
					OUTLINEMAT_START_RANDOM;
					OUTLINEMAT_START_MESH;
					OUTLINEMAT_START_LEFTMOST;
					OUTLINEMAT_START_TOPMOST;
					OUTLINEMAT_START_RIGHTMOST;
					OUTLINEMAT_START_BOTTOMMOST;
					OUTLINEMAT_START_OUTMOST;
					OUTLINEMAT_START_INMOST;
				}
			}
			BOOL OUTLINEMAT_TIME_COHERENCE { }
			STATICTEXT { DUMMY; }

			REAL OUTLINEMAT_START_ANGLE { UNIT DEGREE; MIN 0.0; MAX 360.0; CUSTOMGUI REALSLIDER; }
			STATICTEXT { JOINEND; }
			STATICTEXT { DUMMY; }

			SEPARATOR { LINE; }
			STATICTEXT { JOINEND; }
			STATICTEXT { JOINENDSCALE; }

			LONG OUTLINEMAT_DIRECTION
			{
				CYCLE
				{
					OUTLINEMAT_DIRECTION_CLOCKWISE;
					OUTLINEMAT_DIRECTION_ANTICLOCKWISE;
					OUTLINEMAT_DIRECTION_LEFT;
					OUTLINEMAT_DIRECTION_RIGHT;
					OUTLINEMAT_DIRECTION_UPWARDS;
					OUTLINEMAT_DIRECTION_DOWN;
				}
			}
			STATICTEXT { NEWLINE; }

			SEPARATOR { LINE; }
			STATICTEXT { JOINEND; }
			STATICTEXT { JOINENDSCALE; }

			LONG OUTLINEMAT_END
			{
				CYCLE
				{
					OUTLINEMAT_END_OFF;
					OUTLINEMAT_END_LENGTH;
					OUTLINEMAT_END_ANGLE;
					OUTLINEMAT_END_JOINT;
				}
			}
			BOOL OUTLINEMAT_SPACE_COHERENCE { }
			STATICTEXT { JOINENDSCALE; }

			REAL OUTLINEMAT_END_MAXLENGTH { MIN 0.0; }
			REAL OUTLINEMAT_END_MAXLENGTHVAR { MIN 0.0; }
			STATICTEXT { NEWLINE; }

			REAL OUTLINEMAT_END_MAXANGLE { UNIT DEGREE; MIN 0.0; MAX 180.0; }
			REAL OUTLINEMAT_END_MAXANGLEVAR { UNIT DEGREE; MIN 0.0; MAX 180.0; }
			STATICTEXT { NEWLINE; }

			SEPARATOR { LINE; }
			STATICTEXT { JOINEND; }
			STATICTEXT { JOINENDSCALE; }

			LONG OUTLINEMAT_LINESTART
			{
				CYCLE
				{
					OUTLINEMAT_LINESTARTEND_ROUNDED;
					OUTLINEMAT_LINESTARTEND_FLAT;
					OUTLINEMAT_LINESTARTEND_SQUARE;
					OUTLINEMAT_LINESTARTEND_LINEAR;
					OUTLINEMAT_LINESTARTEND_ARROW;
					OUTLINEMAT_LINESTARTEND_CUSTOM;
				}
			} 
			STATICTEXT { NEWLINE; }

			REAL OUTLINEMAT_STARTCAP_WIDTH	{ UNIT PERCENT; MIN 0.0; }
			REAL OUTLINEMAT_STARTCAP_HEIGHT	{ UNIT PERCENT; MIN 0.0; }
			STATICTEXT { NEWLINE; }

			SHADERLINK OUTLINEMAT_STARTCAP_TEXTURE_LINK { }
			STATICTEXT { JOINEND; }
			STATICTEXT { DUMMY; }

			LONG OUTLINEMAT_LINEEND
			{
				CYCLE
				{
					OUTLINEMAT_LINESTARTEND_ROUNDED;
					OUTLINEMAT_LINESTARTEND_FLAT;
					OUTLINEMAT_LINESTARTEND_SQUARE;
					OUTLINEMAT_LINESTARTEND_LINEAR;
					OUTLINEMAT_LINESTARTEND_ARROW;
					OUTLINEMAT_LINESTARTEND_CUSTOM;
				}
			} 
			STATICTEXT { NEWLINE; }

			REAL OUTLINEMAT_ENDCAP_WIDTH	{ UNIT PERCENT; MIN 0.0; }
			REAL OUTLINEMAT_ENDCAP_HEIGHT	{ UNIT PERCENT; MIN 0.0; }
			STATICTEXT { DUMMY; }

			SHADERLINK OUTLINEMAT_ENDCAP_TEXTURE_LINK { }
			STATICTEXT { JOINEND; }
			STATICTEXT { DUMMY; }

			SEPARATOR { LINE; }
			STATICTEXT { JOINEND; }
			STATICTEXT { JOINENDSCALE; }

			LONG OUTLINEMAT_JOINT
			{
				CYCLE
				{
					OUTLINEMAT_JOINT_MITER;
					OUTLINEMAT_JOINT_BEVEL;
					OUTLINEMAT_JOINT_ROUND;
				}
			}  
			STATICTEXT { NEWLINE; }

			REAL OUTLINEMAT_JOINT_MITER_LIMIT	{ UNIT DEGREE; MIN 1.0; MAX 180.0; CUSTOMGUI REALSLIDER; }
			STATICTEXT { JOINEND; }
			STATICTEXT { DUMMY; }

			SEPARATOR { LINE; }
			STATICTEXT { JOINEND; }
			STATICTEXT { JOINENDSCALE; }

			BOOL OUTLINEMAT_PATTERN {}
			STATICTEXT { NEWLINE; }

			LONG OUTLINEMAT_PATTERN_PRESET
			{
				CYCLE
				{
					OUTLINEMAT_PATTERN_SOLID;
					OUTLINEMAT_PATTERN_DASHED;
					OUTLINEMAT_PATTERN_DOTTED;
					OUTLINEMAT_PATTERN_CENTER;
					OUTLINEMAT_PATTERN_HIDDEN;
					OUTLINEMAT_PATTERN_PHANTOM;
					OUTLINEMAT_PATTERN_DASHDOT;
					OUTLINEMAT_PATTERN_BORDER;
					OUTLINEMAT_PATTERN_DIVIDE;
					OUTLINEMAT_PATTERN_CUSTOM;
				}
			} 
			BUTTON OUTLINEMAT_PATTERN_EDIT { }
			STATICTEXT { DUMMY; }

			REAL OUTLINEMAT_PATTERN_OFFSET { UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; }
			STATICTEXT { JOINEND; }
			STATICTEXT { DUMMY; }

			REAL OUTLINEMAT_PATTERN_SCALE { UNIT PERCENT; MIN 0.0; MAX 1000.0; CUSTOMGUI REALSLIDER; }
			STATICTEXT { JOINEND; }
			STATICTEXT { DUMMY; }

		}
		GROUP
		{
			COLUMNS 1;
			BITMAPBUTTON OUTLINEMAT_PATTERN_PRESET_PREVIEW { BORDER; }
		}
	}
	
	GROUP OUTLINEMAT_GROUP_ADJUSTMENT
	{
		COLUMNS 1;
		
		GROUP OUTLINEMAT_GROUP_ADJUSTMENT_STROKE
		{
			COLUMNS 1; DEFAULT 1;

			BOOL OUTLINEMAT_ADJUSTMENT_STROKE_RESIZE { }

			GROUP
			{
				COLUMNS 2;

				REAL OUTLINEMAT_ADJUSTMENT_STROKESTART { UNIT PERCENT; MIN 0; MAX 100; }
				REAL OUTLINEMAT_ADJUSTMENT_STROKESTART_VAR { UNIT PERCENT; MIN 0; MAX 100; }

				REAL OUTLINEMAT_ADJUSTMENT_STROKEEND { UNIT PERCENT; MIN 0; MAX 100;  }
				REAL OUTLINEMAT_ADJUSTMENT_STROKEEND_VAR { UNIT PERCENT; MIN 0; MAX 100; }
			}

			BOOL OUTLINEMAT_ADJUSTMENT_STROKE_RECALC { }
		}

		GROUP OUTLINEMAT_GROUP_ADJUSTMENT_HSV
		{
			DEFAULT 1; COLUMNS 3;

			REAL OUTLINEMAT_ADJUSTMENT_HSV_H	{ UNIT PERCENT; MIN 0; MAX 100; }
			REAL OUTLINEMAT_ADJUSTMENT_HSV_S	{ UNIT PERCENT; MIN 0; MAX 100; }
			REAL OUTLINEMAT_ADJUSTMENT_HSV_V	{ UNIT PERCENT; MIN 0; MAX 100; }
		}

		GROUP OUTLINEMAT_GROUP_ADJUSTMENT_OFFSET
		{
			COLUMNS 2; DEFAULT 1;

			REAL OUTLINEMAT_OFFSET_START { }
			REAL OUTLINEMAT_OFFSET_START_VAR { UNIT PERCENT; MIN 0; MAX 100; }

			REAL OUTLINEMAT_OFFSET_END { }
			REAL OUTLINEMAT_OFFSET_END_VAR { UNIT PERCENT; MIN 0; MAX 100; }

			REAL OUTLINEMAT_OFFSET_X { }
			REAL OUTLINEMAT_OFFSET_X_VAR { UNIT PERCENT; MIN 0; MAX 100; }

			REAL OUTLINEMAT_OFFSET_Y { }
			REAL OUTLINEMAT_OFFSET_Y_VAR { UNIT PERCENT; MIN 0; MAX 100; }
		}

		GROUP OUTLINEMAT_GROUP_ADJUSTMENT_TRANSFORM
		{
			COLUMNS 2; DEFAULT 1;

			LONG OUTLINEMAT_ADJUSTMENT_TRANSFORM_PIVOT
			{
				CYCLE
				{
					OUTLINEMAT_ADJUSTMENT_TRANSFORM_PIVOT_START;
					OUTLINEMAT_ADJUSTMENT_TRANSFORM_PIVOT_END;
					OUTLINEMAT_ADJUSTMENT_TRANSFORM_PIVOT_CENTER;
					OUTLINEMAT_ADJUSTMENT_TRANSFORM_PIVOT_OBJECT;
				}
			}
			STATICTEXT { DUMMY; }

			REAL OUTLINEMAT_SCALE_X { UNIT PERCENT; }
			REAL OUTLINEMAT_SCALE_X_VAR { UNIT PERCENT; MIN 0; MAX 100; }

			REAL OUTLINEMAT_SCALE_Y { UNIT PERCENT; }
			REAL OUTLINEMAT_SCALE_Y_VAR { UNIT PERCENT; MIN 0; MAX 100; }

			REAL OUTLINEMAT_ROTATE_X { UNIT DEGREE; }
			REAL OUTLINEMAT_ROTATE_X_VAR { UNIT PERCENT; MIN 0; MAX 100; }
		}

		GROUP OUTLINEMAT_GROUP_ADJUSTMENT_OVERSHOOT
		{
			COLUMNS 1; DEFAULT 1;

			BOOL OUTLINEMAT_OVERSHOOT_RELATIVE { }

			GROUP
			{
				COLUMNS 2;

				REAL OUTLINEMAT_OVERSHOOT_START_REL { HIDDEN; UNIT PERCENT; MIN 0; MAX 100; }
				REAL OUTLINEMAT_OVERSHOOT_START { }
				REAL OUTLINEMAT_OVERSHOOT_START_VAR { UNIT PERCENT; MIN 0; MAX 100; }

				REAL OUTLINEMAT_OVERSHOOT_END_REL {  HIDDEN; UNIT PERCENT; MIN 0; MAX 100; }
				REAL OUTLINEMAT_OVERSHOOT_END { }
				REAL OUTLINEMAT_OVERSHOOT_END_VAR { UNIT PERCENT; MIN 0; MAX 100; }
			}
		}

		GROUP OUTLINEMAT_GROUP_ADJUSTMENT_REPOSITION
		{
			COLUMNS 1; DEFAULT 1;

			BOOL OUTLINEMAT_REPOSITION {}

			GROUP
			{
				LAYOUTGROUP; COLUMNS 3;
				GROUP { VECTOR OUTLINEMAT_REPOSITION_POSITION { UNIT METER;  CUSTOMGUI SUBDESCRIPTION; } }
				GROUP { VECTOR OUTLINEMAT_REPOSITION_SCALE    { STEP 0.01;   CUSTOMGUI SUBDESCRIPTION; } }
				GROUP { VECTOR OUTLINEMAT_REPOSITION_ROTATION { UNIT DEGREE; CUSTOMGUI SUBDESCRIPTION; } }
			}
		}
	}

	GROUP OUTLINEMAT_GROUP_DISTORTION
	{
		COLUMNS 3;

		BOOL OUTLINEMAT_CURVE {}
		STATICTEXT { JOINEND; }
		STATICTEXT { JOINENDSCALE; }

		LONG OUTLINEMAT_CURVE_TYPE
		{
			CYCLE
			{
				OUTLINEMAT_CURVE_TYPE_LINEAR;
				OUTLINEMAT_CURVE_TYPE_CUBIC;
				OUTLINEMAT_CURVE_TYPE_AKIMA;
				OUTLINEMAT_CURVE_TYPE_BSPLINE;
				OUTLINEMAT_CURVE_TYPE_BEZIER;
			}
		}
		STATICTEXT { NEWLINE; }

		REAL OUTLINEMAT_CURVE_SUB { MIN 0.1; }
		STATICTEXT { NEWLINE; }

		REAL OUTLINEMAT_CURVE_STRENGTH { UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; }
		STATICTEXT { JOINEND; }
		STATICTEXT { JOINENDSCALE; }

		SEPARATOR { LINE; }
		STATICTEXT { JOINEND; }
		STATICTEXT { JOINENDSCALE; }

		LONG OUTLINEMAT_CURVE_WOBBLE_FN
		{
			CYCLE
			{
				OUTLINEMAT_CURVE_WOBBLE_FN_NONE;
				OUTLINEMAT_CURVE_WOBBLE_FN_SIN;
				OUTLINEMAT_CURVE_WOBBLE_FN_NOISE;
				OUTLINEMAT_CURVE_WOBBLE_FN_SPLINE;
			}
		}
		STATICTEXT { NEWLINE; }

		REAL OUTLINEMAT_CURVE_WOBBLE_STRENGTH { MIN 0; }
		STATICTEXT { NEWLINE; }

		SEPARATOR { }
		STATICTEXT { JOINEND; }
		STATICTEXT { JOINENDSCALE; }

		LONG OUTLINEMAT_CURVE_WOBBLE_TYPE
		{
			CYCLE
			{
				OUTLINEMAT_NOISE_TYPE_BOX_NOISE;
				OUTLINEMAT_NOISE_TYPE_BLIST_TURB;
				OUTLINEMAT_NOISE_TYPE_BUYA;
				OUTLINEMAT_NOISE_TYPE_CELL_NOISE;
				OUTLINEMAT_NOISE_TYPE_CRANAL;
				OUTLINEMAT_NOISE_TYPE_DENTS;
				OUTLINEMAT_NOISE_TYPE_DISPL_TURB;
				OUTLINEMAT_NOISE_TYPE_FBM;
				OUTLINEMAT_NOISE_TYPE_HAMA;
				OUTLINEMAT_NOISE_TYPE_LUKA;
				OUTLINEMAT_NOISE_TYPE_MOD_NOISE;
				OUTLINEMAT_NOISE_TYPE_NAKI;
				OUTLINEMAT_NOISE_TYPE_NOISE;
				OUTLINEMAT_NOISE_TYPE_NUTOUS;
				OUTLINEMAT_NOISE_TYPE_OBER;
				OUTLINEMAT_NOISE_TYPE_PEZO;
				OUTLINEMAT_NOISE_TYPE_POXO;
				OUTLINEMAT_NOISE_TYPE_RANDOM;
				OUTLINEMAT_NOISE_TYPE_SEMA;
				OUTLINEMAT_NOISE_TYPE_STUPL;
				OUTLINEMAT_NOISE_TYPE_TURBULENCE;
				OUTLINEMAT_NOISE_TYPE_VL_NOISE;
				OUTLINEMAT_NOISE_TYPE_WAVY_TURB;
				OUTLINEMAT_NOISE_TYPE_CELL_VORONOI;
				OUTLINEMAT_NOISE_TYPE_DISPL_VORONOI;
				OUTLINEMAT_NOISE_TYPE_SPARSE_CONV;
				OUTLINEMAT_NOISE_TYPE_VORONOI_1;
				OUTLINEMAT_NOISE_TYPE_VORONOI_2;
				OUTLINEMAT_NOISE_TYPE_VORONOI_3;
				OUTLINEMAT_NOISE_TYPE_ZADA;
			}
		}
		STATICTEXT { NEWLINE; }

		SEPARATOR { }
		STATICTEXT { JOINEND; }
		STATICTEXT { JOINENDSCALE; }

		LONG OUTLINEMAT_CURVE_NOISE_MAPPING
		{
			CYCLE
			{
				OUTLINEMAT_CURVE_NOISE_MAPPING_LINE;
				OUTLINEMAT_CURVE_NOISE_MAPPING_SCREEN;
				OUTLINEMAT_CURVE_NOISE_MAPPING_OBJECT;
				OUTLINEMAT_CURVE_NOISE_MAPPING_WORLD;
			}
		}
		STATICTEXT { NEWLINE; }

		REAL OUTLINEMAT_CURVE_WOBBLE_NOISE_OCTAVES	{ MIN 1; MAX 20; }
		STATICTEXT { NEWLINE; }

		REAL OUTLINEMAT_CURVE_WOBBLE_SCALE	{ UNIT PERCENT; MIN 0; MAX 10000; }
		STATICTEXT { NEWLINE; }

		REAL OUTLINEMAT_CURVE_WOBBLE_ANIMSPEED	{ MIN 0; }
		STATICTEXT { NEWLINE; }

		REAL OUTLINEMAT_CURVE_WOBBLE_DETAIL		{ UNIT PERCENT; MIN 0; }
		STATICTEXT { NEWLINE; }

		SEPARATOR { LINE; }
		STATICTEXT { JOINEND; }
		STATICTEXT { JOINENDSCALE; }
			
		BOOL OUTLINEMAT_CURVE_WOBBLE_NOISE_ABS {}
		BOOL OUTLINEMAT_CURVE_WOBBLE_NOISE_INVERT {}
		STATICTEXT { DUMMY; }

		REAL OUTLINEMAT_CURVE_WOBBLE_LOW_CLIP	{ UNIT PERCENT; MIN 0; MAX 100; CUSTOMGUI REALSLIDER; }
		STATICTEXT { JOINEND; }
		STATICTEXT { JOINENDSCALE; }

		REAL OUTLINEMAT_CURVE_WOBBLE_HIGH_CLIP	{ UNIT PERCENT; MIN 0; MAX 100; CUSTOMGUI REALSLIDER; }
		STATICTEXT { JOINEND; }
		STATICTEXT { JOINENDSCALE; }

		REAL OUTLINEMAT_CURVE_WOBBLE_BRIGHTNESS	{ UNIT PERCENT; MIN -100; MAX 100; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }
		STATICTEXT { JOINEND; }
		STATICTEXT { JOINENDSCALE; }

		REAL OUTLINEMAT_CURVE_WOBBLE_CONTRAST	{ UNIT PERCENT; MIN -100; MAX 100; CUSTOMGUI REALSLIDER; }
		STATICTEXT { JOINEND; }
		STATICTEXT { JOINENDSCALE; }

		REAL OUTLINEMAT_CURVE_WOBBLE_LAMBDA { MIN 0.1; MAX 1000.0; CUSTOMGUI REALSLIDER; }
		STATICTEXT { JOINEND; }
		STATICTEXT { JOINENDSCALE; }

		SPLINE OUTLINEMAT_CURVE_WOBBLE_SPLINE
		{ 
		}

		STATICTEXT { JOINEND; }
		STATICTEXT { JOINENDSCALE; }
	}

	GROUP OUTLINEMAT_GROUP_BRUSH
	{
		COLUMNS 1;

		COLOR OUTLINEMAT_COLOR { OPEN; }

		REAL OUTLINEMAT_COLOR_BRIGHTNESS { UNIT PERCENT; MIN 0.0; MAX 10000.0; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }

		GROUP OUTLINEMAT_GROUP_COLOR_MODIFIERS
		{
			COLUMNS 2; DEFAULT 1; LAYOUTGROUP;

			GROUP
			{
				COLUMNS 1;

				BOOL OUTLINEMAT_COLOR_DISTANCE {}
				BOOL OUTLINEMAT_COLOR_POSITION {}
				BOOL OUTLINEMAT_COLOR_SCALE {}
				BOOL OUTLINEMAT_COLOR_ILLUMINATION {}
				BOOL OUTLINEMAT_COLOR_TEXTURE {}
				BOOL OUTLINEMAT_COLOR_FROMSURFACE {}
				BOOL OUTLINEMAT_COLOR_MAP {}
				BOOL OUTLINEMAT_COLOR_SCREENTEXTURE {}
			}

			GROUP
			{
				COLUMNS 1;

				BOOL OUTLINEMAT_COLOR_LENGTH {}
				BOOL OUTLINEMAT_COLOR_SLENGTH {}
				BOOL OUTLINEMAT_COLOR_FACEANGLE {}
				BOOL OUTLINEMAT_COLOR_JOINANGLE {}
				BOOL OUTLINEMAT_COLOR_SCREENANGLE {}
				BOOL OUTLINEMAT_COLOR_FROMEDGE {}
				BOOL OUTLINEMAT_COLOR_COFFEE {}
				BOOL OUTLINEMAT_COLOR_NOISE {}
			}
		}

		GROUP OUTLINEMAT_GROUP_COLOR_COFFEE
		{
			COLUMNS 2; DEFAULT 1; HIDDEN;

			LONG OUTLINEMAT_COLOR_COFFEE_OPMODE
			{
				CYCLE
				{
					OUTLINEMAT_COLOR_MODE_ADD;
					OUTLINEMAT_COLOR_MODE_SUB;
					OUTLINEMAT_COLOR_MODE_MULT;
				}
			}
			REAL OUTLINEMAT_COLOR_COFFEE_STRENGTH		{ UNIT PERCENT; MIN 0; MAX 10000; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }

			STRING OUTLINEMAT_COLOR_COFFEE_CODE { CUSTOMGUI MULTISTRING; }
			STATICTEXT { JOINENDSCALE; }

			BUTTON OUTLINEMAT_COLOR_COFFEE_CODEEDIT { }
			LONG OUTLINEMAT_COLOR_COFFEE_COMMANDS
			{
				CYCLE
				{
				}
			}
		}

		GROUP OUTLINEMAT_GROUP_COLOR_DISTANCE
		{
			COLUMNS 3; DEFAULT 1; HIDDEN;

			REAL OUTLINEMAT_COLOR_DISTANCE_STRENGTH		{ UNIT PERCENT; MIN 0; MAX 10000; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }
			STATICTEXT { JOINEND; }
			STATICTEXT { JOINENDSCALE; }

			LONG OUTLINEMAT_COLOR_DISTANCE_RANGE
			{
				CYCLE
				{
					OUTLINEMAT_MODIFIER_DISTANCE_RANGE_OBJECT;
					OUTLINEMAT_MODIFIER_DISTANCE_RANGE_CAMERA;
					OUTLINEMAT_MODIFIER_DISTANCE_RANGE_USER;
				}
			}
			LONG OUTLINEMAT_COLOR_DISTANCE_OPMODE
			{
				CYCLE
				{
					OUTLINEMAT_COLOR_MODE_ADD;
					OUTLINEMAT_COLOR_MODE_SUB;
					OUTLINEMAT_COLOR_MODE_MULT;
				}
			}
			STATICTEXT { DUMMY; }

			GRADIENT  OUTLINEMAT_COLOR_DISTANCE_SPLINE { COLOR;	ICC_BASEDOCUMENT; }
			STATICTEXT { JOINEND; }
			STATICTEXT { JOINENDSCALE; }

			REAL OUTLINEMAT_COLOR_DISTANCE_MIN	{ UNIT METER; MIN 0.0; }
			REAL OUTLINEMAT_COLOR_DISTANCE_MAX	{ UNIT METER; MIN 0.0; }
		}

		GROUP OUTLINEMAT_GROUP_COLOR_POSITION
		{
			COLUMNS 3; DEFAULT 1; HIDDEN;

			REAL OUTLINEMAT_COLOR_POSITION_STRENGTH		{ UNIT PERCENT; MIN 0; MAX 10000; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }
			STATICTEXT { JOINEND; }
			STATICTEXT { JOINENDSCALE; }

			LONG OUTLINEMAT_COLOR_POSITION_TYPE
			{
				CYCLE
				{
					OUTLINEMAT_COLOR_POSITION_TYPE_X;
					OUTLINEMAT_COLOR_POSITION_TYPE_Y;
					OUTLINEMAT_COLOR_POSITION_TYPE_Z;
				}
			}
			LONG OUTLINEMAT_COLOR_POSITION_OPMODE
			{
				CYCLE
				{
					OUTLINEMAT_COLOR_MODE_ADD;
					OUTLINEMAT_COLOR_MODE_SUB;
					OUTLINEMAT_COLOR_MODE_MULT;
				}
			}
			STATICTEXT { DUMMY; }

			REAL OUTLINEMAT_COLOR_POSITION_MIN	{ UNIT METER; MIN 0.0; }
			REAL OUTLINEMAT_COLOR_POSITION_MAX	{ UNIT METER; MIN 0.0; }
			STATICTEXT { DUMMY; }

			GRADIENT OUTLINEMAT_COLOR_POSITION_SPLINE { COLOR; ICC_BASEDOCUMENT; }
			STATICTEXT { JOINEND; }
			STATICTEXT { JOINENDSCALE; }
		}

		GROUP OUTLINEMAT_GROUP_COLOR_SCALE
		{
			COLUMNS 3; DEFAULT 1; HIDDEN;

			LONG OUTLINEMAT_COLOR_SCALE_OPMODE
			{
				CYCLE
				{
					OUTLINEMAT_COLOR_MODE_ADD;
					OUTLINEMAT_COLOR_MODE_SUB;
					OUTLINEMAT_COLOR_MODE_MULT;
				}
			}
			REAL OUTLINEMAT_COLOR_SCALE_STRENGTH		{ UNIT PERCENT; MIN 0; MAX 10000; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }
			STATICTEXT { JOINENDSCALE; }

			LONG OUTLINEMAT_COLOR_SCALE_TYPE
			{
				CYCLE
				{
					OUTLINEMAT_COLOR_SCALE_TYPE_X;
					OUTLINEMAT_COLOR_SCALE_TYPE_Y;
					OUTLINEMAT_COLOR_SCALE_TYPE_Z;
				}
			}
			LONG OUTLINEMAT_COLOR_SCALE_COORDS
			{
				CYCLE
				{
					OUTLINEMAT_COLOR_SCALE_COORDS_WORLD;
					OUTLINEMAT_COLOR_SCALE_COORDS_LOCAL;
				}
			}
			STATICTEXT { DUMMY; }

			REAL OUTLINEMAT_COLOR_SCALE_MIN	{ MIN 0.0; }
			REAL OUTLINEMAT_COLOR_SCALE_MAX	{ MIN 0.0; }
			STATICTEXT { DUMMY; }

			GRADIENT OUTLINEMAT_COLOR_SCALE_SPLINE { COLOR; ICC_BASEDOCUMENT; }
			STATICTEXT { JOINEND; }
			STATICTEXT { JOINENDSCALE; }
		}

		GROUP OUTLINEMAT_GROUP_COLOR_LENGTH
		{
			COLUMNS 3; DEFAULT 1; HIDDEN;

			REAL OUTLINEMAT_COLOR_LENGTH_STRENGTH		{ UNIT PERCENT; MIN 0; MAX 10000; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }
			STATICTEXT { JOINEND; }
			STATICTEXT { JOINENDSCALE; }

			LONG OUTLINEMAT_COLOR_LENGTH_RANGE
			{
				CYCLE
				{
					OUTLINEMAT_COLOR_LENGTH_RANGE_LINE;
					OUTLINEMAT_COLOR_LENGTH_RANGE_USER;
				}
			}
			LONG OUTLINEMAT_COLOR_LENGTH_OPMODE
			{
				CYCLE
				{
					OUTLINEMAT_COLOR_MODE_ADD;
					OUTLINEMAT_COLOR_MODE_SUB;
					OUTLINEMAT_COLOR_MODE_MULT;
				}
			}
			STATICTEXT { DUMMY; }

			REAL OUTLINEMAT_COLOR_LENGTH_MIN	{ MIN 0.0; }
			REAL OUTLINEMAT_COLOR_LENGTH_MAX	{ MIN 0.0; }
			LONG OUTLINEMAT_COLOR_LENGTH_LOOP	{ MIN 0; }

			GRADIENT OUTLINEMAT_COLOR_LENGTH_SPLINE { COLOR; ICC_BASEDOCUMENT; }
			STATICTEXT { JOINEND; }
			STATICTEXT { JOINENDSCALE; }
		}

		GROUP OUTLINEMAT_GROUP_COLOR_FACEANGLE
		{
			COLUMNS 3; DEFAULT 1; HIDDEN;

			LONG OUTLINEMAT_COLOR_FACEANGLE_OPMODE
			{
				CYCLE
				{
					OUTLINEMAT_COLOR_MODE_ADD;
					OUTLINEMAT_COLOR_MODE_SUB;
					OUTLINEMAT_COLOR_MODE_MULT;
				}
			}
			REAL OUTLINEMAT_COLOR_FACEANGLE_STRENGTH		{ UNIT PERCENT; MIN 0; MAX 10000; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }
			STATICTEXT { JOINENDSCALE; }

			GRADIENT OUTLINEMAT_COLOR_FACEANGLE_SPLINE { COLOR; ICC_BASEDOCUMENT; }
			STATICTEXT { JOINEND; }
			STATICTEXT { JOINENDSCALE; }
		}

		GROUP OUTLINEMAT_GROUP_COLOR_SLENGTH
		{
			COLUMNS 3; DEFAULT 1; HIDDEN;

			LONG OUTLINEMAT_COLOR_SLENGTH_OPMODE
			{
				CYCLE
				{
					OUTLINEMAT_COLOR_MODE_ADD;
					OUTLINEMAT_COLOR_MODE_SUB;
					OUTLINEMAT_COLOR_MODE_MULT;
				}
			}
			REAL OUTLINEMAT_COLOR_SLENGTH_STRENGTH		{ UNIT PERCENT; MIN 0; MAX 10000; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }
			STATICTEXT { JOINENDSCALE; }

			REAL OUTLINEMAT_COLOR_SLENGTH_MIN	{ MIN 0.0; }
			REAL OUTLINEMAT_COLOR_SLENGTH_MAX	{ MIN 0.0; }
			STATICTEXT { DUMMY; }

			GRADIENT OUTLINEMAT_COLOR_SLENGTH_SPLINE { COLOR; ICC_BASEDOCUMENT; }
			STATICTEXT { JOINEND; }
			STATICTEXT { JOINENDSCALE; }
		}

		GROUP OUTLINEMAT_GROUP_COLOR_JOINANGLE
		{
			COLUMNS 3; DEFAULT 1; HIDDEN;

			LONG OUTLINEMAT_COLOR_JOINANGLE_OPMODE
			{
				CYCLE
				{
					OUTLINEMAT_COLOR_MODE_ADD;
					OUTLINEMAT_COLOR_MODE_SUB;
					OUTLINEMAT_COLOR_MODE_MULT;
				}
			}
			REAL OUTLINEMAT_COLOR_JOINANGLE_STRENGTH		{ UNIT PERCENT; MIN 0; MAX 10000; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }
			STATICTEXT { JOINENDSCALE; }

			LONG OUTLINEMAT_COLOR_JOINANGLE_ENDS
			{
				CYCLE
				{
					OUTLINEMAT_JOINANGLE_ENDS_OFF;
					OUTLINEMAT_JOINANGLE_ENDS_MIN;
					OUTLINEMAT_JOINANGLE_ENDS_ZERO;
					OUTLINEMAT_JOINANGLE_ENDS_MAX;
				}
			}
			STATICTEXT { DUMMY; }
			STATICTEXT { DUMMY; }

			GRADIENT OUTLINEMAT_COLOR_JOINANGLE_SPLINE { COLOR; ICC_BASEDOCUMENT; }
			STATICTEXT { JOINEND; }
			STATICTEXT { JOINENDSCALE; }
		}

		GROUP OUTLINEMAT_GROUP_COLOR_SCREENANGLE
		{
			COLUMNS 3; DEFAULT 1; HIDDEN;

			LONG OUTLINEMAT_COLOR_SCREENANGLE_OPMODE
			{
				CYCLE
				{
					OUTLINEMAT_COLOR_MODE_ADD;
					OUTLINEMAT_COLOR_MODE_SUB;
					OUTLINEMAT_COLOR_MODE_MULT;
				}
			}
			REAL OUTLINEMAT_COLOR_SCREENANGLE_STRENGTH		{ UNIT PERCENT; MIN 0; MAX 10000; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }
			STATICTEXT { JOINENDSCALE; }
			
			GRADIENT OUTLINEMAT_COLOR_SCREENANGLE_SPLINE { COLOR; ICC_BASEDOCUMENT; }
			STATICTEXT { JOINEND; }
			STATICTEXT { JOINENDSCALE; }

			REAL OUTLINEMAT_COLOR_SCREENANGLE_ROTATE	{ UNIT DEGREE; MIN -360.0; MAX 360.0; CUSTOMGUI REALSLIDER;}
			STATICTEXT { JOINEND; }
			STATICTEXT { JOINENDSCALE; }
		}

		GROUP OUTLINEMAT_GROUP_COLOR_FROMEDGE
		{
			COLUMNS 3; DEFAULT 1; HIDDEN;

			LONG OUTLINEMAT_COLOR_FROMEDGE_OPMODE
			{
				CYCLE
				{
					OUTLINEMAT_COLOR_MODE_ADD;
					OUTLINEMAT_COLOR_MODE_SUB;
					OUTLINEMAT_COLOR_MODE_MULT;
				}
			}

			REAL OUTLINEMAT_COLOR_FROMEDGE_STRENGTH		{ UNIT PERCENT; MIN 0; MAX 10000; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }
			STATICTEXT { JOINENDSCALE; }

			GRADIENT OUTLINEMAT_COLOR_FROMEDGE_SPLINE { COLOR; ICC_BASEDOCUMENT; }
			STATICTEXT { JOINEND; }
			STATICTEXT { JOINENDSCALE; }
		}

		GROUP OUTLINEMAT_GROUP_COLOR_ILLUMINATION
		{
			COLUMNS 3; DEFAULT 1; HIDDEN;

			LONG OUTLINEMAT_COLOR_ILLUMINATION_OPMODE
			{
				CYCLE
				{
					OUTLINEMAT_COLOR_MODE_ADD;
					OUTLINEMAT_COLOR_MODE_SUB;
					OUTLINEMAT_COLOR_MODE_MULT;
				}
			}
			REAL OUTLINEMAT_COLOR_ILLUMINATION_STRENGTH		{ UNIT PERCENT; MIN 0; MAX 10000; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }
			STATICTEXT { JOINENDSCALE; }
			
			LONG OUTLINEMAT_COLOR_ILLUMINATION_USEMODE
			{
				CYCLE
				{
					OUTLINEMAT_COLOR_ILLUMINATION_USEMODE_INTENSITY;
					OUTLINEMAT_COLOR_ILLUMINATION_USEMODE_COLOR;
				}
			}
			REAL OUTLINEMAT_COLOR_ILLUMINATION_BRIGHTNESS		{ UNIT PERCENT; MIN 0.0; MAX 10000.0; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }
			STATICTEXT { JOINENDSCALE; }

			GRADIENT OUTLINEMAT_COLOR_ILLUMINATION_SPLINE { COLOR; ICC_BASEDOCUMENT; }
			STATICTEXT { JOINEND; }
			STATICTEXT { JOINENDSCALE; }

			LONG OUTLINEMAT_COLOR_ILLUMINATION_LIGHT_MODE
			{
				CYCLE
				{
					OUTLINEMAT_COLOR_ILLUMINATION_LIGHT_MODE_INCLUDE;
					OUTLINEMAT_COLOR_ILLUMINATION_LIGHT_MODE_EXCLUDE;
				}
			}

			LONG OUTLINEMAT_COLOR_ILLUMINATION_MODE
			{
				CYCLE
				{
					OUTLINEMAT_COLOR_ILLUMINATION_MODE_LIGHT;
					OUTLINEMAT_COLOR_ILLUMINATION_MODE_SHADOW;
					OUTLINEMAT_COLOR_ILLUMINATION_MODE_BOTH;
				}
			}

			BOOL OUTLINEMAT_COLOR_ILLUMINATION_INVERT {}

			IN_EXCLUDE  OUTLINEMAT_COLOR_ILLUMINATION_LIGHTS
			{
				NUM_FLAGS 0; INIT_STATE 0; SEND_SELCHNGMSG 1;
				ACCEPT { Olight; };
			}
			STATICTEXT { JOINEND; }
			STATICTEXT { JOINENDSCALE; }
		}

		GROUP OUTLINEMAT_GROUP_COLOR_TEXTURE
		{
			LAYOUTGROUP; COLUMNS 1; DEFAULT 1; HIDDEN;

			GROUP
			{
				COLUMNS 3;

				LONG OUTLINEMAT_COLOR_TEXTURE_OPMODE
				{
					CYCLE
					{
						OUTLINEMAT_BLENDMODE_NORMAL;
						OUTLINEMAT_BLENDMODE_MULTIPLY;
						OUTLINEMAT_BLENDMODE_SCREEN;
						OUTLINEMAT_BLENDMODE_DARKEN;
						OUTLINEMAT_BLENDMODE_LIGHT;
						OUTLINEMAT_BLENDMODE_DIFFERENCE;
						OUTLINEMAT_BLENDMODE_NEGATIVE;
						OUTLINEMAT_BLENDMODE_EXCLUSION;
						OUTLINEMAT_BLENDMODE_OVERLAY;
						OUTLINEMAT_BLENDMODE_HARDLIGHT;
						OUTLINEMAT_BLENDMODE_SOFTLIGHT;
						OUTLINEMAT_BLENDMODE_DODGE;
						OUTLINEMAT_BLENDMODE_BURN;
						OUTLINEMAT_BLENDMODE_REFLECT;
						OUTLINEMAT_BLENDMODE_GLOW;
						OUTLINEMAT_BLENDMODE_FREEZE;
						OUTLINEMAT_BLENDMODE_HEAT;
						OUTLINEMAT_BLENDMODE_ADD;
						OUTLINEMAT_BLENDMODE_SUB;
						OUTLINEMAT_BLENDMODE_STAMP;
						OUTLINEMAT_BLENDMODE_XOR;
						OUTLINEMAT_BLENDMODE_HUE;
						OUTLINEMAT_BLENDMODE_SATURATION;
						OUTLINEMAT_BLENDMODE_LUMINANCE;
						OUTLINEMAT_BLENDMODE_RED;
						OUTLINEMAT_BLENDMODE_GREEN;
						OUTLINEMAT_BLENDMODE_BLUE;
					}
				}

				REAL OUTLINEMAT_COLOR_TEXTURE_STRENGTH		{ UNIT PERCENT; MIN 0; MAX 10000; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }
				STATICTEXT { JOINENDSCALE; }

				SEPARATOR { }
				STATICTEXT { JOINEND; }
				STATICTEXT { JOINENDSCALE; }

				BUTTON OUTLINEMAT_COLOR_TEXTURE_LOAD { }
				BUTTON OUTLINEMAT_COLOR_TEXTURE_SAVE { }
				STATICTEXT { DUMMY; }

				SEPARATOR { }
				STATICTEXT { JOINEND; }
				STATICTEXT { JOINENDSCALE; }

				SHADERLINK OUTLINEMAT_COLOR_TEXTURE_LINK { }
				STATICTEXT { JOINEND; }
				STATICTEXT { JOINENDSCALE; }

				SHADERLINK OUTLINEMAT_COLOR_TEXTUREALPHA_LINK { }
				STATICTEXT { JOINEND; }
				STATICTEXT { JOINENDSCALE; }

				REAL OUTLINEMAT_COLOR_TEXTURE_OFFSETX { UNIT PERCENT; MIN -100.0; MAX 100.0; }
				REAL OUTLINEMAT_COLOR_TEXTURE_OFFSETY { UNIT PERCENT; MIN -100.0; MAX 100.0; }
				STATICTEXT { DUMMY; }

				REAL OUTLINEMAT_COLOR_TEXTURE_SCALEX { UNIT PERCENT; MIN 0.0; MAX 1000.0; }
				REAL OUTLINEMAT_COLOR_TEXTURE_SCALEY { UNIT PERCENT; MIN 0.0; MAX 1000.0; }
				STATICTEXT { DUMMY; }

				REAL OUTLINEMAT_COLOR_TEXTURE_SPACING { UNIT PERCENT; MIN 1.0; MAX 1000.0; }
				SEPARATOR { }
				STATICTEXT { DUMMY; }

				SEPARATOR { }
				STATICTEXT { JOINEND; }
				STATICTEXT { JOINENDSCALE; }
					
				REAL OUTLINEMAT_COLOR_TEXTURE_SCATTER_U { UNIT PERCENT; MIN 0.0; MAX 1000.0; }
				REAL OUTLINEMAT_COLOR_TEXTURE_SCATTER_V { UNIT PERCENT; MIN 0.0; MAX 1000.0; }
				STATICTEXT { DUMMY; }

				REAL OUTLINEMAT_COLOR_TEXTURE_SIZE { UNIT PERCENT; MIN 1.0; MAX 1000.0; }
				REAL OUTLINEMAT_COLOR_TEXTURE_SIZE_VAR { UNIT PERCENT; MIN 0.0; MAX 100.0; }
				STATICTEXT { DUMMY; }
					
				REAL OUTLINEMAT_COLOR_TEXTURE_ROUND { UNIT PERCENT; MIN 1.0; MAX 1000.0; }
				REAL OUTLINEMAT_COLOR_TEXTURE_ASPECT_VAR { UNIT PERCENT; MIN 0.0; MAX 100.0; }
				STATICTEXT { DUMMY; }

				REAL OUTLINEMAT_COLOR_TEXTURE_ANGLE { UNIT DEGREE; MIN 0.0; MAX 360.0; }
				REAL OUTLINEMAT_COLOR_TEXTURE_ANGLE_VAR { UNIT PERCENT; MIN 0.0; MAX 100.0; }
				STATICTEXT { DUMMY; }

				LONG OUTLINEMAT_COLOR_TEXTURE_SCATTER_COUNT { MIN 0; MAX 100; }
				REAL OUTLINEMAT_COLOR_TEXTURE_SCATTER_COUNT_VAR { UNIT PERCENT; MIN 0.0; MAX 100.0; }
				STATICTEXT { DUMMY; }

				SEPARATOR { }
				STATICTEXT { JOINEND; }
				STATICTEXT { JOINENDSCALE; }
			}
			GROUP
			{
				COLUMNS 3;
				BOOL OUTLINEMAT_COLOR_TEXTURE_ASPECT { }
				BOOL OUTLINEMAT_COLOR_TEXTURE_TILING { }
				BOOL OUTLINEMAT_COLOR_TEXTURE_BEND { }
			}
		}

		GROUP OUTLINEMAT_GROUP_COLOR_FROMSURFACE
		{
			COLUMNS 3; DEFAULT 1; HIDDEN;

			LONG OUTLINEMAT_COLOR_FROMSURFACE_OPMODE
			{
				CYCLE
				{
					OUTLINEMAT_COLOR_MODE_ADD;
					OUTLINEMAT_COLOR_MODE_SUB;
					OUTLINEMAT_COLOR_MODE_MULT;
				}
			}
			REAL OUTLINEMAT_COLOR_FROMSURFACE_STRENGTH		{ UNIT PERCENT; MIN 0; MAX 10000; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }
			STATICTEXT { JOINENDSCALE; }

			REAL OUTLINEMAT_COLOR_FROMSURFACE_BRIGHTNESS		{ UNIT PERCENT; MIN 0.0; MAX 10000.0; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }
			STATICTEXT { JOINEND; }
			STATICTEXT { JOINENDSCALE; }

			BOOL OUTLINEMAT_COLOR_FROMSURFACE_ILLUMINATION {}
			BOOL OUTLINEMAT_COLOR_FROMSURFACE_SHADOWS {}
			STATICTEXT { DUMMY; }
		}

		GROUP OUTLINEMAT_GROUP_COLOR_MAP
		{
			COLUMNS 3; DEFAULT 1; HIDDEN;

			LONG OUTLINEMAT_COLOR_MAP_OPMODE
			{
				CYCLE
				{
					OUTLINEMAT_COLOR_MODE_ADD;
					OUTLINEMAT_COLOR_MODE_SUB;
					OUTLINEMAT_COLOR_MODE_MULT;
				}
			}
			REAL OUTLINEMAT_COLOR_MAP_STRENGTH		{ UNIT PERCENT; MIN 0; MAX 10000; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }
			STATICTEXT { JOINENDSCALE; }

			SHADERLINK OUTLINEMAT_COLOR_MAP_LINK { }
			STATICTEXT { JOINEND; }
			STATICTEXT { JOINENDSCALE; }

			LONG OUTLINEMAT_COLOR_MAP_PROJECTION
			{
				CYCLE
				{
					OUTLINEMAT_MAP_PROJECTION_SPHERICAL;
					OUTLINEMAT_MAP_PROJECTION_CYLINDRICAL;
					OUTLINEMAT_MAP_PROJECTION_FLAT;
					OUTLINEMAT_MAP_PROJECTION_CUBIC;
					OUTLINEMAT_MAP_PROJECTION_FRONTAL;
					OUTLINEMAT_MAP_PROJECTION_SPATIAL;
					OUTLINEMAT_MAP_PROJECTION_UVW;
					OUTLINEMAT_MAP_PROJECTION_SHRINKWRAP;
				}
			}
			STATICTEXT { NEWLINE; }

			SEPARATOR { }
			STATICTEXT { JOINEND; }
			STATICTEXT { JOINENDSCALE; }

			REAL OUTLINEMAT_COLOR_MAP_OFFX	{ UNIT PERCENT; }
			REAL OUTLINEMAT_COLOR_MAP_OFFY	{ UNIT PERCENT; }
			STATICTEXT { DUMMY; }

			REAL OUTLINEMAT_COLOR_MAP_LENX	{ UNIT PERCENT; }
			REAL OUTLINEMAT_COLOR_MAP_LENY	{ UNIT PERCENT; }
			STATICTEXT { DUMMY; }
		}

		GROUP OUTLINEMAT_GROUP_COLOR_SCREENTEXTURE
		{
			COLUMNS 3; DEFAULT 1; HIDDEN;

			LONG OUTLINEMAT_COLOR_SCREENTEXTURE_OPMODE
			{
				CYCLE
				{
					OUTLINEMAT_COLOR_MODE_ADD;
					OUTLINEMAT_COLOR_MODE_SUB;
					OUTLINEMAT_COLOR_MODE_MULT;
				}
			}
			REAL OUTLINEMAT_COLOR_SCREENTEXTURE_STRENGTH		{ UNIT PERCENT; MIN 0; MAX 10000; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }
			STATICTEXT { JOINENDSCALE; }

			SHADERLINK OUTLINEMAT_COLOR_SCREENTEXTURE_LINK { }
			STATICTEXT { JOINEND; }
			STATICTEXT { JOINENDSCALE; }

			REAL OUTLINEMAT_COLOR_SCREENTEXTURE_OFFX	{ UNIT PERCENT; }
			REAL OUTLINEMAT_COLOR_SCREENTEXTURE_OFFY	{ UNIT PERCENT; }
			STATICTEXT { DUMMY; }

			REAL OUTLINEMAT_COLOR_SCREENTEXTURE_LENX	{ UNIT PERCENT; }
			REAL OUTLINEMAT_COLOR_SCREENTEXTURE_LENY	{ UNIT PERCENT; }
			STATICTEXT { DUMMY; }
		}

		GROUP OUTLINEMAT_GROUP_COLOR_NOISE
		{
			COLUMNS 3; DEFAULT 1; HIDDEN;

			REAL OUTLINEMAT_COLOR_NOISE_STRENGTH		{ UNIT PERCENT; MIN 0.0; MAX 10000.0; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }
			STATICTEXT { JOINEND; }
			STATICTEXT { JOINENDSCALE; }

			LONG OUTLINEMAT_COLOR_NOISE_TYPE
			{
				CYCLE
				{
					OUTLINEMAT_NOISE_TYPE_BOX_NOISE;
					OUTLINEMAT_NOISE_TYPE_BLIST_TURB;
					OUTLINEMAT_NOISE_TYPE_BUYA;
					OUTLINEMAT_NOISE_TYPE_CELL_NOISE;
					OUTLINEMAT_NOISE_TYPE_CRANAL;
					OUTLINEMAT_NOISE_TYPE_DENTS;
					OUTLINEMAT_NOISE_TYPE_DISPL_TURB;
					OUTLINEMAT_NOISE_TYPE_FBM;
					OUTLINEMAT_NOISE_TYPE_HAMA;
					OUTLINEMAT_NOISE_TYPE_LUKA;
					OUTLINEMAT_NOISE_TYPE_MOD_NOISE;
					OUTLINEMAT_NOISE_TYPE_NAKI;
					OUTLINEMAT_NOISE_TYPE_NOISE;
					OUTLINEMAT_NOISE_TYPE_NUTOUS;
					OUTLINEMAT_NOISE_TYPE_OBER;
					OUTLINEMAT_NOISE_TYPE_PEZO;
					OUTLINEMAT_NOISE_TYPE_POXO;
					OUTLINEMAT_NOISE_TYPE_RANDOM;
					OUTLINEMAT_NOISE_TYPE_SEMA;
					OUTLINEMAT_NOISE_TYPE_STUPL;
					OUTLINEMAT_NOISE_TYPE_TURBULENCE;
					OUTLINEMAT_NOISE_TYPE_VL_NOISE;
					OUTLINEMAT_NOISE_TYPE_WAVY_TURB;
					OUTLINEMAT_NOISE_TYPE_CELL_VORONOI;
					OUTLINEMAT_NOISE_TYPE_DISPL_VORONOI;
					OUTLINEMAT_NOISE_TYPE_SPARSE_CONV;
					OUTLINEMAT_NOISE_TYPE_VORONOI_1;
					OUTLINEMAT_NOISE_TYPE_VORONOI_2;
					OUTLINEMAT_NOISE_TYPE_VORONOI_3;
					OUTLINEMAT_NOISE_TYPE_ZADA;
				}
			}
			STATICTEXT { NEWLINE; }

			SEPARATOR { }
			STATICTEXT { JOINEND; }
			STATICTEXT { JOINENDSCALE; }

			LONG OUTLINEMAT_COLOR_NOISE_MAPPING
			{
				CYCLE
				{
					OUTLINEMAT_COLOR_NOISE_MAPPING_LINE1D;
					OUTLINEMAT_COLOR_NOISE_MAPPING_LINE2D;
					OUTLINEMAT_COLOR_NOISE_MAPPING_SCREEN;
					OUTLINEMAT_COLOR_NOISE_MAPPING_OBJECT;
					OUTLINEMAT_COLOR_NOISE_MAPPING_WORLD;
				}
			}
			LONG OUTLINEMAT_COLOR_NOISE_MODE
			{
				CYCLE
				{
					OUTLINEMAT_COLOR_NOISE_MODE_RGB;
					OUTLINEMAT_COLOR_NOISE_MODE_HSV;
				}
			}
			STATICTEXT { NEWLINE; }

			SEPARATOR { }
			STATICTEXT { JOINEND; }
			STATICTEXT { JOINENDSCALE; }

			REAL OUTLINEMAT_COLOR_ANIMSPEED	{ MIN 0; }
			REAL OUTLINEMAT_COLOR_R_STRENGTH		{ UNIT PERCENT; MIN 0.0; MAX 100.0; }
			REAL OUTLINEMAT_COLOR_H_STRENGTH		{ UNIT PERCENT; MIN 0.0; MAX 100.0; }
			SEPARATOR { }

			REAL OUTLINEMAT_COLOR_NOISE_OCTAVES	{ MIN 1; MAX 20; }
			REAL OUTLINEMAT_COLOR_G_STRENGTH		{ UNIT PERCENT; MIN 0.0; MAX 100.0; }
			REAL OUTLINEMAT_COLOR_S_STRENGTH		{ UNIT PERCENT; MIN 0.0; MAX 100.0; }
			SEPARATOR { }

			REAL OUTLINEMAT_COLOR_NOISE_SCALE	{ UNIT PERCENT; MIN 0; MAX 10000; }
			REAL OUTLINEMAT_COLOR_B_STRENGTH		{ UNIT PERCENT; MIN 0.0; MAX 100.0; }
			REAL OUTLINEMAT_COLOR_V_STRENGTH		{ UNIT PERCENT; MIN 0.0; MAX 100.0; }
			SEPARATOR { }

			REAL OUTLINEMAT_COLOR_NOISE_SCALE_X	{ UNIT PERCENT; MIN 0; MAX 10000; }
			REAL OUTLINEMAT_COLOR_NOISE_SCALE_Y	{ UNIT PERCENT; MIN 0; MAX 10000; }
			STATICTEXT { DUMMY; }

			REAL OUTLINEMAT_COLOR_DETAIL		{ UNIT PERCENT; MIN 0; }
			STATICTEXT { NEWLINE; }

			SEPARATOR { LINE; }
			STATICTEXT { JOINEND; }
			STATICTEXT { JOINENDSCALE; }

			REAL OUTLINEMAT_COLOR_LOW_CLIP	{ UNIT PERCENT; MIN 0; MAX 100; CUSTOMGUI REALSLIDER; }
			STATICTEXT { JOINEND; }
			STATICTEXT { JOINENDSCALE; }

			REAL OUTLINEMAT_COLOR_HIGH_CLIP	{ UNIT PERCENT; MIN 0; MAX 100; CUSTOMGUI REALSLIDER; }
			STATICTEXT { JOINEND; }
			STATICTEXT { JOINENDSCALE; }

			REAL OUTLINEMAT_COLOR_NOISE_BRIGHTNESS	{ UNIT PERCENT; MIN -100; MAX 100; CUSTOMGUI REALSLIDER; }
			STATICTEXT { JOINEND; }
			STATICTEXT { JOINENDSCALE; }

			REAL OUTLINEMAT_COLOR_CONTRAST	{ UNIT PERCENT; MIN -100; MAX 100; CUSTOMGUI REALSLIDER; }
			STATICTEXT { JOINEND; }
			STATICTEXT { JOINENDSCALE; }

			GROUP
			{
				COLUMNS 2;
				BOOL OUTLINEMAT_COLOR_NOISE_ABS {}
				BOOL OUTLINEMAT_COLOR_NOISE_INVERT {}
			}
			STATICTEXT { JOINEND; }
			STATICTEXT { JOINENDSCALE; }
		}
	}

	GROUP OUTLINEMAT_GROUP_THICKNESS
	{
		COLUMNS 1;
		
		REAL OUTLINEMAT_THICKNESS		{ MIN 0.0; MAX 10000.0; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }

		GROUP OUTLINEMAT_GROUP_THICKNESS_MODIFIERS
		{
			COLUMNS 2; DEFAULT 1; LAYOUTGROUP;

			GROUP
			{
				COLUMNS 1;

				BOOL OUTLINEMAT_THICKNESS_DISTANCE {}
				BOOL OUTLINEMAT_THICKNESS_POSITION {}
				BOOL OUTLINEMAT_THICKNESS_SCALE {}
				BOOL OUTLINEMAT_THICKNESS_ILLUMINATION {}
				BOOL OUTLINEMAT_THICKNESS_VERTEX {}
				BOOL OUTLINEMAT_THICKNESS_MAP {}
				BOOL OUTLINEMAT_THICKNESS_SCREENTEXTURE {}
			}

			GROUP
			{
				COLUMNS 1;

				BOOL OUTLINEMAT_THICKNESS_LENGTH {}
				BOOL OUTLINEMAT_THICKNESS_SLENGTH {}
				BOOL OUTLINEMAT_THICKNESS_FACEANGLE {}
				BOOL OUTLINEMAT_THICKNESS_JOINANGLE {}
				BOOL OUTLINEMAT_THICKNESS_SCREENANGLE {}
				BOOL OUTLINEMAT_THICKNESS_NOISE {}
				BOOL OUTLINEMAT_THICKNESS_COFFEE {}
			}
		}

		GROUP OUTLINEMAT_GROUP_THICKNESS_COFFEE
		{
			COLUMNS 3; DEFAULT 1; HIDDEN;

			REAL OUTLINEMAT_THICKNESS_COFFEE_STRENGTH		{ UNIT PERCENT; MIN 0; MAX 10000; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }
			STATICTEXT { JOINEND; }
			STATICTEXT { JOINENDSCALE; }

			STRING OUTLINEMAT_THICKNESS_COFFEE_CODE { CUSTOMGUI MULTISTRING; }
			STATICTEXT { JOINEND; }
			STATICTEXT { JOINENDSCALE; }

			BUTTON OUTLINEMAT_THICKNESS_COFFEE_CODEEDIT { }
			LONG OUTLINEMAT_THICKNESS_COFFEE_COMMANDS
			{
				CYCLE
				{
				}
			}
		}

		GROUP OUTLINEMAT_GROUP_THICKNESS_DISTANCE
		{
			COLUMNS 3; DEFAULT 1; HIDDEN;

			REAL OUTLINEMAT_THICKNESS_DISTANCE_STRENGTH		{ UNIT PERCENT; MIN 0; MAX 10000; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }
			STATICTEXT { JOINEND; }
			STATICTEXT { JOINENDSCALE; }

			LONG OUTLINEMAT_THICKNESS_DISTANCE_RANGE
			{
				CYCLE
				{
					OUTLINEMAT_MODIFIER_DISTANCE_RANGE_OBJECT;
					OUTLINEMAT_MODIFIER_DISTANCE_RANGE_CAMERA;
					OUTLINEMAT_MODIFIER_DISTANCE_RANGE_USER;
				}
			}
			LONG OUTLINEMAT_THICKNESS_DISTANCE_MODE
			{
				CYCLE
				{
					OUTLINEMAT_THICKNESS_DISTANCE_MODE_LINEAR;
					OUTLINEMAT_THICKNESS_DISTANCE_MODE_SPLINE;
				}
			}
			BOOL OUTLINEMAT_THICKNESS_DISTANCE_MODE_INVERT {}

			REAL OUTLINEMAT_THICKNESS_DISTANCE_MIN	{ UNIT METER; MIN 0.0; }
			REAL OUTLINEMAT_THICKNESS_DISTANCE_MAX	{ UNIT METER; MIN 0.0; }
			STATICTEXT { DUMMY; }

			SPLINE OUTLINEMAT_THICKNESS_DISTANCE_SPLINE
			{ 
			}
			STATICTEXT { JOINEND; }
			STATICTEXT { JOINENDSCALE; }
		}

		GROUP OUTLINEMAT_GROUP_THICKNESS_POSITION
		{
			COLUMNS 3; DEFAULT 1; HIDDEN;

			REAL OUTLINEMAT_THICKNESS_POSITION_STRENGTH		{ UNIT PERCENT; MIN 0; MAX 10000; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }
			STATICTEXT { JOINEND; }
			STATICTEXT { JOINENDSCALE; }

			LONG OUTLINEMAT_THICKNESS_POSITION_TYPE
			{
				CYCLE
				{
					OUTLINEMAT_THICKNESS_POSITION_TYPE_X;
					OUTLINEMAT_THICKNESS_POSITION_TYPE_Y;
					OUTLINEMAT_THICKNESS_POSITION_TYPE_Z;
				}
			}
			LONG OUTLINEMAT_THICKNESS_POSITION_MODE
			{
				CYCLE
				{
					OUTLINEMAT_THICKNESS_POSITION_MODE_LINEAR;
					OUTLINEMAT_THICKNESS_POSITION_MODE_SPLINE;
				}
			}
			BOOL OUTLINEMAT_THICKNESS_POSITION_MODE_INVERT {}

			REAL OUTLINEMAT_THICKNESS_POSITION_MIN	{ UNIT METER; MIN 0.0; }
			REAL OUTLINEMAT_THICKNESS_POSITION_MAX	{ UNIT METER; MIN 0.0; }
			STATICTEXT { DUMMY; }

			SPLINE OUTLINEMAT_THICKNESS_POSITION_SPLINE
			{ 
			}
			STATICTEXT { JOINEND; }
			STATICTEXT { JOINENDSCALE; }
		}

		GROUP OUTLINEMAT_GROUP_THICKNESS_SCALE
		{
			COLUMNS 3; DEFAULT 1; HIDDEN;

			REAL OUTLINEMAT_THICKNESS_SCALE_STRENGTH		{ UNIT PERCENT; MIN 0; MAX 10000; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }
			STATICTEXT { JOINEND; }
			STATICTEXT { JOINENDSCALE; }

			LONG OUTLINEMAT_THICKNESS_SCALE_TYPE
			{
				CYCLE
				{
					OUTLINEMAT_THICKNESS_SCALE_TYPE_X;
					OUTLINEMAT_THICKNESS_SCALE_TYPE_Y;
					OUTLINEMAT_THICKNESS_SCALE_TYPE_Z;
				}
			}
			LONG OUTLINEMAT_THICKNESS_SCALE_COORDS
			{
				CYCLE
				{
					OUTLINEMAT_THICKNESS_SCALE_COORDS_WORLD;
					OUTLINEMAT_THICKNESS_SCALE_COORDS_LOCAL;
				}
			}
			STATICTEXT { DUMMY; }

			LONG OUTLINEMAT_THICKNESS_SCALE_RANGE
			{
				CYCLE
				{
					OUTLINEMAT_THICKNESS_SCALE_RANGE_SCALE;
					OUTLINEMAT_THICKNESS_SCALE_RANGE_USER;
				}
			}
			LONG OUTLINEMAT_THICKNESS_SCALE_MODE
			{
				CYCLE
				{
					OUTLINEMAT_THICKNESS_SCALE_MODE_LINEAR;
					OUTLINEMAT_THICKNESS_SCALE_MODE_SPLINE;
				}
			}
			BOOL OUTLINEMAT_THICKNESS_SCALE_MODE_INVERT {}

			REAL OUTLINEMAT_THICKNESS_SCALE_MIN	{ MIN 0.0; }
			REAL OUTLINEMAT_THICKNESS_SCALE_MAX	{ MIN 0.0; }
			STATICTEXT { DUMMY; }

			SPLINE OUTLINEMAT_THICKNESS_SCALE_SPLINE
			{ 
			}
			STATICTEXT { JOINEND; }
			STATICTEXT { JOINENDSCALE; }
		}

		GROUP OUTLINEMAT_GROUP_THICKNESS_LENGTH
		{
			COLUMNS 3; DEFAULT 1; HIDDEN;

			REAL OUTLINEMAT_THICKNESS_LENGTH_STRENGTH		{ UNIT PERCENT; MIN 0; MAX 10000; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }
			STATICTEXT { JOINEND; }
			STATICTEXT { JOINENDSCALE; }

			LONG OUTLINEMAT_THICKNESS_LENGTH_RANGE
			{
				CYCLE
				{
					OUTLINEMAT_THICKNESS_LENGTH_RANGE_LINE;
					OUTLINEMAT_THICKNESS_LENGTH_RANGE_USER;
				}
			}
			LONG OUTLINEMAT_THICKNESS_LENGTH_MODE
			{
				CYCLE
				{
					OUTLINEMAT_THICKNESS_LENGTH_MODE_LINEAR;
					OUTLINEMAT_THICKNESS_LENGTH_MODE_SPLINE;
				}
			}
			BOOL OUTLINEMAT_THICKNESS_LENGTH_MODE_INVERT {}

			REAL OUTLINEMAT_THICKNESS_LENGTH_MIN	{ MIN 0.0; }
			REAL OUTLINEMAT_THICKNESS_LENGTH_MAX	{ MIN 0.0; }
			LONG OUTLINEMAT_THICKNESS_LENGTH_LOOP	{ MIN 0; }

			SPLINE OUTLINEMAT_THICKNESS_LENGTH_SPLINE
			{ 
			}
			STATICTEXT { JOINEND; }
			STATICTEXT { JOINENDSCALE; }
		}

		GROUP OUTLINEMAT_GROUP_THICKNESS_SLENGTH
		{
			COLUMNS 3; DEFAULT 1; HIDDEN;

			REAL OUTLINEMAT_THICKNESS_SLENGTH_STRENGTH		{ UNIT PERCENT; MIN 0; MAX 10000; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }
			STATICTEXT { JOINEND; }
			STATICTEXT { JOINENDSCALE; }

			REAL OUTLINEMAT_THICKNESS_SLENGTH_MIN	{ MIN 0.0; }
			REAL OUTLINEMAT_THICKNESS_SLENGTH_MAX	{ MIN 0.0; }
			STATICTEXT { DUMMY; }

			SPLINE OUTLINEMAT_THICKNESS_SLENGTH_SPLINE
			{ 
			}
			STATICTEXT { JOINEND; }
			STATICTEXT { JOINENDSCALE; }
		}

		GROUP OUTLINEMAT_GROUP_THICKNESS_FACEANGLE
		{
			DEFAULT 1; HIDDEN;

			REAL OUTLINEMAT_THICKNESS_FACEANGLE_STRENGTH		{ UNIT PERCENT; MIN 0; MAX 10000; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }

			SPLINE OUTLINEMAT_THICKNESS_FACEANGLE_SPLINE
			{ 
			}
		}

		GROUP OUTLINEMAT_GROUP_THICKNESS_JOINANGLE
		{
			DEFAULT 1; HIDDEN;

			REAL OUTLINEMAT_THICKNESS_JOINANGLE_STRENGTH		{ UNIT PERCENT; MIN 0; MAX 10000; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }

			LONG OUTLINEMAT_THICKNESS_JOINANGLE_ENDS
			{
				CYCLE
				{
					OUTLINEMAT_JOINANGLE_ENDS_OFF;
					OUTLINEMAT_JOINANGLE_ENDS_MIN;
					OUTLINEMAT_JOINANGLE_ENDS_ZERO;
					OUTLINEMAT_JOINANGLE_ENDS_MAX;
				}
			}

			SPLINE OUTLINEMAT_THICKNESS_JOINANGLE_SPLINE
			{ 
			}
		}

		GROUP OUTLINEMAT_GROUP_THICKNESS_SCREENANGLE
		{
			DEFAULT 1; HIDDEN;

			REAL OUTLINEMAT_THICKNESS_SCREENANGLE_STRENGTH		{ UNIT PERCENT; MIN 0; MAX 10000; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }

			SPLINE OUTLINEMAT_THICKNESS_SCREENANGLE_SPLINE
			{ 
			}

			REAL OUTLINEMAT_THICKNESS_SCREENANGLE_ROTATE	{ UNIT DEGREE; MIN -360.0; MAX 360.0; CUSTOMGUI REALSLIDER;}
		}

		GROUP OUTLINEMAT_GROUP_THICKNESS_VERTEX
		{
			DEFAULT 1; HIDDEN;
			REAL OUTLINEMAT_THICKNESS_VERTEX_STRENGTH		{ UNIT PERCENT; MIN 0; MAX 10000; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }
		}

		GROUP OUTLINEMAT_GROUP_THICKNESS_MAP
		{
			COLUMNS 3; DEFAULT 1; HIDDEN;

			REAL OUTLINEMAT_THICKNESS_MAP_STRENGTH		{ UNIT PERCENT; MIN 0; MAX 10000; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }
			STATICTEXT { JOINEND; }
			STATICTEXT { JOINENDSCALE; }

			SHADERLINK OUTLINEMAT_THICKNESS_MAP_LINK { }
			STATICTEXT { JOINEND; }
			STATICTEXT { JOINENDSCALE; }

			LONG OUTLINEMAT_THICKNESS_MAP_PROJECTION
			{
				CYCLE
				{
					OUTLINEMAT_MAP_PROJECTION_SPHERICAL;
					OUTLINEMAT_MAP_PROJECTION_CYLINDRICAL;
					OUTLINEMAT_MAP_PROJECTION_FLAT;
					OUTLINEMAT_MAP_PROJECTION_CUBIC;
					OUTLINEMAT_MAP_PROJECTION_FRONTAL;
					OUTLINEMAT_MAP_PROJECTION_SPATIAL;
					OUTLINEMAT_MAP_PROJECTION_UVW;
					OUTLINEMAT_MAP_PROJECTION_SHRINKWRAP;
				}
			}
			STATICTEXT { DUMMY; }
			STATICTEXT { DUMMY; }

			REAL OUTLINEMAT_THICKNESS_MAP_OFFX	{ UNIT PERCENT; }
			REAL OUTLINEMAT_THICKNESS_MAP_OFFY	{ UNIT PERCENT; }
			STATICTEXT { DUMMY; }

			REAL OUTLINEMAT_THICKNESS_MAP_LENX	{ UNIT PERCENT; }
			REAL OUTLINEMAT_THICKNESS_MAP_LENY	{ UNIT PERCENT; }
			STATICTEXT { DUMMY; }
		}

		GROUP OUTLINEMAT_GROUP_THICKNESS_ILLUMINATION
		{
			COLUMNS 3; DEFAULT 1; HIDDEN;

			SPLINE OUTLINEMAT_THICKNESS_ILLUMINATION_SPLINE
			{ 
			}
			STATICTEXT { JOINEND; }
			STATICTEXT { JOINENDSCALE; }

			LONG OUTLINEMAT_THICKNESS_ILLUMINATION_LIGHT_MODE
			{
				CYCLE
				{
					OUTLINEMAT_THICKNESS_ILLUMINATION_LIGHT_MODE_INCLUDE;
					OUTLINEMAT_THICKNESS_ILLUMINATION_LIGHT_MODE_EXCLUDE;
				}
			}
			LONG OUTLINEMAT_THICKNESS_ILLUMINATION_MODE
			{
				CYCLE
				{
					OUTLINEMAT_THICKNESS_ILLUMINATION_MODE_LIGHT;
					OUTLINEMAT_THICKNESS_ILLUMINATION_MODE_SHADOW;
					OUTLINEMAT_THICKNESS_ILLUMINATION_MODE_BOTH;
				}
			}
			BOOL OUTLINEMAT_THICKNESS_ILLUMINATION_INVERT {}
			
			REAL OUTLINEMAT_THICKNESS_ILLUMINATION_STRENGTH		{ UNIT PERCENT; MIN 0; MAX 10000; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }
			STATICTEXT { JOINEND; }
			STATICTEXT { JOINENDSCALE; }

			IN_EXCLUDE  OUTLINEMAT_THICKNESS_ILLUMINATION_LIGHTS
			{
				NUM_FLAGS 0; INIT_STATE 0; SEND_SELCHNGMSG 1;
				ACCEPT { Olight; };
			}
			STATICTEXT { JOINEND; }
			STATICTEXT { JOINENDSCALE; }
		}

		GROUP OUTLINEMAT_GROUP_THICKNESS_NOISE
		{
			COLUMNS 2; DEFAULT 1; HIDDEN;

			REAL OUTLINEMAT_THICKNESS_NOISE_STRENGTH		{ UNIT PERCENT; MIN 0; MAX 10000; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }
			STATICTEXT { JOINENDSCALE; }

			LONG OUTLINEMAT_THICKNESS_NOISE_TYPE
			{
				CYCLE
				{
					OUTLINEMAT_NOISE_TYPE_BOX_NOISE;
					OUTLINEMAT_NOISE_TYPE_BLIST_TURB;
					OUTLINEMAT_NOISE_TYPE_BUYA;
					OUTLINEMAT_NOISE_TYPE_CELL_NOISE;
					OUTLINEMAT_NOISE_TYPE_CRANAL;
					OUTLINEMAT_NOISE_TYPE_DENTS;
					OUTLINEMAT_NOISE_TYPE_DISPL_TURB;
					OUTLINEMAT_NOISE_TYPE_FBM;
					OUTLINEMAT_NOISE_TYPE_HAMA;
					OUTLINEMAT_NOISE_TYPE_LUKA;
					OUTLINEMAT_NOISE_TYPE_MOD_NOISE;
					OUTLINEMAT_NOISE_TYPE_NAKI;
					OUTLINEMAT_NOISE_TYPE_NOISE;
					OUTLINEMAT_NOISE_TYPE_NUTOUS;
					OUTLINEMAT_NOISE_TYPE_OBER;
					OUTLINEMAT_NOISE_TYPE_PEZO;
					OUTLINEMAT_NOISE_TYPE_POXO;
					OUTLINEMAT_NOISE_TYPE_RANDOM;
					OUTLINEMAT_NOISE_TYPE_SEMA;
					OUTLINEMAT_NOISE_TYPE_STUPL;
					OUTLINEMAT_NOISE_TYPE_TURBULENCE;
					OUTLINEMAT_NOISE_TYPE_VL_NOISE;
					OUTLINEMAT_NOISE_TYPE_WAVY_TURB;
					OUTLINEMAT_NOISE_TYPE_CELL_VORONOI;
					OUTLINEMAT_NOISE_TYPE_DISPL_VORONOI;
					OUTLINEMAT_NOISE_TYPE_SPARSE_CONV;
					OUTLINEMAT_NOISE_TYPE_VORONOI_1;
					OUTLINEMAT_NOISE_TYPE_VORONOI_2;
					OUTLINEMAT_NOISE_TYPE_VORONOI_3;
					OUTLINEMAT_NOISE_TYPE_ZADA;
				}
			}
			STATICTEXT { DUMMY; }

			SEPARATOR { }
			STATICTEXT { JOINENDSCALE; }

			LONG OUTLINEMAT_THICKNESS_NOISE_MAPPING
			{
				CYCLE
				{
					OUTLINEMAT_THICKNESS_NOISE_MAPPING_LINE;
					OUTLINEMAT_THICKNESS_NOISE_MAPPING_SCREEN;
					OUTLINEMAT_THICKNESS_NOISE_MAPPING_OBJECT;
					OUTLINEMAT_THICKNESS_NOISE_MAPPING_WORLD;
				}
			}
			STATICTEXT { DUMMY; }

			REAL OUTLINEMAT_THICKNESS_NOISE_OCTAVES	{ MIN 1; MAX 20; }
			STATICTEXT { DUMMY; }

			REAL OUTLINEMAT_THICKNESS_NOISE_SCALE	{ UNIT PERCENT; MIN 0; MAX 10000; }
			STATICTEXT { DUMMY; }

			REAL OUTLINEMAT_THICKNESS_ANIMSPEED	{ MIN 0; }
			STATICTEXT { DUMMY; }

			REAL OUTLINEMAT_THICKNESS_DETAIL		{ UNIT PERCENT; MIN 0; }
			STATICTEXT { DUMMY; }

			SEPARATOR { LINE; }
			STATICTEXT { JOINENDSCALE; }

			REAL OUTLINEMAT_THICKNESS_LOW_CLIP	{ UNIT PERCENT; MIN 0; MAX 100; CUSTOMGUI REALSLIDER;}
			STATICTEXT { JOINENDSCALE; }

			REAL OUTLINEMAT_THICKNESS_HIGH_CLIP	{ UNIT PERCENT; MIN 0; MAX 100; CUSTOMGUI REALSLIDER; }
			STATICTEXT { JOINENDSCALE; }

			REAL OUTLINEMAT_THICKNESS_BRIGHTNESS	{ UNIT PERCENT; MIN -100; MAX 100; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }
			STATICTEXT { JOINENDSCALE; }

			REAL OUTLINEMAT_THICKNESS_CONTRAST	{ UNIT PERCENT; MIN -100; MAX 100; CUSTOMGUI REALSLIDER; }
			STATICTEXT { JOINENDSCALE; }

			GROUP
			{
				COLUMNS 2;
				BOOL OUTLINEMAT_THICKNESS_NOISE_ABS {}
				BOOL OUTLINEMAT_THICKNESS_NOISE_INVERT {}
			}
			STATICTEXT { JOINENDSCALE; }
		}

		GROUP OUTLINEMAT_GROUP_THICKNESS_SCREENTEXTURE
		{
			COLUMNS 3; DEFAULT 1; HIDDEN;

			SHADERLINK OUTLINEMAT_THICKNESS_SCREENTEXTURE_LINK { }
			STATICTEXT { JOINEND; }
			STATICTEXT { JOINENDSCALE; }

			REAL OUTLINEMAT_THICKNESS_SCREENTEXTURE_STRENGTH		{ UNIT PERCENT; MIN 0; MAX 10000; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }
			STATICTEXT { JOINEND; }
			STATICTEXT { JOINENDSCALE; }

			REAL OUTLINEMAT_THICKNESS_SCREENTEXTURE_OFFX	{ UNIT PERCENT; }
			REAL OUTLINEMAT_THICKNESS_SCREENTEXTURE_OFFY	{ UNIT PERCENT; }
			STATICTEXT { DUMMY; }

			REAL OUTLINEMAT_THICKNESS_SCREENTEXTURE_LENX	{ UNIT PERCENT; }
			REAL OUTLINEMAT_THICKNESS_SCREENTEXTURE_LENY	{ UNIT PERCENT; }
			STATICTEXT { DUMMY; }
		}
	}

	GROUP OUTLINEMAT_GROUP_OPACITY
	{
		COLUMNS 1;

		REAL OUTLINEMAT_OPACITY		{ UNIT PERCENT; MIN 0.0; MAX 10000.0; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }
		BOOL OUTLINEMAT_OPACITY_LINKTHICKNESS {}

		GROUP OUTLINEMAT_GROUP_OPACITY_MODIFIERS
		{
			COLUMNS 2; DEFAULT 1; LAYOUTGROUP;

			GROUP
			{
				COLUMNS 1;

				BOOL OUTLINEMAT_OPACITY_DISTANCE {}
				BOOL OUTLINEMAT_OPACITY_POSITION {}
				BOOL OUTLINEMAT_OPACITY_SCALE {}
				BOOL OUTLINEMAT_OPACITY_ILLUMINATION {}
				BOOL OUTLINEMAT_OPACITY_TEXTURE {}
				BOOL OUTLINEMAT_OPACITY_VERTEX {}
				BOOL OUTLINEMAT_OPACITY_MAP {}
				BOOL OUTLINEMAT_OPACITY_SCREENTEXTURE {}
			}

			GROUP
			{
				COLUMNS 1;

				BOOL OUTLINEMAT_OPACITY_LENGTH {}
				BOOL OUTLINEMAT_OPACITY_SLENGTH {}
				BOOL OUTLINEMAT_OPACITY_FACEANGLE {}
				BOOL OUTLINEMAT_OPACITY_JOINANGLE {}
				BOOL OUTLINEMAT_OPACITY_SCREENANGLE {}
				BOOL OUTLINEMAT_OPACITY_FROMEDGE {}
				BOOL OUTLINEMAT_OPACITY_COFFEE {}
				BOOL OUTLINEMAT_OPACITY_NOISE {}
			}
		}

		GROUP OUTLINEMAT_GROUP_OPACITY_COFFEE
		{
			COLUMNS 3; DEFAULT 1; HIDDEN;

			REAL OUTLINEMAT_OPACITY_COFFEE_STRENGTH		{ UNIT PERCENT; MIN 0.0; MAX 10000.0; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }
			STATICTEXT { JOINEND; }
			STATICTEXT { JOINENDSCALE; }

			STRING OUTLINEMAT_OPACITY_COFFEE_CODE { CUSTOMGUI MULTISTRING; }
			STATICTEXT { JOINEND; }
			STATICTEXT { JOINENDSCALE; }

			BUTTON OUTLINEMAT_OPACITY_COFFEE_CODEEDIT { }
			LONG OUTLINEMAT_OPACITY_COFFEE_COMMANDS
			{
				CYCLE
				{
				}
			}
			STATICTEXT { DUMMY; }
		}

		GROUP OUTLINEMAT_GROUP_OPACITY_DISTANCE
		{
			COLUMNS 3; DEFAULT 1; HIDDEN;

			REAL OUTLINEMAT_OPACITY_DISTANCE_STRENGTH		{ UNIT PERCENT; MIN 0.0; MAX 10000.0; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }
			STATICTEXT { JOINEND; }
			STATICTEXT { JOINENDSCALE; }

			LONG OUTLINEMAT_OPACITY_DISTANCE_RANGE
			{
				CYCLE
				{
					OUTLINEMAT_MODIFIER_DISTANCE_RANGE_OBJECT;
					OUTLINEMAT_MODIFIER_DISTANCE_RANGE_CAMERA;
					OUTLINEMAT_MODIFIER_DISTANCE_RANGE_USER;
				}
			}
			LONG OUTLINEMAT_OPACITY_DISTANCE_MODE
			{
				CYCLE
				{
					OUTLINEMAT_OPACITY_DISTANCE_MODE_LINEAR;
					OUTLINEMAT_OPACITY_DISTANCE_MODE_SPLINE;
				}
			}
			BOOL OUTLINEMAT_OPACITY_DISTANCE_MODE_INVERT {}

			REAL OUTLINEMAT_OPACITY_DISTANCE_MIN	{ UNIT METER; MIN 0.0; }
			REAL OUTLINEMAT_OPACITY_DISTANCE_MAX	{ UNIT METER; MIN 0.0; }
			STATICTEXT { DUMMY; }

			SPLINE OUTLINEMAT_OPACITY_DISTANCE_SPLINE
			{ 
			}
			STATICTEXT { JOINEND; }
			STATICTEXT { JOINENDSCALE; }
		}

		GROUP OUTLINEMAT_GROUP_OPACITY_POSITION
		{
			COLUMNS 3; DEFAULT 1; HIDDEN;

			REAL OUTLINEMAT_OPACITY_POSITION_STRENGTH		{ UNIT PERCENT; MIN 0.0; MAX 10000.0; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }
			STATICTEXT { JOINEND; }
			STATICTEXT { JOINENDSCALE; }

			LONG OUTLINEMAT_OPACITY_POSITION_TYPE
			{
				CYCLE
				{
					OUTLINEMAT_OPACITY_POSITION_TYPE_X;
					OUTLINEMAT_OPACITY_POSITION_TYPE_Y;
					OUTLINEMAT_OPACITY_POSITION_TYPE_Z;
				}
			}
			LONG OUTLINEMAT_OPACITY_POSITION_MODE
			{
				CYCLE
				{
					OUTLINEMAT_OPACITY_POSITION_MODE_LINEAR;
					OUTLINEMAT_OPACITY_POSITION_MODE_SPLINE;
				}
			}
			BOOL OUTLINEMAT_OPACITY_POSITION_MODE_INVERT {}

			REAL OUTLINEMAT_OPACITY_POSITION_MIN	{ UNIT METER; MIN 0.0; }
			REAL OUTLINEMAT_OPACITY_POSITION_MAX	{ UNIT METER; MIN 0.0; }
			STATICTEXT { DUMMY; }

			SPLINE OUTLINEMAT_OPACITY_POSITION_SPLINE
			{ 
			}
			STATICTEXT { JOINEND; }
			STATICTEXT { JOINENDSCALE; }
		}

		GROUP OUTLINEMAT_GROUP_OPACITY_SCALE
		{
			COLUMNS 3; DEFAULT 1; HIDDEN;

			REAL OUTLINEMAT_OPACITY_SCALE_STRENGTH		{ UNIT PERCENT; MIN 0.0; MAX 10000.0; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }
			STATICTEXT { JOINEND; }
			STATICTEXT { JOINENDSCALE; }

			LONG OUTLINEMAT_OPACITY_SCALE_TYPE
			{
				CYCLE
				{
					OUTLINEMAT_OPACITY_SCALE_TYPE_X;
					OUTLINEMAT_OPACITY_SCALE_TYPE_Y;
					OUTLINEMAT_OPACITY_SCALE_TYPE_Z;
				}
			}
			LONG OUTLINEMAT_OPACITY_SCALE_COORDS
			{
				CYCLE
				{
					OUTLINEMAT_OPACITY_SCALE_COORDS_WORLD;
					OUTLINEMAT_OPACITY_SCALE_COORDS_LOCAL;
				}
			}
			STATICTEXT { DUMMY; }

			LONG OUTLINEMAT_OPACITY_SCALE_RANGE
			{
				CYCLE
				{
					OUTLINEMAT_OPACITY_SCALE_RANGE_SCALE;
					OUTLINEMAT_OPACITY_SCALE_RANGE_USER;
				}
			}
			LONG OUTLINEMAT_OPACITY_SCALE_MODE
			{
				CYCLE
				{
					OUTLINEMAT_OPACITY_SCALE_MODE_LINEAR;
					OUTLINEMAT_OPACITY_SCALE_MODE_SPLINE;
				}
			}
			BOOL OUTLINEMAT_OPACITY_SCALE_MODE_INVERT {}

			REAL OUTLINEMAT_OPACITY_SCALE_MIN	{ MIN 0.0; }
			REAL OUTLINEMAT_OPACITY_SCALE_MAX	{ MIN 0.0; }
			STATICTEXT { DUMMY; }

			SPLINE OUTLINEMAT_OPACITY_SCALE_SPLINE
			{ 
			}
			STATICTEXT { JOINEND; }
			STATICTEXT { JOINENDSCALE; }
		}

		GROUP OUTLINEMAT_GROUP_OPACITY_LENGTH
		{
			COLUMNS 3; DEFAULT 1; HIDDEN;

			REAL OUTLINEMAT_OPACITY_LENGTH_STRENGTH		{ UNIT PERCENT; MIN 0.0; MAX 10000.0; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }
			STATICTEXT { JOINEND; }
			STATICTEXT { JOINENDSCALE; }

			LONG OUTLINEMAT_OPACITY_LENGTH_RANGE
			{
				CYCLE
				{
					OUTLINEMAT_OPACITY_LENGTH_RANGE_LINE;
					OUTLINEMAT_OPACITY_LENGTH_RANGE_USER;
				}
			}
			LONG OUTLINEMAT_OPACITY_LENGTH_MODE
			{
				CYCLE
				{
					OUTLINEMAT_OPACITY_LENGTH_MODE_LINEAR;
					OUTLINEMAT_OPACITY_LENGTH_MODE_SPLINE;
				}
			}
			BOOL OUTLINEMAT_OPACITY_LENGTH_MODE_INVERT {}

			REAL OUTLINEMAT_OPACITY_LENGTH_MIN	{ MIN 0.0; }
			REAL OUTLINEMAT_OPACITY_LENGTH_MAX	{ MIN 0.0; }
			LONG OUTLINEMAT_OPACITY_LENGTH_LOOP	{ MIN 0; }

			SPLINE OUTLINEMAT_OPACITY_LENGTH_SPLINE
			{ 
			}
			STATICTEXT { JOINEND; }
			STATICTEXT { JOINENDSCALE; }
		}

		GROUP OUTLINEMAT_GROUP_OPACITY_SLENGTH
		{
			COLUMNS 3; DEFAULT 1; HIDDEN;

			REAL OUTLINEMAT_OPACITY_SLENGTH_STRENGTH		{ UNIT PERCENT; MIN 0.0; MAX 10000.0; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }
			STATICTEXT { JOINEND; }
			STATICTEXT { JOINENDSCALE; }

			REAL OUTLINEMAT_OPACITY_SLENGTH_MIN	{ MIN 0.0; }
			REAL OUTLINEMAT_OPACITY_SLENGTH_MAX	{ MIN 0.0; }
			STATICTEXT { DUMMY; }

			SPLINE OUTLINEMAT_OPACITY_SLENGTH_SPLINE
			{ 
			}
			STATICTEXT { JOINEND; }
			STATICTEXT { JOINENDSCALE; }
		}

		GROUP OUTLINEMAT_GROUP_OPACITY_FACEANGLE
		{
			DEFAULT 1; HIDDEN;

			REAL OUTLINEMAT_OPACITY_FACEANGLE_STRENGTH		{ UNIT PERCENT; MIN 0.0; MAX 10000.0; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }

			SPLINE OUTLINEMAT_OPACITY_FACEANGLE_SPLINE
			{ 
			}
		}

		GROUP OUTLINEMAT_GROUP_OPACITY_JOINANGLE
		{
			DEFAULT 1; HIDDEN;

			REAL OUTLINEMAT_OPACITY_JOINANGLE_STRENGTH		{ UNIT PERCENT; MIN 0.0; MAX 10000.0; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }
			
			LONG OUTLINEMAT_OPACITY_JOINANGLE_ENDS
			{
				CYCLE
				{
					OUTLINEMAT_JOINANGLE_ENDS_OFF;
					OUTLINEMAT_JOINANGLE_ENDS_MIN;
					OUTLINEMAT_JOINANGLE_ENDS_ZERO;
					OUTLINEMAT_JOINANGLE_ENDS_MAX;
				}
			}

			SPLINE OUTLINEMAT_OPACITY_JOINANGLE_SPLINE
			{ 
			}
		}

		GROUP OUTLINEMAT_GROUP_OPACITY_SCREENANGLE
		{
			DEFAULT 1; HIDDEN;

			REAL OUTLINEMAT_OPACITY_SCREENANGLE_STRENGTH		{ UNIT PERCENT; MIN 0.0; MAX 10000.0; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }

			SPLINE OUTLINEMAT_OPACITY_SCREENANGLE_SPLINE
			{ 
			}

			REAL OUTLINEMAT_OPACITY_SCREENANGLE_ROTATE	{ UNIT DEGREE; MIN -360.0; MAX 360.0; CUSTOMGUI REALSLIDER;}
		}

		GROUP OUTLINEMAT_GROUP_OPACITY_FROMEDGE
		{
			DEFAULT 1; HIDDEN;

			REAL OUTLINEMAT_OPACITY_FROMEDGE_STRENGTH		{ UNIT PERCENT; MIN 0.0; MAX 10000.0; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }

			SPLINE OUTLINEMAT_OPACITY_FROMEDGE_SPLINE
			{ 
			}
		}

		GROUP OUTLINEMAT_GROUP_OPACITY_TEXTURE
		{
			LAYOUTGROUP; COLUMNS 1; DEFAULT 1; HIDDEN;

			GROUP
			{
				COLUMNS 3;
			
				BUTTON OUTLINEMAT_OPACITY_TEXTURE_LOAD { }
				BUTTON OUTLINEMAT_OPACITY_TEXTURE_SAVE { }
				STATICTEXT { DUMMY; }

				SEPARATOR { }
				STATICTEXT { JOINEND; }
				STATICTEXT { JOINENDSCALE; }

				SHADERLINK OUTLINEMAT_OPACITY_TEXTURE_LINK { }
				STATICTEXT { JOINEND; }
				STATICTEXT { JOINENDSCALE; }

				REAL OUTLINEMAT_OPACITY_TEXTURE_STRENGTH		{ UNIT PERCENT; MIN 0.0; MAX 10000.0; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }
				STATICTEXT { JOINEND; }
				STATICTEXT { JOINENDSCALE; }

				REAL OUTLINEMAT_OPACITY_TEXTURE_OFFSETX { UNIT PERCENT; MIN -100.0; MAX 100.0; }
				REAL OUTLINEMAT_OPACITY_TEXTURE_OFFSETY { UNIT PERCENT; MIN -100.0; MAX 100.0; }
				STATICTEXT { DUMMY; }

				REAL OUTLINEMAT_OPACITY_TEXTURE_SCALEX { UNIT PERCENT; MIN 0.0; MAX 1000.0; }
				REAL OUTLINEMAT_OPACITY_TEXTURE_SCALEY { UNIT PERCENT; MIN 0.0; MAX 1000.0; }
				STATICTEXT { DUMMY; }

				REAL OUTLINEMAT_OPACITY_TEXTURE_SPACING { UNIT PERCENT; MIN 1.0; MAX 1000.0; }
				STATICTEXT { DUMMY; }
				STATICTEXT { DUMMY; }
				
				SEPARATOR { }
				STATICTEXT { JOINEND; }
				STATICTEXT { JOINENDSCALE; }
					
				REAL OUTLINEMAT_OPACITY_TEXTURE_SCATTER_U { UNIT PERCENT; MIN 0.0; MAX 1000.0; }
				REAL OUTLINEMAT_OPACITY_TEXTURE_SCATTER_V { UNIT PERCENT; MIN 0.0; MAX 1000.0; }
				STATICTEXT { DUMMY; }

				REAL OUTLINEMAT_OPACITY_TEXTURE_SIZE { UNIT PERCENT; MIN 1.0; MAX 1000.0; }
				REAL OUTLINEMAT_OPACITY_TEXTURE_SIZE_VAR { UNIT PERCENT; MIN 0.0; MAX 100.0; }
				STATICTEXT { DUMMY; }
					
				REAL OUTLINEMAT_OPACITY_TEXTURE_ROUND { UNIT PERCENT; MIN 1.0; MAX 1000.0; }
				REAL OUTLINEMAT_OPACITY_TEXTURE_ASPECT_VAR { UNIT PERCENT; MIN 0.0; MAX 100.0; }
				STATICTEXT { DUMMY; }

				REAL OUTLINEMAT_OPACITY_TEXTURE_ANGLE { UNIT DEGREE; MIN 0.0; MAX 360.0; }
				REAL OUTLINEMAT_OPACITY_TEXTURE_ANGLE_VAR { UNIT PERCENT; MIN 0.0; MAX 100.0; }
				STATICTEXT { DUMMY; }

				LONG OUTLINEMAT_OPACITY_TEXTURE_SCATTER_COUNT { MIN 0; MAX 100; }
				REAL OUTLINEMAT_OPACITY_TEXTURE_SCATTER_COUNT_VAR { UNIT PERCENT; MIN 0.0; MAX 100.0; }
				STATICTEXT { DUMMY; }
			}
			GROUP
			{
				COLUMNS 4;

				BOOL OUTLINEMAT_OPACITY_TEXTURE_ASPECT { }
				BOOL OUTLINEMAT_OPACITY_TEXTURE_INVERT { }
				BOOL OUTLINEMAT_OPACITY_TEXTURE_TILING { }
				BOOL OUTLINEMAT_OPACITY_TEXTURE_BEND { }
			}
		}

		GROUP OUTLINEMAT_GROUP_OPACITY_SCREENTEXTURE
		{
			COLUMNS 3; DEFAULT 1; HIDDEN;

			SHADERLINK OUTLINEMAT_OPACITY_SCREENTEXTURE_LINK { }
			STATICTEXT { JOINEND; }
			STATICTEXT { JOINENDSCALE; }

			REAL OUTLINEMAT_OPACITY_SCREENTEXTURE_STRENGTH		{ UNIT PERCENT; MIN 0.0; MAX 10000.0; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }
			STATICTEXT { JOINEND; }
			STATICTEXT { JOINENDSCALE; }

			REAL OUTLINEMAT_OPACITY_SCREENTEXTURE_OFFX	{ UNIT PERCENT; }
			REAL OUTLINEMAT_OPACITY_SCREENTEXTURE_OFFY	{ UNIT PERCENT; }
			STATICTEXT { DUMMY; }

			REAL OUTLINEMAT_OPACITY_SCREENTEXTURE_LENX	{ UNIT PERCENT; }
			REAL OUTLINEMAT_OPACITY_SCREENTEXTURE_LENY	{ UNIT PERCENT; }
			STATICTEXT { DUMMY; }
		}

		GROUP OUTLINEMAT_GROUP_OPACITY_VERTEX
		{
			DEFAULT 1; HIDDEN;
			REAL OUTLINEMAT_OPACITY_VERTEX_STRENGTH		{ UNIT PERCENT; MIN 0.0; MAX 10000.0; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }
		}

		GROUP OUTLINEMAT_GROUP_OPACITY_MAP
		{
			COLUMNS 3; DEFAULT 1; HIDDEN;

			REAL OUTLINEMAT_OPACITY_MAP_STRENGTH		{ UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; }
			STATICTEXT { JOINEND; }
			STATICTEXT { JOINENDSCALE; }

			SHADERLINK OUTLINEMAT_OPACITY_MAP_LINK { }
			STATICTEXT { JOINEND; }
			STATICTEXT { JOINENDSCALE; }

			LONG OUTLINEMAT_OPACITY_MAP_PROJECTION
			{
				CYCLE
				{
					OUTLINEMAT_MAP_PROJECTION_SPHERICAL;
					OUTLINEMAT_MAP_PROJECTION_CYLINDRICAL;
					OUTLINEMAT_MAP_PROJECTION_FLAT;
					OUTLINEMAT_MAP_PROJECTION_CUBIC;
					OUTLINEMAT_MAP_PROJECTION_FRONTAL;
					OUTLINEMAT_MAP_PROJECTION_SPATIAL;
					OUTLINEMAT_MAP_PROJECTION_UVW;
					OUTLINEMAT_MAP_PROJECTION_SHRINKWRAP;
				}
			}
			STATICTEXT { DUMMY; }
			STATICTEXT { DUMMY; }

			REAL OUTLINEMAT_OPACITY_MAP_OFFX	{ UNIT PERCENT; }
			REAL OUTLINEMAT_OPACITY_MAP_OFFY	{ UNIT PERCENT; }
			STATICTEXT { DUMMY; }

			REAL OUTLINEMAT_OPACITY_MAP_LENX	{ UNIT PERCENT; }
			REAL OUTLINEMAT_OPACITY_MAP_LENY	{ UNIT PERCENT; }
			STATICTEXT { DUMMY; }
		}

		GROUP OUTLINEMAT_GROUP_OPACITY_ILLUMINATION
		{
			COLUMNS 3; DEFAULT 1; HIDDEN;

			SPLINE OUTLINEMAT_OPACITY_ILLUMINATION_SPLINE
			{ 
			}
			STATICTEXT { JOINEND; }
			STATICTEXT { JOINENDSCALE; }

			LONG OUTLINEMAT_OPACITY_ILLUMINATION_LIGHT_MODE
			{
				CYCLE
				{
					OUTLINEMAT_OPACITY_ILLUMINATION_LIGHT_MODE_INCLUDE;
					OUTLINEMAT_OPACITY_ILLUMINATION_LIGHT_MODE_EXCLUDE;
				}
			}

			LONG OUTLINEMAT_OPACITY_ILLUMINATION_MODE
			{
				CYCLE
				{
					OUTLINEMAT_OPACITY_ILLUMINATION_MODE_LIGHT;
					OUTLINEMAT_OPACITY_ILLUMINATION_MODE_SHADOW;
					OUTLINEMAT_OPACITY_ILLUMINATION_MODE_BOTH;
				}
			}

			BOOL OUTLINEMAT_OPACITY_ILLUMINATION_INVERT {}
			
			REAL OUTLINEMAT_OPACITY_ILLUMINATION_STRENGTH		{ UNIT PERCENT; MIN 0.0; MAX 10000.0; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }
			STATICTEXT { JOINEND; }
			STATICTEXT { JOINENDSCALE; }

			IN_EXCLUDE  OUTLINEMAT_OPACITY_ILLUMINATION_LIGHTS
			{
				NUM_FLAGS 0; INIT_STATE 0; SEND_SELCHNGMSG 1;
				ACCEPT { Olight; };
			}
			STATICTEXT { JOINEND; }
			STATICTEXT { JOINENDSCALE; }
		}

		GROUP OUTLINEMAT_GROUP_OPACITY_NOISE
		{
			COLUMNS 3; DEFAULT 1; HIDDEN;

			REAL OUTLINEMAT_OPACITY_NOISE_STRENGTH		{ UNIT PERCENT; MIN 0.0; MAX 10000.0; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }
			STATICTEXT { JOINEND; }
			STATICTEXT { JOINENDSCALE; }

			LONG OUTLINEMAT_OPACITY_NOISE_TYPE
			{
				CYCLE
				{
					OUTLINEMAT_NOISE_TYPE_BOX_NOISE;
					OUTLINEMAT_NOISE_TYPE_BLIST_TURB;
					OUTLINEMAT_NOISE_TYPE_BUYA;
					OUTLINEMAT_NOISE_TYPE_CELL_NOISE;
					OUTLINEMAT_NOISE_TYPE_CRANAL;
					OUTLINEMAT_NOISE_TYPE_DENTS;
					OUTLINEMAT_NOISE_TYPE_DISPL_TURB;
					OUTLINEMAT_NOISE_TYPE_FBM;
					OUTLINEMAT_NOISE_TYPE_HAMA;
					OUTLINEMAT_NOISE_TYPE_LUKA;
					OUTLINEMAT_NOISE_TYPE_MOD_NOISE;
					OUTLINEMAT_NOISE_TYPE_NAKI;
					OUTLINEMAT_NOISE_TYPE_NOISE;
					OUTLINEMAT_NOISE_TYPE_NUTOUS;
					OUTLINEMAT_NOISE_TYPE_OBER;
					OUTLINEMAT_NOISE_TYPE_PEZO;
					OUTLINEMAT_NOISE_TYPE_POXO;
					OUTLINEMAT_NOISE_TYPE_RANDOM;
					OUTLINEMAT_NOISE_TYPE_SEMA;
					OUTLINEMAT_NOISE_TYPE_STUPL;
					OUTLINEMAT_NOISE_TYPE_TURBULENCE;
					OUTLINEMAT_NOISE_TYPE_VL_NOISE;
					OUTLINEMAT_NOISE_TYPE_WAVY_TURB;
					OUTLINEMAT_NOISE_TYPE_CELL_VORONOI;
					OUTLINEMAT_NOISE_TYPE_DISPL_VORONOI;
					OUTLINEMAT_NOISE_TYPE_SPARSE_CONV;
					OUTLINEMAT_NOISE_TYPE_VORONOI_1;
					OUTLINEMAT_NOISE_TYPE_VORONOI_2;
					OUTLINEMAT_NOISE_TYPE_VORONOI_3;
					OUTLINEMAT_NOISE_TYPE_ZADA;
				}
			}
			STATICTEXT { DUMMY; }
			STATICTEXT { DUMMY; }

			LONG OUTLINEMAT_OPACITY_NOISE_MAPPING
			{
				CYCLE
				{
					OUTLINEMAT_OPACITY_NOISE_MAPPING_LINE1D;
					OUTLINEMAT_OPACITY_NOISE_MAPPING_LINE2D;
					OUTLINEMAT_OPACITY_NOISE_MAPPING_SCREEN;
					OUTLINEMAT_OPACITY_NOISE_MAPPING_OBJECT;
					OUTLINEMAT_OPACITY_NOISE_MAPPING_WORLD;
				}
			}
			STATICTEXT { DUMMY; }
			STATICTEXT { DUMMY; }

			REAL OUTLINEMAT_OPACITY_NOISE_OCTAVES	{ MIN 1; MAX 20; }
			STATICTEXT { DUMMY; }
			STATICTEXT { DUMMY; }

			REAL OUTLINEMAT_OPACITY_NOISE_SCALE	{ UNIT PERCENT; MIN 0; MAX 10000; }
			STATICTEXT { DUMMY; }
			STATICTEXT { DUMMY; }

			REAL OUTLINEMAT_OPACITY_NOISE_SCALE_X	{ UNIT PERCENT; MIN 0; MAX 10000; }
			REAL OUTLINEMAT_OPACITY_NOISE_SCALE_Y	{ UNIT PERCENT; MIN 0; MAX 10000; }
			STATICTEXT { DUMMY; }

			REAL OUTLINEMAT_OPACITY_ANIMSPEED	{ MIN 0; }
			STATICTEXT { DUMMY; }
			STATICTEXT { DUMMY; }

			REAL OUTLINEMAT_OPACITY_DETAIL		{ UNIT PERCENT; MIN 0; }
			STATICTEXT { DUMMY; }
			STATICTEXT { DUMMY; }

			SEPARATOR { LINE; }
			STATICTEXT { JOINEND; }
			STATICTEXT { JOINENDSCALE; }

			REAL OUTLINEMAT_OPACITY_LOW_CLIP	{ UNIT PERCENT; MIN 0; MAX 100; CUSTOMGUI REALSLIDER; }
			STATICTEXT { JOINEND; }
			STATICTEXT { JOINENDSCALE; }

			REAL OUTLINEMAT_OPACITY_HIGH_CLIP	{ UNIT PERCENT; MIN 0; MAX 100; CUSTOMGUI REALSLIDER; }
			STATICTEXT { JOINEND; }
			STATICTEXT { JOINENDSCALE; }

			REAL OUTLINEMAT_OPACITY_BRIGHTNESS	{ UNIT PERCENT; MIN -100; MAX 100; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }
			STATICTEXT { JOINEND; }
			STATICTEXT { JOINENDSCALE; }

			REAL OUTLINEMAT_OPACITY_CONTRAST	{ UNIT PERCENT; MIN -100; MAX 100; CUSTOMGUI REALSLIDER; }
			STATICTEXT { JOINEND; }
			STATICTEXT { JOINENDSCALE; }

			GROUP
			{
				COLUMNS 2;

				BOOL OUTLINEMAT_OPACITY_NOISE_ABS {}
				BOOL OUTLINEMAT_OPACITY_NOISE_INVERT {}
			}
		}
	}

	GROUP OUTLINEMAT_GROUP_SCENE
	{
		COLUMNS 3;

		LONG OUTLINEMAT_SCENE_AA
		{
			HIDDEN;

			CYCLE
			{
				OUTLINEMAT_SCENE_AA_OFF;
				OUTLINEMAT_SCENE_AA_1;
				OUTLINEMAT_SCENE_AA_2;
				OUTLINEMAT_SCENE_AA_3;
				OUTLINEMAT_SCENE_AA_4;
			}
		}
		STATICTEXT { DUMMY; }
		STATICTEXT { DUMMY; }

		SEPARATOR { LINE; }
		STATICTEXT { JOINEND; }
		STATICTEXT { JOINENDSCALE; }

		BOOL OUTLINEMAT_SCENE_POSTRENDER { HIDDEN; }
		STATICTEXT { DUMMY; }
		STATICTEXT { DUMMY; }

		BOOL OUTLINEMAT_ADV_BACKBLEND {}
		STATICTEXT { DUMMY; }
		STATICTEXT { DUMMY; }

		LONG OUTLINEMAT_SCENE_INEX_MODE
		{
			CYCLE
			{
				OUTLINEMAT_SCENE_INEX_MODE_INCLUDE;
				OUTLINEMAT_SCENE_INEX_MODE_EXCLUDE;
			}
		}
		STATICTEXT { DUMMY; }
		STATICTEXT { DUMMY; }

		IN_EXCLUDE  OUTLINEMAT_SCENE_INEXCLUDE
		{
			NUM_FLAGS 1; INIT_STATE 1; SEND_SELCHNGMSG 1;
			IMAGE_01_ON 1009316; IMAGE_01_OFF 1009320;
			ACCEPT { Obase; };
		}
		STATICTEXT { JOINEND; }
		STATICTEXT { JOINENDSCALE; }

		SEPARATOR { LINE; }
		STATICTEXT { JOINEND; }
		STATICTEXT { JOINENDSCALE; }

		REAL OUTLINEMAT_SCENE_SCALE	{ UNIT PERCENT; MIN 0; }
		STATICTEXT { DUMMY; }
		STATICTEXT { DUMMY; }

		LONG OUTLINEMAT_SCENE_PIXELUNITS
		{
			CYCLE
			{
				OUTLINEMAT_SCENE_PIXELUNITS_ABSPIXELS;
				OUTLINEMAT_SCENE_PIXELUNITS_RELPIXELS;
				OUTLINEMAT_SCENE_PIXELUNITS_WORLD;
			}
		}
		STATICTEXT { DUMMY; }
		STATICTEXT { DUMMY; }

		SEPARATOR { LINE; }
		STATICTEXT { JOINEND; }
		STATICTEXT { JOINENDSCALE; }

		BOOL OUTLINEMAT_PIXELUNITS_INDEPENDENT {}
		STATICTEXT { DUMMY; }
		STATICTEXT { DUMMY; }

		LONG OUTLINEMAT_PIXELUNITS_INDEPENDENT_MODE
		{
			CYCLE
			{
				OUTLINEMAT_PIXELUNITS_INDEPENDENT_MODE_RENDER;
				OUTLINEMAT_PIXELUNITS_INDEPENDENT_MODE_CUSTOM;
			}
		}
		STATICTEXT { DUMMY; }
		STATICTEXT { DUMMY; }

		REAL OUTLINEMAT_PIXELUNITS_BASEW	{ MIN 1; }
		REAL OUTLINEMAT_PIXELUNITS_BASEH	{ MIN 1; }
		STATICTEXT { DUMMY; }

		BUTTON OUTLINEMAT_PIXELUNITS_ASEDITOR {}
		BUTTON OUTLINEMAT_PIXELUNITS_ASRENDER {}
		STATICTEXT { JOINEND; }
		STATICTEXT { JOINENDSCALE; }
		STATICTEXT { DUMMY; }

		SEPARATOR { LINE; }
		STATICTEXT { JOINEND; }
		STATICTEXT { JOINENDSCALE; }

		BOOL OUTLINEMAT_STOKECLIP_TOSCREEN {}
		STATICTEXT { DUMMY; }
		STATICTEXT { DUMMY; }

		REAL OUTLINEMAT_CAMERACLIP_MINZ	{ UNIT METER; MIN 0.05; HIDDEN; }
		STATICTEXT { DUMMY; }
		STATICTEXT { DUMMY; }

		REAL OUTLINEMAT_CAMERACLIP_MAXZ	{ UNIT METER; MIN 0.05; HIDDEN; }
		BOOL OUTLINEMAT_CAMERACLIP_FAR { HIDDEN; }
		STATICTEXT { DUMMY; }

		SEPARATOR { LINE; }
		STATICTEXT { JOINEND; }
		STATICTEXT { JOINENDSCALE; }

		LONG OUTLINEMAT_ADV_SELFBLENDMODE
		{
			CYCLE
			{
				OUTLINEMAT_BLENDMODE_AVERAGE;
				OUTLINEMAT_BLENDMODE_NORMAL;
				OUTLINEMAT_BLENDMODE_MULTIPLY;
				OUTLINEMAT_BLENDMODE_SCREEN;
				OUTLINEMAT_BLENDMODE_DARKEN;
				OUTLINEMAT_BLENDMODE_LIGHT;
				OUTLINEMAT_BLENDMODE_DIFFERENCE;
				OUTLINEMAT_BLENDMODE_NEGATIVE;
				OUTLINEMAT_BLENDMODE_EXCLUSION;
				OUTLINEMAT_BLENDMODE_OVERLAY;
				OUTLINEMAT_BLENDMODE_HARDLIGHT;
				OUTLINEMAT_BLENDMODE_SOFTLIGHT;
				OUTLINEMAT_BLENDMODE_DODGE;
				OUTLINEMAT_BLENDMODE_BURN;
				OUTLINEMAT_BLENDMODE_REFLECT;
				OUTLINEMAT_BLENDMODE_GLOW;
				OUTLINEMAT_BLENDMODE_FREEZE;
				OUTLINEMAT_BLENDMODE_HEAT;
				OUTLINEMAT_BLENDMODE_ADD;
				OUTLINEMAT_BLENDMODE_SUB;
				OUTLINEMAT_BLENDMODE_STAMP;
				OUTLINEMAT_BLENDMODE_XOR;
				OUTLINEMAT_BLENDMODE_HUE;
				OUTLINEMAT_BLENDMODE_SATURATION;
				OUTLINEMAT_BLENDMODE_LUMINANCE;
				OUTLINEMAT_BLENDMODE_RED;
				OUTLINEMAT_BLENDMODE_GREEN;
				OUTLINEMAT_BLENDMODE_BLUE;
				OUTLINEMAT_BLENDMODE_OVERWRITE;
				OUTLINEMAT_BLENDMODE_LEVR;
			}
		}
		STATICTEXT { DUMMY; }
		STATICTEXT { DUMMY; }

		LONG OUTLINEMAT_ADV_BLENDMODE
		{
			CYCLE
			{
				OUTLINEMAT_BLENDMODE_AVERAGE;
				OUTLINEMAT_BLENDMODE_NORMAL;
				OUTLINEMAT_BLENDMODE_MULTIPLY;
				OUTLINEMAT_BLENDMODE_SCREEN;
				OUTLINEMAT_BLENDMODE_DARKEN;
				OUTLINEMAT_BLENDMODE_LIGHT;
				OUTLINEMAT_BLENDMODE_DIFFERENCE;
				OUTLINEMAT_BLENDMODE_NEGATIVE;
				OUTLINEMAT_BLENDMODE_EXCLUSION;
				OUTLINEMAT_BLENDMODE_OVERLAY;
				OUTLINEMAT_BLENDMODE_HARDLIGHT;
				OUTLINEMAT_BLENDMODE_SOFTLIGHT;
				OUTLINEMAT_BLENDMODE_DODGE;
				OUTLINEMAT_BLENDMODE_BURN;
				OUTLINEMAT_BLENDMODE_REFLECT;
				OUTLINEMAT_BLENDMODE_GLOW;
				OUTLINEMAT_BLENDMODE_FREEZE;
				OUTLINEMAT_BLENDMODE_HEAT;
				OUTLINEMAT_BLENDMODE_ADD;
				OUTLINEMAT_BLENDMODE_SUB;
				OUTLINEMAT_BLENDMODE_STAMP;
				OUTLINEMAT_BLENDMODE_XOR;
				OUTLINEMAT_BLENDMODE_HUE;
				OUTLINEMAT_BLENDMODE_SATURATION;
				OUTLINEMAT_BLENDMODE_LUMINANCE;
				OUTLINEMAT_BLENDMODE_RED;
				OUTLINEMAT_BLENDMODE_GREEN;
				OUTLINEMAT_BLENDMODE_BLUE;
				OUTLINEMAT_BLENDMODE_OVERWRITE;
				OUTLINEMAT_BLENDMODE_LEVR;
			}
		}
		STATICTEXT { DUMMY; }
		STATICTEXT { DUMMY; }

		SEPARATOR { LINE; }
		STATICTEXT { JOINEND; }
		STATICTEXT { JOINENDSCALE; }

		LONG OUTLINEMAT_LINE_RENDERCLIP
		{
			CYCLE
			{
				OUTLINEMAT_LINE_RENDERCLIP_OFF;
				OUTLINEMAT_LINE_RENDERCLIP_IN;
				OUTLINEMAT_LINE_RENDERCLIP_OUT;
			}
		}
		STATICTEXT { DUMMY; }
		STATICTEXT { DUMMY; }

		LONG OUTLINEMAT_LINE_RENDERCLIP_MODE
		{
			CYCLE
			{
				OUTLINEMAT_LINE_RENDERCLIP_MODE_SELF;
				OUTLINEMAT_LINE_RENDERCLIP_MODE_WITHCHILD;
				OUTLINEMAT_LINE_RENDERCLIP_MODE_HIERARCHY;
				OUTLINEMAT_LINE_RENDERCLIP_MODE_SCENE;
				OUTLINEMAT_LINE_RENDERCLIP_MODE_OBJECTS;
			}
		}
		BOOL OUTLINEMAT_LINE_RENDERCLIP_SELF { }
		STATICTEXT { DUMMY; }

		IN_EXCLUDE  OUTLINEMAT_LINE_RENDERCLIP_OBJECTS
		{
			NUM_FLAGS 1; INIT_STATE 1; SEND_SELCHNGMSG 1; HIDDEN;
			IMAGE_01_ON 1009316; IMAGE_01_OFF 1009320;
			ACCEPT { Obase; };
		}
		STATICTEXT { JOINEND; }
		STATICTEXT { JOINENDSCALE; }

		SEPARATOR { LINE; }
		STATICTEXT { JOINEND; }
		STATICTEXT { JOINENDSCALE; }

		LONG OUTLINEMAT_LINE_RENDERCULL_TYPE
		{
			CYCLE
			{
				OUTLINEMAT_LINE_RENDERCULL_TYPE_VISIBLE;
				OUTLINEMAT_LINE_RENDERCULL_TYPE_HIDDEN;
			}
		}
		BOOL OUTLINEMAT_LINE_RENDERCULL_QUALITY { }
		STATICTEXT { DUMMY; }

		LONG OUTLINEMAT_LINE_RENDERCULL_MODE
		{
			CYCLE
			{
				OUTLINEMAT_LINE_RENDERCULL_MODE_SELF;
				OUTLINEMAT_LINE_RENDERCULL_MODE_WITHCHILD;
				OUTLINEMAT_LINE_RENDERCULL_MODE_HIERARCHY;
				OUTLINEMAT_LINE_RENDERCULL_MODE_SCENE;
				OUTLINEMAT_LINE_RENDERCULL_MODE_OBJECTS;
			}
		}
		BOOL OUTLINEMAT_LINE_RENDERCULL_SELF { }
		STATICTEXT { DUMMY; }

		IN_EXCLUDE  OUTLINEMAT_LINE_RENDERCULL_OBJECTS
		{
			NUM_FLAGS 1; INIT_STATE 1; SEND_SELCHNGMSG 1;
			IMAGE_01_ON 1009316; IMAGE_01_OFF 1009320;
			ACCEPT { Obase; };
		}
		STATICTEXT { JOINEND; }
		STATICTEXT { JOINENDSCALE; }

		LONG OUTLINEMAT_SCENE_SEED { MIN 0; }
		BOOL OUTLINEMAT_SCENE_SEED_STATIC {}
		STATICTEXT { DUMMY; }
	}
	
	GROUP OUTLINEMAT_GROUP_MULTIPASS
	{
		COLUMNS 1; HIDDEN;

		BOOL OUTLINEMAT_MULTIPASS_RGB { ANIM OFF; }
		BOOL OUTLINEMAT_MULTIPASS_DEPTH { ANIM OFF; }
		BOOL OUTLINEMAT_MULTIPASS_ALPHA { ANIM OFF; }
		BOOL OUTLINEMAT_MULTIPASS_SPLITTYPES { ANIM OFF; }
		BOOL OUTLINEMAT_MULTIPASS_SPLITSHOW { ANIM OFF; }

		SEPARATOR { }

		GROUP
		{
			COLUMNS 2;

			BOOL OUTLINEMAT_MULTIPASS_LINE_OUTLINE { ANIM OFF; }
			BOOL OUTLINEMAT_MULTIPASS_LINE_FOLD { ANIM OFF; }
			BOOL OUTLINEMAT_MULTIPASS_LINE_OVERLAPS { ANIM OFF; }
			BOOL OUTLINEMAT_MULTIPASS_LINE_CREASE { ANIM OFF; }
			BOOL OUTLINEMAT_MULTIPASS_LINE_ANGLE { ANIM OFF; }
			BOOL OUTLINEMAT_MULTIPASS_LINE_BORDER { ANIM OFF; }
			BOOL OUTLINEMAT_MULTIPASS_LINE_MATERIAL { ANIM OFF; }
			BOOL OUTLINEMAT_MULTIPASS_LINE_EDGES { ANIM OFF; }
			BOOL OUTLINEMAT_MULTIPASS_LINE_INTERSECTION { ANIM OFF; }
			BOOL OUTLINEMAT_MULTIPASS_LINE_TRI { ANIM OFF; }
			BOOL OUTLINEMAT_MULTIPASS_LINE_MOTION { ANIM OFF; }
			BOOL OUTLINEMAT_MULTIPASS_LINE_CONTOUR { ANIM OFF; }
			BOOL OUTLINEMAT_MULTIPASS_LINE_ISOPARMS { ANIM OFF; }
			BOOL OUTLINEMAT_MULTIPASS_LINE_SPLINES { ANIM OFF; }
			BOOL OUTLINEMAT_MULTIPASS_LINE_PARTICLES { ANIM OFF; }
		}
	}

	GROUP OUTLINEMAT_GROUP_CLONE
	{
		COLUMNS 1;

		GROUP
		{
			COLUMNS 2;

			BOOL OUTLINEMAT_CLONE_ENABLE {}
			LONG OUTLINEMAT_CLONE_REPEAT { MIN 1; }
		}

		SEPARATOR { }

		GROUP
		{
			COLUMNS 2;

			REAL OUTLINEMAT_CLONE_STROKE_START { UNIT PERCENT;  MIN 0; MAX 100; }
			REAL OUTLINEMAT_CLONE_STROKE_START_VAR { UNIT PERCENT; MIN 0; MAX 100; }
			
			REAL OUTLINEMAT_CLONE_STROKE_END { UNIT PERCENT;  MIN 0; MAX 100; }
			REAL OUTLINEMAT_CLONE_STROKE_END_VAR { UNIT PERCENT;  MIN 0; MAX 100; }
		}

		GROUP OUTLINEMAT_GROUP_CLONE_VARIATIONS
		{
			COLUMNS 1; DEFAULT 1;

			GROUP
			{
				COLUMNS 2;

				REAL OUTLINEMAT_CLONE_LINE_OFFSET { }

				LONG OUTLINEMAT_CLONE_METHOD
				{
					CYCLE
					{
						OUTLINEMAT_CLONE_METHOD_UNIFORM;
						OUTLINEMAT_CLONE_METHOD_GAUSSIAN;
					}
				}

				SEPARATOR { }
				STATICTEXT { JOINEND; }

				REAL OUTLINEMAT_CLONE_THICKNESS_VAR { UNIT PERCENT;  MIN 0; MAX 100; }
				REAL OUTLINEMAT_CLONE_THICKNESS { UNIT PERCENT;  MIN 0; MAX 100; }

				REAL OUTLINEMAT_CLONE_OPACITY_VAR { UNIT PERCENT; MIN 0; MAX 100;  }
				REAL OUTLINEMAT_CLONE_OPACITY { UNIT PERCENT;  MIN 0; }

				REAL OUTLINEMAT_CLONE_NOISE_VAR { UNIT PERCENT; MIN 0; MAX 100; }
				REAL OUTLINEMAT_CLONE_NOISEOFF_VAR { MIN 0; }
			}

			SEPARATOR { }

			GROUP
			{
				COLUMNS 3;

				REAL OUTLINEMAT_CLONE_COLOUR_H_VAR { UNIT PERCENT; MIN 0; MAX 100; }
				REAL OUTLINEMAT_CLONE_COLOUR_S_VAR { UNIT PERCENT; MIN 0; MAX 100; }
				REAL OUTLINEMAT_CLONE_COLOUR_V_VAR { UNIT PERCENT; MIN 0; MAX 100; }
			}

			SEPARATOR { }

			REAL OUTLINEMAT_CLONE_OFFSET_VAR { UNIT PERCENT; MIN 0; MAX 100; CUSTOMGUI REALSLIDER; }
			REAL OUTLINEMAT_CLONE_OVERSHOOT_VAR { UNIT PERCENT; MIN 0; MAX 100; CUSTOMGUI REALSLIDER; }
			REAL OUTLINEMAT_CLONE_SCALE_VAR { UNIT PERCENT; MIN 0; MAX 100; CUSTOMGUI REALSLIDER; }
			REAL OUTLINEMAT_CLONE_ROTATE_VAR { UNIT PERCENT; MIN 0; MAX 100; CUSTOMGUI REALSLIDER; }


		}

		GROUP OUTLINEMAT_GROUP_CLONE_TRANSFORM
		{
			COLUMNS 1; DEFAULT 1;

			BOOL OUTLINEMAT_CLONE_INCREMENTAL { }
			SEPARATOR { }

			GROUP
			{
				COLUMNS 2;

				LONG OUTLINEMAT_CLONE_PIVOT
				{
					CYCLE
					{
						OUTLINEMAT_CLONE_PIVOT_START;
						OUTLINEMAT_CLONE_PIVOT_END;
						OUTLINEMAT_CLONE_PIVOT_CENTER;
						OUTLINEMAT_CLONE_PIVOT_OBJECT;
					}
				}
				SEPARATOR { }

				SEPARATOR { }
				SEPARATOR { }
				
				REAL OUTLINEMAT_CLONE_CLONEMOVE_X { }
				REAL OUTLINEMAT_CLONE_CLONEMOVE_X_VAR { MIN 0; MAX 100; }

				REAL OUTLINEMAT_CLONE_CLONEMOVE_Y { }
				REAL OUTLINEMAT_CLONE_CLONEMOVE_Y_VAR { MIN 0; MAX 100; }

				REAL OUTLINEMAT_CLONE_CLONESCALE_X { UNIT PERCENT; }
				REAL OUTLINEMAT_CLONE_CLONESCALE_X_VAR { UNIT PERCENT; MIN 0; MAX 100; }

				REAL OUTLINEMAT_CLONE_CLONESCALE_Y { UNIT PERCENT; }
				REAL OUTLINEMAT_CLONE_CLONESCALE_Y_VAR { UNIT PERCENT; MIN 0; MAX 100; }

				REAL OUTLINEMAT_CLONE_CLONEROTATE_X { UNIT DEGREE; }
				REAL OUTLINEMAT_CLONE_CLONEROTATE_X_VAR { UNIT PERCENT; MIN 0; MAX 100; }
			}
		}
	}

	GROUP OUTLINEMAT_GROUP_ANIMATE
	{
		COLUMNS 1;

		BOOL OUTLINEMAT_ANIMATE_AUTODRAW { }

		SEPARATOR { }

		LONG OUTLINEMAT_ANIMATE_STROKE_MODE
		{
			CYCLE
			{
				OUTLINEMAT_ANIMATE_STROKE_MODE_DRAW;
				OUTLINEMAT_ANIMATE_STROKE_MODE_LENGTH;
				OUTLINEMAT_ANIMATE_STROKE_MODE_OPACITY;
				OUTLINEMAT_ANIMATE_STROKE_MODE_THICKNESS;
				OUTLINEMAT_ANIMATE_STROKE_MODE_BUILD;
			}
		}

		LONG OUTLINEMAT_ANIMATE_STROKES
		{
			CYCLE
			{
				OUTLINEMAT_ANIMATE_STROKES_LONGTOSHORT;
				OUTLINEMAT_ANIMATE_STROKES_SHORTTOLONG;
				OUTLINEMAT_ANIMATE_STROKES_TOPBOTTOM;
				OUTLINEMAT_ANIMATE_STROKES_BOTTOMTOP;
				OUTLINEMAT_ANIMATE_STROKES_LEFTRIGHT;
				OUTLINEMAT_ANIMATE_STROKES_RIGHTLEFT;
				OUTLINEMAT_ANIMATE_STROKES_RANDOM;
			}
		}

		SEPARATOR { }

		LONG OUTLINEMAT_ANIMATE_STROKE_METHOD
		{
			CYCLE
			{
				OUTLINEMAT_ANIMATE_STROKE_METHOD_SINGLE;
				OUTLINEMAT_ANIMATE_STROKE_METHOD_ALL;
			}
		}
		
		LONG OUTLINEMAT_ANIMATE_STROKE_SPEED_TYPE
		{
			CYCLE
			{
				OUTLINEMAT_ANIMATE_STROKE_SPEED_TYPE_PIXELS_LENGTH;
				OUTLINEMAT_ANIMATE_STROKE_SPEED_TYPE_TIME;
				OUTLINEMAT_ANIMATE_STROKE_SPEED_TYPE_COMPLETION;
				OUTLINEMAT_ANIMATE_STROKE_SPEED_TYPE_TOTALTIME;
				OUTLINEMAT_ANIMATE_STROKE_SPEED_TYPE_ENDFRAME;
				OUTLINEMAT_ANIMATE_STROKE_SPEED_TYPE_ANIMEND;
			}
		}

		SEPARATOR { }
		
		BASETIME OUTLINEMAT_ANIMATE_START	 { MIN 0; }

		REAL OUTLINEMAT_ANIMATE_STROKE_SPEED { }
		BASETIME OUTLINEMAT_ANIMATE_STROKE_TIME	 { MIN 0; }
		BASETIME OUTLINEMAT_ANIMATE_END		 { MIN 0; }
		REAL OUTLINEMAT_ANIMATE_STROKE_SPEED_COMPLETE { UNIT PERCENT; MIN 0; MAX 100; }
	}
	
	GROUP OUTLINEMAT_GROUP_SHADING
	{
		COLUMNS 1;

		LONG OUTLINEMAT_SHADING_BACK
		{
			CYCLE
			{
				OUTLINEMAT_SHADING_BACK_CINEMA;
				OUTLINEMAT_SHADING_BACK_COLOR;
				OUTLINEMAT_SHADING_BACK_TEXTURE;
			}
		}

		COLOR OUTLINEMAT_SHADING_BACK_COL { HIDDEN; OPEN; }

		SHADERLINK OUTLINEMAT_SHADING_BACK_TEX { }

		GROUP
		{
			COLUMNS 3;

			BOOL OUTLINEMAT_SHADING_BACK_ALPHA { }
			BOOL OUTLINEMAT_SHADING_BACK_ALPHALINES { }
			BOOL OUTLINEMAT_SHADING_BACK_ALPHAOBJECTS { }
		}

		REAL OUTLINEMAT_SHADING_BACK_ALPHA_STRENGTH { UNIT PERCENT; MIN 0; MAX 10000; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }

		SHADERLINK OUTLINEMAT_SHADING_BACK_TEX_ALPHA { }

		SEPARATOR { LINE; }

		BOOL OUTLINEMAT_SHADING_ENABLE { HIDDEN; }

		LONG OUTLINEMAT_SHADING_OBJECT
		{
			CYCLE
			{
				OUTLINEMAT_SHADING_OBJECT_CINEMA;
				OUTLINEMAT_SHADING_OBJECT_COLOR_DISPLAY;
				OUTLINEMAT_SHADING_OBJECT_COLOR_USER;
				OUTLINEMAT_SHADING_OBJECT_TEXTURE;
				OUTLINEMAT_SHADING_OBJECT_BACKGROUND;
				OUTLINEMAT_SHADING_OBJECT_SHADED;
			}
		}
		
		COLOR OUTLINEMAT_SHADING_OBJECT_COL { HIDDEN; OPEN; }

		SHADERLINK OUTLINEMAT_SHADING_OBJECT_TEX { }

		LONG OUTLINEMAT_SHADING_OBJECT_MODEL
		{
			CYCLE
			{
				OUTLINEMAT_SHADING_OBJECT_MODEL_QUANTISE;
				OUTLINEMAT_SHADING_OBJECT_MODEL_GRADQUANT;
			}
		}

		LONG OUTLINEMAT_SHADING_QUANTISE_LEVEL { MIN 1; MAX 100; }
		GRADIENT  OUTLINEMAT_SHADING_GRADQUANT { ALPHA;	ICC_BASEDOCUMENT; }

		BOOL OUTLINEMAT_SHADING_ILLUMINATION { }
		BOOL OUTLINEMAT_SHADING_SHADOWS { }

		BOOL OUTLINEMAT_SHADING_SHADOW_COLORIZE { }

		GRADIENT  OUTLINEMAT_SHADING_SHADOW_COL { COLOR; ICC_BASEDOCUMENT; }
		REAL OUTLINEMAT_SHADING_SHADOW_COL_STRENGTH { UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; }

		SEPARATOR { }

		BOOL OUTLINEMAT_SHADING_ALLTOON { }

		LONG OUTLINEMAT_SHADING_INEX_MODE
		{
			CYCLE
			{
				OUTLINEMAT_SHADING_INEX_MODE_INCLUDE;
				OUTLINEMAT_SHADING_INEX_MODE_EXCLUDE;
			}
		}

		IN_EXCLUDE  OUTLINEMAT_SHADING_INEXCLUDE
		{
			NUM_FLAGS 1; INIT_STATE 1; SEND_SELCHNGMSG 1;
			IMAGE_01_ON 1009316; IMAGE_01_OFF 1009320;
			ACCEPT { Obase; };
		}
	}

	GROUP OUTLINEMAT_GROUP_EDITORLINES
	{
		COLUMNS 1; HIDDEN;

		GROUP
		{
			COLUMNS 2;

			BOOL OUTLINEMAT_EDLINES_SHOWLINES {}
			BOOL OUTLINEMAT_EDLINES_REDRAW_FULL {}
		}

		LONG OUTLINEMAT_EDLINES_LINE_DRAW
		{
			CYCLE
			{
				OUTLINEMAT_EDLINES_LINE_DRAW_2D;
				OUTLINEMAT_EDLINES_LINE_DRAW_3D;
			}
		}

		LONG OUTLINEMAT_EDLINES_LINE_OBJECTS_MODE
		{
			CYCLE
			{
				OUTLINEMAT_EDLINES_LINE_OBJECTS_INCLUDE;
				OUTLINEMAT_EDLINES_LINE_OBJECTS_EXCLUDE;
				OUTLINEMAT_EDLINES_LINE_OBJECTS_ACTIVEONLY;
			}
		}

		IN_EXCLUDE  OUTLINEMAT_EDLINES_LINE_OBJECTS
		{
			NUM_FLAGS 1; INIT_STATE 1; SEND_SELCHNGMSG 1;
			IMAGE_01_ON 1009316; IMAGE_01_OFF 1009320;
			ACCEPT { Obase; };
		}

		SEPARATOR { }

		GROUP
		{
			COLUMNS 2;

			BOOL OUTLINEMAT_EDLINES_LINE_OUTLINE {}
			BOOL OUTLINEMAT_EDLINES_LINE_FOLD {}
			BOOL OUTLINEMAT_EDLINES_LINE_OVERLAPS {}
			BOOL OUTLINEMAT_EDLINES_LINE_CREASE {}
			BOOL OUTLINEMAT_EDLINES_LINE_ANGLE {}
			BOOL OUTLINEMAT_EDLINES_LINE_BORDER {}
			BOOL OUTLINEMAT_EDLINES_LINE_MATERIAL {}
			BOOL OUTLINEMAT_EDLINES_LINE_EDGES {}
			BOOL OUTLINEMAT_EDLINES_LINE_TRI {}
			BOOL OUTLINEMAT_EDLINES_LINE_CONTOUR {}
			BOOL OUTLINEMAT_EDLINES_LINE_INTERSECTION {}
		}

		SEPARATOR { }

		GROUP
		{
			COLUMNS 2;

			BOOL OUTLINEMAT_EDLINES_LINE_SHOWCOLOR {}
			BOOL OUTLINEMAT_EDLINES_LINE_SHOWTHICKNESS {}
		}

		LONG OUTLINEMAT_EDLINES_LINE_THICKNESS { MIN 1; MAX 100; }
		COLOR OUTLINEMAT_EDLINES_LINE_COLOR { OPEN; }
	}

	GROUP OUTLINEMAT_GROUP_ASSIGN
	{
		SCALE_V;

		MATASSIGN OUTLINEMAT_ASSIGN { TAG_ID 1011012; MATERIAL_ID 1011014; CONTAINER_ID 10071; }
	}
}
