CONTAINER Mtoonup
{
	NAME Mtoonup;

	INCLUDE Mpreview;
	INCLUDE Moutliner;

	HIDE OUTLINEMAT_GROUP_LINE;

	HIDE OUTLINEMAT_ADV_BACKBLEND;
	HIDE OUTLINEMAT_GROUP_SHADING;

	HIDE OUTLINEMAT_SCENE_AA;
	HIDE OUTLINEMAT_SCENE_SCALE;
	HIDE OUTLINEMAT_PIXELUNITS_INDEPENDENT;
	HIDE OUTLINEMAT_PIXELUNITS_INDEPENDENT_MODE;
	HIDE OUTLINEMAT_PIXELUNITS_BASEW;
	HIDE OUTLINEMAT_PIXELUNITS_BASEH;
	HIDE OUTLINEMAT_PIXELUNITS_ASEDITOR;
	HIDE OUTLINEMAT_PIXELUNITS_ASRENDER;
	HIDE OUTLINEMAT_SCENE_INEX_MODE;
	HIDE OUTLINEMAT_SCENE_INEXCLUDE;
	HIDE OUTLINEMAT_SCENE_POSTRENDER;
	HIDE OUTLINEMAT_SCENE_VOLUMETRIC;

	GROUP OUTLINEMAT_GROUP_BASIC
	{
		SEPARATOR { LINE; }
		STATICTEXT { JOINEND; }
		STATICTEXT { JOINENDSCALE; }
		STATICTEXT { NEWLINE; }

		STRING OUTLINEMAT_NOTES { CUSTOMGUI MULTISTRING; WORDWRAP; }
		STATICTEXT { JOINEND; }
		STATICTEXT { JOINENDSCALE; }
		STATICTEXT { NEWLINE; }
	}
}
