CONTAINER Osketch
{
	NAME Osketch;
	INCLUDE Obase;
	INCLUDE Moutliner;

	HIDE OUTLINEMAT_GROUP_BASIC;
	HIDE OUTLINEMAT_GROUP_BRUSH;
	HIDE OUTLINEMAT_GROUP_THICKNESS;
	HIDE OUTLINEMAT_GROUP_OPACITY;
	HIDE OUTLINEMAT_GROUP_DISTORTION;
	HIDE OUTLINEMAT_GROUP_ANIMATE;
	HIDE OUTLINEMAT_GROUP_ASSIGN;
	HIDE OUTLINEMAT_GROUP_SHADING;
	HIDE OUTLINEMAT_GROUP_SCENE;
	SHOW OUTLINEMAT_GROUP_DISTORTION;
	HIDE OUTLINEMAT_LINE_DEFAULT_MAT_V;
	HIDE OUTLINEMAT_LINE_DEFAULT_MAT_H;
	HIDE OUTLINEMAT_LINE_INDIVIDUALMATS;
	HIDE OUTLINEMAT_LINE_PARTICLES;
	HIDE OUTLINEMAT_LINE_SPLINES;
	HIDE OUTLINEMAT_LINE_MOTION;
	HIDE OUTLINEMAT_LINE_MATERIAL;
	HIDE OUTLINEMAT_GROUP_ADJUSTMENT_HSV;
	HIDE OUTLINEMAT_CLONE_COLOUR_H_VAR;
	HIDE OUTLINEMAT_CLONE_COLOUR_S_VAR;
	HIDE OUTLINEMAT_CLONE_COLOUR_V_VAR;

	GROUP ID_OBJECTPROPERTIES
	{
		GROUP
		{
			COLUMNS 1;

			IN_EXCLUDE  ID_ST_OBJECT_OBJECTS
			{
				NUM_FLAGS 2; INIT_STATE 3; SEND_SELCHNGMSG 1; SCALE_V;

				IMAGE_01_ON 1009316; IMAGE_01_OFF 1009320;
				IMAGE_02_ON 300000231; IMAGE_02_OFF 300000230;

				ACCEPT { Obase; }
			}

			BOOL ID_ST_OBJECT_LINE_HIDDEN {}
			BOOL ID_ST_OBJECT_LINE_VISIBLE {}

			SEPARATOR { LINE; }
						
			LONG ID_ST_OBJECT_SPLINE_TYPE
			{
				CYCLE
				{
					ID_ST_OBJECT_SPLINE_TYPE_LINEAR;
					ID_ST_OBJECT_SPLINE_TYPE_CUBIC;
					ID_ST_OBJECT_SPLINE_TYPE_AKIMA;
					ID_ST_OBJECT_SPLINE_TYPE_BSPLINE;
					ID_ST_OBJECT_SPLINE_TYPE_BEZIER;
				}
			}
			
			LONG ID_ST_OBJECT_SPLINE_INTERPOLATION
			{
				CYCLE
				{
					ID_ST_OBJECT_SPLINE_INTERPOLATION_NONE;
					ID_ST_OBJECT_SPLINE_INTERPOLATION_NATURAL;
					ID_ST_OBJECT_SPLINE_INTERPOLATION_UNIFORM;
					ID_ST_OBJECT_SPLINE_INTERPOLATION_ADAPTIVE;
					ID_ST_OBJECT_SPLINE_INTERPOLATION_SUBDIVIDED;
				}
			}
			
			LONG ID_ST_OBJECT_SPLINE_SUBD { MIN 0; MAX 5000; }
			REAL ID_ST_OBJECT_SPLINE_ANGLE { UNIT DEGREE; MIN 0.0; MAX 90.0; }
			REAL ID_ST_OBJECT_SPLINE_LENGTH { UNIT METER; MIN 0.01; }
		}
	}

	GROUP ID_ST_OBJECT_GROUP_SELECTIONS
	{
		LONG ID_ST_OBJECT_LINES_MODE
		{
			CYCLE
			{
				ID_ST_OBJECT_LINES_MODE_INCLUDE;
				ID_ST_OBJECT_LINES_MODE_EXCLUDE;
			}
		}

		IN_EXCLUDE  ID_ST_OBJECT_LINES
		{
			NUM_FLAGS 0; INIT_STATE 0; SEND_SELCHNGMSG 1; SCALE_V;

			ACCEPT { Tpolygonselection; Tedgeselection; }
		}

		SEPARATOR { LINE; }

		IN_EXCLUDE  ID_ST_OBJECT_BORDER
		{
			NUM_FLAGS 0; INIT_STATE 0; SEND_SELCHNGMSG 1; SCALE_V;

			ACCEPT { Tpolygonselection; }
		}

		IN_EXCLUDE  ID_ST_OBJECT_EDGES
		{
			NUM_FLAGS 0; INIT_STATE 0; SEND_SELCHNGMSG 1; SCALE_V;

			ACCEPT { Tedgeselection; }
		}

		IN_EXCLUDE  ID_ST_OBJECT_UVW
		{
			NUM_FLAGS 0; INIT_STATE 0; SEND_SELCHNGMSG 1; SCALE_V;

			ACCEPT { 5671; }
		}
	}
}
