CONTAINER Tignoreobj
{
	NAME Tignoreobj;
	INCLUDE Tbase;

	GROUP Obaselist
	{
		DEFAULT 1;

		BOOL OUTLINEITAG_INCCHILDREN {}

		SEPARATOR { }

		BOOL OUTLINEITAG_TOONALLOWED {}
		BOOL OUTLINEITAG_SHADERALLOWED {}

		SEPARATOR { }

		LONG OUTLINEITAG_MODE
		{
			CYCLE
			{
				OUTLINEITAG_MODE_IGNORECULL;
				OUTLINEITAG_MODE_CULLINSIDE;
			}
		}

		IN_EXCLUDE  OUTLINEITAG_TAGLIST
		{
			NUM_FLAGS 0; INIT_STATE 0; SEND_SELCHNGMSG 1;
			ACCEPT { 1011012; };
		}
	}
}
