CONTAINER Toutliner
{
	NAME Toutliner;

	INCLUDE Moutliner;

	HIDE TOONRESTRICT_MATERIAL;

	HIDE OUTLINEMAT_PRESET;
	HIDE OUTLINEMAT_PRESET_ADD;
	HIDE OUTLINEMAT_MATERIALS;
	HIDE OUTLINEMAT_SCENE_PIXELUNITS;
	HIDE OUTLINEMAT_PRESET_LOAD;
	HIDE OUTLINEMAT_PRESET_SAVE;

	HIDE OUTLINEMAT_LINE_OUTLINE_SHOW;
	SHOW OUTLINEMAT_LINE_COMBINEMODE;

	HIDE OUTLINEMAT_SHADING_BACK;
	HIDE OUTLINEMAT_SHADING_BACK_COL;
	HIDE OUTLINEMAT_SHADING_BACK_TEX;
	HIDE OUTLINEMAT_SHADING_ALLTOON;
	HIDE OUTLINEMAT_SHADING_INEX_MODE;
	HIDE OUTLINEMAT_SHADING_INEXCLUDE;
	SHOW OUTLINEMAT_SHADING_ENABLE;
	HIDE OUTLINEMAT_SHADING_BACK_ALPHA;
	HIDE OUTLINEMAT_SHADING_BACK_ALPHA_STRENGTH;
	HIDE OUTLINEMAT_SHADING_BACK_TEX_ALPHA;
	HIDE OUTLINEMAT_SHADING_BACK_ALPHALINES;
	HIDE OUTLINEMAT_SHADING_BACK_ALPHAOBJECTS;

	HIDE OUTLINEMAT_GROUP_SCENE;
	SHOW OUTLINEMAT_GROUP_LINE;
	HIDE OUTLINEMAT_GROUP_STROKE;
	HIDE OUTLINEMAT_GROUP_BRUSH;
	HIDE OUTLINEMAT_GROUP_THICKNESS;
	HIDE OUTLINEMAT_GROUP_OPACITY;
	HIDE OUTLINEMAT_GROUP_DISTORTION;
	HIDE OUTLINEMAT_GROUP_ANIMATE;
	HIDE OUTLINEMAT_GROUP_CLONE;
	HIDE OUTLINEMAT_GROUP_ADJUSTMENT;
	HIDE OUTLINEMAT_GROUP_ASSIGN;

	HIDE OUTLINEMAT_PAGE_SCENE;
	HIDE OUTLINEMAT_PAGE_PREVIEW;
	HIDE OUTLINEMAT_PAGE_ASSIGN;

	HIDE OUTLINEMAT_PRIORITY;

	GROUP OUTLINEMAT_GROUP_BASIC
	{
		COLUMNS 3;

		BOOL TOONRESTRICT_ENABLE {}
		STATICTEXT { NEWLINE; }

		BOOL TOONRESTRICT_GROUPING_INCCHILDREN {}
		STATICTEXT { NEWLINE; }
		
		SEPARATOR { LINE; }
		STATICTEXT { JOINEND; }
		STATICTEXT { JOINENDSCALE; }
		STATICTEXT { NEWLINE; }

		LONG TOONRESTRICT_MIX
		{
			CYCLE
			{
				TOONRESTRICT_MIX_REPLACE;
				TOONRESTRICT_MIX_REPLACE_LINES;
				TOONRESTRICT_MIX_ADD;
				TOONRESTRICT_MIX_SET;
			}
		}
		STATICTEXT { NEWLINE; }

		SEPARATOR { LINE; }
		STATICTEXT { JOINEND; }
		STATICTEXT { JOINENDSCALE; }

		GROUP
		{
			COLUMNS 2;

			BUTTON TOONUP_STYLE_LOAD { }
			BUTTON TOONUP_STYLE_SAVE { }
		}
	}

	GROUP TOONRESTRICT_GROUP
	{
		COLUMNS 1;

		LONG TOONRESTRICT_LINES_RESTRICT_MODE
		{
			CYCLE
			{
				TOONRESTRICT_LINES_RESTRICT_MODE_INCLUDE;
				TOONRESTRICT_LINES_RESTRICT_MODE_EXCLUDE;
			}
		}

		IN_EXCLUDE  TOONRESTRICT_LINES_RESTRICT {	NUM_FLAGS 0; INIT_STATE 0; SEND_SELCHNGMSG 1; ACCEPT { Tpolygonselection; Tedgeselection; }; }
		
		SEPARATOR { LINE; }

		IN_EXCLUDE  TOONRESTRICT_BORDER_RESTRICT {	NUM_FLAGS 0; INIT_STATE 0; SEND_SELCHNGMSG 1; ACCEPT { Tpolygonselection; }; }
		IN_EXCLUDE  TOONRESTRICT_EDGES_RESTRICT {	NUM_FLAGS 0; INIT_STATE 0; SEND_SELCHNGMSG 1; ACCEPT { Tedgeselection; }; }
		IN_EXCLUDE  TOONRESTRICT_CONTOUR_UVW {	NUM_FLAGS 0; INIT_STATE 0; SEND_SELCHNGMSG 1; ACCEPT { 5671; }; }
		IN_EXCLUDE  TOONRESTRICT_MOTION_SELECTIONS {	NUM_FLAGS 0; INIT_STATE 0; SEND_SELCHNGMSG 1; ACCEPT { Tpolygonselection; }; }
	}

	GROUP TOONRESTRICT_MAPS_GROUP
	{
		COLUMNS 1;

		LINK TOONRESTRICT_THICKNESS_MAP { ACCEPT { 5682; } }
		LINK TOONRESTRICT_OPACITY_MAP { ACCEPT { 5682; } }
		LINK TOONRESTRICT_NOISE_MAP { ACCEPT { 5682; } }
	}
}
