CONTAINER Ttoonupprefs
{
	NAME Ttoonupprefs;

		GROUP TOONUP_PREFS_MAIN_GROUP
		{
			COLUMNS 2; DEFAULT 1;
		
			BOOL TOONUP_PREFS_SETUP_AUTOVP { }
			STATICTEXT {}
			BOOL TOONUP_PREFS_SETUP_AUTOADDVPMAT { }
			STATICTEXT {}
			BOOL TOONUP_PREFS_SETUP_AUTOADDTAGMAT { }
			STATICTEXT {}

			SEPARATOR { LINE; }
			STATICTEXT {JOINENDSCALE;}

			LONG TOONUP_PREFS_PREVIEW_BACKGROUND
			{
				CYCLE
				{
					TOONUP_PREFS_PREVIEW_BACKGROUND_DEFAULT;
					TOONUP_PREFS_PREVIEW_BACKGROUND_WHITE;
					TOONUP_PREFS_PREVIEW_BACKGROUND_BLACK;
					TOONUP_PREFS_PREVIEW_BACKGROUND_SHADED;
				}
			}
			STATICTEXT {}

			LONG TOONUP_PREFS_PREVIEW_OBJECT
			{
				CYCLE
				{
					TOONUP_PREFS_PREVIEW_OBJECT_DEFAULT;
					TOONUP_PREFS_PREVIEW_OBJECT_WHITE;
					TOONUP_PREFS_PREVIEW_OBJECT_BLACK;
					TOONUP_PREFS_PREVIEW_OBJECT_TRANS;
					TOONUP_PREFS_PREVIEW_OBJECT_SHADED;
				}
			}

			SEPARATOR { }
			STATICTEXT {JOINENDSCALE;}
			
			LONG TOONUP_PREFS_PREVIEW
			{
				CYCLE
				{
					TOONUP_PREFS_PREVIEW_STANDARD;
					TOONUP_PREFS_PREVIEW_CUBE;
					TOONUP_PREFS_PREVIEW_ROUNDCUBE;
					TOONUP_PREFS_PREVIEW_PLANE;
					TOONUP_PREFS_PREVIEW_CYLINDER;
					TOONUP_PREFS_PREVIEW_TORUS;
					TOONUP_PREFS_PREVIEW_PLANEBACK;
					TOONUP_PREFS_PREVIEW_SPHERE;
					TOONUP_PREFS_PREVIEW_DOUBLETORUS;
					TOONUP_PREFS_PREVIEW_KNOT;
					TOONUP_PREFS_PREVIEW_STROKE;
					TOONUP_PREFS_PREVIEW_CUSTOM;
				}
			}
			STATICTEXT {}
			LONG TOONUP_PREFS_CUSTOMPREVIEW
			{
				CYCLE
				{
				}
			}
			STATICTEXT {}
		}
}
