CONTAINER VPtoonup
{
	NAME VPtoonup;
	INCLUDE Toutliner;

	HIDE Obaselist;

	HIDE TOONRESTRICT_GROUP;
	HIDE TOONRESTRICT_MAPS_GROUP;

	HIDE TOONRESTRICT_ENABLE;
	HIDE TOONRESTRICT_GROUPING_INCCHILDREN;
	HIDE TOONRESTRICT_MIX;

	HIDE OUTLINEMAT_STOKECLIP_TOSCREEN;
	HIDE OUTLINEMAT_LINE_RENDERCLIP;
	HIDE OUTLINEMAT_LINE_RENDERCLIP_SELF;
	HIDE OUTLINEMAT_LINE_RENDERCLIP_MODE;
	HIDE OUTLINEMAT_LINE_RENDERCLIP_OBJECTS;

	HIDE OUTLINEMAT_LINE_RENDERCULL_TYPE;
	HIDE OUTLINEMAT_LINE_RENDERCULL_MODE;
	HIDE OUTLINEMAT_LINE_RENDERCULL_SELF;
	HIDE OUTLINEMAT_LINE_RENDERCULL_OBJECTS;
	HIDE OUTLINEMAT_LINE_RENDERCULL_QUALITY;

	HIDE OUTLINEMAT_SCENE_SEED;
	HIDE OUTLINEMAT_SCENE_SEED_STATIC;
	HIDE OUTLINEMAT_CAMERACLIP_MINZ;
	HIDE OUTLINEMAT_CAMERACLIP_MAXZ;
	HIDE OUTLINEMAT_GROUP_ASSIGN;

	SHOW OUTLINEMAT_GROUP_SCENE;

	SHOW OUTLINEMAT_SHADING_BACK;
	SHOW OUTLINEMAT_SHADING_BACK_COL;
	SHOW OUTLINEMAT_SHADING_BACK_TEX;
	SHOW OUTLINEMAT_SHADING_ALLTOON;
	SHOW OUTLINEMAT_SHADING_INEX_MODE;
	SHOW OUTLINEMAT_SHADING_INEXCLUDE;

	SHOW OUTLINEMAT_CAMERACLIP_MINZ;
	SHOW OUTLINEMAT_CAMERACLIP_FAR;
	SHOW OUTLINEMAT_CAMERACLIP_MAXZ;

	HIDE OUTLINEMAT_SHADING_ENABLE;
	SHOW OUTLINEMAT_GROUP_EDITORLINES;
	HIDE OUTLINEMAT_PRIORITY;

	HIDE OUTLINEMAT_ADV_SELFBLENDMODE;
	HIDE OUTLINEMAT_ADV_BLENDMODE;
	HIDE OUTLINEMAT_SCENE_PIXELUNITS;

	HIDE OUTLINEMAT_LINE_MATERIAL_MODE;
	HIDE OUTLINEMAT_LINE_MATERIAL_COMBINE;
	HIDE OUTLINEMAT_LINE_MATERIAL_TAGS;

	SHOW OUTLINEMAT_GROUP_MULTIPASS;
	HIDE OUTLINEMAT_MULTIPASS_RGB;
}
