CONTAINER Xartshader
{
	NAME Xartshader;

	INCLUDE Mpreview;
	INCLUDE Xbase;

	GROUP ID_SHADERPROPERTIES
	{
		SHADERLINK ARTSHADER_TEXTURE { }

		GROUP
		{
			COLUMNS 2;

			BOOL ARTSHADER_BUMP { }
			LONG ARTSHADER_SPACE
			{
				CYCLE
				{
					ARTSHADER_SPACE_WORLD;
					ARTSHADER_SPACE_CAMERA;
					ARTSHADER_SPACE_NORMAL;
				}
			}
		}

		GROUP
		{
			COLUMNS 2;

			REAL ARTSHADER_SCALE { UNIT PERCENT; MIN 0.0; }
			REAL ARTSHADER_ROTATE { UNIT DEGREE; MIN -360.0; MAX 360.0; }

			REAL ARTSHADER_SCALE_U { UNIT PERCENT; MIN 0.0; }
			REAL ARTSHADER_SCALE_V { UNIT PERCENT; MIN 0.0; }
		}

		BOOL ARTSHADER_SHADOW { }
		SHADERLINK ARTSHADER_SHADOW_TEXTURE { }

		BOOL ARTSHADER_BACKFACE { }
		SHADERLINK ARTSHADER_BACKFACE_TEXTURE { }
		
	}
}