CONTAINER Xcelshader
{
	NAME Xcelshader;

	INCLUDE Mpreview;
	INCLUDE Xbase;

	GROUP ID_SHADERPROPERTIES
	{
		COLUMNS 1;

		GRADIENT CELSHADER_SHADOW { COLOR; ICC_BASEDOCUMENT; }
		GRADIENT CELSHADER_DIFFUSE { COLOR; ICC_BASEDOCUMENT; }
		GRADIENT CELSHADER_SPEC { COLOR; ICC_BASEDOCUMENT; }
		GRADIENT CELSHADER_ILLUM { ALPHA; ICC_BASEDOCUMENT; }

		GROUP
		{
			COLUMNS 3;

			BOOL CELSHADER_BUMP { }
			BOOL CELSHADER_BACKFACE { }
			SEPARATOR { }

			SEPARATOR { }
			SEPARATOR { }
			STATICTEXT { NEWLINE; }
		
			BOOL CELSHADER_CAMERA { }
			BOOL CELSHADER_LIGHTS { }
			BOOL CELSHADER_SPECULAR { }

			BOOL CELSHADER_ILLUMINATION { }
			BOOL CELSHADER_LIGHTSCOL { }
			BOOL CELSHADER_SHADOWS { }
		}

		SEPARATOR { }

		GROUP
		{
			COLUMNS 2;

			LONG CELSHADER_SHADOWSTYPE
			{
				CYCLE
				{
					CELSHADER_SHADOWSTYPE_MULTIPLY;
					CELSHADER_SHADOWSTYPE_COLOR;
					CELSHADER_SHADOWSTYPE_LIGHTS;
				}
			}

			SEPARATOR { }

			LONG CELSHADER_SHADOWSMODE
			{
				CYCLE
				{
					CELSHADER_SHADOWSMODE_NORMAL;
					CELSHADER_SHADOWSMODE_H;
					CELSHADER_SHADOWSMODE_S;
					CELSHADER_SHADOWSMODE_V;
				}
			}

			BOOL CELSHADER_SHADOWSMODE_INV {}

			SEPARATOR { }
			STATICTEXT { NEWLINE; }

			LONG CELSHADER_INCEXC
			{
				CYCLE
				{
					CELSHADER_INCEXC_INCLUDE;
					CELSHADER_INCEXC_EXCLUDE;
				}
			}
		}

		IN_EXCLUDE  CELSHADER_INCEXC_LIGHTS
		{
			NUM_FLAGS 0; INIT_STATE 0; SEND_SELCHNGMSG 1;
			ACCEPT { Olight; };
		}
	}
}