CONTAINER Xspotshader
{
	NAME Xspotshader;

	INCLUDE Mpreview;
	INCLUDE Xbase;

	GROUP ID_SHADERPROPERTIES
	{
		LONG SPOTSHADER_GAP_SHAPE
		{
			DEFAULT 1;

			CYCLE
			{
				SPOTSHADER_GAP_SHAPE_CIRCLE;
				SPOTSHADER_GAP_SHAPE_DIAMOND;
				SPOTSHADER_GAP_SHAPE_CHECKER;
				SPOTSHADER_GAP_SHAPE_SQUARE;
				SPOTSHADER_GAP_SHAPE_ULINES;
				SPOTSHADER_GAP_SHAPE_VLINES;
				SPOTSHADER_GAP_SHAPE_GRID;
				SPOTSHADER_GAP_SHAPE_TEXTURE;
			}
		}

		SHADERLINK SPOTSHADER_GAP_TEXTURE { }

		COLOR SPOTSHADER_GAP_COLOR { OPEN; }
		COLOR SPOTSHADER_CIRCLE_COLOR { OPEN; }

		SEPARATOR { }

		GROUP
		{
			COLUMNS 3;

			REAL SPOTSHADER_SCALE { UNIT PERCENT; MIN 0.0; }
			REAL SPOTSHADER_SCALE_U { UNIT PERCENT; MIN 0.0; }
			REAL SPOTSHADER_SCALE_V { UNIT PERCENT; MIN 0.0; }
		}

		REAL SPOTSHADER_ROTATE { UNIT DEGREE; MIN 0.0; MAX 360.0; }

		SEPARATOR { }

		GRADIENT SPOTSHADER_SHADOW { ALPHA; ICC_BASEDOCUMENT; }
		GRADIENT SPOTSHADER_DIFFUSE { ALPHA; ICC_BASEDOCUMENT; }
		GRADIENT SPOTSHADER_SPEC { ALPHA; ICC_BASEDOCUMENT; }
		GRADIENT SPOTSHADER_ILLUM { ALPHA; ICC_BASEDOCUMENT; }

		SEPARATOR { }
		
		GROUP
		{
			COLUMNS 3;

			BOOL SPOTSHADER_CAMERA { }
			BOOL SPOTSHADER_LIGHTS { }
			BOOL SPOTSHADER_SPECULAR { }

			BOOL SPOTSHADER_ILLUMINATION { }
			BOOL SPOTSHADER_SHADOWS { }
			BOOL SPOTSHADER_INVERT { }
		}

		LONG SPOTSHADER_INCEXC
		{
			CYCLE
			{
				SPOTSHADER_INCEXC_INCLUDE;
				SPOTSHADER_INCEXC_EXCLUDE;
			}
		}

		IN_EXCLUDE  SPOTSHADER_INCEXC_LIGHTS
		{
			NUM_FLAGS 0; INIT_STATE 0; SEND_SELCHNGMSG 1;
			ACCEPT { Olight; };
		}
	}
}