#ifndef C4D_SYMBOLS_H
#define C4D_SYMBOLS_H

enum
{
	__FIRST_ELEMENT__ = 10000,

	IDS_MENU_HOUDINI_ENGINE,
	IDS_HOUDINI_SCENE_LOADER,

	IDS_COMMAND_LOAD_ASSET_NAME,									// Load Asset command name
	IDS_COMMAND_LOAD_ASSET_HELP,									// Load Asset command help
	IDS_COMMAND_LOAD_ASSET_TITLE,									// Load Asset file selection dialog title
	IDS_COMMAND_SAVE_SCENE_NAME,									// Save Houdini Scene command name
	IDS_COMMAND_SAVE_SCENE_HELP,									// Save Houdini Scene command help
	IDS_COMMAND_SAVE_SCENE_TITLE,									// Save Houdini Scene file selection dialog title
	IDS_COMMAND_GET_ASSETS_FROM_ORBOLT_NAME,			// Get Assets From Orbolt command name
	IDS_COMMAND_GET_ASSETS_FROM_ORBOLT_HELP,			// Get Assets From Orbolt command help

	IDS_STATUS_CREATING_OBJECTS,

	IDS_HOUDINI_GENERATOR,

	IDS_HOUDINI_GENERATOR_ASSET,
	IDS_HOUDINI_GENERATOR_OBJECT,

	IDS_HOUDINI_INPUTS,
	IDS_HOUDINI_PARAMETERS,

	IDS_PREFS_INSTALLATION_STATUS_FOUND,
	IDS_PREFS_INSTALLATION_STATUS_NOT_FOUND,

	IDS_PREFS_LICENSE_TYPE_UNCONFIRMED,
	IDS_PREFS_LICENSE_TYPE_NONE,
	IDS_PREFS_LICENSE_TYPE_HOUDINI,
	IDS_PREFS_LICENSE_TYPE_HOUDINI_ENGINE,
	IDS_PREFS_LICENSE_TYPE_HOUDINI_FX,
	IDS_PREFS_LICENSE_TYPE_HOUDINI_ENGINE_INDIE,
	IDS_PREFS_LICENSE_TYPE_HOUDINI_INDIE,
	IDS_PREFS_LICENSE_TYPE_HOUDINI_EDUCATION,
	IDS_PREFS_LICENSE_TYPE_HOUDINI_APPRENTICE,
	IDS_PREFS_LICENSE_TYPE_HOUDINI_UNKNOWN,

	IDS_LICENSE_TYPE_NOT_FOUND,
	IDS_LICENSE_TYPE_APPRENTICE,
	
	IDS_LICENSE_ASSET_LEVEL_INCOMPATIBLE,
	IDS_LICENSE_ASSET_LEVEL_LC,
	IDS_LICENSE_ASSET_LEVEL_NC,

	IDS_ASSET_INSTANTIATION_FAILURE,

	IDS_PREFS_LICENSE_STATUS_UNINITIALIZED,
	IDS_PREFS_LICENSE_STATUS_INITIALIZED,

	IDS_HOUDINI_INFO_INSTANCE_ID,
	IDS_HOUDINI_INFO_OBJECT_ID,
	IDS_HOUDINI_INFO_GEO_ID,
	IDS_HOUDINI_INFO_PART_ID,

	// Multi-asset selection dialog
	DLG_ASSETSELECTION,
	GADGET_LISTVIEW_GROUP,
	GADGET_LISTVIEW,
	SELECT_ALL,
	DESELECT_ALL,

	IDS_COMMAND_GET_MORE_INFORMATION_NAME,				// Get More Information command name
	IDS_COMMAND_GET_MORE_INFORMATION_HELP,				// Get More Information command help
	
	IDS_STATUS_LOADING_ASSET,
	IDS_STATUS_COOKING_ASSET,

	IDS_STATUS_LOADING_ASSET_NO_ESC,
	IDS_STATUS_COOKING_ASSET_NO_ESC,

	IDS_DESC_NAME_INCLUDE_CHILDREN,
	IDS_DESC_NAME_INCLUDE_PARTICLE_SUB_GROUPS,
	
	// End of symbol definition
	_DUMMY_ELEMENT_
};

#endif /* C4D_SYMBOLS_H */