#ifndef C4D_SYMBOLS_H__
#define C4D_SYMBOLS_H__

enum
{
		// string table definitions

		IDS_START = 50000,

		// nurbs library ....

		IDS_BASEGROUP,
		IDS_BASECURVE,
		IDS_BASESURFACE,
		IDS_MAPPEDCURVE,
		IDS_TRIMMEDSURFACE,
		IDS_NURBSCURVE,
		IDS_POLYNOMCURVE,
		IDS_LINEARCURVE,
		IDS_CIRCULARCURVE,
		IDS_CONICCURVE,
		IDS_COMPOSITECURVE,
		IDS_NURBSSURFACE,
		IDS_POLYNOMSURFACE,
		IDS_PLANARSURFACE,
		IDS_EXTRUDESURFACE,
		IDS_ROTATESURFACE,

		DUMMY_DWG_OBJECTS
};

#endif // C4D_SYMBOLS_H__
