CONTAINER Tcameramapping
{
	NAME Tcameramapping;
	INCLUDE Texpression;

	GROUP CM_GROUP_IMAGE
	{
		GROUP
		{
			// COLUMNS 3;
			FILENAME CM_IMAGE_FILENAME { ANIM OFF; FIT_H; SCALE_H; }
			// BUTTON CM_IMAGE_RESET {}
			// BUTTON CM_IMAGE_RELOAD {}
		}
		GROUP
		{
			COLUMNS 3;
			REAL CM_RDATA_FILMASPECT { ANIM OFF; STEP 0.01; MIN 0.001; MAX 1000.0; }
			LONG CM_RDATA_FILMPRESET { ANIM OFF; CYCLE { CM_RDATA_FILMPRESET_CUSTOM; CM_RDATA_FILMPRESET_SQUARE; CM_RDATA_FILMPRESET_STANDARD; CM_RDATA_FILMPRESET_HDTV; CM_RDATA_FILMPRESET_35MMSTILL; CM_RDATA_FILMPRESET_WIDESCREEN; CM_RDATA_FILMPRESET_35MM; CM_RDATA_FILMPRESET_PANAVISION; } }
			STATICTEXT CM_RDATA_RENDER_FILM_ASPECT { FIT_H; SCALE_H; }
		}

		SEPARATOR { LINE; }

		// PHLENS Lens Distortion support - needed in all elements which support usage of lenses.
		GROUP CM_GROUP_LENS_DISTORTION
		{
			FILENAME CM_LENS_PROFILE_FILENAME { ANIM OFF; FIT_H; SCALE_H; PARENTCOLLAPSE; } // Add OPEN to make fold-out default to open
			STATICTEXT CM_LENS_PROFILE_TYPE { PARENTCOLLAPSE CM_LENS_PROFILE_FILENAME; }
			GROUP
			{
				COLUMNS 6; FIT_H; SCALE_H;
				STATICTEXT CM_LENS_PARAM_RC_00 { FIT_H; SCALE_H; PARENTCOLLAPSE CM_LENS_PROFILE_FILENAME; }
				STATICTEXT CM_LENS_PARAM_RC_01 { FIT_H; SCALE_H; PARENTCOLLAPSE CM_LENS_PROFILE_FILENAME; }
				STATICTEXT CM_LENS_PARAM_RC_02 { FIT_H; SCALE_H; PARENTCOLLAPSE CM_LENS_PROFILE_FILENAME; }
				STATICTEXT CM_LENS_PARAM_RC_03 { FIT_H; SCALE_H; PARENTCOLLAPSE CM_LENS_PROFILE_FILENAME; }
				STATICTEXT CM_LENS_PARAM_RC_04 { FIT_H; SCALE_H; PARENTCOLLAPSE CM_LENS_PROFILE_FILENAME; }
				STATICTEXT CM_LENS_PARAM_RC_05 { FIT_H; SCALE_H; PARENTCOLLAPSE CM_LENS_PROFILE_FILENAME; }

				STATICTEXT CM_LENS_PARAM_RC_10 { FIT_H; SCALE_H; PARENTCOLLAPSE CM_LENS_PROFILE_FILENAME; }
				STATICTEXT CM_LENS_PARAM_RC_11 { FIT_H; SCALE_H; PARENTCOLLAPSE CM_LENS_PROFILE_FILENAME; }
				STATICTEXT CM_LENS_PARAM_RC_12 { FIT_H; SCALE_H; PARENTCOLLAPSE CM_LENS_PROFILE_FILENAME; }
				STATICTEXT CM_LENS_PARAM_RC_13 { FIT_H; SCALE_H; PARENTCOLLAPSE CM_LENS_PROFILE_FILENAME; }
				STATICTEXT CM_LENS_PARAM_RC_14 { FIT_H; SCALE_H; PARENTCOLLAPSE CM_LENS_PROFILE_FILENAME; }
				STATICTEXT CM_LENS_PARAM_RC_15 { FIT_H; SCALE_H; PARENTCOLLAPSE CM_LENS_PROFILE_FILENAME; }

				STATICTEXT CM_LENS_PARAM_RC_20 { FIT_H; SCALE_H; PARENTCOLLAPSE CM_LENS_PROFILE_FILENAME; }
				STATICTEXT CM_LENS_PARAM_RC_21 { FIT_H; SCALE_H; PARENTCOLLAPSE CM_LENS_PROFILE_FILENAME; }
				STATICTEXT CM_LENS_PARAM_RC_22 { FIT_H; SCALE_H; PARENTCOLLAPSE CM_LENS_PROFILE_FILENAME; }
				STATICTEXT CM_LENS_PARAM_RC_23 { FIT_H; SCALE_H; PARENTCOLLAPSE CM_LENS_PROFILE_FILENAME; }
				STATICTEXT CM_LENS_PARAM_RC_24 { FIT_H; SCALE_H; PARENTCOLLAPSE CM_LENS_PROFILE_FILENAME; }
				STATICTEXT CM_LENS_PARAM_RC_25 { FIT_H; SCALE_H; PARENTCOLLAPSE CM_LENS_PROFILE_FILENAME; }

				STATICTEXT CM_LENS_PARAM_RC_30 { FIT_H; SCALE_H; PARENTCOLLAPSE CM_LENS_PROFILE_FILENAME; }
				STATICTEXT CM_LENS_PARAM_RC_31 { FIT_H; SCALE_H; PARENTCOLLAPSE CM_LENS_PROFILE_FILENAME; }
				STATICTEXT CM_LENS_PARAM_RC_32 { FIT_H; SCALE_H; PARENTCOLLAPSE CM_LENS_PROFILE_FILENAME; }
				STATICTEXT CM_LENS_PARAM_RC_33 { FIT_H; SCALE_H; PARENTCOLLAPSE CM_LENS_PROFILE_FILENAME; }
				STATICTEXT CM_LENS_PARAM_RC_34 { FIT_H; SCALE_H; PARENTCOLLAPSE CM_LENS_PROFILE_FILENAME; }
				STATICTEXT CM_LENS_PARAM_RC_35 { FIT_H; SCALE_H; PARENTCOLLAPSE CM_LENS_PROFILE_FILENAME; }

				STATICTEXT CM_LENS_PARAM_RC_40 { FIT_H; SCALE_H; PARENTCOLLAPSE CM_LENS_PROFILE_FILENAME; }
				STATICTEXT CM_LENS_PARAM_RC_41 { FIT_H; SCALE_H; PARENTCOLLAPSE CM_LENS_PROFILE_FILENAME; }
				STATICTEXT CM_LENS_PARAM_RC_42 { FIT_H; SCALE_H; PARENTCOLLAPSE CM_LENS_PROFILE_FILENAME; }
				STATICTEXT CM_LENS_PARAM_RC_43 { FIT_H; SCALE_H; PARENTCOLLAPSE CM_LENS_PROFILE_FILENAME; }
				STATICTEXT CM_LENS_PARAM_RC_44 { FIT_H; SCALE_H; PARENTCOLLAPSE CM_LENS_PROFILE_FILENAME; }
				STATICTEXT CM_LENS_PARAM_RC_45 { FIT_H; SCALE_H; PARENTCOLLAPSE CM_LENS_PROFILE_FILENAME; }
			}
		STATICTEXT { PARENTCOLLAPSE CM_LENS_PROFILE_FILENAME; } // Blank line
		}

		GROUP
		{
			GROUP
			{
				LAYOUTGROUP; COLUMNS 2;
				GROUP
				{			
					REAL CM_IMAGE_VIEW_SCALE { ANIM OFF; STEP 1.0; MIN 1.0; MAX 10000.0; UNIT PERCENT;}
					REAL CM_IMAGE_VIEW_OFFSET_X { ANIM OFF; STEP 1.0; MIN -500.0; MAX 500.0; UNIT PERCENT;}
					BOOL CM_IMAGE_SHOW_IMAGE { ANIM OFF; }
				}
				GROUP
				{
					STATICTEXT {}
					REAL CM_IMAGE_VIEW_OFFSET_Y { ANIM OFF; STEP 1.0; MIN -500.0; MAX 500.0; UNIT PERCENT;}
					BOOL CM_IMAGE_USE_FOREGROUND_DISPLAY { ANIM OFF; }
				}
			}
			REAL CM_IMAGE_BRIGHTNESS { ANIM OFF; MIN 0.0; MAX 200.0; MINSLIDER 0.0; MAXSLIDER 200.0;  CUSTOMGUI REALSLIDER; UNIT PERCENT; }
			//  REAL CM_IMAGE_ROTATION { ANIM OFF; MIN -180.0; MAX 180.0; MINSLIDER -180.0; MAXSLIDER 180.0;  CUSTOMGUI REALSLIDER; UNIT DEGREE; }
		}

		SEPARATOR { LINE; }

		GROUP
		{
			COLUMNS 3;
			BUTTON CM_IMAGE_VIEW_FULL {}
			BUTTON CM_IMAGE_MATCH_VIEW_WIDTH {}
			BUTTON CM_IMAGE_MATCH_VIEW_HEIGHT {}
		}
	}


	GROUP CM_GROUP_CALIBRATE
	{
		GROUP
		{
			COLUMNS 3;
			BUTTON ADD_NEW_LINE {}
			BUTTON ADD_NEW_GRID {}
			BUTTON ADD_NEW_PIN {}
			BUTTON DELETE_LINE  {}
			BUTTON DELETE_GRID  {}
			BUTTON DELETE_PIN  {}
		}

		SEPARATOR { LINE; }
		GROUP
		{
			STATICTEXT IDC_SELECTED_STR {}
			STATICTEXT IDC_SELECTED_STATE { }
		}

		GROUP ID_LINEINTERNALS
		{
			GROUP
			{
				COLUMNS 4;
				STATICTEXT CM_LINE_AXIS_STR  {}
				BOOL CM_LINE_HAS_MEASUREMENT { ANIM OFF; }
				REAL CM_LINE_WORLD_LENGTH { ANIM OFF; UNIT METER; MIN 0.0;}
				STATICTEXT {}
			}

		}


		GROUP ID_GRIDINTERNALS
		{
			GROUP
			{
				COLUMNS 4;
				STATICTEXT CM_GRID_AXIS_A_STR {}
				BOOL CM_GRID_HAS_MEASUREMENT_A { ANIM OFF; }
				REAL CM_GRID_WORLD_LENGTH_A { ANIM OFF; UNIT METER; MIN 0.0;}
				STATICTEXT {}

				STATICTEXT CM_GRID_AXIS_B_STR {}
				BOOL CM_GRID_HAS_MEASUREMENT_B { ANIM OFF; }
				REAL CM_GRID_WORLD_LENGTH_B { ANIM OFF; UNIT METER; MIN 0.0;}
				STATICTEXT {}

				STATICTEXT CM_GRID_ASPECT_STR {}
				BOOL CM_GRID_HAS_ASPECT { ANIM OFF; }
				REAL CM_GRID_WORLD_ASPECT_A_OVER_B_USER { ANIM OFF; MIN 0.0; STEP 0.05; }
				STATICTEXT CM_GRID_WORLD_ASPECT_A_OVER_B_CAL {}
			}	
			GROUP ID_GRIDINTERNALS_INNER
			{
				COLUMNS 5;
				STATICTEXT CM_GRID_AXIS_AA_STR {}
				STATICTEXT CM_NUM_GRID_SEGMENTS_A_STR { }
				LONG CM_NUM_GRID_SEGMENTS_0 { MIN 1; MAX 100; }
				STATICTEXT CM_GRID_OFFSET_A_STR { }
				REAL CM_GRID_OFFSET_0 { MIN 0.0; MAX 100.0; STEP 1.0; UNIT PERCENT; }

				STATICTEXT CM_GRID_AXIS_BB_STR {}
				STATICTEXT CM_NUM_GRID_SEGMENTS_B_STR { }
				LONG CM_NUM_GRID_SEGMENTS_1 { MIN 1; MAX 100; }
				STATICTEXT CM_GRID_OFFSET_B_STR { }
				REAL CM_GRID_OFFSET_1 { MIN 0.0; MAX 100.0; STEP 1.0; UNIT PERCENT; }
			}
		}

		GROUP ID_PININTERNALS
		{

			GROUP
			{
				COLUMNS 2;
				STATICTEXT CM_PIN_COORDS_STR {}
				VECTOR CM_PIN_COORDS { ANIM OFF; UNIT METER; }
			}
		}

		SEPARATOR { LINE; }
		STATICTEXT IDC_STATUS_STR {}
		GROUP
		{
			GROUP
			{	
				COLUMNS 3;
				STATICTEXT IDC_X_VP_STR { }
				COLORBAR COLOR_X_VP_STATE { }
				VARTEXT IDC_X_VP_STATE { }

				STATICTEXT IDC_Y_VP_STR {  }
				COLORBAR COLOR_Y_VP_STATE { }
				VARTEXT IDC_Y_VP_STATE { }

				STATICTEXT IDC_Z_VP_STR {  }
				COLORBAR COLOR_Z_VP_STATE { }
				VARTEXT IDC_Z_VP_STATE { }

				//STATICTEXT IDC_CAMERA_CALIBRATOR_STATE_STR {  }
				//COLORBAR COLOR_CAMERA_CALIBRATOR_STATE { }
				//VARTEXT IDC_CAMERA_CALIBRATOR_STATE_2 { }

				STATICTEXT IDC_CAM_CAL_FOCAL_STATE_STR {  }
				COLORBAR COLOR_CAM_CAL_FOCAL_STATE { }
				VARTEXT IDC_CAM_CAL_FOCAL_STATE { }

				STATICTEXT IDC_CAM_CAL_ORIENTATION_STATE_STR {  }
				COLORBAR COLOR_CAM_CAL_ORIENTATION_STATE { }
				VARTEXT IDC_CAM_CAL_ORIENTATION_STATE { }

				STATICTEXT IDC_CAM_CAL_POS_STATE_STR {  }
				COLORBAR COLOR_CAM_CAL_POS_STATE { }
				VARTEXT IDC_CAM_CAL_POS_STATE { }
			}
			//STATICTEXT IDC_CAMERA_CALIBRATOR_STATE { }

			//STATICTEXT IDC_CAMERA_CALIBRATOR_FOCAL_LENGTH_NORMALISED { }
			STATICTEXT IDC_CAMERA_CALIBRATOR_FOCAL_LENGTH_35MM_EQUIV { }
		}

		SEPARATOR { LINE; }

		GROUP
		{
			COLUMNS 2;
			BUTTON CREATE_CAMERA_MAPPING_TEXTURE_TAG {}
			BUTTON CREATE_BACKGROUND_OBJECT {}
		}

	}

	GROUP CM_GROUP_SETTINGS
	{
		GROUP
		{
			BOOL CM_CALC_PP_WHEN_3VPS { ANIM OFF; }
			BOOL CM_LOUPE_USE_OFFSET { ANIM OFF; }
			REAL CM_LOUPE_MAGNIFICATION { ANIM OFF; STEP 1.0; MIN 100.0; MAX 1000.0; UNIT PERCENT;}
			REAL CM_LOUPE_SIZE_PIX { ANIM OFF; STEP 1.0; MIN 8.0; MAX 512.0;}
		}
	}

	GROUP CM_GROUP_LINKS
	{
		GROUP
		{
			SCALE_V;
			IN_EXCLUDE  LINKED_ELEMENT_LIST   { SCALE_V; NUM_FLAGS 0; ACCEPT { Ttexture; }; }
		}
	}
}
