CONTAINER Tphconstraintvector
{
  NAME Tphconstraintvector;
  INCLUDE Tbase;

  GROUP PH_SCENE_CAL_VECTOR
  { 
	DEFAULT 1;
	GROUP
	{
		GROUP
		{ 
			COLUMNS 2;
			LONG PH_SCENE_CAL_VECTOR_MODE { ANIM OFF; CYCLE { PH_SCENE_CAL_VECTOR_MODE_CAMTRACK; PH_SCENE_CAL_VECTOR_MODE_SELECT; } }
			STATICTEXT {}

			LONG PH_SCENE_CAL_VECTOR_AXIS { ANIM OFF; CYCLE { PH_SCENE_CAL_VECTOR_AXIS_NONE; PH_SCENE_CAL_VECTOR_AXIS_X; PH_SCENE_CAL_VECTOR_AXIS_Y; PH_SCENE_CAL_VECTOR_AXIS_Z; } }
			BOOL PH_SCENE_CAL_VECTOR_FLIP_AXIS { ANIM OFF; }

			LONG PH_SCENE_CAL_VECTOR_HAS_MEASUREMENT { ANIM OFF; CYCLE { PH_SCENE_CAL_VECTOR_WORLD_LENGTH_UNKNOWN; PH_SCENE_CAL_VECTOR_WORLD_LENGTH_KNOWN; } }
			REAL PH_SCENE_CAL_VECTOR_WORLD_LENGTH { ANIM OFF; UNIT METER; MIN 0.0;}
		}
	}

	GROUP PH_SCENE_CAL_VECTOR_TARGETS
	{ 
		GROUP
		{
			LINK PH_SCENE_CAL_VECTOR_TARGET_0 { ANIM OFF; FIT_H; SCALE_H; ACCEPT { Onull; } }
			LINK PH_SCENE_CAL_VECTOR_TARGET_1 { ANIM OFF; FIT_H; SCALE_H; ACCEPT { Onull; } }
		}
	}

	SEPARATOR { LINE; }
	BUTTON PH_SCENE_CAL_VECTOR_FORCE_EXPORT {}
  }
}
