CONTAINER Tphconstraintplanar
{
  NAME Tphconstraintplanar;
  INCLUDE Tbase;

  GROUP PH_SCENE_CAL_PLANAR
  { 
		DEFAULT 1;
			SCALE_V;
    GROUP
    {
			GROUP
			{ 
				COLUMNS 2;
				LONG PH_SCENE_CAL_PLANAR_MODE { ANIM OFF; CYCLE { PH_SCENE_CAL_PLANAR_MODE_CAMTRACK; PH_SCENE_CAL_PLANAR_MODE_SELECT; } }
				STATICTEXT {}

				LONG PH_SCENE_CAL_PLANAR_AXIS { ANIM OFF; CYCLE { PH_SCENE_CAL_PLANAR_AXIS_NONE; PH_SCENE_CAL_PLANAR_AXIS_X; PH_SCENE_CAL_PLANAR_AXIS_Y; PH_SCENE_CAL_PLANAR_AXIS_Z; } }
				BOOL PH_SCENE_CAL_PLANAR_FLIP_AXIS { ANIM OFF; }
			}

			GROUP PH_SCENE_CAL_PLANAR_TARGETS
			{ 
				DEFAULT 1;
				SCALE_V;
				GROUP
				{
					SCALE_V;
					IN_EXCLUDE  PH_SCENE_CAL_PLANAR_TARGET_SET { SCALE_V; NUM_FLAGS 0; INIT_STATE 0; ACCEPT { Onull; }; }
				}
				BUTTON PH_SCENE_CAL_PLANAR_CREATE_SCENE_PLANE {}
			}
		}

    SEPARATOR { LINE; }
    BUTTON PH_SCENE_CAL_PLANAR_FORCE_EXPORT {}
  }
}
