CONTAINER Tphconstraintmask
{
  NAME Tphconstraintmask;
  INCLUDE Tbase;

  GROUP PH_SCENE_CAL_MASK
  { 
	DEFAULT 1;
	GROUP
	{ 
		GROUP
		{ 
			COLUMNS 1;
			LONG PH_SCENE_CAL_MASK_ADDSUB_MODE { ANIM OFF; CYCLE { PH_SCENE_CAL_MASK_ADDSUB_MODE_SUB; PH_SCENE_CAL_MASK_ADDSUB_MODE_ADD; } }
		}
		GROUP
		{ 
			COLUMNS 2;
			LONG PH_SCENE_CAL_MASK_FIRST_FRAME { ANIM OFF; }
			LONG PH_SCENE_CAL_MASK_LAST_FRAME { ANIM OFF; }
		}
	}

	SEPARATOR { LINE; }
	BUTTON PH_SCENE_CAL_MASK_FORCE_UPDATE {}
 }

 GROUP PH_SCENE_CAL_MASK_DISPLAY
 { 
			BOOL PH_SCENE_CAL_MASK_DISPLAY_MASK { ANIM OFF; }
			COLOR PH_SCENE_CAL_MASK_DISPLAY_COLOUR {}
 }

}
