CONTAINER Tphconstraintcameraorient
{
	NAME Tphconstraintcameraorient;
	INCLUDE Tbase;

	GROUP PH_SCENE_CAL_CAMERA_ORIENT
	{ 
		DEFAULT 1;
		GROUP
		{ 
			COLUMNS 3;
			LONG PH_SCENE_CAL_CAMERA_ORIENT_FRAME_NUM{ ANIM OFF; }
			LONG PH_SCENE_CAL_CAMERA_ORIENT_AXIS { ANIM OFF; CYCLE { PH_SCENE_CAL_CAMERA_ORIENT_AXIS_ALL; PH_SCENE_CAL_CAMERA_ORIENT_AXIS_X; PH_SCENE_CAL_CAMERA_ORIENT_AXIS_Y; PH_SCENE_CAL_CAMERA_ORIENT_AXIS_Z; } }
			BOOL PH_SCENE_CAL_CAMERA_ORIENT_FLIP_AXIS { ANIM OFF; }
		}
	}
}
