CONTAINER Tphconstraintpos
{
  NAME Tphconstraintpos;
  INCLUDE Tbase;

  GROUP PH_SCENE_CAL_POS
  {
	DEFAULT 1;
	GROUP
	{ 
		GROUP
		{ 
			COLUMNS 1;
			LONG PH_SCENE_CAL_POS_MODE { ANIM OFF; CYCLE { PH_SCENE_CAL_POS_MODE_CAMERA_TO_POS; PH_SCENE_CAL_POS_MODE_SELECT_TO_POS; } }
			LONG PH_SCENE_CAL_POS_FRAME_NUM{ ANIM OFF; }
		}

		SEPARATOR { LINE; }
		GROUP
		{ 
			COLUMNS 3;
			REAL PH_SCENE_CAL_POS_X_COORD { ANIM OFF; }
			REAL PH_SCENE_CAL_POS_Y_COORD { ANIM OFF; }
			REAL PH_SCENE_CAL_POS_Z_COORD { ANIM OFF; }
		}
	}


	GROUP PH_SCENE_CAL_POS_TARGETS
	{ 
		DEFAULT 1;
		GROUP
		{
			LINK PH_SCENE_CAL_POS_TARGET_0 { ANIM OFF; FIT_H; SCALE_H; ACCEPT { Onull; } }
		}
	}

	SEPARATOR { LINE; }
	BUTTON PH_SCENE_CAL_POS_FORCE_EXPORT {}
  }
}
