CONTAINER Xphlensdistortionshader
{
	NAME Xphlensdistortionshader;

	INCLUDE Mpreview;
	INCLUDE Xbase;

	GROUP ID_SHADERPROPERTIES
	{
		// PHLENS Lens Distortion support - needed in all elements which support usage of lenses.
		GROUP 
		{
			FILENAME PH_LENS_PROFILE_FILENAME { ANIM OFF; FIT_H; SCALE_H; PARENTCOLLAPSE; } // Add OPEN to make fold-out default to open
			STATICTEXT PH_LENS_PROFILE_TYPE { PARENTCOLLAPSE PH_LENS_PROFILE_FILENAME; }
			GROUP
			{
				COLUMNS 6; FIT_H; SCALE_H;
				STATICTEXT PH_LENS_PARAM_RC_00 { FIT_H; SCALE_H; PARENTCOLLAPSE PH_LENS_PROFILE_FILENAME; }
				STATICTEXT PH_LENS_PARAM_RC_01 { FIT_H; SCALE_H; PARENTCOLLAPSE PH_LENS_PROFILE_FILENAME; }
				STATICTEXT PH_LENS_PARAM_RC_02 { FIT_H; SCALE_H; PARENTCOLLAPSE PH_LENS_PROFILE_FILENAME; }
				STATICTEXT PH_LENS_PARAM_RC_03 { FIT_H; SCALE_H; PARENTCOLLAPSE PH_LENS_PROFILE_FILENAME; }
				STATICTEXT PH_LENS_PARAM_RC_04 { FIT_H; SCALE_H; PARENTCOLLAPSE PH_LENS_PROFILE_FILENAME; }
				STATICTEXT PH_LENS_PARAM_RC_05 { FIT_H; SCALE_H; PARENTCOLLAPSE PH_LENS_PROFILE_FILENAME; }

				STATICTEXT PH_LENS_PARAM_RC_10 { FIT_H; SCALE_H; PARENTCOLLAPSE PH_LENS_PROFILE_FILENAME; }
				STATICTEXT PH_LENS_PARAM_RC_11 { FIT_H; SCALE_H; PARENTCOLLAPSE PH_LENS_PROFILE_FILENAME; }
				STATICTEXT PH_LENS_PARAM_RC_12 { FIT_H; SCALE_H; PARENTCOLLAPSE PH_LENS_PROFILE_FILENAME; }
				STATICTEXT PH_LENS_PARAM_RC_13 { FIT_H; SCALE_H; PARENTCOLLAPSE PH_LENS_PROFILE_FILENAME; }
				STATICTEXT PH_LENS_PARAM_RC_14 { FIT_H; SCALE_H; PARENTCOLLAPSE PH_LENS_PROFILE_FILENAME; }
				STATICTEXT PH_LENS_PARAM_RC_15 { FIT_H; SCALE_H; PARENTCOLLAPSE PH_LENS_PROFILE_FILENAME; }

				STATICTEXT PH_LENS_PARAM_RC_20 { FIT_H; SCALE_H; PARENTCOLLAPSE PH_LENS_PROFILE_FILENAME; }
				STATICTEXT PH_LENS_PARAM_RC_21 { FIT_H; SCALE_H; PARENTCOLLAPSE PH_LENS_PROFILE_FILENAME; }
				STATICTEXT PH_LENS_PARAM_RC_22 { FIT_H; SCALE_H; PARENTCOLLAPSE PH_LENS_PROFILE_FILENAME; }
				STATICTEXT PH_LENS_PARAM_RC_23 { FIT_H; SCALE_H; PARENTCOLLAPSE PH_LENS_PROFILE_FILENAME; }
				STATICTEXT PH_LENS_PARAM_RC_24 { FIT_H; SCALE_H; PARENTCOLLAPSE PH_LENS_PROFILE_FILENAME; }
				STATICTEXT PH_LENS_PARAM_RC_25 { FIT_H; SCALE_H; PARENTCOLLAPSE PH_LENS_PROFILE_FILENAME; }

				STATICTEXT PH_LENS_PARAM_RC_30 { FIT_H; SCALE_H; PARENTCOLLAPSE PH_LENS_PROFILE_FILENAME; }
				STATICTEXT PH_LENS_PARAM_RC_31 { FIT_H; SCALE_H; PARENTCOLLAPSE PH_LENS_PROFILE_FILENAME; }
				STATICTEXT PH_LENS_PARAM_RC_32 { FIT_H; SCALE_H; PARENTCOLLAPSE PH_LENS_PROFILE_FILENAME; }
				STATICTEXT PH_LENS_PARAM_RC_33 { FIT_H; SCALE_H; PARENTCOLLAPSE PH_LENS_PROFILE_FILENAME; }
				STATICTEXT PH_LENS_PARAM_RC_34 { FIT_H; SCALE_H; PARENTCOLLAPSE PH_LENS_PROFILE_FILENAME; }
				STATICTEXT PH_LENS_PARAM_RC_35 { FIT_H; SCALE_H; PARENTCOLLAPSE PH_LENS_PROFILE_FILENAME; }

				STATICTEXT PH_LENS_PARAM_RC_40 { FIT_H; SCALE_H; PARENTCOLLAPSE PH_LENS_PROFILE_FILENAME; }
				STATICTEXT PH_LENS_PARAM_RC_41 { FIT_H; SCALE_H; PARENTCOLLAPSE PH_LENS_PROFILE_FILENAME; }
				STATICTEXT PH_LENS_PARAM_RC_42 { FIT_H; SCALE_H; PARENTCOLLAPSE PH_LENS_PROFILE_FILENAME; }
				STATICTEXT PH_LENS_PARAM_RC_43 { FIT_H; SCALE_H; PARENTCOLLAPSE PH_LENS_PROFILE_FILENAME; }
				STATICTEXT PH_LENS_PARAM_RC_44 { FIT_H; SCALE_H; PARENTCOLLAPSE PH_LENS_PROFILE_FILENAME; }
				STATICTEXT PH_LENS_PARAM_RC_45 { FIT_H; SCALE_H; PARENTCOLLAPSE PH_LENS_PROFILE_FILENAME; }
			}
			STATICTEXT { PARENTCOLLAPSE PH_LENS_PROFILE_FILENAME; } // Blank line
		}

		GROUP
		{
			LAYOUTGROUP; COLUMNS 2;
			GROUP
			{			
				REAL PH_IMAGE_VIEW_SCALE { ANIM OFF; STEP 1.0; MIN 1.0; MAX 10000.0; UNIT PERCENT;}
				REAL PH_IMAGE_VIEW_OFFSET_X { ANIM OFF; STEP 1.0; MIN -500.0; MAX 500.0; UNIT PERCENT;}
			}
			GROUP
			{
				STATICTEXT {}
				REAL PH_IMAGE_VIEW_OFFSET_Y { ANIM OFF; STEP 1.0; MIN -500.0; MAX 500.0; UNIT PERCENT;}
			}
        }

		SHADERLINK LENSDISTORTIONSHADER_TEXTURE { }
	}
}
