CONTAINER	Falembicimport
{
	NAME Falembicimport;
	INCLUDE	Fbase;

	GROUP ABCIMPORT_GROUP
	{
		SEPARATOR ABCIMPORT_STR_ANIMATION {}

		GROUP
		{
			COLUMNS 2;

			LONG ABCIMPORT_FPS { MIN 1; MAX 500; STEP 1; SCALE_H; DEFAULT 30; }
			STATICTEXT {JOINEND;}

			LONG ABCIMPORT_STARTFRAME { CUSTOMGUI LONGSLIDER; MIN -300000; MAX 300000; STEP 1; MINSLIDER 0; MAXSLIDER 90; SCALE_H; DEFAULT 0; }
			BOOL ABCIMPORT_NOSTARTFRAME { DEFAULT 1; }
		}

		SEPARATOR ABCIMPORT_STR_GENERAL {}

		UNITSCALE ABCIMPORT_SCALE { }

		SEPARATOR { LINE; }

		GROUP
		{
			COLUMNS 2;

			BOOL ABCIMPORT_CAMERAS { DEFAULT 1; }
			STATICTEXT { JOINEND; }

			BOOL ABCIMPORT_SUBDS { DEFAULT 1; }
			STATICTEXT { JOINEND; }

			BOOL ABCIMPORT_CURVES { DEFAULT 0; }
			LONG ABCIMPORT_CURVES_AS
			{
				CYCLE
				{
					ABCIMPORT_CURVES_AS_SPLINES~12196;
					ABCIMPORT_CURVES_AS_HAIR~1017578;
				}
			}

			BOOL ABCIMPORT_POINTS { DEFAULT 0; }
			LONG ABCIMPORT_POINTS_AS
			{
				CYCLE
				{
					ABCIMPORT_POINTS_AS_TPARTICLES~1001414;
					ABCIMPORT_POINTS_AS_GEOMETRY~5100;
				}
			}
		}

		SEPARATOR ABCIMPORT_STR_OPTIONS {}

		BOOL ABCIMPORT_VISIBILITY { DEFAULT 0; }
		BOOL ABCIMPORT_NORMALS { DEFAULT 1; }
		BOOL ABCIMPORT_UVS { DEFAULT 1; }
		BOOL ABCIMPORT_FACESETS { DEFAULT 1; }
	}
}