CONTAINER	Falembicexport
{
	NAME Falembicexport;
	INCLUDE	Fbase;

	GROUP ABCEXPORT_GROUP
	{
		COLUMNS 2;

		LONG ABCEXPORT_FORMAT { CYCLE { ABCEXPORT_FORMAT_OGAWA; ABCEXPORT_FORMAT_HDF5_LEGACY; } DEFAULT ABCEXPORT_FORMAT_OGAWA; }
		STATICTEXT { JOINENDSCALE; }

		SEPARATOR ABCEXPORT_STR_ANIMATION { }
		STATICTEXT { JOINENDSCALE; }

		LONG ABCEXPORT_FRAME_START { CUSTOMGUI LONGSLIDER; MIN -18000; MAX 3240000; STEP 1; MINSLIDER 0; MAXSLIDER 90; SCALE_H; DEFAULT 0; }
		STATICTEXT { JOINENDSCALE; }
		LONG ABCEXPORT_FRAME_END   { CUSTOMGUI LONGSLIDER; MIN -18000; MAX 3240000; STEP 1; MINSLIDER 0; MAXSLIDER 90; SCALE_H; DEFAULT 90; }
		STATICTEXT { JOINENDSCALE; }
		LONG ABCEXPORT_FRAME_STEP  { MIN 1; MAX 100; STEP 1; SCALE_H; DEFAULT 1; }
		STATICTEXT { }
		LONG ABCEXPORT_SUBFRAMES   { MIN 1; MAX 100; STEP 1; SCALE_H; DEFAULT 1; }
		STATICTEXT { }

		SEPARATOR ABCEXPORT_STR_GENERAL { }
		STATICTEXT { JOINENDSCALE; }

		UNITSCALE ABCEXPORT_SCALE { ANIM OFF; }
		STATICTEXT { JOINENDSCALE; }

		SEPARATOR { LINE; SCALE_H; }
		STATICTEXT { JOINENDSCALE; }

		BOOL ABCEXPORT_SELECTION_ONLY { DEFAULT 0; }
		BOOL ABCEXPORT_GLOBAL_MATRIX { DEFAULT 0; }
		BOOL ABCEXPORT_CAMERAS { DEFAULT 1; }
		BOOL ABCEXPORT_HYPERNURBS { DEFAULT 1; }
		BOOL ABCEXPORT_SPLINES { DEFAULT 1; }
		BOOL ABCEXPORT_PARTICLES { DEFAULT 0; }
		BOOL ABCEXPORT_HAIR { DEFAULT 0; }
		BOOL ABCEXPORT_PARTICLE_GEOMETRY { DEFAULT 0; }
		BOOL ABCEXPORT_XREFS { DEFAULT 0; }
		STATICTEXT { JOINENDSCALE; }


		SEPARATOR ABCEXPORT_STR_OPTIONS {}
		STATICTEXT { JOINENDSCALE; }
		BOOL ABCEXPORT_VISIBILITY { DEFAULT 0; }
		BOOL ABCEXPORT_NORMALS { DEFAULT 1; }
		BOOL ABCEXPORT_UVS { DEFAULT 1; }
		BOOL ABCEXPORT_POLYGONSELECTIONS { DEFAULT 1; }
		BOOL ABCEXPORT_VERTEX_MAPS { DEFAULT 0; }
		STATICTEXT { JOINENDSCALE; }

		SEPARATOR { LINE; }
		STATICTEXT { JOINENDSCALE; }

		BOOL ABCEXPORT_POINTS_ONLY { DEFAULT 0; }
		BOOL ABCEXPORT_MERGE_CACHE { DEFAULT 0; }
	}
}