CONTAINER Oalembicgenerator
{
	NAME Oalembicgenerator;
	INCLUDE Obase;

	GROUP ID_OBJECTPROPERTIES
	{
		COLUMNS 1;

		GROUP
		{
			COLUMNS 2;

			BASETIME ALEMBIC_START_DELAY { }
			BUTTON ALEMBIC_START_DELAY_RESET { }
		}

		UNITSCALE ALEMBIC_UNIT_SCALE { ANIM OFF; }

		SEPARATOR { LINE; }

		GROUP
		{
			COLUMNS 2;

			FILENAME ALEMBIC_PATH { ANIM OFF; SCALE_H; }
			BOOL ALEMBIC_PATH_STATE { }
			STRING ALEMBIC_IDENTIFIER { ANIM OFF; SCALE_H; }
			BOOL ALEMBIC_IDENT_STATE { }
		}

		SEPARATOR ALEMBIC_STR_RENDERING { }

		BOOL ALEMBIC_OVERRIDE_FOR_RENDERING { }
		BOOL ALEMBIC_USE_ORIGINAL_PATH { ANIM OFF; }

		GROUP
		{
			COLUMNS 2;

			FILENAME ALEMBIC_PATH_FOR_RENDERING { PARENTID ALEMBIC_OVERRIDE_FOR_RENDERING; ANIM OFF; SCALE_H; }
			BOOL ALEMBIC_PATH_STATE_RENDERING { }
			STRING ALEMBIC_IDENTIFIER_FOR_RENDERING { PARENTID ALEMBIC_OVERRIDE_FOR_RENDERING; ANIM OFF; SCALE_H; }
			BOOL ALEMBIC_IDENT_STATE_RENDERING { }
		}

		SEPARATOR ALEMBIC_STR_UPDATE { }

		GROUP
		{
			COLUMNS 2;

			BOOL ALEMBIC_UPDATE_XFORM { ANIM OFF; }
			BOOL ALEMBIC_UPDATE_GEOMETRY { ANIM OFF; }

			BOOL ALEMBIC_USE_VISIBILITY { ANIM OFF; }
			BOOL ALEMBIC_USE_NORMALS { ANIM OFF; }
			BOOL ALEMBIC_USE_UVS { ANIM OFF; }
			BOOL ALEMBIC_USE_FACESETS { ANIM OFF; }
		}
	}
}
