CONTAINER	Ffbximport
{
	NAME Ffbximport;
	INCLUDE	Fbase;

	GROUP FBXIMPORT_GROUP
	{
		SEPARATOR FBXIMPORT_GRP_GENERAL {}

		BOOL FBXIMPORT_GEOMETRY { DEFAULT 1; }
		BOOL FBXIMPORT_LIGHTS { DEFAULT 1; }
		BOOL FBXIMPORT_CAMERAS { DEFAULT 1; }
		BOOL FBXIMPORT_CURVES { DEFAULT 1; }
		BOOL FBXIMPORT_MARKERS { DEFAULT 1; }

		SEPARATOR FBXIMPORT_GRP_ANIMATION { }

		BOOL FBXIMPORT_TRACKS { DEFAULT 1; }
		BOOL FBXIMPORT_CLEAN_TRACKS { DEFAULT 0; }
		BOOL FBXIMPORT_VERTEXCACHE_TO_PLA { DEFAULT 0; }

		SEPARATOR  FBXIMPORT_GRP_GEOMETRY {}

		BOOL FBXIMPORT_SHAPES { DEFAULT 1; }
		BOOL FBXIMPORT_NORMALS { DEFAULT 0; }
		BOOL FBXIMPORT_CONVERT_TO_PHONGTAG { DEFAULT 1; }
		BOOL FBXIMPORT_COLORS_AS_VERTEX_MAPS { DEFAULT 0; }
		BOOL FBXIMPORT_SINGLE_MAT_SELECTIONTAGS { DEFAULT 0; }

		SEPARATOR FBXIMPORT_GRP_ADDITIONAL { }

		BOOL FBXIMPORT_TEXTURES { DEFAULT 1; }
		BOOL FBXIMPORT_ACTIVATE_JOINTS { DEFAULT 1; }
	}
}