enum
{
	// string table definitions
	IDS_SKPIMPORTER = 10000,
	IDS_SKPIMPORTER_COMP_INSTANCE,
	IDS_SKPIMPORTER_GROUP,
	IDS_SKPIMPORTER_STANDALONE_EDGES,
	IDS_SKPIMPORTER_STANDALONE_EDGE,
	IDS_SKPIMPORTER_CLOSED_CURVE,
	IDS_SKPIMPORTER_OPEN_CURVE,
	IDS_SKPIMPORTER_ONE_EDGE_CURVE,
	IDS_SKPIMPORTER_SKETCHUP_VERSION,
	IDS_SKPIMPORTER_ERROR_SKETCHUP_VERSION_NOT_RETRIEVED,
	IDS_SKPIMPORTER_MODEL_STATS_TITLE,
	IDS_SKPIMPORTER_STATS_EDGES,
	IDS_SKPIMPORTER_STATS_FACES,
	IDS_SKPIMPORTER_STATS_COMP_INSTANCES,
	IDS_SKPIMPORTER_STATS_GROUPS,
	IDS_SKPIMPORTER_STATS_IMAGES,
	IDS_SKPIMPORTER_STATS_COMP_DEFINITIONS,
	IDS_SKPIMPORTER_STATS_LAYERS,
	IDS_SKPIMPORTER_STATS_MATERIALS,
	IDS_SKPIMPORTER_STATS_ERROR_NOT_RETRIEVED,

	// End of symbol definition
	_DUMMY_ELEMENT_
};
