enum
{
	// string table definitions
	STR_HALVAR_REFERENCE_NAME = 10000,
	STR_HALVAR_TUTORIAL_NAME,
	STR_HALVAR_WINDOW_TITLE,
	STR_HALVAR_REFERENCE_DESCRIPTION,
	STR_HALVAR_TUTORIAL_DESCRIPTION,

	GADGET_HALVAR_ENCLOSING_GROUP,

	GADGET_HALVAR_TOOLBAR_GROUP,
	GADGET_HALVAR_BACK,
	GADGET_HALVAR_FORWARD,
	GADGET_HALVAR_HOME,
	GADGET_HALVAR_PREVIOUS_PAGE,
	GADGET_HALVAR_NEXT_PAGE,
	GADGET_HALVAR_SEARCH,
	GADGET_HALVAR_SEARCH_TEXT,
	GADGET_HALVAR_REFRESH,
	GADGET_HALVAR_STOP,
	GADGET_HALVAR_SEARCH_GROUP,
	GADGET_HALVAR_SEARCH_RANGE,
	GADGET_HALVAR_MIN_SEARCH_RANGE,
	GADGET_HALVAR_SEARCH_NEAR,
	GADGET_HALVAR_SEARCH_FAR,
	GADGET_HALVAR_SEARCH_PROGRESSSOR,
	GADGET_HALVAR_SEARCH_CLEAR_BUTTON,
	STR_HALVAR_LOCAL_SEARCH,
	STR_HALVAR_SEARCH_ALL,

	STR_HALVAR_BACK,
	STR_HALVAR_FORWARD,
	STR_HALVAR_HOME,
	STR_HALVAR_PREVIOUS_PAGE,
	STR_HALVAR_NEXT_PAGE,
	STR_HALVAR_SEARCH,
	STR_HALVAR_DETAILS,
	STR_HALVAR_REFRESH,
	STR_HALVAR_STOP,

	GADGET_HALVAR_MAIN_GROUP,

	GADGET_HALVAR_SIDEBAR_GROUP,
	GADGET_HALVAR_SIDEBAR_TAB,
	GADGET_HALVAR_INDEX_GROUP,
	GADGET_HALVAR_TREEVIEW_DLG,
	GADGET_HALVAR_TREEVIEW,
	GADGET_HALVAR_RESULTS_GROUP,
	GADGET_HALVAR_RESULTS_DLG,
	GADGET_HALVAR_RESULTS_LISTVIEW,
	STR_HALVAR_INDEX_GROUP,
	STR_HALVAR_RESULTS_GROUP,

	GADGET_HALVAR_CONTENT_GROUP,
	GADGET_HALVAR_CONTENT_AREA,

	HALVAR_BOOKMARKS_MENU,
	HALVAR_BOOKMARKS_ADD,
	HALVAR_BOOKMARKS_MANAGE,

	STR_HALVAR_BOOKMARKS_TITLE,
	STR_HALVAR_BOOKMARK,
	STR_HALVAR_RENAME,

	GADGET_HALVAR_BOOKMARKS_LISTVIEW,

	STR_HALVAR_TROUBLESHOOTING_NAME,
	STR_HALVAR_TROUBLESHOOTING_DESCRIPTION,

// the bookmarks, insert new ids *BEFORE* this
	GADGET_HALVAR_BOOKMARK_START = 1000000,
	GADGET_HALVAR_BOOKMARK_END = 2000000,

// End of symbol definition
	_DUMMY_ELEMENT_
};
