CONTAINER Netprefs
{
	NAME Netprefs;

	GROUP PREF_TEAMRENDERGROUP
	{
		DEFAULT 1;
		COLUMNS 2;

		BOOL PREF_ENABLETEAMRENDER { }
		STATICTEXT { JOINENDSCALE; }

		SEPARATOR PREF_SEP_1 { LINE; }
		STATICTEXT { JOINENDSCALE; }
		
		STRING PREF_NAME { }
		STATICTEXT { JOINENDSCALE; }
			
		STRING PREF_SECURITYTOKEN { }
		STATICTEXT { JOINENDSCALE; }
		
		STRING PREF_SERVICEPORTNUMBER { ANIM OFF; }
		STATICTEXT { JOINENDSCALE; }
		
		STRING PREF_WEBSERVERPORT { ANIM OFF; }
		STATICTEXT { JOINENDSCALE; }
		
		BOOL PREF_USERMANAGEMENTENABLED { }
		STATICTEXT { JOINENDSCALE; }

		BOOL PREF_USEBONJOUR { }
		STATICTEXT { JOINENDSCALE; }

		STATICTEXT PREF_USEBONJOUR_BLOCKED { ANIM OFF; }
		STATICTEXT PREF_USEBONJOUR_BLOCKED_JS { JOINENDSCALE; }
		
		SEPARATOR  PREF_SEP_LOCAL {}
		STATICTEXT { JOINENDSCALE; }

		BOOL PREF_SHARE { }
		STATICTEXT { JOINENDSCALE; }
		
		BOOL PREF_THREADCUSTOM { ANIM OFF; }
		LONG PREF_RENDERTHREADS	{ ANIM OFF; MIN 1; MAX 256;}

		BOOL PREF_ABORTRENDERINGONCLIENTERROR { }
		STATICTEXT { JOINENDSCALE; }

		BOOL PREF_FETCHASSETSALWAYSFROMSERVER { }
		STATICTEXT { JOINENDSCALE; }

		BOOL PREF_KEEPB3DFILESAFTERASSEMBLING { }
		STATICTEXT { JOINENDSCALE; }

		BOOL PREF_WAKEONLANFOROFFLINEMACHINES { }
		STATICTEXT { JOINENDSCALE; }
		
		BOOL PREF_ENABLERENDERINGTIMEOUT { ANIM OFF; }
		LONG PREF_RENDERINGTIMEOUT { MIN 30; }
		
		SEPARATOR  PREF_SEP_CLIENT {}
		STATICTEXT { JOINENDSCALE; }

		BOOL PREF_USEENCRYPTION { }
		STATICTEXT { JOINENDSCALE; }	

		BOOL PREF_REQUESTONDEMAND { }
		STATICTEXT { JOINENDSCALE; }

		BOOL PREF_HANDLEWARNINGASERROR { }
		STATICTEXT { JOINENDSCALE; }

		BOOL PREF_EXCLUDECLIENTONLOADINGERROR { }
		STATICTEXT { JOINENDSCALE; }

		SEPARATOR PREF_SEP_2 { LINE; }
		STATICTEXT { JOINENDSCALE; }

		BOOL PREF_PEERTOPEERASSETDISTRIBUTION { }
		STATICTEXT { JOINENDSCALE; }

		LONG PREF_ASSETCHUNKSIZE { ANIM OFF; MIN 2; MAX 256;}
		STATICTEXT { JOINENDSCALE; }	

		SEPARATOR PREF_SEP_PATHS { }
		STATICTEXT { JOINENDSCALE; }
	
		FILENAME PREF_SERVICEREPOSITORYPATH { DIRECTORY; }
		STATICTEXT { JOINENDSCALE; }
	}
}
