// C4D-DialogResource

DIALOG DLG_ASSETSELECTION
{
	NAME	STRING_TITLE;
	
	GROUP
	{
		COLUMNS 1;
		BORDERSIZE 8,8,8,8;
		
		STATICTEXT { SIZE -320, -1; }
	
		LISTVIEW GADGET_LISTVIEW { SCALE_H; SCALE_V; SIZE 250, 200; };
	
		GROUP
		{
			BUTTON SELECT_ALL { NAME STRING_SELECT_ALL; }
			BUTTON DESELECT_ALL { NAME STRING_DESELECT_ALL; }
		}
  }
	DLGGROUP { OK; CANCEL; }
}
