CONTAINER tctpobjectdata
{
	NAME tctpobjectdata;
	INCLUDE Tbase;


	GROUP ID_TAGPROPERTIES
	{
		BOOL CTP_OBJECT_TAG_ENABLED		{ }
		LONG CTP_OBJECT_TAG_TYPE		{ FIT_H; SCALE_H; CYCLE { CTP_OBJECT_TAG_DEFAULT; CTP_OBJECT_TAG_COMPLETE; CTP_OBJECT_TAG_BOUNDING; } }
	}
}
